### ISSUE TITLE
How to return instance  or a message depending on condition in Ninja APIs

### ISSUE THREAD

**Issue by rjsh6697** [vitalik/django-ninja#10]
f```
rom ninja import Schema

class UserIn(Schema):
    username: str
    password: str

class UserOut(Schema):
    id: int
    username: str

@api.post("/users/", response=UserOut)
def create_user(request, data: UserIn):
    user = User(username=data.username)
    user.set_password(data.password)
    user.save()
    return user
```

This Above example is taken from the Docs, as I  am stuck in a Case in which there is no chance of always passing the Instance to the return , As If we pass @api.post("/users/", response=UserOut)   Userout then it will always waiting for the user instance to return , But in my case its may be or may not be. 
Here Below is my Use Case which I want to achieve
class UserLogin(Schema):
	email: str
	password: str
    
class UserOut(Schema):
    id: int
    username: str
    email: str
    phone_number : int
    is_active: bool

```
@authapi.post("auth/login", response=UserOut)
def login(request, user_login: UserLogin):
	if "@" in user_login.email:
		user = User.objects.get(email__iexact=user_login.email)
		if hasattr(user, 'teacher'):
			if request.META.get('HTTP_CLIENT_NAME') == 'teacher':
				if not user.is_active:
					try:
						message = "An email containing verification instructions was sent"
						return {"message": message, "code": 401, "data": {'is_active': False}, "error_message": ""}
					except:
						pass
				if user.teacher.is_verified == False:
					message = "Admin verification is required, please wait."
					return {"message": message, "code": 400, "data": {}, "error_message": message}

				return user
as In my Case there will be a chance of Coming error message also, But if we pass userout then Complusorily they want only User instance to be return , Showing me the error when we are using Userout and the string message comes:-

ydantic.error_wrappers.ValidationError: 5 validation errors for Response
response -> id
  field required (type=value_error.missing)
response -> username
  field required (type=value_error.missing)
response -> email
  field required (type=value_error.missing)
response -> phone_number
  field required (type=value_error.missing)
response -> is_active
  field required (type=value_error.missing)

Please help me out 
```

**Comment by rjsh6697** [comment]
Anybody is here ? to help me

**Comment by vitalik** [comment]
hey @rjsh6697 , currently multiple response schemas are not supported, but it is planed in the near future.

but at this moment you can use the following:

```python
...

from ninja.responses import Response

...

@authapi.post("auth/login", response=UserOut)
def login(request, user_login: UserLogin):
      ...
      if not user.is_active:
          message = "An email containing verification instructions was sent"
          data = {"message": message, "code": 401, "data": {'is_active': False}, "error_message": ""}
          return Response(data, status=401)


just return ninja Response or any other django HttpResponse

**Comment by vitalik** [comment]
hey @rjsh6697 , did it work for you ?
