### ISSUE TITLE
[BUG] With ModelSchema and  create_schema -> fields_optional and optional_fields

### ISSUE THREAD

**Issue by Redowan-Ahmed** [vitalik/django-ninja#1016]
I'm interested in Django Ninja and tried to check on my environment. I applied the ModelSchema from Ninja and then created a Schema. I was following the documentation and I saw that we could make a list of files Optional and tried the fields_optional 2 ways 

1 is:

```
class ProjectSchema(ModelSchema):
    class Meta:
        model = Project
        fields = ['id', 'created_at']
        fields_optional  = ['id']
```

Another one is :

```
from ninja.orm import create_schema

ProjectSchema2 = create_schema(Project , optional_fields=['id'])
```

With these 2 ways, I Faced an issue showing me an error ( `TypeError: cannot specify both default and default_factory` )
if I disable those then the application runs perfectly. 

Please solve that 

**Versions **
 - Python version: [ 3.12]
 - Django version: [ 5.0]
 - Django-Ninja version: [1.1.0]
 - Pydantic version: 2.5.2

![Screenshot 2023-12-18 224825](https://github.com/vitalik/django-ninja/assets/55311231/8729657f-b6ba-4dc5-a007-41dc452266c6)
![Screenshot 2023-12-18 224805](https://github.com/vitalik/django-ninja/assets/55311231/ec8b3f01-4fcf-4adc-8441-1f5685625096)

**Comment by Redowan-Ahmed** [comment]
![Screenshot 2023-12-18 225046](https://github.com/vitalik/django-ninja/assets/55311231/18db4f3e-82d7-4cc0-88f6-e4b79432c7e1)


Working Image

**Comment by vitalik** [comment]
@Redowan-Ahmed 

are you sure you did not mix anything - I just copied your code and it works for me:

```Python
class ProjectSchema(ModelSchema):
    class Meta:
        model = Project
        fields = ['id', 'created_at']
        fields_optional = ['id']


ProjectSchema2 = create_schema(Project, optional_fields=['id'])


print(ProjectSchema.model_json_schema())
print(ProjectSchema2.model_json_schema())
```

outputs:

```
{'properties': {'id': {'anyOf': [{'type': 'integer'}, {'type': 'null'}], 'default': None, 'title': 'ID'}, 'created_at': {'format': 'date-time', 'title': 'Created At', 'type': 'string'}}, 'required': ['created_at'], 'title': 'ProjectSchema', 'type': 'object'}
{'properties': {'id': {'anyOf': [{'type': 'integer'}, {'type': 'null'}], 'default': None, 'title': 'ID'}, 'created_at': {'format': 'date-time', 'title': 'Created At', 'type': 'string'}}, 'required': ['created_at'], 'title': 'Project', 'type': 'object'}
```
env:

```
Python 3.10.8
Django  5.0
Ninja 1.1.0
Pydantic 2.5.1
```

**Comment by vitalik** [comment]
@Redowan-Ahmed could you show listing of your Project model ?

**Comment by Redowan-Ahmed** [comment]
I'll double check and show the output here
