### ISSUE TITLE
[many-to-many field] add count in schema

### ISSUE THREAD

**Issue by amzar96** [vitalik/django-ninja#1032]
Hi everyone,

I've difficulty adding the count of many to many fields in the schema. I want the query (filter query) always to include the count of the fields. What I do right now is I need to put `x = books. count()` in the endpoint before sending to schema response.

Thanks

**Comment by amzar96** [comment]
Solved.

1. models.py
```python

class Profile():
    following = models.ManyToManyField(...)

    @property
    def following_count(self):
        return self.following.filter(...).count()
```

2. schema.py
```python
class ProfileSchemaLogin(ModelSchema):
    following_count: Optional[int] = None
```

setup like this to make it work.

**Comment by OtherBarry** [comment]
You could also do this with a resolver

```python
class ProfileSchemaLogin(ModelSchema):
    following_count: Optional[int] = None

    @staticmethod
    def resolve_following_count(obj):
        return obj.following.filter(...).count()
```
