### ISSUE TITLE
Access old version document

### ISSUE THREAD

**Issue by nwattana** [vitalik/django-ninja#1035]
**Is your feature request related to a problem? Please describe.**
Now I'm using ninja version 0.19.1 and cant upgrade to  latest version.

**Describe the solution you'd like**
need to access old version of document in web. for now it's only version 1.1.0

**Comment by vitalik** [comment]
Hi @nwattana 

v 0.x docs are available here - https://v0.django-ninja.dev/

**Comment by vitalik** [comment]
TODO: add link to the header to switch between versiosns
