### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by vitalik** [vitalik/django-ninja#104]
Pagination decorator should be supported out of the box

```Python
@api.get('/list', ...)
@paginage
def myoperation(request):
     return Model.objects.all()

```

**Comment by hermansc** [comment]
FWIW I hacked up a solution which I'm pretty happy with, using the builtin paginator of Django:

```python
# Utils
def replace_query_param(url, key, val):
    """
    Given a URL and a key/val pair, set or replace an item in the query
    parameters of the URL, and return the new URL.

    Taken from: https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/urls.py
    """

    (scheme, netloc, path, query, fragment) = parse.urlsplit(force_str(url))
    query_dict = parse.parse_qs(query, keep_blank_values=True)
    query_dict[force_str(key)] = [force_str(val)]
    query = parse.urlencode(sorted(query_dict.items()), doseq=True)
    return parse.urlunsplit((scheme, netloc, path, query, fragment))


def get_next_page_url(request, page: Page) -> Optional[str]:
    if not page.has_next():
        return None
    return replace_query_param(request.build_absolute_uri(), "page", page.number + 1)


def get_previous_page_url(request, page: Page) -> Optional[str]:
    if not page.has_previous():
        return None
    return replace_query_param(request.build_absolute_uri(), "page", page.number - 1)

# Schemas
GenericResultsType = TypeVar("GenericResultsType")
class PaginatedResponseSchema(GenericModel, Generic[GenericResultsType]):
    count: int
    next: Optional[pydantic.AnyHttpUrl]
    previous: Optional[pydantic.AnyHttpUrl]
    results: List[GenericResultsType]

class UserSchema(pydantic.BaseModel):
    id: uuid.UUID
    username: str

# API views
router = Router()
@router.get("/", response=PaginatedResponseSchema[AccountSchema])
def list_users(request, page: int = 1):
    accounts = User.objects.all()
    paginator_page = Paginator(accounts, per_page=50).get_page(page)
    users = [
        UserSchema(id=user.id, username=user.username)
        for users in paginator_page.object_list
    ]
    return PaginatedResponseSchema[UserSchema](
        count=paginator_page.paginator.count,
        next=get_next_page_url(request, paginator_page),
        previous=get_previous_page_url(request, paginator_page),
        results=users,
    )
```

Returns a JSON like this:

```json
{
  "count": 1234,
  "next": "http://localhost:8000/api/users/?page=2",
  "previous": null,
  "results": [
      {"id": 1, "username": "herman"}
   ],
}
```

Looks a bit overwhelming perhaps but I moved the utility stuff in it's own file and using the Generics of pydantic I'm able to re-use it across all APIs with lists that needs to be paginated.

**Comment by EMUNES** [comment]
Yeah, pagination is a core functionality for building restful API system. Though django can provide Paginator but it will be much better if the pagination can work with a decorator. Thanks for your work and I'm really expected to see this come to work.

**Comment by applecat** [comment]
It would be great if with built in pagination (`from ninja.pagination import paginate`) we could get `count` property to figure out if we need show a `load more` button to a user. It could be passed in response body (`json`) or in response headers.

**Comment by lihuacai168** [comment]
> FWIW I hacked up a solution which I'm pretty happy with, using the builtin paginator of Django:
> 
> ```python
> # Utils
> def replace_query_param(url, key, val):
>     """
>     Given a URL and a key/val pair, set or replace an item in the query
>     parameters of the URL, and return the new URL.
> 
>     Taken from: https://github.com/encode/django-rest-framework/blob/master/rest_framework/utils/urls.py
>     """
> 
>     (scheme, netloc, path, query, fragment) = parse.urlsplit(force_str(url))
>     query_dict = parse.parse_qs(query, keep_blank_values=True)
>     query_dict[force_str(key)] = [force_str(val)]
>     query = parse.urlencode(sorted(query_dict.items()), doseq=True)
>     return parse.urlunsplit((scheme, netloc, path, query, fragment))
> 
> 
> def get_next_page_url(request, page: Page) -> Optional[str]:
>     if not page.has_next():
>         return None
>     return replace_query_param(request.build_absolute_uri(), "page", page.number + 1)
> 
> 
> def get_previous_page_url(request, page: Page) -> Optional[str]:
>     if not page.has_previous():
>         return None
>     return replace_query_param(request.build_absolute_uri(), "page", page.number - 1)
> 
> # Schemas
> GenericResultsType = TypeVar("GenericResultsType")
> class PaginatedResponseSchema(GenericModel, Generic[GenericResultsType]):
>     count: int
>     next: Optional[pydantic.AnyHttpUrl]
>     previous: Optional[pydantic.AnyHttpUrl]
>     results: List[GenericResultsType]
> 
> class UserSchema(pydantic.BaseModel):
>     id: uuid.UUID
>     username: str
> 
> # API views
> router = Router()
> @router.get("/", response=PaginatedResponseSchema[UserSchema])
> def list_users(request, page: int = 1):
>     users = User.objects.all()
>     paginator_page = Paginator(users, per_page=50).get_page(page)
>     users = [
>         UserSchema(id=user.id, username=user.username)
>         for users in paginator_page.object_list
>     ]
>     return PaginatedResponseSchema[UserSchema](
>         count=paginator_page.paginator.count,
>         next=get_next_page_url(request, paginator_page),
>         previous=get_previous_page_url(request, paginator_page),
>         results=users,
>     )
> ```
> 
> Returns a JSON like this:
> 
> ```json
> {
>   "count": 1234,
>   "next": "http://localhost:8000/api/users/?page=2",
>   "previous": null,
>   "results": [
>       {"id": 1, "username": "herman"}
>    ],
> }
> ```
> 
> Looks a bit overwhelming perhaps but I moved the utility stuff in it's own file and using the Generics of pydantic I'm able to re-use it across all APIs with lists that needs to be paginated.
> 
> This also plays nice with the API docs and generates the swagger/openapi spec you would expect.

```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```
how to solve it?
![image](https://user-images.githubusercontent.com/11568297/140250890-aec92206-0fa9-4180-ab5b-4f85dcece21b.png)

**Comment by omidraha** [comment]
> Pagination decorator should be supported out of the box
> 
> ```python
> @api.get('/list', ...)
> @paginage
> def myoperation(request):
>      return Model.objects.all()
> ```

The correct syntax is `paginate`.

```python
from ninja.pagination import paginate
paginate
```

**Comment by LaundroMat** [comment]
That link 404's, here's an updated link: https://django-ninja.rest-framework.com/guides/response/pagination/
