### ISSUE TITLE
Pydantic / Schema: pass the entire dataset to a nested field

### ISSUE THREAD

**Issue by khan-asfi-reza** [vitalik/django-ninja#1049]
### Discussed in https://github.com/vitalik/django-ninja/discussions/1046

<div type='discussions-op-text'>

<sup>Originally posted by **khan-asfi-reza** January 13, 2024</sup>
I am using django, django-ninja framework to replace some of my apis ( written in drf, as it is becoming more like a boilerplate codebase ). Now while transforming some legacy api to django-ninja, I need to follow the old structure, so the client side doesn't face any issue. Django-ninja helped a lot to reduce a lot of boilerplate codes and helped to increase the code readability. This is just the backstory.

Now coming to the issue: 

I have two separate models.
```py
class Author(models.Model):
   username = models.CharField(...)
   email = models.CharField(...)
   ... # Other fields

class Blog(models.Model):
   title = models.CharField(...)
   text = models.CharField(...)
   tags = models.CharField(...)
   author = models.ForeignKey(...)
   ... # Other fields
```

The structure written in django rest framework serializer

```py
class BlogBaseSerializer(serializers.Serializer):
   class Meta:
       model = Blog
       exclude = ["author"]

class AuthorSerializer(serializers.Serializer):
   class Meta:
       model = Author
       fields = "__all__"


class BlogSerializer(serializers.Serializer):
   blog = BlogBaseSerializer(source="*")
   author = AuthorSerializer()
```

In viewset the following queryset will be passed

```py
class BlogViewSet(viewsets.GenericViewSet, ListViewMixin):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    ... # Other config
```

I have the following code for pydantic/ninja schema

```py
AuthorSchema = create_schema(Author, exclude=["updated", "date_joined"])


class BlogBaseSchema(ModelSchema):
    class Meta:
        model = Blog
        exclude = ["author", ]


class BlogSchema(Schema):
    blog: BlogBaseSchema
    author: AuthorSchema

```

But as you can see, drf serializer has a parameter called `source`, where `source="*"` means to pass the entire original dataset to the nested field serializer. Is there any option to do the exact same with pydantic?

Except for creating a list of dictionaries ```[{author: blog.author, "blog": blog} for blog in queryset]```

</div>

**Comment by vitalik** [comment]
Hi @khan-asfi-reza 

could you show what do you expect your final JSON to look like ?

**Comment by vitalik** [comment]
@khan-asfi-reza you can use `resolve_<field>` for this:


```Python


class AuthorSchema(ModelSchema):
    class Meta:
        model = Author
        exclude=["updated", "date_joined"]

class BlogBaseSchema(ModelSchema):
    class Meta:
        model = Blog
        exclude = ["author", ]


class BlogSchema(Schema):
    blog: BlogBaseSchema
    author: AuthorSchema

    @staticmethod
    def resolve_blog(self, obj):
        return obj


@api.get("/blog", reponse=list[BlogSchema])
def list_of_detailed_blogs(request):
    return Blog.objects.all()

```

**Comment by khan-asfi-reza** [comment]
Thanks @vitalik
