### ISSUE TITLE
Missing editor hints when creating new instance

### ISSUE THREAD

**Issue by torx-cz** [vitalik/django-ninja#1050]
Hello

I would like to ask if it is possible to "turn on" (somehow) the ability to see editor hints when creating new instances of Schemas.

For example, see this code:

```python
import pydantic
import ninja

class PydanticModel(pydantic.BaseModel):
    a: int = 0
    b: str

class NinjaSchema(ninja.Schema):
    a: int = 0
    b: str

PydanticModel()
NinjaSchema()
```

When i write this code in VS Code i can see this for `PydanticModel()` (when hover over + red line under it, signaling something is wrong!)

![pydantic_model](https://github.com/vitalik/django-ninja/assets/22475728/cd87e97e-f99a-484d-b1df-51cbd105192d)

But for `NinjaSchema()` i see only this:

![ninja_schema](https://github.com/vitalik/django-ninja/assets/22475728/6da78f4d-924f-4986-b708-0a518ca3cf86)

---

My question is: **Is there some way to turn on the same behavior for NinjaSchemas like it is for PydanticModel?**
Namely:
- when hover over - to be able to see which params need to be defined (not just  `**data: Any`) 
- red line under when something is wrong

Thank you very much!

**Comment by vitalik** [comment]
Hi @torx-cz 

yeah indeed - I did not notice that before - and it is interesting to find out what's the trick (as Schema is just inherited from the BaseModel... maybe metaclass helps here)
