### ISSUE TITLE
Make dark theme for the docs 

### ISSUE THREAD

**Issue by fannigurt** [vitalik/django-ninja#1051]
Please, subj.

**Comment by carlosxfelipe** [comment]
Problem partially solved, I created a .css file and a template for Django Ninja.
Repo: https://github.com/carlosxfelipe/swagger-dark

<img width="1248" height="813" alt="Image" src="https://github.com/user-attachments/assets/85556393-050b-41b8-918d-3443055e691f" />
<img width="1248" height="813" alt="Image" src="https://github.com/user-attachments/assets/380276f1-1bcc-466a-a103-f843136545d6" />
<img width="1248" height="813" alt="Image" src="https://github.com/user-attachments/assets/0d3d72f8-2ed4-41cb-8986-d6121a3f4f5b" />
