### ISSUE TITLE
How do I make trailing slashes optional?

### ISSUE THREAD

**Issue by taobojlen** [vitalik/django-ninja#1058]
In my API, I'd like to make trailing slashes optional. I don't want to use Django's `APPEND_SLASH`, since the contents of POST requests will get lost in the redirect.

Instead, I think the most user-friendly approach is to make trailing slashes optional in my API: either `/api/foobar` and `/api/foobar/` should return the same content.

Is it possible to achieve this with django-ninja?

**Comment by LouisDelbosc** [comment]
I'm also interested in a solution where you can easily make `/api/foobar` and `/api/foobar/` coexists.

**Comment by vitalik** [comment]
@taobojlen @LouisDelbosc 

you can try to achieve this with django middleware

1) make sure all your apis ends with slash

2) create middleware that will append slash to every request:

```Python
def add_slash(get_response):
    def middleware(request):
        if not request.path.endswith('/'):
            request.path_info = request.path = f"{request.path}/"
        return get_response(request)

    return middleware

```

3) Add to settings.py

```Python
MIDDLEWARE = [
    # ...
    'path.to.yyour.middleware.add_slash',
    # ...
]
```

**Comment by lapinvert** [comment]
This should be part of the documentation and also provided by ninja utility middleware I guess, because this always(?) the behavior you want when you build an API.
