### ISSUE TITLE
Provide a way to specify response headers

### ISSUE THREAD

**Issue by playpauseandstop** [vitalik/django-ninja#106]
Seems like currently [Operation._result_to_response](https://github.com/vitalik/django-ninja/blob/5a19d230cb451f1f3ab0e167460bc05f49a6554e/ninja/operation.py#L106-L135) do not expect response headers from view function result (if not already part of `HttpResponse` instance).

This makes passing response headers tedious task.

Maybe `django-ninja` should allow view handler to setup response headers,

1. Via [temporal Response instance](https://fastapi.tiangolo.com/advanced/response-headers/) as done in FastAPI 
2. Or via [last tuple item](https://flask.palletsprojects.com/en/1.1.x/quickstart/#about-responses) as done in Flask

What do you think?

**Comment by vitalik** [comment]
FastAPI's seems nicer...

but the last item in tuple seems the easiest...
so that returning results can be like

 - {'response_body': 'foo'}
 - 201, {'response_body': 'foo'}
 - 202, {'response_body': 'foo'}, {'header1': 'Value'}
 
Looks a bit ugly/not-explicit...

maybe some helper class would make more sense

```
return Response({'body', 'foo'}, code=200, headers{'x-header1', 'value'}) 
```

**Comment by tomchuk** [comment]
I would like to add a note/suggestion regarding headers: In addition to adding the ability to set headers in individual responses, it would be handy to have a standard way to add headers across all endpoints in a `router` or `api` - perhaps implemented as a `render_headers` method of response renderers which `create_response` could call?

My use-case is calling `add_never_cache_headers` on all responses from an API

**Comment by vitalik** [comment]
@tomchuk 
well it is still controversial... some users preferrer one way other like different...

as for your case - if you need to add headers acrosss all endpoints just override


```Python
class MyApi(NinjaAPI):
    def create_response(self, *a, **kw):
            response = super.create_response(*a, **kw)
            response.headers['foo'] = 'bar'
            return response

api = MyApi()

```
