### ISSUE TITLE
Begin working on support for Django 3.2

### ISSUE THREAD

**Issue by bubthegreat** [vitalik/django-ninja#107]
It looks like pre-release has been available for a little bit, and with the 3.2 release, django will support async ORM operations.  

I'd love to use this project and was wondering if there's already any work under way to test/validate the async operations of the django ORM?

https://docs.djangoproject.com/en/3.2/releases/3.2/

**Comment by vitalik** [comment]
Hi @bubthegreat 

well I do not see any news in 3.2 release about the async ORM

but anyway async access to ORM is already possible with sync_to_async adapter:

https://django-ninja.rest-framework.com/async-support/#using-orm
