### ISSUE TITLE
A way to provide description for responses

### ISSUE THREAD

**Issue by Vulwsztyn** [vitalik/django-ninja#1077]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to add description to responses as in https://swagger.io/docs/specification/describing-responses/

**Describe the solution you'd like**
A field in some meta subclass for a schema, maybe?

If this is already possible, please add an example to the docs.

**Comment by RW21** [comment]
afaik `@summary` and `@description` are possible.

**Comment by Vulwsztyn** [comment]
@RW21 could you provide an example?

**Comment by vitalik** [comment]
@Vulwsztyn  you can find doss describing it here - https://django-ninja.dev/reference/operations-parameters/


```Python

@api.get("/some", summary="My summary", description="My description")
def some(request):
    ...

```

or description is also automatically taken from docstring:

```Python
@api.get("/some")
def some(request):
    """
    This is my description that will be in Swagger
    """
    ...
    
```

**Comment by Vulwsztyn** [comment]
@vitalik if I understand correctly that's for describing operations (endpoints) and not operation responses (an endpoint can have a few)

**Comment by vitalik** [comment]
@Vulwsztyn yeah.. well full response description is taken from http codes

but what you can do is overwrite description for your response schema:

```Python
class SomeShema(Schema):
    """
    This is the description of the schema that should be visible in swagger
    """
    ...

@api.get("/some", response={201: SomeShema})
...
```

**Comment by l1b3r** [comment]
You can also customize the response descriptions on a per-endpoint basis by populating openapi_extra:

```python
@api.get(
    "/some",
    response={
        200: SomeSchema,
        403: ForbiddenSchema
    },
    openapi_extra = {
        "responses": {
            200: {"description": "You will receive this response if everything is ok"},
            403: {"description": "You don't have what it takes for this API"}
        }
    }
)
def some(request):
    # ...
```

**Comment by Vulwsztyn** [comment]
@vitalik The way you provided doesn't work. Please see:
https://github.com/Vulwsztyn/django-ninja-testing/tree/response_desc_comment_override

@l1b3r Thank you. This works.
