### ISSUE TITLE
[Docs issue] Inconsistency in indentation

### ISSUE THREAD

**Issue by dabarov** [vitalik/django-ninja#1088]
It is a nitpicking but could you please fix this inconsistency in indentation:

<img width="981" alt="Screenshot 2024-02-19 at 23 52 00" src="https://github.com/vitalik/django-ninja/assets/36531464/dd0396fc-a8c7-4f7c-99b1-15c0125751a4">

It is in: [_Path parameters > Django Path Converters > Path params with slashes_](https://django-ninja.dev/guides/input/path-params/#path-params-with-slashes)

I guess it can be good-first-issue for someone.

**Comment by Nirmalkumar6112** [comment]
Hey, Created a PR.
Hope I have fixed the Issue.
