### ISSUE TITLE
Response renderers on routers/endpoints

### ISSUE THREAD

**Issue by ognjenk** [vitalik/django-ninja#109]
Hi,

is it possible to define different response renderers only on certain endpoints (or at least routers)?
As far as I can see from the docs, the only way to declare different renderer is to provide it to NinjaAPI instance.

But I would ideally like to be able to serve different output on same endpoint based on MIME type, so I would have the standard JSON response with application/json, and then XLS response for i.e. application/vnd.ms-excel.
Any info on how this could be done is much appreciated!

Thanks!

**Comment by vitalik** [comment]
Hi @ognjenk 


1) I guess you can access request.path in the render

```
from ninja.renderers import BaseRenderer

class MyRenderer(BaseRenderer):
    def render(self, request, data, *, response_status):
        if request.path.startswith('/router1/')
                return json.dumps(...)
         else:
               return excel.render(....)

api = NinjaAPI(renderer=MyRenderer)
```
2)

you can detect `Accept` header:

```
if request.headers['Accept'] == 'application/vnd.ms-excel':
    return excel.render
else:
   return json.rednder
```

**Comment by ognjenk** [comment]
Hi, thank you for the quick response!

I have managed to get this to work by detecting Accept headers in my Renderer and then calling the appropriate render method.
Thanks again!

**Comment by ognjenk** [comment]
One additional small question - is it possible to somehow change the list of values with media types in generated API doc? So that we can change accept header directly from there? It's a minor thing, so no problem if not possible.
Thanks!

**Comment by vitalik** [comment]
@ognjenk 
not sure I understand - can you give example of openapi that you get and expected ?

**Comment by ognjenk** [comment]
Hi,
actually I meant just this thing, but I understand that it is used to display response schema:
![image](https://user-images.githubusercontent.com/793415/112447287-71708900-8d51-11eb-89a6-5bb09015ce17.png)

My real question I guess is: is there a way to change -H  "accept: application/json" parameter that gets generated in request from API docs?

**Comment by vitalik** [comment]
@ognjenk  ok, I see..

I will keep this ticket open, maybe will find some solution later...

but as for now what you can do is override `get_openapi_schema` methhod:

```Python
class MyApi(NinjaAPI):
    def get_openapi_schema(self, path_prefix=None):
        schema = super().get_openapi_schema(path_prefix=path_prefix)
        for path in schema["paths"].values():
            for operation in path.values():
                for response in operation["responses"].values():
                    content = response.get("content", {})
                    if not content:
                        content["application/json"] = {}
                    content["application/vnd.ms-excel"] = {}    # !!!!!!!! <----- 
                    response["content"] = content
        return schema


api = MyApi()


```

**Comment by ognjenk** [comment]
Hi, yes I see, this works great!
It's a really minor thing so if it is not in the scope of your app feel free to close the issue.
Thank you!
