### ISSUE TITLE
Creating data with POST request

### ISSUE THREAD

**Issue by Harshav0423** [vitalik/django-ninja#1095]
I have a model in that a field takes ManyToManyField with reference to a Model. It throws an error, can't bulk assign the data, and suggests to use `.set(data)`. is there any other way to create the data?
```
PrimaryModel:
    id = UUIDField(primary_key=True, editable=False)
    actors = ManyToManyField(Actor, blank=True)
```

```
Actor:
    id = UUIDField(primary_key=True, editable=False)
    name=CharField(max_length=50)
```
While there is a `post` request to the PrimaryModel, the payload comes as `[id, id]`.

```Python
@router.post("/", response={201: MovieOut})
def create_movie(request, data: MovieIn):
    list_id = data.list_id
    result = Term.objects.create(**data.dict(exclude=["actors"]))
    result.actor.set(data.actor)
    return 201, result
  ```

**Comment by vitalik** [comment]
@Harshav0423 

 - what's your django-ninja version
 - share code of your  your your MovieIn
 - what error do you see (show traceback)
 - I see you  called field `actors` but in view you calling `result.actor.set` (without s)
 - I think `.set(...)` should actually take array

**Comment by Harshav0423** [comment]
Thanks @vitalik, `.set()` does work.
