### ISSUE TITLE
nested schema not working on many to many fields

### ISSUE THREAD

**Issue by bugiebhavya** [vitalik/django-ninja#11]
i used a nested schema to get data of the many to many field but it does not seem to work.

**Comment by bugiebhavya** [comment]
here music_genre is  manytomanyfield on user

class UserSchema(Schema):
	id: int
	name: str
    
class UserOut(Schema):
    id: int
    username: str
    about: str
    music_genre: UserSchema



    result = self.response_model(response=result).dict()["response"]
  File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Response
response -> music_genre -> id
  field required (type=value_error.missing)
response -> music_genre -> name
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by vitalik** [comment]
@bugiebhavya 

not sure if I understand this correctly - but here is my guess:

you have the following models structure:



```python

class MusicGenre(models.Model):
       name = models.CharField(...)


class User(models.Model):
      username = models.CharField(...)
      about = models.CharField(...)
      music_genre = models.ManyToManyField(MusicGenre) # <--m2m !!!!!!
```


Now to return a user with list of genres:

```python

from typing import List

class MusicGenreSchema(Schema):
    id: int
    name: str

class UserOut(Schema):
    id: int
    username: str
    about: str
    music_genre: List[MusicGenreSchema]  # <-- typing.List !!!!!

@api.post("/foo", response=UserOut)
def some_operation(request, ...):
       user = ... get from db ...
       user.music_genre = list(user.music_genre.all())  # evaluate m2m queryset to list
       return user
  

```

yeah, it's a bit uncomfortable at the moment, but there are plans to allow to attach m2m fields directly to schemas

**Comment by vitalik** [comment]
hey @bugiebhavya, let me know if it worked for you
