### ISSUE TITLE
[BUG] The other API URLs work, but the openapi docs don't appear.

### ISSUE THREAD

**Issue by TGoddessana** [vitalik/django-ninja#1110]
**Describe the bug**
The other API URLs work, but the openapi docs don't appear.

in `config/ninja_api.py`, see this:
```python
api = NinjaAPI(urls_namespace="api")

api.add_router("/users/", users_router)

```

and `users/api/views.py`:
```python
# other imports..
from ninja import Router

users_router = Router(tags=["users"])


@users_router.get("/", response=list[UserSchema])
def user_list(request):
    return User.objects.all()


@users_router.get("{username}/", response=UserSchema, url_name="user-detail",)
def user_detail(request, username: str):
    return User.objects.get(username=username)

```

and what i see with `1270.0.1:8000/api/docs/`:

<img width="1191" alt="스크린샷 2024-03-20 오전 3 49 22" src="https://github.com/vitalik/django-ninja/assets/88619089/95d45fa0-ea3b-4a73-906d-939e1ecab98e">

this is weird. cuz `127.0.0.1:8000/api/users/` really works.

<img width="896" alt="image" src="https://github.com/vitalik/django-ninja/assets/88619089/e9056c3e-687a-476c-9c47-a17d067bbe55">

i think this occurs because original docs URL in `NinjaAPI` doesn't have trailing slash.
(look debug message from first screenshot, the url named `api/docs`, not `api/docs/`)

if i change docs url like below, it works.

```python
api = NinjaAPI(urls_namespace="api", docs_url="docs/")
```

<img width="896" alt="image" src="https://github.com/vitalik/django-ninja/assets/88619089/10c1a8f8-6275-41ed-bbe5-cfb2537d3ed3">

However, the test code below from the django ninja package passes. i don't know what i'm doing wrong..

<img width="612" alt="image" src="https://github.com/vitalik/django-ninja/assets/88619089/7fd923e1-128e-40af-a05b-843d0719a10b">

Is this a bug, or did I do something wrong?

**Versions (please complete the following information):**
 - Python version: 3.12
 - Django version: 4.2.11
 - Django-Ninja version: 1.1.0
 - Pydantic version: 2.6.4

**Comment by pmdevita** [comment]
I suspect this is a "slash or no slash at the end of the URL" sort of problem. The endpoint is mounted to `/docs` but in your browser screenshot you are at `/docs/`

**Comment by TGoddessana** [comment]
Yup my browser auto redirects to /docs/.

**Comment by TGoddessana** [comment]
Okay, let's dig a little deeper into this.

It turns out that the problem is not reproducible in safari - as I expected, the document appears fine because there is no trailing / (because the browser doesn't automatically append /).

Can we consider this a bug and do we need a pull request for this?
I'd love to hear your thoughts. @vitalik 

<img width="697" alt="image" src="https://github.com/vitalik/django-ninja/assets/88619089/55722b3e-f543-446a-8422-44b754cc7543">

**Comment by pmdevita** [comment]
Having been confused by a trailing slash before with Django myself, I'm almost certain you're seeing normal behavior, you just need to remove the slash from the end of the URL. `/api/docs` and `/api/docs/` are not equivalent URLs. Run `curl http://127.0.0.1:8000/api/docs` and post that if it's not a 200. Chrome will automatically add a slash if `/api/docs` 404s to try to find it. It may have also cached Django's redirect from adding the slash to the endpoint configuration yourself.
