### ISSUE TITLE
Traversing the data structures to create an HTTP API client

### ISSUE THREAD

**Issue by scrwghub** [vitalik/django-ninja#1119]
I love ninja and have been using it in all my projects for a few years now.

As part of my workflow, I implement a command line python HTTP client for every single API endpoint I create. This is needed to fulfill unusual login/cryptographic/websocket requirements that can't be handled by Curl, Hurl and company, but also very useful for development, debugging and testing (this client is scriptable and outputs performance stats).

Naturally there is a common library of code shared among projects and then the implementation of the individual api client calls. My goal is to replace the implementation of the individual calls by running within the django/ninja context and traversing the Ninja data structures to obtain the **urls**, **http methods**, **schemas** and **url parameters** programmatically. If I manage this to a satisfactory degree, I would likely release the whole thing as Free Software after some polishing.

I welcome guidance in what objects/methods/functions can give me that information if we start for example from the context of running `manage.py shell` on a working ninja project.

Many thanks.

**Comment by pmdevita** [comment]
I might be misunderstanding but it sounds like OpenAPI is what you want, Ninja generates an OpenAPI spec already that describes everything you listed (urls, http methods, schemas and url parameters). You'll still probably need to devise your own parser to meaningfully turn it into a command line tool, it doesn't look like a command line client for OpenAPI already exists. If you're just looking to generate a Python client, there's this project here https://github.com/openapi-generators/openapi-python-client

**Comment by pmdevita** [comment]
Lol glad I could help
