### ISSUE TITLE
[BUG] ModelSchema with ManyToManyField won't work under async views

### ISSUE THREAD

**Issue by sunhs** [vitalik/django-ninja#1129]
**Describe the bug**

Say I have the following models.

```python
class Tag(models.Model):
    text = models.CharField(max_length=32, unique=True)

class Doc(models.Model):
    title = models.CharField(max_length=512)
    content = models.TextField()
    tags = models.ManyToManyField(Tag)
```

And the schema.

```python
class DocSchema(ModelSchema):
    class Meta:
        model = Doc
        fields = ["title", "content", "tags"]
```

Then use it in an async view.

```python
@doc_router.get("/", response=List[DocSchema])
async def get_docs(request):
    qs = Doc.objects.filter(user=request.auth)
    return [doc async for doc in qs]
```

This will yield an error.

```log
response.0.tags
  Error extracting attribute: SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async. [type=get_attribute_error, input_value=<DjangoGetter: <Doc: Basi...th Django and Postgres>>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.6/v/get_attribute_error
```

Looking into `DjangoGetter._convert_result`, it's returning `list(result.all())` since `result` is an instance of `Manager`.

It seems that async model validation is not taken into account now, so this may not be a bug, but rather a feature request?

If currently no plan to support this scenario, is there any workaround to address the problem?

**Versions (please complete the following information):**
 - Python version: 3.12
 - Django version: [5.0.3]
 - Django-Ninja version: [1.1.0]
 - Pydantic version: [2.6.4]

**Comment by uzineck** [comment]
check this, maybe it would help https://django-ninja.dev/guides/async-support/#using-orm

**Comment by sunhs** [comment]
Thank you. I understand how to use ORM with async. But `ModelSchema` seems not to be supporting this right now?

**Comment by ariponce** [comment]
You'll get the same error with any related fields on a model, it doesn't matter if you're using a `ModelSchema` or a base `Schema`.

From what I gather, the issue comes from the `getattr` call on the `DjangoGetter` class. Since the attributes are related fields, django will make a DB call to retrieve the values synchronously, causing the SynchronousOnlyOperation exception.

I'm not sure if this can be handled by ninja directly, but you can avoid this error by prefetching the related objects, using either `prefetch_related` or  `select_related`  depending on the type of relation.

**Comment by adambenali** [comment]
`_convert_result` doesn't indeed seem to support async operations, so whenever a database hit is required, the function will fail.

To add to @ariponce's comment and workaround, if you need to do this for a single model instance, you can use await `(a)prefetch_related_objects`. e.g.:

```python
await aprefetch_related_objects([user_instance], "groups", "user_permissions")
```

**Comment by sunhs** [comment]
@ariponce Thanks. Not familiar with `prefetch_related`, but for now it works as expected.
