### ISSUE TITLE
Router should support url_name

### ISSUE THREAD

**Issue by rajaiswal** [vitalik/django-ninja#113]
Based on the documentation: [docs: url_name](https://django-ninja.rest-framework.com/tutorial/operation_params/#url_name)
we can do:

```python
@api.post("/tasks", url_name='tasks')
def some_operation(request):
    pass
```

But what if we have routers defining the view like:
```python
@router.post("/tasks", url_name='tasks')
def some_operation(request):
    pass
```
Throws an error:
```python
File "/...", line 20, in <module>
    from test import api_v1
  File "/.../api_v1.py", line 5, in <module>
    from org.api_v1 import router as org_router
  File "/.../api_v1.py", line 135, in <module>
    url_name="test"
TypeError: post() got an unexpected keyword argument 'url_name'
```
Not sure if I am missing something, is there some other way to do this with router based url definition?

**Comment by vitalik** [comment]
@rajaiswal 
can you check your ninja `__version__`
url_name introduced in `0.12`

**Comment by rajaiswal** [comment]
@vitalik You're right, I didn't have the latest update, apologies for my ignorance. It works as expected in `0.12`. I will close the issue.
