### ISSUE TITLE
Security (best practice): Not every exception during validation is a validation error

### ISSUE THREAD

**Issue by Adamantish** [vitalik/django-ninja#114]
While working locally I saw the server return a 400 response like this

```json
{
  "detail": [
    {
      "loc": [
        "body",
        "farmer_request",
        "retailer_phone_number"
      ],
      "msg": "is_valid_number() missing 1 required positional argument: 'numobj'",
      "type": "type_error"
    }
  ]
}
```

It occurred inside `PhoneNumber`, a [custom type](https://pydantic-docs.helpmanual.io/usage/types/#classes-with-__get_validators__) I'm working on. This was a basic programming error, in this case just because I typed the wrong function name and such a problem couldn't reach production. 

But I wonder what other runtime errors could come up in production and expose arbitrary internals to API users especially if I were undisciplined about encapsulating a custom type like that. I don't know if there are other ways of causing this trouble without custom types.

Might it be possible to whitelist certain exception types which allow a message to be displayed and any others will only display if `DEBUG=True`?

**Comment by vitalik** [comment]
@Adamantish 

I would ask this one at pydantic... I guess goal here should be that it should raise general `Exception` instead of pydantic.ValidationError..

but meanwhile you can just add exception handler for `ValidationError` and sanitise/clean `message`

see docs https://django-ninja.rest-framework.com/tutorial/errors/#ninjaerrorsvalidationerror

**Comment by vitalik** [comment]
btw, can you show your code - maybe you actually catching Exception instead of ValueError or something and re-raising original message as ValueError ?

**Comment by Adamantish** [comment]
Thanks @vitalik If it's actually a Pydantic ValidationError then yes that's where I'll take this.

Here are the relevant parts

```python
def _unhandled_error(request, exc):
    capture_exception(exc)

    return api.create_response(
        request,
        ErrorMessage.prepare_unhandled_error(exc),
        status=500,
    )


for api in (api_sys, api_v1, api_v2):
    api.add_exception_handler(
        ValidationError,
        lambda request, exc: api.create_response(
            request, NinjaNativeErrorMessage.prepare_request_validation_error(exc), status=400
        ),
    )

    api.add_exception_handler(
        RequestValidationError,
        lambda request, exc: api.create_response(
            request, ErrorMessage.prepare_request_validation_error(exc), status=400
        ),
    )

    api.add_exception_handler(Exception, _unhandled_error)
```
We know it wasn't caught by the general Exception catcher because it came back with a 400.

(Note: `RequestValidationError` comes from our app and is just my near clone of the ninja `ValidationError` except using a version of an `ErrorMessage` schema which uses Enum restricted "type" values. We had to make a schema to document and enforce the error response format which I've just seen [here](https://github.com/vitalik/django-ninja/blob/4ee97cb7c8a99942e72a87c7682319295b5bf179/ninja/operation.py#L194) is already implicitly defined by pydantic.)

 As you can probably tell, we really are trying to keep the `msg` when it's actually a validation error.
