### ISSUE TITLE
[BUG] cdn error.

### ISSUE THREAD

**Issue by quroom** [vitalik/django-ninja#1146]
**Describe the bug**
It's not bug.
It has cdn error.
```
GET https://cdn.jsdelivr.net/npm/swagger-ui-dist@4.15.5/swagger-ui.css net::ERR_CERT_DATE_INVALID
docs:12 
GET https://cdn.jsdelivr.net/npm/swagger-ui-dist@4.15.5/swagger-ui-bundle.js net::ERR_CERT_DATE_INVALID
docs:14 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at docs:14:20
(anonymous) @ docs:14
```

It looks like jsdelivr.net ssl certificate is expired.

**Versions (please complete the following information):**
 - Python version: 3.9
 - Django version: 4.2.1
 - Django-Ninja version: 0.21
 - Pydantic version: 1.10.8

**Comment by quroom** [comment]
How do you think include those static files in this repo.

**Comment by ndjman7** [comment]
Same issue.

The same thing happens in other versions of the Swagger ui.

```
GET https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css net::ERR_CERT_DATE_INVALID
GET https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js net::ERR_CERT_DATE_INVALID
```

**Version**
- Python version: 3.11.1
- Django: 4.2.7
- Django-Ninja version: 1.0.1
- Pydantic versin: 2.5.2

**Comment by ivvve** [comment]
FYI: https://github.com/jsdelivr/jsdelivr/issues/18565
