### ISSUE TITLE
When are we getting a new release?

### ISSUE THREAD

**Issue by austinpgraham** [vitalik/django-ninja#1164]
1.1.0 was released late last year, and since then there have been some awesome bug fixes and other additions. What can myself or other contributors do to help push along cutting a new release so the wider audience can start reaping these benefits?

**Comment by GoldenCorgo** [comment]
From the owner's profile: he is originally from Kharkiv, Ukraine. Currently the situation worsened pretty much in the region. I hope he is safe and we will here from him soon.

**Comment by austinpgraham** [comment]
Ah, thanks for pointing that out @GoldenCorgo. We pray for his safety.

**Comment by d33kayyy** [comment]
hi @vitalik hope you doing well. I just saw you committed some stuff 2 weeks ago, any update on this?
