### ISSUE TITLE
Cookies and responses

### ISSUE THREAD

**Issue by ifxory-plugins** [vitalik/django-ninja#117]
Just needed to set cookie when returning json from an api-function.

**Comment by vitalik** [comment]
@ifxory-plugins 

for now you can jsut output django HttpResponse with cookies

...

but there is similar discussion here #106 about headers

feel free to add your thoughts ..

I thinkn the niciest solution woult be to have some builtin Response object which can render objects and also you can pass there headers and cookies

**Comment by ifxory-plugins** [comment]
> @ifxory-plugins
> 
> for now you can jsut output django HttpResponse with cookies
> 
> ...
> 
> but there is similar discussion here #106 about headers
> 
> feel free to add your thoughts ..
> 
> I thinkn the niciest solution woult be to have some builtin Response object which can render objects and also you can pass there headers and cookies

Yes, in my opinion, this should be the most correct and convenient solution.
