### ISSUE TITLE
[BUG] Pydantic doesn't allow null=True on BooleanFields when using ModelSchema.

### ISSUE THREAD

**Issue by lanzclintonv** [vitalik/django-ninja#1179]
Using `models.BooleanField(default=True, null=True, blank=True)` and `ModelSchema` leads to an error when pulling up data that has a null value. The issue seems to be from pydantic as this is the error message:

> Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]
>     For further information visit https://errors.pydantic.dev/2.7/v/bool_type

Sample Model:

```
class Customer(models.Model):
  last_name = models.CharField(max_length=255)
  first_name = models.CharField(max_length=255)
  is_active = models.BooleanField(default=True, null=True, blank=True)
```

Sample Schema:
```
class CustomerOutSchema(ModelSchema):
  class Meta:
    model = Customer
    fields = "__all__"
```

Sample API:

```
@api.get("/customer/", response=List[CustomerOutSchema], tags=["Customer"])
def get_customer_list(request):
    customer = Customer.objects.all()
    return customer
```

Current workaround see to be adding the boolean field in fields_optional.

`fields_optional = 'is_active'`

This doesn't seem to be the standard as other fields, such as ForeignKey, DateField, and CharField is allowed to be null if null=True is configured.

**Versions**
 - Python version: [3.12.3]
 - Django version: [5.0.6]
 - Django-Ninja version: [1.1.0]
 - Pydantic version: [2.7.1]

**Comment by JFeldaca** [comment]
I don't see the point in having a null field with a default value, it's contradictory.

**Comment by lanzclintonv** [comment]
> I don't see the point in having a null field with a default value, it's contradictory.

That's true. But some data are migrated elsewhere and, migrated data where rules have changed will have null values and filling them with True or False won't make sense.
