### ISSUE TITLE
Docs not updated?

### ISSUE THREAD

**Issue by boxed** [vitalik/django-ninja#1194]
https://django-ninja.dev/guides/testing/ incorrectly mentions `NinjaTestClient`, but https://github.com/vitalik/django-ninja/blob/master/docs/docs/guides/testing.md does not.

**Comment by stumpylog** [comment]
https://github.com/vitalik/django-ninja/commits/master/docs/docs/guides/testing.md makes it clear.

**Comment by boxed** [comment]
3 months old hmm. I guess this ticket should be about setting up CI for the docs..

**Comment by stumpylog** [comment]
The publish job is run when a release is created.  So given there hasn't been a release in a bit, the docs would not be expected to be updated until that point.  Expected, given the documentation is versioned.

**Comment by stumpylog** [comment]
Given the new release, this can be closed
