### ISSUE TITLE
Typing improvements

### ISSUE THREAD

**Issue by sobolevn** [vitalik/django-ninja#12]
Hi! Thanks a lot for building this project. It looks really interesting.

I have seen that your docs says that 
> Type hints and automatic docs let's you focus only on business logic

But, there are some things to improve in this field:
1. You are missing `py.typed` file in the root, example: https://github.com/dry-python/returns/blob/master/returns/py.typed Without this file `mypy` won't be able to know that sources are typed
2. `mypy` support! This is very important for end users of typed libs. I was not able to find any `mypy` references in the CI 
3. `django-stubs` support. I have seen that you have troubles typing `HttpRequest` and `HttpResponse`. That's what `django-stubs` can solve! https://github.com/typeddjango/django-stubs

Cheers! 👍

**Comment by vitalik** [comment]
Hi @sobolevn 
Thanks for the feedbak
Indeed py.typed / mypy support is in my backlog - stay tuned ;)
