### ISSUE TITLE
Why is django-ninja PUT endpoint not using value from request body but instead is returning the default value for field to be updated (ModelSchema)?

### ISSUE THREAD

**Issue by shadowplumber** [vitalik/django-ninja#1215]
I've made a [detailed explanation of the issue on StackOverflow](https://stackoverflow.com/questions/78693858/why-is-django-ninja-put-endpoint-not-using-value-from-request-body-but-instead-i). It's my first time trying to use Django Ninja, so it could just be a total goof on my part, but I can't find anything in the documentation about what might be causing the issue.

**Comment by vitalik** [comment]
@shadowplumber 

seems you just forgot to return result from endpoint ?

```Python
@api.put("/member/{member_id}", response={200: UserTimezoneSchema, 404: NotFoundSchema})
def change_tz(request, member_id: int, data: UserTimezoneSchema):
    try:
        member = User.objects.get(pk=member_id)
        member.tz_preference = data.tz_preference
        member.save()
        return member     # <-------------------------------- try this -------------- !
    except User.DoesNotExist as e:
        return 404, {'message': 'User does not exist'}
```

**Comment by shadowplumber** [comment]
Was a total goof on my part; that made everything work as expected. Thanks @vitalik!
