### ISSUE TITLE
Throttling is not support async based view

### ISSUE THREAD

**Issue by itm10** [vitalik/django-ninja#1217]
why throttling is not working in async, it works in simple function based view
How can i troubleshoot it

**Comment by itm10** [comment]
this code works in simple function based view
here is code:

from ninja.throttling import AnonRateThrottle, SimpleRateThrottle, UserRateThrottle


load_dotenv()

sadulla_hakim = Router(throttle=[AnonRateThrottle('3/h')])


@sadulla_hakim.get("/category-get/", response=list[dict])
def get_category(request):
    categories = Categoriya.objects.all()
    category_tree = build_category_tree(categories)

    return JsonResponse(category_tree, safe=False)
    
  
  
  but when i used async based view, there is no affect of throttling to view:
  
  here is code of async based view:
  
  
  from ninja.throttling import AnonRateThrottle, SimpleRateThrottle, UserRateThrottle


load_dotenv()

sadulla_hakim = Router(throttle=[AnonRateThrottle('3/h')])


@sadulla_hakim.get("/category-get/", response=list[dict])
async def get_category(request):
    categories = await sync_to_async(list)(Categoriya.objects.all())
    category_tree = build_category_tree(categories)

    return JsonResponse(category_tree, safe=False)

**Comment by vitalik** [comment]
@itm10 please try with version 1.2.1
