### ISSUE TITLE
reverse() cannot resolve url_name if same url but different method

### ISSUE THREAD

**Issue by rajaiswal** [vitalik/django-ninja#122]
In this example we have defined POST and GET (list) endpoints that have the same url.

```python
@router.post("/employees", url_name="create-employees")
def create_employee(request, payload: EmployeeIn):
    pass


@router.get("/employees", url_name="get-employees", response=List[EmployeeOut])
def list_employees(request):
    pass
```
For some reason when I do the reverse() url lookup I get an error for `"create-employees"` and success for `"get-employees"`. If I switch the order of view definition then `"create-employees"` works and  `"get-employees"` doesn't. The one defined after seems to be overwriting the one defined before. Am I doing something unexpected?

Ninja version: 0.12.2

**Comment by vitalik** [comment]
@rajaiswal 
well django does not let you set 2 names for the same path...

I would just call it employees for both

`@router.post("/employees", url_name="employees")`
`@router.get("/employees", url_name="employees", response=List[EmployeeOut])`

and then call with GET employees, and POST employees

**Comment by rajaiswal** [comment]
@vitalik Oh I see, that makes sense. Yeah I ended up doing the 1 url for both thing. Thanks for quick response, will close the issue. Also, really enjoying this library so really appreciate all the awesome work you are doing!

**Comment by redlovv** [comment]
This will work.

```py
@router.post("/employees", url_name="employees")
def create_employee(request, payload: EmployeeIn):
    pass


@router.get("/employees", url_name="employees", response=List[EmployeeOut])
def list_employees(request):
    pass
```
