### ISSUE TITLE
[BUG] Swagger UI always sends requests using the first defined HTTP method for endpoints with the same name

### ISSUE THREAD

**Issue by luckyabsoluter** [vitalik/django-ninja#1221]
**Versions (please complete the following information):**
 - Python version: 3.12.4
 - Django version: 5.0.6
 - Django-Ninja version: 1.2.1
 - Pydantic version: 2.8.2

**Describe the bug**
When defining multiple API endpoints with the same name but different HTTP methods (e.g., GET, POST) using django-ninja, the Swagger UI(Try it out, Execute) consistently sends requests using the HTTP method of the first defined endpoint, regardless of the method selected in the UI.

For example, if a POST endpoint named "hello" is defined first, followed by a GET endpoint also named "hello", the Swagger UI will send POST requests even when attempting to execute the GET endpoint. Conversely, if the GET endpoint is defined first, all requests will be sent as GET, even for the POST endpoint.

This behavior occurs despite the Swagger UI correctly displaying both endpoints with their respective methods.

This makes it impossible to test different HTTP methods for endpoints with the same name using the built-in Swagger UI documentation.

``` python
from ninja import NinjaAPI, Schema
api = NinjaAPI()

@api.get("/hello")
def hello(request):
    return "Hello world"

class HelloSchema(Schema):
    name: str = "world"

@api.post("/hello")
def hello(request, data: HelloSchema):
    return f"Hello {data.name}"
```

POST requests function correctly when sent manually.
The issue only occurs when using the "Try it out" button in Swagger UI.

![image](https://github.com/vitalik/django-ninja/assets/80892490/ad6cbdd7-d6cc-434c-85cf-5d014a3d85b7)

---
# Separator
## Line
---

![image](https://github.com/vitalik/django-ninja/assets/80892490/b2eff868-4d29-4b06-b104-3cc5444564e6)

**Comment by mister-rao** [comment]
function names should be different for each http method

**Comment by vitalik** [comment]
@luckyabsoluter 
Yes, @mister-rao is right - the problem that you have a function with the same name (not a good practice) 

I made an extra warning print during init - in new version it will print in red bold that function better have different names
