### ISSUE TITLE
How to receive keys that don't already know

### ISSUE THREAD

**Issue by chengair** [vitalik/django-ninja#1235]
as in fastapi :
Bodies of arbitrary dicts[¶](https://fastapi.tiangolo.com/tutorial/body-nested-models/#bodies-of-arbitrary-dicts)
You can also declare a body as a dict with keys of some type and values of some other type.
This way, you don't have to know beforehand what the valid field/attribute names are (as would be the case with Pydantic models).
This would be useful if you want to receive keys that you don't already know.

what can we do in ninja to  receive keys that don't already know

**Comment by vitalik** [comment]
you need to highlight to read dict from Body

```python
from ninja import Body


@api.post("/test")
def test(request, data: Body[dict[str, int]]):
    return {"data": data}

```
