### ISSUE TITLE
[QUESTION] Endpoint returns 422 even via api/docs

### ISSUE THREAD

**Issue by MKindshofer** [vitalik/django-ninja#1236]
I want to update an Entry with a PUT request. It also Includes an Optional File Upload

```
class UnterlageCreateSchema(Schema):
    name: str
    version: str
    anmerkung: Optional[str] = ''
    ablageort: Optional[str] = ''
    stand: str

@mitgeltende_unterlagen_router.post("/", response={201: UnterlageSchema})
def create_unterlage(request: HttpRequest,  data: UnterlageCreateSchema, dokument: Optional[UploadedFile] = File(None)):
    if not request.auth.has_perm("mitgeltende_unterlagen.add_unterlage"):
        return 403
    unterlage = Unterlage.objects.create(**data.dict())
    if dokument:
        unterlage.dokument.save(dokument.name, dokument)

    return unterlage

@mitgeltende_unterlagen_router.put("/{id}/", response={201: UnterlageSchema})
def update_unterlage(request: HttpRequest, id: int, data: UnterlageCreateSchema, dokument: Optional[UploadedFile] = File(None)):
    if not request.auth.has_perm("mitgeltende_unterlagen.change_unterlage"):
        return 403
    unterlage = Unterlage.objects.get(id=id)
    for attr, value in data.dict().items():
        setattr(unterlage, attr, value)
    unterlage.save()
    if dokument:
        unterlage.dokument.save(dokument.name, dokument)

    return unterlage
```

update_unterlage returns 422, while create_unterlage works. Even from the `/api/docs/` page the update function does not work:

![image](https://github.com/user-attachments/assets/9189345a-af5d-4e50-a144-646ee2a1f6d3)

What am I doing wrong here?

**Comment by vitalik** [comment]
Hi @MKindshofer 

for some reason django does not process files during PUT requests..

to avoid this you can add middleware that will read files - here is one example - https://github.com/vitalik/django-ninja/issues/1059#issuecomment-1904178553

**Comment by KonstantinosPetrakis** [comment]
Hello @vitalik! 

I want to share that the issue doesn't concern only files, it concerns Forms in general. The issue persists even if a form with plain data (urlencoded form) without files is used.

Can't anything be done to fix this issue without workarounds such as the one suggested in [issue 1059](https://github.com/vitalik/django-ninja/issues/1059#issuecomment-1904178553)? I think it's pretty common to use forms with PATCH/PUT methods. I can only imagine me copying the suggested middleware to almost every project I work. 

Thanks for your time!
