### ISSUE TITLE
Authentication Docs Error

### ISSUE THREAD

**Issue by luizfelipevbll** [vitalik/django-ninja#125]
![image](https://user-images.githubusercontent.com/40257388/116146811-4dd49180-a6b5-11eb-967b-8204e8a95eb8.png)
![image](https://user-images.githubusercontent.com/40257388/116146862-5e850780-a6b5-11eb-8fd0-658ec88a0615.png)

I am trying to use Django Auth system, but the Docs are not working on POST/PUT requests and also on Django core admin requests.

Config:
```python3
api = NinjaAPI(csrf=True, auth=[django_auth])
```
The only way I could do to access and execute a POST on the Swagger documentation is by adding **@csrf_exempt** decorator from django.views.decorators.csrf

```python3
@router.delete('/v1/auth/logout/', auth=None)
def auth_logout(request):
    logout(request)
    resp = HttpResponseRedirect('/')
    # trocar o método para GET -> 303
    resp.status_code = 303
    return resp


@router.post('/v1/auth/status/')
@csrf_exempt
def auth_status(request):
    if request.user.is_authenticated:
        return True
    else:
        return HttpError(401, 'Unauthenticated')
```
I already tryed commenting django.middleware.csrf.CsrfViewMiddleware, but doest work.

Is there a way to use django_sessions with documentation working on POST requests and default admin endpoints? if not, just allow us to use django_auth without forcing to enable CSRF token pls.

**Comment by vitalik** [comment]
Hi @luizfelipevbll 

CSRF should work in swagger UI:

![CleanShot 2021-04-27 at 00 31 12@2x](https://user-images.githubusercontent.com/95222/116153440-f7d10f80-a6ef-11eb-8f1c-ce586a7d0cef.png)

what browser do you use ?

**Comment by luizfelipevbll** [comment]
> Hi @luizfelipevbll 
> 
> CSRF should work in swagger UI:
> 
> ![CleanShot 2021-04-27 at 00 31 12@2x](https://user-images.githubusercontent.com/95222/116153440-f7d10f80-a6ef-11eb-8f1c-ce586a7d0cef.png)
> 
> what browser do you use ?
> 
> 

 
I am currently using Firefox for Linux
I'll try again with another browser

**Comment by luizfelipevbll** [comment]
> what browser do you use ?

I tried using Chrome, but still have the same problem 
![image](https://user-images.githubusercontent.com/40257388/116237899-23c3b380-a737-11eb-85c6-7133be32ce62.png)

**Comment by vitalik** [comment]
are you sure 403 is CSRF ?

would you be able to create some reproducable example of code zip ?

**Comment by luizfelipevbll** [comment]
![image](https://user-images.githubusercontent.com/40257388/116241843-b8c8ab80-a73b-11eb-8afe-c27e9ecc681d.png)



> would you be able to create some reproducable example of code zip ?
I cant, this project has sensitive content. But I can show some parts of it.


This is are the classes used to authenticate the user and store the SessionID cookie
```python


def store_token_user(request, token, user, usuario):
    # Precisamos ver se já existe um token, se existir vamos atualizar o token, se não existir vamos criar um novo!
    try:
        microsoft_token = TokenMicrosoft.objects.get(usuario=usuario)
        microsoft_token.token = token
        microsoft_token.save()
    except TokenMicrosoft.DoesNotExist:
        microsoft_token = TokenMicrosoft.objects.create(usuario=usuario, token=token)
        microsoft_token.save()

    login(request, microsoft_token.usuario)
    request.session['oauth_token'] = token
    
```
    
 After that the user is authenticated 
 
 Isnt this supposed to have a field to input the CSRF? or should it get the CSRF cookie from session with django [CSRF_USE_SESSIONS](https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-use-sessions) ?

![image](https://user-images.githubusercontent.com/40257388/116243192-114c7880-a73d-11eb-81af-fd2dfab79063.png)

**Comment by vitalik** [comment]
do you run swagger on the same host as api ?

note: csrf token is [obtained by javascript using swagger.requestInterceptor](https://github.com/vitalik/django-ninja/blob/5d3454815f8cddf4f6f8771b20103de95a206e29/ninja/templates/ninja/swagger.html#L25)

**Comment by vitalik** [comment]
@luizfelipevbll btw you can verify it clicking view source on the swagger ui page

you should fine this line in html:
```
req.headers['X-CSRFToken'] = ...
```

**Comment by luizfelipevbll** [comment]
> do you run swagger on the same host as api ?
Yes, they are the same


> @luizfelipevbll btw you can verify it clicking view source on the swagger ui page
> 
> you should fine this line in html:
> 
> ```
> req.headers['X-CSRFToken'] = ...
> ```

I just checked, but seems it is not getting the CSRF from the cookie to set this X-CSRFToken Header

![image](https://user-images.githubusercontent.com/40257388/116245747-a3558080-a73f-11eb-935b-fb5b18cfa5f9.png)
![image](https://user-images.githubusercontent.com/40257388/116245905-d8fa6980-a73f-11eb-8d52-30b75200eb1e.png)

**Comment by vitalik** [comment]
> I just checked,
how you checked ?

can you show screenshot of the view-source swagger page ?

![CleanShot 2021-04-27 at 16 12 07](https://user-images.githubusercontent.com/95222/116247268-568b9d00-a773-11eb-9226-66760f1d296d.png)

**Comment by luizfelipevbll** [comment]
![image](https://user-images.githubusercontent.com/40257388/116248310-24157c00-a742-11eb-8d63-2342679f0dcb.png)
It seens is not entering on the if **api.csrf and csrf_token**

**Comment by luizfelipevbll** [comment]
![image](https://user-images.githubusercontent.com/40257388/116249232-fb41b680-a742-11eb-9444-5e5ee3a1b60d.png)
![image](https://user-images.githubusercontent.com/40257388/116249308-0f85b380-a743-11eb-8d3b-f634574e8c90.png)

**Comment by luizfelipevbll** [comment]
@vitalik found the problem for the Swagger CSRF...

I redefined the URLS to the docs to add _read_docs_ permission, but it was not sending the params of context to **swagger_cdn** function, my bad
just rewrite the line on **get_docs** func to:
` swagger_cdn(request, {'openapi_json_url': openapi_json_url, 'api': api, 'csrf_token': get_csrf_token(request)})`

Now the CSRF is working perfectly on docs!


![image](https://user-images.githubusercontent.com/40257388/116281236-e293c980-a75f-11eb-8792-3fbe91ba277a.png)
I still have problem with Django-Admin field referencig FK filters returning 403 but I dont think Its related to the django-ninja
will be closing this issue, thank you very much for the support

**Comment by wuwenrufeng** [comment]
@vitalik Why is there no session_id in the cookie? thanks
![image](https://github.com/user-attachments/assets/6925285d-2cf8-4d4c-b7ca-5930b2f7a647)
![image](https://github.com/user-attachments/assets/dd4a86a8-1fd3-4d0d-afff-a962bad3eb65)

**Comment by vitalik** [comment]
@wuwenrufeng hard to tell - need to see your code/authentication settings
