### ISSUE TITLE
Documentation Error on POSTing data

### ISSUE THREAD

**Issue by luizfelipevbll** [vitalik/django-ninja#128]
Hello, I have a POST endpoint, with this params:
```python
@router.post('/v1/update')
def update(request, id: int=Form(...), descricao: str=Form(None), id_reporte: int=Form(None), id_tipo: int=Form(None), id_usuario: int=Form(None), is_active: bool=Form(None)):
    try:
        table = Table.objects.filter(id=id, is_deleted=False).first()
        if descricao:
            table.descricao = descricao
        if id_reporte:
            id_reporte = None if id_reporte == 'null' else id_reporte
            table.estrutura_reporte_id = id_reporte
        if id_tipo:
            table.tipo_id = id_tipo
        if id_usuario:
            table.usuario_responsavel_id = id_usuario
        if is_active is not None:
            is_active = 1 if is_active else 0
            table.is_active = is_active
        table.save()
    except Exception:
        raise HttpError(400, 'Bad Request')
...
```

The only required parameter is the **id**, but every time I try to make a request on swagger I receive this error, even if I flag the arguments as **Send Empty Value**:

![image](https://user-images.githubusercontent.com/40257388/116609780-2971f280-a90b-11eb-84fa-d24eaf8f7b4b.png)
![image](https://user-images.githubusercontent.com/40257388/116609856-3f7fb300-a90b-11eb-9ddc-0bfcea479ed1.png)

These are the CURL headers being sent on swagger 
```sh
 -H  "Content-Type: application/x-www-form-urlencoded" -d "id=2&descricao=&id_reporte=&id_tipo=&id_usuario=&is_active="
 ```

**Comment by luizfelipevbll** [comment]
This error occurs even when I try using the Optional function
is_active: Optional[bool]=Form(None)
send empty value:
![image](https://user-images.githubusercontent.com/40257388/116695547-27557580-a997-11eb-8f6d-899c08746339.png)
Receive 422 response:
```json
{
  "detail": [
    {
      "loc": [
        "form",
        "is_active"
      ],
      "msg": "value could not be parsed to a boolean",
      "type": "type_error.bool"
    }
  ]
}
```

It seems all fields are being required even when I pass default as None on Form()
It happens for all fields that are being typed

**Comment by vitalik** [comment]
@luizfelipevbll  yes, seems like a bug

for now try the following workaround ?

```Python
class FormSchema(Schema):
     id: int
     descricao: str = None
     id_reporte: int = None
     id_tipo: int = None
     id_usuario: int = None
     is_active: bool = None


@router.post('/v1/update')
def update(request, data: FormSchema = Form(...)):
    table = Table.objects.filter(id=data.id, is_deleted=False).first()
    ...
```

**Comment by luizfelipevbll** [comment]
When trying to make POST/PUT using a request body as JSON it doesnt recognize the JSON format as default.

```python3
@router.post('/stuff/create')
def create_stuffrequest, id: int, value: str):
...
```
If the **=Form()** is not given, it understands as a Query parameter and not a request body of JSON type.
 
![image](https://user-images.githubusercontent.com/40257388/118163293-31945c80-b3f8-11eb-86be-187c4acceaac.png)

**Comment by luizfelipevbll** [comment]
> @luizfelipevbll yes, seems like a bug
> 
> for now try the following workaround ?
> 
> ```python
> class FormSchema(Schema):
>      id: int
>      descricao: str = None
>      id_reporte: int = None
>      id_tipo: int = None
>      id_usuario: int = None
>      is_active: bool = None
> 
> 
> @router.post('/v1/update')
> def update(request, data: FormSchema = Form(...)):
>     table = Table.objects.filter(id=data.id, is_deleted=False).first()
>     ...
> ```

I tryed this but still get the 422 error
![image](https://user-images.githubusercontent.com/40257388/118172088-5c83ae00-b402-11eb-8e82-deb017dc65f6.png)
![image](https://user-images.githubusercontent.com/40257388/118172219-81782100-b402-11eb-98aa-99727e20a3d1.png)

**Comment by stephenrauch** [comment]
This can be fixed, as described in the Pydantic docs, by using [Generic Classes as Types](https://pydantic-docs.helpmanual.io/usage/types/#generic-classes-as-types).

```python
from ninja import Form, Schema
from pydantic.fields import ModelField
from typing import Generic, TypeVar

PydanticField = TypeVar("PydanticField")


class EmptyStrToDefault(Generic[PydanticField]):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, value: PydanticField, field: ModelField) -> PydanticField:
        if value == "":
            return field.default
        return value


class Item(Schema):
    name: str
    description: str = None
    price: EmptyStrToDefault[float] = 0.0
    quantity: EmptyStrToDefault[int] = 0
    in_stock: EmptyStrToDefault[bool] = True


@api.post("/items-blank-default")
def update(request, item: Item=Form(...)):
    return item.dict()
```

**Comment by LexxLuey** [comment]
```python

class Movie(models.Model):
    class Status_Choices(models.IntegerChoices):
        COMING_UP = 1
        STARTING = 2
        RUNNING = 3
        FINISHED = 4

    name = models.CharField(max_length=200, null=True)
    protagonists = models.CharField(max_length=200, null=True)
    poster = models.ImageField(upload_to ='posters/', null=True)
    trailer = models.FileField(upload_to ='trailers/', null=True)
    start_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)
    status = models.IntegerField(choices=Status_Choices.choices, default=Status_Choices.COMING_UP)
    ranking = models.IntegerField(validators=[MinValueValidator(0, message="Cannot have ranking below 0")], default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "movie"
        verbose_name_plural = "movies"

    def __str__(self):
        return self.name

class MovieIn(ModelSchema):
    class Meta:
        model = Movie
        exclude = ["id", "created_at", "modified_at"]
        fields_optional = "__all__"


class MovieOut(ModelSchema):
    class Meta:
        model = Movie
        fields = "__all__"
        fields_optional = "__all__"


class Message(Schema):
    message: str


router = Router()


@router.post("/", response=MovieOut)
def create_movie(
    request,
    payload: MovieIn,
    poster_file: UploadedFile = None,
    trailer_file: UploadedFile = None,
):
    payload_dict = payload.dict()
    movie = Movie(**payload_dict)
    if not poster_file or trailer_file:
        movie.save()
    if poster_file:
        movie.poster.save(movie.name, poster_file)  # will save model instance as well
    if trailer_file:
        movie.trailer.save(movie.name, trailer_file)  # will save model instance as well
    return movie

@router.put("/{movie_id}", response=MovieOut)
def update_movie(
    request,
    movie_id: int,
    payload: MovieIn,
    poster_file: UploadedFile = None,
    trailer_file: UploadedFile = None,
):
    print(movie_id)
    print(payload)
    print(poster_file)
    print(trailer_file)
    movie = get_object_or_404(Movie, id=movie_id)
    for attr, value in payload.dict(exclude_unset=True).items():
        setattr(movie, attr, value)
    movie.save()
    if not poster_file or trailer_file:
        movie.save()
    if poster_file:
        movie.poster.save(movie.name, poster_file)  # will save model instance as well
    if trailer_file:
        movie.trailer.save(movie.name, trailer_file)  # will save model instance as well
    return movie
```

The POST method works fine whether you send a file or not when trying out the api in the swagger interactive docs.
But it fails when it is a PUT method. This is the output I get in my terminal:

```bash
Unprocessable Entity: /api/cinema/2
[23/Mar/2024 12:27:48] "PUT /api/cinema/2 HTTP/1.1" 422 86
```

```json
{
  "detail": [
    {
      "type": "missing",
      "loc": [
        "body",
        "payload"
      ],
      "msg": "Field required"
    }
  ]
}
```
the curl:
```bash
curl -X 'PUT' \
  'http://127.0.0.1:8000/api/cinema/2' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'poster_file=@GID_1127-DeNoiseAI-standard.jpg;type=image/jpeg' \
  -F 'trailer_file=@IMG-20230101-WA0129 (1).jpg;type=image/jpeg' \
  -F 'payload={
  "name": "3535353"
}'
```

Any help will be appreciated. Perhaps I am using the ninja wrong?

**Comment by LexxLuey** [comment]
> ```python
> class Movie(models.Model):
>     class Status_Choices(models.IntegerChoices):
>         COMING_UP = 1
>         STARTING = 2
>         RUNNING = 3
>         FINISHED = 4
> 
>     name = models.CharField(max_length=200, null=True)
>     protagonists = models.CharField(max_length=200, null=True)
>     poster = models.ImageField(upload_to ='posters/', null=True)
>     trailer = models.FileField(upload_to ='trailers/', null=True)
>     start_date = models.DateTimeField(auto_now=False, auto_now_add=False, null=True)
>     status = models.IntegerField(choices=Status_Choices.choices, default=Status_Choices.COMING_UP)
>     ranking = models.IntegerField(validators=[MinValueValidator(0, message="Cannot have ranking below 0")], default=0)
>     created_at = models.DateTimeField(auto_now_add=True)
>     modified_at = models.DateTimeField(auto_now=True)
> 
>     class Meta:
>         verbose_name = "movie"
>         verbose_name_plural = "movies"
> 
>     def __str__(self):
>         return self.name
> 
> class MovieIn(ModelSchema):
>     class Meta:
>         model = Movie
>         exclude = ["id", "created_at", "modified_at"]
>         fields_optional = "__all__"
> 
> 
> class MovieOut(ModelSchema):
>     class Meta:
>         model = Movie
>         fields = "__all__"
>         fields_optional = "__all__"
> 
> 
> class Message(Schema):
>     message: str
> 
> 
> router = Router()
> 
> 
> @router.post("/", response=MovieOut)
> def create_movie(
>     request,
>     payload: MovieIn,
>     poster_file: UploadedFile = None,
>     trailer_file: UploadedFile = None,
> ):
>     payload_dict = payload.dict()
>     movie = Movie(**payload_dict)
>     if not poster_file or trailer_file:
>         movie.save()
>     if poster_file:
>         movie.poster.save(movie.name, poster_file)  # will save model instance as well
>     if trailer_file:
>         movie.trailer.save(movie.name, trailer_file)  # will save model instance as well
>     return movie
> 
> @router.put("/{movie_id}", response=MovieOut)
> def update_movie(
>     request,
>     movie_id: int,
>     payload: MovieIn,
>     poster_file: UploadedFile = None,
>     trailer_file: UploadedFile = None,
> ):
>     print(movie_id)
>     print(payload)
>     print(poster_file)
>     print(trailer_file)
>     movie = get_object_or_404(Movie, id=movie_id)
>     for attr, value in payload.dict(exclude_unset=True).items():
>         setattr(movie, attr, value)
>     movie.save()
>     if not poster_file or trailer_file:
>         movie.save()
>     if poster_file:
>         movie.poster.save(movie.name, poster_file)  # will save model instance as well
>     if trailer_file:
>         movie.trailer.save(movie.name, trailer_file)  # will save model instance as well
>     return movie
> ```
> 
> The POST method works fine whether you send a file or not when trying out the api in the swagger interactive docs. But it fails when it is a PUT method. This is the output I get in my terminal:
> 
> ```shell
> Unprocessable Entity: /api/cinema/2
> [23/Mar/2024 12:27:48] "PUT /api/cinema/2 HTTP/1.1" 422 86
> ```
> 
> ```json
> {
>   "detail": [
>     {
>       "type": "missing",
>       "loc": [
>         "body",
>         "payload"
>       ],
>       "msg": "Field required"
>     }
>   ]
> }
> ```
> 
> the curl:
> 
> ```shell
> curl -X 'PUT' \
>   'http://127.0.0.1:8000/api/cinema/2' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: multipart/form-data' \
>   -F 'poster_file=@GID_1127-DeNoiseAI-standard.jpg;type=image/jpeg' \
>   -F 'trailer_file=@IMG-20230101-WA0129 (1).jpg;type=image/jpeg' \
>   -F 'payload={
>   "name": "3535353"
> }'
> ```
> 
> Any help will be appreciated. Perhaps I am using the ninja wrong?
> 
> _EDIT_: I updated my PUT to this:
> 
> ```python
> @router.put("/{movie_id}", response=MovieOut)
> def update_movie(
>     request,
>     movie_id: int,
>     payload: Form[MovieIn],
>     poster_file: Optional[UploadedFile] = File(None),
>     trailer_file: Optional[UploadedFile] = File(None),
> ):
>     print(movie_id)
>     print(payload)
>     print(poster_file)
>     print(trailer_file)
>     movie = get_object_or_404(Movie, id=movie_id)
>     for attr, value in payload.dict(exclude_unset=True).items():
>         setattr(movie, attr, value)
>     if not poster_file or trailer_file:
>         movie.save()
>     if poster_file:
>         movie.poster.save(movie.name, poster_file)  # will save model instance as well
>     if trailer_file:
>         movie.trailer.save(movie.name, trailer_file)  # will save model instance as well
>     return movie
> ```
> 
> in my terminal i get this:
> 
> ```shell
> 2
> name=None protagonists=None poster=None trailer=None start_date=None status=None ranking=None
> None
> None
> ```
> 
> the payload is always empty even though there is data sent from the client.

Please. 4 months later. I am still facing this issue. Any help will be appreciated

**Comment by vitalik** [comment]
Hi @LexxLuey  I see you are using PUT method (not POST like in the title of this issue)


For some reason django does not process **files** during **PUT** requests..

to avoid this you can add middleware that will read files in put method - here is one example - https://github.com/vitalik/django-ninja/issues/1059#issuecomment-1904178553
