### ISSUE TITLE
[Question] Unable to cache paginated queryset `PicklingError`

### ISSUE THREAD

**Issue by Tragio** [vitalik/django-ninja#1283]
Hellooo 👋 

I'm having an issue with caching a paginated queryset that uses `prefetch_related` or `select_related`. Initially, I was using `@paginate` from Django Ninja, however, I was not able to cache it properly as the `count` query would always be requested since it happens outside my API view. _(Please let me know if there is any way to do it. 🙏 )_ 

----

**Problem Details**:

So I created a custom pagination decorator that caches the results of a paginated queryset. The caching works correctly when no `prefetch_related` or `select_related` fields are involved. However, when I add `prefetch_related` or `select_related`  fields to the queryset, the caching process fails, and I encounter a `PicklingError` or in some code variations, I have Pydantic errors.

----

**What I've Tried**:

- I tried using `.values()` but it doesn't work because it seems to exclude `prefetch_related` fields.
- I attempted to serialize the queryset using Django serializers, but this approach threw errors when the data was passed to Pydantic for validation, in some ways it worked but only for `prefetch_related`, for `selected_related` it did not.

At this point, I have no clue how I can solve this issue. I already searched and searched but couldn't find a way 🤔

Another way I thought was to get the final data after it is processed by Pydantic, but I have no clue how can I get that data after goes to Pydantic and I also don't know if that would work. I searched through the docs and issues but couldn't find anything related to that. 🤔 

----

**Code Example**:

Here's the decorator code:

```python
def paginate(
    cache_key: str | None = None, cache_timeout: int = 5 * 60, default_limit: int = 20
):
    def decorator(func):
        @wraps(func)
        def wrapper(api_instance, request, *args, **kwargs):
            limit = request.GET.get("limit", default_limit)
            offset = request.GET.get("offset", 0)

            # Get cache
            if cache_key:
                cached_data = cache.get(cache_key)
                if cached_data:
                    return cached_data

            try:
                limit = int(limit)
                offset = int(offset)
            except ValueError:
                raise HttpError(400, "Limit and offset must be integers.")

            queryset = func(api_instance, request, *args, **kwargs)

            paginated_queryset = queryset[offset : offset + limit]

            data = {"count": queryset.count(), "items": paginated_queryset}

            # Set cache
            if cache_key:
                cache.set(cache_key, data, timeout=cache_timeout)

            return data

        return wrapper

    return decorator
```

And here's the relevant view:

```python
@http_get("", response=NinjaPaginationResponseSchema[StockItemSupplierSchemaOut])
@paginate(cache_key="stock_suppliers")
def get_all_suppliers(self, request, **kwargs):
    return (
        StockItemSupplier.objects.filter(deleted_at=None)
        .order_by("name")
        .prefetch_related("phone_numbers", "addresses")
    )
```

**Error Traceback**:

When the view tries to set the cache, the following error is raised:

```
Traceback (most recent call last):
  File "/path/to/ninja_extra/operation.py", line 194, in run
    result = self.view_func(request, **values)
  File "/path/to/ninja_extra/controllers/route/route_functions.py", line 89, in as_view
    result = self.route.view_func(
  File "/path/to/pagination.py", line 61, in wrapper
    cache.set(cache_key, data, timeout=cache_timeout)
  File "/path/to/django_redis/cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
  File "/path/to/django_redis/cache.py", line 81, in set
    return self.client.set(*args, **kwargs)
  File "/path/to/django_redis/client/default.py", line 143, in set
    nvalue = self.encode(value)
  File "/path/to/django_redis/client/default.py", line 461, in encode
    value = self._serializer.dumps(value)
  File "/path/to/django_redis/serializers/pickle.py", line 29, in dumps
    return pickle.dumps(value, self._pickle_version)
_pickle.PicklingError: Can't pickle <function QuerySet._clone at 0x11013d6c0>: it's not the same object as django.db.models.query.QuerySet._clone
```

Thank you very much ❤️

**Comment by vitalik** [comment]
@Tragio 

probably need this:

```Python
# change this
data = {"count": queryset.count(), "items": paginated_queryset}
# to this:
data = {"count": queryset.count(), "items": list(paginated_queryset)}
```

OR maybe better split paginate and caching logic like this (which is more recomended)


```Python
from ninja.decorators import decorate_view
from ninja.pagination import paginate
from django.views.decorators.cache import cache_page


@http_get("", response=NinjaPaginationResponseSchema[StockItemSupplierSchemaOut])
@decorate_view(cache_page(5 * 60))
@paginate
def get_all_suppliers(self, request, **kwargs):
    ...
```

**Comment by Tragio** [comment]
Hi @vitalik 👋 

Thank you for taking the time to take a look and this, and mainly for making this awesome framework 🚀 

The `list()` was also one of my many tries 😓 it works for all queries including `selected_related` but when there is `prefetch_related` it throws that `PicklingError`.
```py
data = {"count": queryset.count(), "items": list(paginated_queryset)}
```
```
_pickle.PicklingError: Can't pickle <function QuerySet._clone at 0x1328ea340>: it's not the same object as django.db.models.query.QuerySet._clone
```

Related to `@decorate_view(cache_page(5 * 60))` I always thought that would be unique to each user, but in a further look, seems not, which is good for my use case. Another issue was how to clear the related cache since it generates a unique ID, however, since I'm using django-redis, I can clear the related cache using: `cache.delete_pattern("*my_key_prefix*")`

I would prefer to stick with the first solution since I have more control over it, but if is not possible or you don't have any other ideas, I would change to the second one. 🙏  

Thank you once again 😃

**Comment by vitalik** [comment]
@Tragio 

`cache_page` is actually more flexible - [it can vary on user headers](https://docs.djangoproject.com/en/5.1/topics/cache/#using-vary-headers) (like cookies or auth header) it has it's own cache prefix and you can as well change that - [see docs](https://docs.djangoproject.com/en/5.1/topics/cache/#the-per-view-cache) )

**Comment by Tragio** [comment]
Thank you once again @vitalik ❤️ you're awesome, keep up the amazing work!! 🚀
