### ISSUE TITLE
Purpose of the project?

### ISSUE THREAD

**Issue by AlwxSin** [vitalik/django-ninja#13]
Can you explain why one should use django-ninja and what cases of using it?

From the docs, it's unclear what benefits `django-ninja` offer. For example:
* It based on django, but doesn't show how to work with core django features like DjangoORM, etc. Said that django-ninja is fast thanks to pydantic and async, but django didn't migrate all their stuff to async code, therefore they'll be issues with that.
* Django-ninja looks basically the same as FastAPI, which is good from some perspective. But FastAPI built on asyncio code and has no limitations of half-async django. So, why not just FastAPI?

**Comment by vitalik** [comment]
hope new docs make it more clear (more articles still to come)

**Comment by rajaiswal** [comment]
Hi @vitalik, really interesting project. The way I see it, and correct me if I'm wrong, it's a DRF replacement for Django with added support for async inspired by FastAPI. Would like to contribute to this project. Do you have a roadmap or list of outstanding features/enhancement for next release?

**Comment by vitalik** [comment]
Hey @rajaiswal 

I would not say it's a replacement, but indeed it's an option to DRF

The primary features are:

 - async support (with Django3.1)
 - type-hint based API  declaration (from FastAPI)
 - Schemas that support django ORM

as for the upcoming features you can see list of design proposals:

https://django-ninja.rest-framework.com/proposals/

and a list of issues marked as enhancement here - https://github.com/vitalik/django-ninja/issues
