### ISSUE TITLE
Middleware in Django `test.Client` / Ninja `TestClient`

### ISSUE THREAD

**Issue by c4ffein** [vitalik/django-ninja#1315]
Hi, someone asked on the Discord if there is a way to write tests that work with middlewares. I see 2 potential solutions:

- Adding an optional list of middlewares to the Ninja `TestClient` parameters
  - But the implementation would probably be a bit hacky
  - And I'm not sure it can work for all cases
- Provide a `DjangoTestClient` (or whatever we name it) in Ninja, based on the regular `test.Client`
  - It would implement the same features as the current `TestClient` (the default `headers` and `COOKIES` set on instantiation of the class, the `data` helper for the requests result...)
  - It would be far closer to the real behavior of the framework at the cost of a slightly slower test, but you can use it only when you need it
  - It would require temporarily bypassing `urlpatterns` with the provided api or router content
  
I think the latter would be a nice addition to Ninja, but I'd rather get some opinions before dropping a PR, so thanks for reading and don't hesitate to react to this issue

**Comment by vitalik** [comment]
Well Ninja client is purely focued on API instance testing (avoid the rest of the django stack to speedup test processing)

basically to use middlewares users just need to use [standard django test client ](https://docs.djangoproject.com/en/5.1/topics/testing/tools/#the-test-client)

**Comment by c4ffein** [comment]
Yeah that's my point
I proposed to make a subclass of that standard django test client in Ninja that could
- be connected to routers and api on `__init__` just like Ninja's TestClient does
- implement `.data` just like Ninja's TestClient does
- implement any other feature that get added to Ninja's TestClient
But that may be overkill, close that issue if you feel like it
