### ISSUE TITLE
This product must be known by more developers.

### ISSUE THREAD

**Issue by riseryan89** [vitalik/django-ninja#132]
I am using django-ninja on production level. 

If the maintainers do not allow contribution at code level, please allow other developers to translate the document.
I also want to try to implement @background_tasks from FastAPI on Django-ninja as well.

Thanks anyway.

**Comment by sharshub** [comment]
@vitalik is this project open to contribution?

**Comment by Smyja** [comment]
> I am using django-ninja on production level.
> 
> If the maintainers do not allow contribution at code level, please allow other developers to translate the document. I also want to try to implement @background_tasks from FastAPI on Django-ninja as well.
> 
> Thanks anyway.

@riseryan89 were you able to implement background tasks?

**Comment by riseryan89** [comment]
@Smyja Hi Smyja, I have built own custom background task handler with APScheduler.
