### ISSUE TITLE
ModelSchema 

### ISSUE THREAD

**Issue by ierror** [vitalik/django-ninja#1337]
First of all, thank you very much for this great library! Developing with is truly a pleasure.

I'm having trouble getting related objects work with `ModelSchema`.

That works:

```python
class CountryRead(ModelSchema):
    news: list[NewsRead]

    class Config:
        model = Country
        model_fields = [
            "id",
            "name",
            "created",
            "modified",
        ]

    @staticmethod
    def resolve_news(obj):
        return obj.news.all()
```

If I change 

```return obj.news.all()```

to 

```return obj.news.all().order_by("-datetime")```

i get the following error:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for NinjaResponseSchema
response.news
  Error extracting attribute: SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async. [type=get_attribute_error, input_value=<DjangoGetter: <Asset: Apple Inc.>>, input_type=DjangoGetter]
    For further information visit https://errors.pydantic.dev/2.9/v/get_attribute_error
```

Another problem: If I want to limit the news count:

```return obj.news.all()[:5]```

I do get 5 entries, but the SQL query does not include a LIMIT 5 as is usually the case with Django.

Does anyone have an idea what I might be doing wrong?

**Comment by vitalik** [comment]
Hi @ierror 

well both `.all()` and `.all().order_by` should not work in pydantic context in async mode... maybe you already called `await obj.news.all()` somewhere before serialization or something hard to tell

try changing your method to sync mode and see if that helps..

but if you reallyl need async only - then maybe solution would be to attach news as new attribute and use it later:

```Python
from ninja import NinjaAPI, ModelSchema, Field
from django.shortcuts import aget_object_or_404
from news.models import News, Country

api = NinjaAPI()


class NewsRead(ModelSchema):
    class Meta:
        model = News
        fields = [
            "id",
            "title",
            "content",
        ]


class CountryRead(ModelSchema):
    news: list[NewsRead] = Field([], alias="news_fetched") # !!! note the news_fetched alias see that later

    class Meta:
        model = Country
        fields = [
            "id",
            "name",
        ]


@api.get("/country/{id}", response=CountryRead)
async def get_country(request, id: int):
    country = await aget_object_or_404(Country, id=id)
    country.news_fetched = [n async for n in obj.news.all()]  # Forcing fetch from DB in async mode !!!!
    return country
```

**Comment by ierror** [comment]
Thank you!
