### ISSUE TITLE
[BUG] Using PGVector's VectorField while using ModelSchema's causes an error

### ISSUE THREAD

**Issue by eliorc** [vitalik/django-ninja#1350]
**Describe the bug**
I have a django-ninja app, which is fully working and operational. Some of my schemas are based on `ModelSchema` for convinience.
Today, I tried adding to an abstract class the `pgvector.django.VectorField` and when trying to `makemigrations` the command fails with a traceback that indicates that the problem somehow relates to `ModelSchemas`

The abstract class:

Traceback:
```python3
class VectorSearchable(models.Model):
    """Abstract base class for models that support vector search"""

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        field_name = "semantic_embeddings"

        # Create the vector field dynamically
        vector_field = VectorField(dimensions=SEMANTIC_SIMILARITY_EMBEDDING_DIMENSIONS,
                                   null=True,
                                   blank=True)

        # Add the field to the subclass
        cls.add_to_class(field_name, vector_field)

        # Generate unique index name
        index_name = f"semantic_similarity_vectors_{cls.__name__.lower()}_index"

        # Set up the unique index for this subclass
        cls._meta.indexes = [HnswIndex(name=index_name,
                                       fields=[field_name],
                                       m=16,
                                       ef_construction=100,
                                       opclasses=["vector_cosine_ops"])]

    class Meta:
        abstract = True

    ... more irrelevant class code
```

Traceback:

>   File "<path_in_my_project>/schemas.py", line 227, in <module>
>     class MySchema(ModelSchema, SomeOtherSchema):
>   File "<path_in_my_project>/.venv/lib/python3.12/site-packages/ninja/orm/metaclass.py", line 106, in __new__
>     model_schema = create_schema(
>                    ^^^^^^^^^^^^^^
>   File "<path_in_my_project>/.venv/lib/python3.12/site-packages/ninja/orm/factory.py", line 65, in create_schema
>     python_type, field_info = get_schema_field(
>                               ^^^^^^^^^^^^^^^^^
>   File "<path_in_my_project>/.venv/lib/python3.12/site-packages/ninja/orm/fields.py", line 151, in get_schema_field
>     python_type = TYPES[internal_type]
>                   ~~~~~^^^^^^^^^^^^^^^
> KeyError: 'VectorField'

**Versions (please complete the following information):**
 - Python version: 3.12.3
 - Django version: 5.1.1
 - Django-Ninja version: 1.3.0
 - Pydantic version: 2.9.2

**Comment by eliorc** [comment]
A workaround that made the `makemigrations` go through was adding the following before any other code in my app

```python3
from ninja.orm.fields import TYPES
TYPES['VectorField'] = list
```

though this doesn't seem like a best practice 🤷🏼‍♂️

**Comment by vitalik** [comment]
Hi @eliorc 

Yes indeed, the next version of django ninja comes with register_field utility:

usage will be like this
```python
from ninja.orm import register_field

register_field("VectorField", list)
```
