### ISSUE TITLE
create_schema with custom Schema base model

### ISSUE THREAD

**Issue by javierhuerta** [vitalik/django-ninja#136]
Hello, thank you for this great project. 

`class CamelModelSchema(Schema):

    class Config:
        alias_generator = to_camel
        allow_population_by_field_name = True`

I have a class that inherits from Schema to be able to alias properties. However when I want to use the create_schema function I cannot use my custom class. Can you think of a way how I can solve this?

Thanks

**Comment by robinsandstrom** [comment]
I hade the same issue myself in #131. Django ninja aliases (or perhaps pydantic itself) seems to be be a bit unpredictable when it comes to aliases. For now we went with skipping camelcase until there is a more stable way of generating the aliases. 😌
