### ISSUE TITLE
POST/PUT(Body Arguments) Not Working

### ISSUE THREAD

**Issue by luizfelipevbll** [vitalik/django-ninja#137]
It is not recognizing arguments:

Ex on Form(...):
```python3
@router.put('/indicadores/update')
def update_indicadores(request, id: int=Form(...)):
    return {'id': id}
```
![image](https://user-images.githubusercontent.com/40257388/118164942-1296ca00-b3fa-11eb-8926-9296b6c0fc1e.png)

Ex on Form(None):
```python3
@router.put('/indicadores/update')
def update_indicadores(request, id: int=Form(None)):
    return {'id': id}
```

![image](https://user-images.githubusercontent.com/40257388/118164774-d9f6f080-b3f9-11eb-9c68-92e232039973.png)

This happens on PUT request

**Comment by vitalik** [comment]
well it seems PUT methods generally do  not support form-data payloads (or it really depends on server side implementation)

in case of django you do not have access to formdata  variables (via like request.PUT or request.POST) so body need to be parsed manually

even XHTML 1.x forms only support GET and POST

so I would say this is not solvable inside the ninja package
