### ISSUE TITLE
swagger-ui 敢不敢不要把资源写死

### ISSUE THREAD

**Issue by lqx131499** [vitalik/django-ninja#14]
C:\thirds\Python37\Lib\site-packages\ninja\templates\ninja\swagger.html<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui.css">    
<script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js"></script>

**Comment by vitalik** [comment]
@lqx131499 I'm not sure I understand the issue...

**Comment by lqx131499** [comment]
I mean to make the referenced resources configurable, because the network in many places is not connected to the Internet.

Location: Lib\site-packages\ninja\templates\ninja\swagger.html

Where needs to be configured: 
<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui.css">   
<link rel="shortcut icon" href="https://ninja.rest-framework.com/favicon.png">
<script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js"></script>

**Comment by MaxZzyo** [comment]
23333333

**Comment by vitalik** [comment]
@lqx131499 @MaxZzyo 

this should work now

Please install latest verstion, and put  `"ninja"` to `INSTALLED_APPS`

**Comment by lqx131499** [comment]
ok thanks💪🏻💪🏻💪🏻💪🏻💪🏻
