### ISSUE TITLE
To fix typo in docs

### ISSUE THREAD

**Issue by TaeHyoungKwon** [vitalik/django-ninja#140]
I found typo from official docs below

Tutorial/Reference -> Schemas from Django models -> create_schema method
![스크린샷 2021-05-18 오전 9 50 08](https://user-images.githubusercontent.com/18538418/118573970-7e907e00-b7be-11eb-847c-fc8f0900154f.png)

form -> from

Can I create a PR to fix typo?? 
I just created a Issue first because I couldn't find that how to contribute about fixing typo.

Thank you 😄

**Comment by vitalik** [comment]
@TaeHyoungKwon 
sure, go ahead, PRs are always welcome

**Comment by thkwon1** [comment]
Hello

I found commit fixed by you 😄
Thank you~

**Comment by TaeHyoungKwon** [comment]
Hello

I found commit fixed by you 😄
Thank you~
