### ISSUE TITLE
How to catch exception raised by auth module

### ISSUE THREAD

**Issue by icebearrrr** [vitalik/django-ninja#141]
I wrote an auth module, an raised an exception inside it , but this exception seems not be handled by exception handler,  just throwed directly. When i raised it from view, the handler just works well.

**Comment by vitalik** [comment]
at this moment exceptions can be handled only globally (via api instance)

as an alternative you can make your global exception handler, and then check request.path for router path prefix and do your logic based on that

**Comment by icebearrrr** [comment]
> at this moment exceptions can be handled only globally (via api instance)
> 
> as an alternative you can make your global exception handler, and then check request.path for router path prefix and do your logic based on that

Thanks a lot, i'll try it.

**Comment by dozer133** [comment]
Wouldn't this work?

```python
def _run_authentication(self, request: HttpRequest) -> Optional[HttpResponse]:
        for callback in self.auth_callbacks:
            try:
                result = callback(request)
            except Exception as e:
                return self.api.on_exception(request, e)

            result = callback(request)

            if result:
                request.auth = result  # type: ignore
                return None
        return self.api.create_response(request, {"detail": "Unauthorized"}, status=401)
```

If no handler is defined for that exception, it would be raised by `on_exception`.
This way we can raise exceptions like `InvalidToken` or `RequiredRoleMissing` from within the authentication method which would be nice.

**Comment by vitalik** [comment]
done in 0.14
