### ISSUE TITLE
django-ninja with BasicAuth

### ISSUE THREAD

**Issue by rngallen** [vitalik/django-ninja#144]
Am using custom user model on my project where email is used instead of username.
Everything works fine but on api root login form instead of showing `email` is shows `username`
how can I change this?
![image](https://user-images.githubusercontent.com/47332486/120094635-2c3e4e00-c12a-11eb-9d5a-9402199045a4.png)

**Comment by vitalik** [comment]
I do not think this is possible to override:

see here https://swagger.io/docs/specification/authentication/bearer-authentication/

we can only pass `type: http` and `scheme: bearer`

the rest is doing swagger-ui javascript 

so I guess you can insert some of you custom on docs page that can override this lable

**Comment by rngallen** [comment]
closed
