### ISSUE TITLE
Query parameters with filter schema and enum type is not displayed in swagger

### ISSUE THREAD

**Issue by duducp** [vitalik/django-ninja#145]
Hi, I'm creating the following schema:

schema.py
```python
from datetime import datetime
from enum import IntEnum

from ninja import Schema
from pydantic import Field


class Range(IntEnum):
    TWENTY = 20
    FIFTY = 50
    TWO_HUNDRED = 200


class Filter(Schema):
    to_datetime: datetime = Field(alias='to')
    from_datetime: datetime = Field(alias='from')
    range: Range
```

api.py
```python
@api.get(
    path='/{pair}/mms',
    response={
        HTTPStatus.OK: List[QuotationOutSchema],
    }
)
async def retrieve_quotation(
    request,
    pair: str,
    filters: Filter = Query(None)
):
    ...
```

When rendering the documentation, only the range parameter is being presented:

![image](https://user-images.githubusercontent.com/16366240/120402204-fd85ca80-c317-11eb-89f0-097f27ca53c8.png)

If I exclude the `range: Range` parameter, the documentation presents the other parameters (from, to):

![image](https://user-images.githubusercontent.com/16366240/120402465-ad5b3800-c318-11eb-8bd8-b5e83b1c87e0.png)

I believe that there may be a bug in the verification of the query params when Enum is used causing the other parameters to be discarded.

**Comment by vitalik** [comment]
hi @duducp 

please try to test your case  with latest version (0.13.1)

**Comment by duducp** [comment]
hi @vitalik 

I took the test now and it's working. Thanks for the quick fix and congratulations on the project.
