### ISSUE TITLE
v1 changes

### ISSUE THREAD

**Issue by vitalik** [vitalik/django-ninja#146]
Outlining here potential backward incompatible changes that might be introduced in v1 release

 - auth will be class interface instead of callable (to support async authenticators)
 - responses to support codes/headers/content (like general Response class)
 - [routers paths joined with "/"](https://github.com/vitalik/django-ninja/blob/56ad4d614c6743197f3b1babefe23e0059ef9f74/ninja/router.py#L345) - which might not needed on some cases where router prefix will act like a prefix and not subfolder

**Comment by ahmadaidin** [comment]
is there any plan to add custom decorator to the api module?

**Comment by vitalik** [comment]
> is there any plan to add custom decorator support to the api module?

what do you mean ? example ?

**Comment by ahmadaidin** [comment]
> > is there any plan to add custom decorator support to the api module?
> 
> what do you mean ? example ?

I tried to implement an async decorator to check whether user exists or not on database before an API function is called. At first I got an error and I think it's impossible to add any async decorator for now. But then I found a way to create one. So, I think it's already solved.

**Comment by MathiasAG** [comment]
When i add List[ModelSchema] in another schema, he generate an error "AttributeError: __fields__". I don't understand why

**Comment by WarKaa** [comment]
Hey @vitalik thank you for your great work

Will it be possible in v1 to add custom example to our open api schemas like in https://fastapi.tiangolo.com/tutorial/schema-extra-example/?h=example#pydantic-schema_extra ?

**Comment by rngallen** [comment]
> When i add List[ModelSchema] in another schema, he generate an error "AttributeError: __fields__". I don't understand why
> 

Kindly share your schema and models code. It will be easy to solve having some hints

**Comment by A-Asror** [comment]
will there be permission, for example, like [django rest framework ](https://www.django-rest-framework.org/api-guide/permissions/)

**Comment by SaluteGF** [comment]
a error “TypeError: __modify_schema__() missing 1 required positional argument: 'field'
[28/Oct/2022 10:11:47] "GET /api/openapi.json HTTP/1.1" 500 254519
”，when i use “file: UploadedFile = File(...)”
