### ISSUE TITLE
Decorators

### ISSUE THREAD

**Issue by vitalik** [vitalik/django-ninja#148]
```
@api.get("/add")
@cache_page(60 * 15)
def add(request, a: int, b: int):
    return {"result": a + b}
```
so currently this will not work due to inspection procedure...

I guess there must be some `@decorate` helper to allow to add custom decorators that will not conflict with arguments/annotations resolution

UPD:

looks like when `functools.wraps` is used it is possible to get to the original function declaration via `__wrapped__` attribute

**Comment by jonykalavera** [comment]
A possible workaround is to actually return a response object which is allowed as far as I can see in the code. https://github.com/vitalik/django-ninja/blob/9e07839deee83a0b7edf59b2b35e0f54d326e284/ninja/operation.py#L150

**Comment by fabiocaccamo** [comment]
I'm just experiencing the same problem for both, caching and profiling.

**Comment by fabiocaccamo** [comment]
This is the decorator I'm using now, maybe it will be useful to someone else:
```python
def api_cached(key, timeout):
    def inner(f):
        @wraps(f)
        def wrapper(*args, **kwargs):
            cache = get_cache()
            key_with_params = '-'.join([key] + list(kwargs.values()))
            value = cache.get(key_with_params)
            if value:
                return value
            value = f(*args, **kwargs)
            cache.set(key_with_params, value, timeout)
            return value
        return wrapper
    return inner
```
```python
@api.get('/', response=AppSchema, url_name='app')
@api_cached(key="app", timeout=60)
def app(request):
    return {
    }
```
