### ISSUE TITLE
create_schema with custom model property / method

### ISSUE THREAD

**Issue by fabiocaccamo** [vitalik/django-ninja#150]
I'm using `create_schema` on a very simple model with `name` and `slug` fields and an `url` property:
```python
MyObjectSchema = create_schema(MyObject, fields=['name', 'slug', 'url'])
```

Unexpectedly, if `url` is a model `@property` the following exception is raised:
```python
ninja.errors.ConfigError: Field(s) {'url'} are not in model.
```

I tried by making `url` a model method, in this way any `Exception` is raised at compile time, but the error is visible in the api response body (very bad):
```python
Traceback (most recent call last):
  File "/root/xxx/lib/python3.8/site-packages/ninja/operation.py", line 94, in run
    return self._result_to_response(request, result)
  File "/root/xxx/lib/python3.8/site-packages/ninja/operation.py", line 177, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
  File "pydantic/main.py", line 631, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 33 validation errors for NinjaResponseSchema
response -> 0 -> url
  str type expected (type=type_error.str)
 ```

In the end I solved it by creating the schema manually and using a model `@property`, but ...

```python
class MyObjectSchema(Schema):
    name: str
    slug: str
    url: str
```

... it would be nice if **both model property and method would work** even using the `create_schema` function.

---

*Thank you for this amazing library!*

**Comment by GTBebbo** [comment]
Looking at this issue, I think manually creating the schema is a valid workaround. To implement the ability for the `create_schema` method to use fields with the `@property` decorator would also require the property to be explicitly typed for the OpenAPI schema to use.

**Comment by vitalik** [comment]
@fabiocaccamo 

fields are really looking only into model fields

to add some arbitrary attribute use `custom_fields`

```Python
MyObjectSchema = create_schema(
      MyObject,
      fields=['name', 'slug'],
      custom_fields=[
             ('url', str, None),
      ],
)
```

**Comment by paqstd-dev** [comment]
> Hi I recently discovered the same issue for myself. How can I use the `custom_fields` feature using the `ModelSchema` class?

**Comment by vitalik** [comment]
> Hi I recently discovered the same issue for myself. How can I use the `custom_fields` feature using the `ModelSchema` class?

@paqstd-dev 

pretty similar to how django model form works:
```Python

MyObjectSchema(ModelSchema):
    custom_field: str  # <-- define custom fields as typed attributes
    class Meta:
            model = MyObject
            model_fields = ['name', 'slug']


```

**Comment by frocelu** [comment]
I have a question about the custom_fields.
What is the 3rd element in the custom_fields tuple?
I know the first is property name, the second is property type.
Is the 3rd elm is for validators?How to use it?

**Comment by fabiocaccamo** [comment]
@frocelu if I'm not wrong it means that the property value is optional and to use that default.

**Comment by edugmes** [comment]
@frocelu Here is the code for `custom_fields`: [link](https://github.com/vitalik/django-ninja/blob/5dac89c59cf0371fa3ed51906072c4a9b7db2309/ninja/orm/factory.py#L42)

It turns out to be a default value, as pointed by @fabiocaccamo and as I could read at `api/docs`, but I couldn't figure it out how this makes the schema field optional. It's not very clear for me 😄 

Could anyone help us mere mortals with one example using `custom_fields` ? Thanks in advance!
