### ISSUE TITLE
Swagger: Cannot use Enum as type in query params

### ISSUE THREAD

**Issue by Adamantish** [vitalik/django-ninja#152]
The following creates a functioning api just fine

```python
from enum import Enum

class Language(Enum):
    en = "en"
    de = "de"
    

@router.get("/availability", response={200: Availability, 400: ErrorMessage})
def availability(
    _: WSGIRequest,
    language_alpha_2: Language,
    other_param: str = None,
):
    ...
```
However, this is shown  at the top of the swagger docs
![Screenshot from 2021-06-15 15-42-31](https://user-images.githubusercontent.com/9261192/122064234-49913e80-cdf1-11eb-9a5f-940394a1e9ea.png)

Of course, this is no problem when the argument is instead listed in a pydantic schema. That would mean API breaking changes though.

**Comment by Adamantish** [comment]
I just found that if I use this `Language` enum in one of the pydantic schemas it fixes the problem everywhere. So I guess the issue is that the Enums are turned into openapi schemas only when they're included in another schema. Is there a workaround here?

**Comment by Adamantish** [comment]
Great. Tried it. Works. Thank you!

**Comment by michaldyczko** [comment]
The same problem appears in the case of list of enums, like`List[Language]`. The same error is raised. It would be nice to have `<select multiple>` also.

**Comment by vitalik** [comment]
@michaldyczko 

could you provide full example ? what is `Language` in your case ?

**Comment by vvoody** [comment]
Everything works, the query parameter `protocol` is documented and shown as selectable values.
```python
class Proto(Enum):
    SSL2 = "SSL2"
    SSL3 = "SSL3"
    TLS1 = "TLS1"
    TLS1_1 = "TLS1_1"
    TLS1_2 = "TLS1_2"
    TLS1_3 = "TLS1_3"


class VersionsQueryParams(Schema):
    ipv4: IPv4Address
    port: conint(ge=0, le=2**16 - 1) = 443
    protocol: Optional[Proto] = None


@router.get(
    "/versions",
    summary="Get Supported SSL Versions on IP",
    operation_id="get_versions",
    response=list[SSLVersionSupported],
)
def get_versions(request, filters: VersionsQueryParams = Query(...)):
    logger.debug("protos: %s", filters.protocol)
    return {}
```
<img width="564" alt="image" src="https://user-images.githubusercontent.com/65963/167373199-3d3d32d3-91e5-4f6f-b2b0-304124447ea9.png">

---

Have some issues if uses `List[Enum]`:
```python
class Proto(Enum):
    SSL2 = "SSL2"
    SSL3 = "SSL3"
    TLS1 = "TLS1"
    TLS1_1 = "TLS1_1"
    TLS1_2 = "TLS1_2"
    TLS1_3 = "TLS1_3"


class VersionsQueryParams(Schema):
    ipv4: IPv4Address
    port: conint(ge=0, le=2**16 - 1) = 443
    protocols: Optional[List[Proto]] = None  # !! make a list


@router.get(
    "/versions",
    summary="Get Supported SSL Versions on IP",
    operation_id="get_versions",
    response=list[SSLVersionSupported],
)
def get_versions(request, filters: VersionsQueryParams = Query(...)):
    logger.debug("protos: %s", filters.protocol)
    return {}
```

There is an warning on Swagger docs and no docs of `protocols` shown, but code works...
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/65963/167372412-a9d36db4-e42f-440a-a313-6ef49edbd3cd.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/65963/167372614-20c93c90-5f21-4948-a8e0-12a1d6be8645.png">

**Comment by michaldyczko** [comment]
@vitalik, I have the same problem as @vvoody with `List[Enum]`

**Comment by vitalik** [comment]
@michaldyczko try to use str enum:
```Python
class SomeChoice(str, Enum):  # <---
    FOO = "foo"
    BAR = "bar"
```

**Comment by Jragon** [comment]
Hi @vitalik - I get the same problem with an str enum using :
```
class FiltersQuery(Schema):
    fields: List[StrEnum]
```

![image](https://user-images.githubusercontent.com/845112/218109492-645b5a2e-88c3-43ba-b6e7-4d477f2becf2.png)

**Comment by Jragon** [comment]
Hi @vitalik the strenum looks like:

```
class StrEnum(str, Enum):
    one = "one"
    two = "two
```

I've made a pull request with a possible fix and the tests to show how it is broken (they don't pass on the current code base)
