### ISSUE TITLE
Types for "urls" property

### ISSUE THREAD

**Issue by Bizilizi** [vitalik/django-ninja#155]
### Problem
Current implementation of NinjaAPI has a following signature for `urls` property:

``` Python
@property
    def urls(self) -> Tuple[Any, ...]:
```

Which is not compatible with expected `Tuple[List[Union[URLResolver, URLPattern]], Optional[str], Optional[str]]` type for second argument. Therefore  when you try to path `NinjaAPI` urls to `path` function.
```Python
urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", api.urls), 
]
```

Mypy returns this error: `error: Argument 2 to "path" has incompatible type "Tuple[Any, ...]"; expected "Tuple[List[Union[URLResolver, URLPattern]], Optional[str], Optional[str]]"
`

### Workaround 
```Python
...
    path("api/", api.urls),  # type: ignore
...
```

Please, consider extend typings for urls property.

**Comment by vitalik** [comment]
@Bizilizi let me know if this works now (released in v 0.15.0 )
