### ISSUE TITLE
"none is not an allowed value"

### ISSUE THREAD

**Issue by 2ik** [vitalik/django-ninja#159]
I found an error on the part of pydantic
Example:

```python

# model.py
TestModel(models.Model):
    revenue_total = models.FloatField(default=0, null=True, blank=True)

# schemas.py
TestSchema = create_schema(TestModel)

# api.py
@api.get("/tests", response=List[TestSchema])
def get_tests(request):
    return TestModel.objects.all()
```

output:
```
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/ninja/operation.py", line 94, in run
    return self._result_to_response(request, result)
  File "venv/lib/python3.8/site-packages/ninja/operation.py", line 177, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
  File "pydantic/main.py", line 631, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 1 validation error for NinjaResponseSchema
response -> 5 -> revenue_total
  none is not an allowed value (type=type_error.none.not_allowed)
```

exception if the value in db is NULL

**Comment by 2ik** [comment]
temporary solution:
```Python
class TestSchema(Schema):
    revenue: float = None
```

**Comment by vitalik** [comment]
@2ik 
Hi it's not clear where/how you defined field `revenue_total` ? are you sure it's present in your model and null=True ?

**Comment by 2ik** [comment]
Hi, sorry, this is a typo, I just used it for an example. Changed in the question.
in db:
![image](https://user-images.githubusercontent.com/6692517/123241494-42a1b480-d4f2-11eb-8b5c-0d4eab6cd204.png)

The error happens only when **null** is in the record. This seems to be due to the fact that there is a default value

**Comment by vitalik** [comment]
well I cannot reproduce this..

maybe you can give more details.. your actual model and schema
and also ninja version

**Comment by 2ik** [comment]
Thank you for your response

Have you filled in the "revenue_total" field with value "None"? Not in admin, try directly in the database for example.

v0.13.2

**Comment by vitalik** [comment]
ok, I know whats' your issue

you defined both `default=0, null=True` , which I cannot find any logical sense...

django ninja basically uses the `default` first to create schema

----

for you solution would be
- either remove `default=0`
- either remove `null=True` - but then patch all current  null values with 0


PS. btw counting money with float field is not a good idea (if total revenue is money) - you should consider decimal (or integer coins) instead

**Comment by 2ik** [comment]
ok, understand. I just thought it was a bug in the package)) Yes, I have bad logic with the model, but I needed "default" for admin panel only. I will make changes to in method "save"

As for the float field, it suits me better, because the numbers are approximate. I know about the money field, but thank you for paying attention to this ;)
