### ISSUE TITLE
[proposal] Multiple Response Schemas

### ISSUE THREAD

**Issue by vitalik** [vitalik/django-ninja#16]
Read full proposal here - http://django-ninja.rest-framework.com/proposals/responses/

Allow to define multiple response schemas for API operation

See also #4 discussion

**Comment by fletcheaston** [comment]
This looks like a feature I'd really like to use, do you know if anyone has started working on it yet?

If not, I might try working on this myself. I'm fairly busy so it might take a few weeks, but I'm retooling my Django APIs right now and this looks great to implement.

**Comment by vitalik** [comment]
@fletcheaston , so what's your preferable way ? via Union or via Dict ?  ( see http://django-ninja.rest-framework.com/proposals/responses/ )

**Comment by fletcheaston** [comment]
@vitalik Dct makes the most sense to me, I know I'd personally want to attach schemas to status codes in the documentation.

For reference, I've used drf-spectacular's extend schema decorator (https://drf-spectacular.readthedocs.io/en/latest/customization.html) to build my documentation with DRF, and it uses Dict in the same way you've proposed.

**Comment by fletcheaston** [comment]
drf spectacular also offers the ability to return different schemas for a single status code (https://drf-spectacular.readthedocs.io/en/latest/faq.html#my-endpoints-use-different-serializers-depending-on-the-situation), but this isn't something I've used before or felt a need to use. I wouldn't attempt to implement something that complicated at first anyway.

**Comment by vitalik** [comment]
The dict version is implemented thanks to @dozer133
Released in 0.9.0
