### ISSUE TITLE
`update_forward_refs` doesn't work with `create_schema`

### ISSUE THREAD

**Issue by fabiocaccamo** [vitalik/django-ninja#161]
`update_forward_refs` doesn't work with `create_schema`

doing this:

```python
NodeSchema = create_schema(Node,
    depth=1,
    fields=['name', 'slug'],
    custom_fields=[
        ('childnodes', List['NodeSchema'], None),
    ]
)

NodeSchema.update_forward_refs()
```
the following exception is raised:
```python
NameError: name 'NodeSchema' is not defined
```

but it works if I do this:
```python
class NodeSchema(Schema):
    name: str
    slug: str
    childnodes: List['NodeSchema'] = None

NodeSchema.update_forward_refs()
```

**Comment by stephenrauch** [comment]
`create_schema()` defaults to using the name of the Model, if a name is not passed.  So you can fix this by passing a name thus:

```python
NodeSchema = create_schema(
    Node,
    name='NodeSchema'
    depth=1,
    fields=['name', 'slug'],
    custom_fields=[
        ('childnodes', List['NodeSchema'], None),
    ]
)
NodeSchema.update_forward_refs()
```

Or you you can work around this by forcing a name into the namespace with something like:

```python
class NodeSchema(create_schema(Node,
    depth=1,
    fields=['name', 'slug'],
    custom_fields=[
        ('childnodes', List['NodeSchema'], None),
    ]
)):
    pass

NodeSchema.update_forward_refs()
```

**Comment by fabiocaccamo** [comment]
@stephenrauch thank you!

**Comment by fabiocaccamo** [comment]
@stephenrauch adding  a `name` **that matches the schema variable name** solves the problem.

In this case, in the docs schemas section the name of the schema is used `NodeSchema` instead of the model name `Node`, is it possible the change it somehow?

**Comment by vitalik** [comment]
> In this case, in the docs schemas section the name of the schema is used `NodeSchema` instead of the model name `Node`, is it possible the change it somehow?

Well this is more like verbal agreement - some companies use other naming notation...

as for the next steps I'm planing to integrate metaclasses as well - in that case we will know the desired name and it will be automatically assigned

something like this:

```Python

class NodeSchema(ninja.ModelSchema):
      childnodes: List['NodeSchema'] = None

      class Meta:
              model = Node
              fields = ['id', 'name']
```
