### ISSUE TITLE
[QUESTION] How to pass list in query parameters separated by comma?

### ISSUE THREAD

**Issue by abxsantos** [vitalik/django-ninja#171]
Is it possible to pass a list of query parameters separated by comma and still generate the correct automatic documentation?

Something like `http://localhost/item?q=1,2,3,4,5,6` 
instead of `http://localhost/item?q=1&q=2&q=3&q=4&q=5&q=6`

**Comment by vitalik** [comment]
@abxsantos 

yes, basically user pydantic validator with `pre=True` and convert you value from string to list:


```Python
from typing import List
from ninja import NinjaAPI, Query
from pydantic import validator

class QSchema(Schema):
    q: List[int]

    @validator('q', pre=True)  # !!!
    def convert_q(value):
        items = [i.strip() for i in value[0].split(',') if i.strip()]
        return list(map(int, items))


@api.get("/test")
def test(request, data: QSchema = Query(...)):
    return data.dict()  # q = [1,2,3]

```
