### ISSUE TITLE
[QUESTION] How to add validators when using create_schema

### ISSUE THREAD

**Issue by Bouni** [vitalik/django-ninja#172]
Hi,

I use `create_schema` to ceate schemas from Django models but have no idea how to add validators!?
Is that even possible or do I have to create the Schemas by hand in order to get validators working?

**Comment by vitalik** [comment]
Hi @Bouni 

In a future releases there will be a metaclass support, so that should be easier..

but as for now try the following (not sure it will work): 

```Python

SomeSchemaBase = create_schema(SomeModel)

class SomeSchema(SomeSchemaBase):
    
   @validaor('foo')
   def validate_foo(...
         ....
# and then use SomeSchema
```

**Comment by Bouni** [comment]
Hi,

just did a quick test and works like a charm!
Thank you very much for the fast response and for django-ninja 😄
