### ISSUE TITLE
How to make a login request ?

### ISSUE THREAD

**Issue by jet10000** [vitalik/django-ninja#179]
I want to make a login request , I test it in api docs, It's work, but when I use sveltekit js for a  login request, response like this:

```shell
Bad Request: /api/auth/login2.json
[21/Jul/2021 12:50:29] "POST /api/auth/login2.json HTTP/1.1" 400 83
{
  detail: 'Cannot parse request body (Expecting value: line 1 column 2 (char 1))'
}

```

```shell
Forbidden (CSRF cookie not set.): /api/auth/login2.json
[21/Jul/2021 13:10:12] "POST /api/auth/login2.json HTTP/1.1" 403 2870
Unexpected token < in JSON at position 1

```

login.js
```javascript
export async function post(request) {
    console.log('doPost$$$')
    const res = await fetch('http://127.0.0.1:8000/api/auth/login2.json', request)
    // const res = await fetch(`http://127.0.0.1:8000/api/auth/login2.json`, {
    //     method: 'POST',
    //     headers: {
    //         'Accept': 'application/json',
    //         'Content-Type': 'application/json',
    //         'X-CSRFToken': 'LsP3MZui772fkrcrY42SfMNoahbQ1pItmpz4L3tYEhR6YHe3PfCB08YR2EFOCAeN'
    //     },
    //     body: JSON.stringify({
    //         username: 'test',
    //         password: 'a******'
    //     })
    // })
    const jsonData = await res.json()
    console.log(jsonData)
    if (res) {
        return {
            body: {
                jsonData
            }
        };
    }
}
```

api.py
```python
class UserIn(Schema):
    username: str
    password: str


@router.post("/login2.json")
def auth_login2(request, user_password: UserIn):
    print('auth_login2!')
    user = authenticate(request, username=user_password.username, password=user_password.password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return {'test': 'ok'}
    else:
        # Return an 'invalid auth' error message.
        return {}
```

**Comment by vitalik** [comment]
@jet10000

looks like your json is not valid or something...

can you do console.log(request) before `await fetch` ?

**Comment by jet10000** [comment]
@vitalik 

I I have solved this problem by refactoring the request. It seems to be very repetitive. Construct a request on the client side, refactor it on the server side because of the change of the request address, and finally request to the back-end django api. I hope it will be simpler. Currently using django_auth is very troublesome because of csrf. However, there is no ready-made method based on the header's api, which can be used out of the box.

**Comment by jet10000** [comment]
![image](https://user-images.githubusercontent.com/2258120/126513811-40c9fe1e-536a-4949-8108-d5f31994e12f.png)

**Comment by vitalik** [comment]
> . However, there is no ready-made method based on the header's api, which can be used out of the box.

you can skip django auth and use some [header based auth](https://django-ninja.rest-framework.com/tutorial/authentication/#in-header)

basically 

1) create some auth method where you return some token if username+pass is success
2) then use [APIKeyHeader based class](https://django-ninja.rest-framework.com/tutorial/authentication/#in-header) to parse token and return user
