### ISSUE TITLE
About django_auth csrf

### ISSUE THREAD

**Issue by jet10000** [vitalik/django-ninja#180]
Warning: It is not secure to use API's with cookie-based authentication! (like CookieKey, or django_auth)

https://django-ninja.rest-framework.com/tutorial/csrf/

https://www.youtube.com/watch?v=bG7cxwBMVag

I expect to enable django_auth authentication and avoid csrf in the api.

I'm using sveltekit to combine django and django-ninja. Many problems have been solved. If csrf is set, a lot of code must be added to the front end. The front-end reads the cookie through the session at the front-end server side, and the browser-side js does not directly read the cookie.

If I set djanog's csrf cookie to httponly, isn't it safe?

**Comment by rngallen** [comment]
I have created web app which will be used internally in our office, I have used django-ninja with django_auth. I know token is not good for browsers as it have to be saved on local storage which is less secure. I normally use token on mobile apps/server intergrations

**Comment by jet10000** [comment]
I test the client to get csrfToken


api.py
```
from django.middleware.csrf import get_token
from django.views.decorators.csrf import ensure_csrf_cookie

@router.get("/csrf")
@ensure_csrf_cookie
def csrf_token(request):
    token = get_token(request)
    return {'token': token}
```

display:

````
  File "app-x0rJexYI/lib/python3.9/site-packages/django/middleware/csrf.py", line 186, in _set_token
    response.set_cookie(
AttributeError: 'dict' object has no attribute 'set_cookie'
````

I have to add function to the view of django

views.py
```
from django.http import JsonResponse
from django.middleware.csrf import get_token
from django.views.decorators.csrf import ensure_csrf_cookie


@ensure_csrf_cookie
def refresh_csrf_token(request):
    token = get_token(request)
    return JsonResponse({'token': token})
```

It's work, I don’t know how to put this view directly into api.py

**Comment by vitalik** [comment]
@jet10000 

`ensure_csrf_cookie` works with Django responses only

so you need to return httpresponsne instead of dict


```Python
from django.http import JsonResponse

@router.get("/csrf")
@ensure_csrf_cookie
def csrf_token(request):
    token = get_token(request)
    return JsonResponse({'token': token})

```

**Comment by jet10000** [comment]
How API directly response login session_id in cookies? 


views.py
```python
def login_view(request):
    if request.method == 'POST':
        print('!!@!@login_view')
        print(request.POST['username'])
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return JsonResponse({'login': True})
        else:
            return JsonResponse({'login': False})
```

This is work. session_id in response.


api.py
```python
@router.post("/login2")
def login(request, payload: Credentials):
    print(payload)
    user = authenticate(request, username=payload.username, password=payload.password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        resp = JsonResponse({'username': user.username})
        resp.set_cookie(key='test123', value='123')
        return resp
    else:
        # Return an 'invalid auth' error message.
        return {}
```
No session_id in cookies.
