### ISSUE TITLE
Form-data/x-www-form-urlencoded did not work on put method

### ISSUE THREAD

**Issue by icebearrrr** [vitalik/django-ninja#183]
A weird bug...When i choose form-data or x-www-form-urlencoded as body, and use "PUT" method,  it gives "value_error.missing" error. And when i  replace the method with "POST", everything just goes well.

release version: 0.13.0

**Comment by vitalik** [comment]
@icebearrrr apprently PUT are not compatible with form-data

see #137

**Comment by icebearrrr** [comment]
got it. thanks
