### ISSUE TITLE
should we verify content-type instead of assuming application/json?

### ISSUE THREAD

**Issue by davidszotten** [vitalik/django-ninja#189]
to avoid vulnerability like https://blog.azuki.vip/csrf/

(submitting html forms avoids cors, and can be tricked to send json using content-type text/plain)

**Comment by vitalik** [comment]
@davidszotten 
Ninja relies on Django csrf mechanism ...
and as far as I know ALL POST requests are covered with csrf token check ..

**Comment by davidszotten** [comment]
well endpoints that are built to be called by api clients don't tend to be protected with csrf

**Comment by stephenrauch** [comment]
@davidszotten The linked article also mentions, in an update at the end, that with a modern browser, you should use the [`SameSite` cookie attribute](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite):

> UPDATE: Multiple folks have kindly pointed out that setting the SameSite cookie attribute in modern browsers to Strict effectively prevents this attack and most other CSRFs.

**Comment by vitalik** [comment]
> well endpoints that are built to be called by api clients don't tend to be protected with csrf

the csrf issue can happen only if you use some sort of cookie/session based authentication - and if you do use - Django Ninja will raise an exception forcing you to enable crsf

**Comment by davidszotten** [comment]
> @davidszotten The linked article also mentions, in an update at the end, that with a modern browser, you should use the [`SameSite` cookie attribute](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite):
> 
> > UPDATE: Multiple folks have kindly pointed out that setting the SameSite cookie attribute in modern browsers to Strict effectively prevents this attack and most other CSRFs.

> Which made me think that defaulting to SameSite=Strict for all authentication-related cookies would be a good idea... except that if you do that, your users will see the logged-out state when they follow a link to your site. That seems bad!

**Comment by stephenrauch** [comment]
> Which made me think that defaulting to SameSite=Strict for all authentication-related cookies would be a good idea... except that if you do that, your users will see the logged-out state when they follow a link to your site. That seems bad!

@davidszotten That in general seems to be the usecase for [`SameSite=lax`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#lax)
