### ISSUE TITLE
response schema openapi

### ISSUE THREAD

**Issue by thelittlebug** [vitalik/django-ninja#19]
the docs state that the response schema gets documented but im unable to see it.

am i doing something wrong?

**Comment by begyy** [comment]
I have this problem too :( 
![image](https://user-images.githubusercontent.com/44405438/96616264-c7ad4c00-131b-11eb-8d15-af8f71da60cc.png)
![image](https://user-images.githubusercontent.com/44405438/96616287-d09e1d80-131b-11eb-9054-a62603210ab4.png)
@vitalik did not fix this problem?

**Comment by vitalik** [comment]
fixed

Please use `pip install django-ninja==0.8.0`
