### ISSUE TITLE
Combine docs from different ninja instances

### ISSUE THREAD

**Issue by PyB1l** [vitalik/django-ninja#191]
Hi there, great work for ninja framework, I ve been using it for the couple 8 months and it feels great!

I wanted to ask if there is a way to join the different docs that direve from different ninja api instances. for the scope of my implementation I need to avoid to create and API module within each django app and create a sepate API app that implements 
all apps apis. Per app a have a different ninja instance to handle auth, tags, sessions, etc and as a result I have 7 or 8 different 
api docs. I dont really mind the different doc urls, but I was wondering FI there is a way to make it in one place!

Thanks in advance!

**Comment by vitalik** [comment]
hm.. not sure why you went that route... (maybe we did not had router auth and tacks 8 mont ago ? )
the routers could do the job for you:

```Python
#app 1:
app1_router = Router(auth=app1_auth, tags=["app1"])

# app2:
app2_router = Router(auth=app2_auth, tags=["app2"])

# and then finally

api = NinjaAPI()
api.add_router('/app1', app1_router)
api.add_router('/app2', app2_router)
```

But if that will be a complex change in your case - maybe the solution would be to build some sort of merge open api schemas:

```Python
from app1 import api as api1
from app2 import api as api2
from app3 import api as api3

def merge_schema():
    result = api1.get_openapi_schema()
    for api in [api2, api3]:
         schema = api.get_openapi_schema()
         ...merge restul and schema...
```
but my feeling this merge code will be as complex as changing NinajAPI to Router in code

**Comment by PyB1l** [comment]
Hm so I guess router should replace the multiuple ninja instances?

**Comment by vitalik** [comment]
I think yes, best case if you just find/replace "NinjaAPI" to "Router" in code
and then add all routers to one NinjaAPI instance

**Comment by PyB1l** [comment]
I wiil definitely make this refactor, thanks!
