### ISSUE TITLE
Response body getting out of parent container in openapi docs.

### ISSUE THREAD

**Issue by Laikos38** [vitalik/django-ninja#194]
Hi folks! First of all, thanks for this wonderful module.

Now the issue, when the response body has a large string it bugs the container instead of enable the horizontal scroll or wrap the text:

![image](https://user-images.githubusercontent.com/37281784/128620274-5c69c483-bc5c-434a-a173-fa62de00df0c.png)

Any idea on how to fix this?

**Comment by vitalik** [comment]
Hi @Laikos38 

I guess you can do the following

 - put 'ninja' to INSTALLED_APPS
 - then you would be able to override `ninja/swagger.html` inside your project
 - just add few css lines to the original template to make body scrollable or hidden

**Comment by vitalik** [comment]
hope that worked

**Comment by Laikos38** [comment]
Yes, indeed works, and with last version 0.14 this fix is no longer necessary thanks to the updated swagger :smile:
