### ISSUE TITLE
Single name path & numbers in Routers

### ISSUE THREAD

**Issue by LcTheSecond** [vitalik/django-ninja#195]
I'm testing the api. 
I Have the following set up in order to send a create POST method for lots of records at the same time.

Sorry in advance, English isn't my native language.

 "Files are as shown below"

<img width="170" alt="Captura de Tela 2021-08-08 às 19 41 03" src="https://user-images.githubusercontent.com/23480740/128647811-cb15a289-61ba-42ec-8e4e-b814fd022283.png">
<img width="683" alt="Captura de Tela 2021-08-08 às 19 41 26" src="https://user-images.githubusercontent.com/23480740/128647814-b561d8d3-c5fd-410d-9aa8-72d4e3cdf185.png">
<img width="709" alt="Captura de Tela 2021-08-08 às 19 41 33" src="https://user-images.githubusercontent.com/23480740/128647817-72f45f77-f92e-4c1c-98be-0f9487bd8c7c.png">
<img width="1206" alt="Captura de Tela 2021-08-08 às 19 46 01" src="https://user-images.githubusercontent.com/23480740/128647913-fe54b004-69e2-4974-8242-d0dcb08de18e.png">

The code Shown above works, i inserted 950 entries in the db at once.

but the path in the decorator next doesn't, i dont know why, even without the DOT

<img width="645" alt="Captura de Tela 2021-08-08 às 19 49 13" src="https://user-images.githubusercontent.com/23480740/128647978-11cf28ab-dc97-4d6d-be47-3e1d80f8c166.png">

or with a single word,  even /add or. /add/

<img width="637" alt="Captura de Tela 2021-08-08 às 19 50 24" src="https://user-images.githubusercontent.com/23480740/128648001-5aed17a7-ec65-4702-9b26-087a6601ec71.png">

It always returns the error shown below

<img width="1188" alt="Captura de Tela 2021-08-08 às 19 42 58" src="https://user-images.githubusercontent.com/23480740/128647843-2222a8f3-e972-427e-92e8-bc68a5419eb4.png">

**Comment by igoose1** [comment]
Hey, @LcTheSecond!

I wrote lines like yours and found no errors.

Is there a chance that Swagger UI wasn't reloaded after changing the code? What looks strange for me in the last screenshot: cURL example goes to `.../v01/...`, not to `.../v0.1/...`, and a server responses "`allow: GET`" in headers which means there is a GET endpoint `.../v01/add`.

(By the way, consider creating multiple rows with [bulk_create](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create). It's more polite for a database.)

**Comment by LcTheSecond** [comment]
> Hey, @LcTheSecond!
> 
> I wrote lines like yours and found no errors.
> 
> Is there a chance that Swagger UI wasn't reloaded after changing the code? What looks strange for me in the last screenshot: cURL example goes to `.../v01/...`, not to `.../v0.1/...`, and a server responses "`allow: GET`" in headers which means there is a GET endpoint `.../v01/add`.
> 
> (By the way, consider creating multiple rows with [bulk_create](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create). It's more polite for a database.)

Strange. I did try with and without dots.
Like  0.1 and 01
I remember reloading the server and clearing the cache in the browser.
I will try and replicate the issue and give U a feed back tomorrow.

 ( my timezone is GTM-3 )

**Comment by LcTheSecond** [comment]
> Hey, @LcTheSecond!
> 
> I wrote lines like yours and found no errors.
> 
> Is there a chance that Swagger UI wasn't reloaded after changing the code? What looks strange for me in the last screenshot: cURL example goes to `.../v01/...`, not to `.../v0.1/...`, and a server responses "`allow: GET`" in headers which means there is a GET endpoint `.../v01/add`.
> 
> (By the way, consider creating multiple rows with [bulk_create](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create). It's more polite for a database.)

Hello there,

Ur right.
I've got no idea why. But now. Every time I try, it works.
Really strange....
Thanks 4 your help.
