### ISSUE TITLE
Using create_schema twice causes inconsistency in schema output 

### ISSUE THREAD

**Issue by seeyabye** [vitalik/django-ninja#198]
I've been trying to use `create_schema` to create two different types of schema, one for get and one for put:

```python
class SampleModel(models.Model):
    first_field = models.CharField(max_length=100)
    second_field = models.CharField(max_length=100)

SampleSchema = create_schema(SampleModel, exclude=['id', 'first_field'])
SampleAllSchema = create_schema(SampleModel)
```

The first schema will exclude `id` and some other fields, let's say `first_field`. The second schema just shows everything. The paths are then define as follows:

```python
@api.get('/', response=List[SampleAllSchema])
def get_all(request):
    return SampleModel.objects.all()

@api.put('/{sample_id}')
def update(request, sample_id: int, payload: SampleSchema):
    return get_object_or_404(SampleModel, pk=sample_id)
```

If we check `localhost:8000/api/docs`, we will find that both endpoints show exactly the same schema.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/36906720/129326918-dee79115-1311-410d-950f-4171501cd49f.png)

</details>

If I perform inheritance on `SampleSchema`, this problem doesn't happen:

```python
SampleSchema = create_schema(SampleModel, exclude=['id', 'first_field'])
class SampleAllSchema(SampleSchema):
   id: int
   first_field: str
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/36906720/129328151-a1bb652a-80c0-42df-9adf-2eae011da493.png)

</summary>

**Comment by rngallen** [comment]
Pass kwarg name="foo" for each becase by default it takes models name which will be the same for both of them.
```
SampleSchema = create_schema(SampleModel, exclude=['id', 'first_field'], name="SampleSchema")
SampleAllSchema = create_schema(SampleModel, name="SampleAllSchema")```

**Comment by seeyabye** [comment]
Thanks! That appears to be working
