### ISSUE TITLE
Authentication is not working on router.

### ISSUE THREAD

**Issue by ahsan-kamal-sdq** [vitalik/django-ninja#20]
I was trying to add authentication on routers but it's not working. Below is the code snippet how I am implement the authentication.
 
### api.py file
```
api = NinjaAPI(version="1.0.0", auth=TokenAuthentication())
api.add_router('/', account_router)
```
### routers.py file

```
from ninja import Router
router = Router()


@router.post("/login")
def login(request):
    pass

@router.post("/register")
def register(request):
    pass

```

**Comment by vitalik** [comment]
hi @ahsan-kamal-sdq 
thank you for this catch

fixed,
Please use latest version 

`pip install django-ninja==0.6.0`

**Comment by ahsan-kamal-sdq** [comment]
Hi @vitalik thanks for quick fix.
