### ISSUE TITLE
add api in a installed apps can't find route?

### ISSUE THREAD

**Issue by jiamo** [vitalik/django-ninja#216]
In top project urls

```
urlpatterns = [
    # path('admin/', admin.site.urls),
    path("", hello),
    path("test/", include(("project.app.urls", "project.app"), namespace="app")),
]


```

Then in app urls:

```
from .views import api  # ninja api

urlpatterns = [
    path("/", api.urls)
]

```

After run . I can't find /test/someapi

**Comment by stephenrauch** [comment]
It looks like you attached it to `"/test"`.

**Comment by jiamo** [comment]
Update the mistake spell.

**Comment by stephenrauch** [comment]
Suggest you try removing the `'/'`
```
urlpatterns = [
    path("", api.urls)
]
```

**Comment by jiamo** [comment]
Thanks.  removing `'/'` works.

A little more confuse with ninja . I must use `127.0.0.1:80/test/test-ninja` .    `127.0.0.1:80/voip/test-ninja/` will 404
However using django view.  `127.0.0.1:80/voip/test-normal` I got `"GET /voip/test-normal HTTP/1.1" 301 Moved Permanently` while `127.0.0.1:80/voip/test-normal/` will ok.

So If I mix use normal view and ninja. The api access mode are not same.

**Comment by stephenrauch** [comment]
Yes that can be quite confusing.  It is inherent with the way django builds urls with and without the trailing slash.  If you want to be able to match the `/` where you were putting it in the `path` , you will need to put it into the operation instead, with something like:

```
@api.get("/")
def ...
```

Also the 301 behavior is driven via this: https://docs.djangoproject.com/en/3.2/ref/settings/#append-slash

**Comment by jiamo** [comment]
`@api.get("/test-ninja/")` make the same result.  thanks.
