### ISSUE TITLE
Returning redirect responses in endpoints

### ISSUE THREAD

**Issue by itaisteinherz** [vitalik/django-ninja#224]
I recently started using Django Ninja, and encountered a scenario where I need to return a redirect response to another endpoint (though it would be cool if I could redirect to any URL). I couldn't find a way to do this, and was unable to use something like [`redirect()`](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect)/[`HttpResponseRedirect`](https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpResponseRedirect) (the error I received was Pydantic-related, but I assume that even if validation was disabled, this still wouldn't have worked).

Is there a way to do this in Django Ninja?

**Comment by itaisteinherz** [comment]
@vitalik Thanks for the quick reply!

This is a simplified version of what I tried:

```python
from ninja import NinjaAPI

api = NinjaAPI()


@api.get('/something')
def some_redirect():
    return 302, '/another-endpoint'

# The API is then used in urls.py
```

**Comment by vitalik** [comment]
@itaisteinherz 
well seems you forgot the first parameter `request`

this works for me :

```Python
from django.shortcuts import redirect

api = NinjaAPI()


@api.get("/something")
def some_redirect(request): # < request
    return redirect("/some-path")

```

test:

```
$ http GET 'http://localhost:8000/api/something'
HTTP/1.1 302 Found
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Sat, 11 Sep 2021 13:52:12 GMT
Location: /some-path
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.6.9
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
```

**Comment by itaisteinherz** [comment]
I forgot to add the `request` argument in my comment, however I did add it in my actual codebase.

This probably didn't work for me because I did `return 302, redirect("/some-path")` in my endpoint, which I expected to work, but results in tthis error:

```
Schema for status 302 is not set in response dict_keys([200])
Traceback (most recent call last):
  File "C:\Users\itais\AppData\Local\Programs\Python\Python39\lib\site-packages\ninja\operation.py", line 95, in run
    return self._result_to_response(request, result)
  File "C:\Users\itais\AppData\Local\Programs\Python\Python39\lib\site-packages\ninja\operation.py", line 174, in _result_to_response
    raise ConfigError(
ninja.errors.ConfigError: Schema for status 302 is not set in response dict_keys([200])
Internal Server Error: /something
[11/Sep/2021 17:06:21] "GET /something HTTP/1.1" 500 450
```

In my opinion this is not trivial. Also, I'd like to have a way to control the specific status code used in the redirect.

1. Would you be in favor of documenting this in the docs?
2. Is there a way to use a specific status code for the redirect?

**Comment by stephenrauch** [comment]
The [`redirect()` function](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect) returns a [`HttpResponse` Object](https://docs.djangoproject.com/en/3.2/ref/request-response/#httpresponse-objects) which ninja passes through unmolested.  If the `redirect()` shortcut does not meet your needs you can construct any Django response object, with any status code or other details that you need, and return it from your view function.

**Comment by vitalik** [comment]
@itaisteinherz 
if you returning redirect - you do not need to output status code

change this:
```Python
return 302, redirect("/some-path")
```
to this:
```Python
return redirect("/some-path")
```

**Comment by itaisteinherz** [comment]
Got it.

I would add to the docs that you can return Django response objects from Ninja endpoints, and include redirects as an example (I went over the whole docs a few days ago and don't remember seeing this, and think that this is worth adding). I'd be happy to contribute the change myself if you're interested.

Thanks for explaining @vitalik @stephenrauch!

**Comment by thkwon1** [comment]
@itaisteinherz 

Hello, Thanks to your question, I could solve my problem about `redirect` that is same your problem. Thank you 😄 

In last comment, you said that you will contribute docs about `redirect` but, I can not find any `redirect` part in docs 😢

If you will have a plan that contributing docs about this issue, please contribute 🙏🏿

**Comment by vitalik** [comment]
done https://github.com/vitalik/django-ninja/commit/39a1e5b3f28c5e6d1261513015d882376af0f220
