### ISSUE TITLE
How to close api docs after release the product version!

### ISSUE THREAD

**Issue by song61069140** [vitalik/django-ninja#225]
How to close api docs after release the product version! Maybe fastapi framework is a good example.

**Comment by vitalik** [comment]
@song61069140 

```Python
api = NinjaAPI(openapi_url=None)
```
or based on DEBUG settings:
```Python
api = NinjaAPI(openapi_url=settings.DEBUG and "/openapi.json" or "")
```

**Comment by song61069140** [comment]
> @song61069140
> 
> ```python
> api = NinjaAPI(openapi_url=None)
> ```
> 
> or based on DEBUG settings:
> 
> ```python
> api = NinjaAPI(openapi_url=settings.DEBUG and "/openapi.json" or "")
> ```


I prefer this configure:
`api = NinjaAPI(openapi_url = settings.DEBUG and "/openapi.json" or "")`

`api = NinjaAPI(openapi_url = False)`

**Comment by picturedots** [comment]
With also the docs_url parameter, it's 
```
api = NinjaAPI(
    docs_url=settings.DEBUG and "/docs" or "",
    openapi_url=settings.DEBUG and "/openapi.json" or "",
    ...
)
```
