### ISSUE TITLE
Schema doesn't render properly

### ISSUE THREAD

**Issue by aprilahijriyan** [vitalik/django-ninja#236]
![Screenshot from 2021-10-03 10-31-49](https://user-images.githubusercontent.com/37798612/135746628-277455b5-d19a-424e-8caa-de4a58ec3557.png)

Code:

```python
def forgot_password(request: HttpRequest, email: EmailStr = Form(...)):
    ...

# And

def reset_password(
    request: HttpRequest,
    token: str,
    password: constr(strip_whitespace=True, min_length=8) = Form(...),
):
    ...
```

**Comment by aprilahijriyan** [comment]
![Screenshot from 2021-10-03 15-55-15](https://user-images.githubusercontent.com/37798612/135746709-f997bd4c-b9f3-4bbc-b8c0-03692fc58f0a.png)

**Comment by stephenrauch** [comment]
Can you help me understand what is improper here?  What should it be rendering?

**Comment by aprilahijriyan** [comment]
![Screenshot from 2021-10-04 13-17-51](https://user-images.githubusercontent.com/37798612/135802860-f2f6c58c-ed71-4150-878a-c2c7fbc2205f.png)

As you can see, the form data submission is incorrect. This should, send data like: `-d password=secret`

```
curl -X 'POST' \
  'http://127.0.0.1:8009/api/v1/auth/reset-password/sa' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d '0=s&1=t&2=r&3=i&4=n&5=g&6=s&7=t'
```
