### ISSUE TITLE
[proposal] need DATETIME_FORMAT to ninja Schema

### ISSUE THREAD

**Issue by KimSoungRyoul** [vitalik/django-ninja#244]
maybe I think that Datetime format is useful feature  like drf settings  (https://www.django-rest-framework.org/api-guide/settings/#date-and-time-formatting)

#### proposal 1  with Pydantic Config
~~~Python

api =NinjaAPI(
   ...
  renderer= ....
  ...
  config= Config(
      DATETIME_FORMAT = "%Y-%M-%D HH:MM:SS",
      DATE_FORMAT = "%Y-%M-%D",
      TIME_FORMAT = "%Y-%M-%D HH:MM:SS",
  )
)
~~~

or. it can use it using django config.

~~~Python

# settings.py 

DJANGO_NINJA =  {
      ....
      "DATETIME_FORMAT": "%Y-%M-%D HH:MM:SS",
      "DATE_FORMAT": "%Y-%M-%D",
      "TIME_FORMAT": "%Y-%M-%D HH:MM:SS",

}

~~~

if you think it's necessary,  can i pull request and request review?

**Comment by stephenrauch** [comment]
@KimSoungRyoul, so I have contributed to quite a few open source projects over the years, and they have all welcomed pull requests.  The standard necessary to have a pull request accepted has varied with the project, and with the scope of the pull request itself.

I am only a contributor here, but I for one would love to see how you how you would do this sort of thing at the framework (django ninja) level or at the pydantic level, or at what combination of the two.

**Comment by vitalik** [comment]
but yeah.. this quesions pops up pretty often... maybe it worth at least some documentation section

**Comment by KimSoungRyoul** [comment]
`Well the json representation layer is fully depends on pydantic...`

yeah fastapi is fully depends on pydantic  

but It seems like a good idea to provide django-ninja's features using pydantic config.

`ninja/schema.Schema` & `pydantic BaseModel` 

What do you think about managing these two classes differently?

`ninja/schema.Schema` is depend on `django settings.NINJA["DATETIME_FORMAT"]`. or `NinjaAPI()` Object


~~~Python
# ninja/schema.py

# this is Ninja's Object
class Schema(BaseModel):

    class Config:
        json_encoders = {
            datetime: lambda v: v.timestamp(),
        }


~~~

**Comment by wjhgg** [comment]
What's the status of this proposal？ @vitalik @KimSoungRyoul

**Comment by LeonemZhang** [comment]
I tried several schemes, but the format of the returned datetime cannot be changed
Does the configuration file exist to solve the problem

**Comment by vitalik** [comment]
https://github.com/vitalik/django-ninja/issues/1451#issuecomment-2814642405
