### ISSUE TITLE
Are recursive schemas supported?

### ISSUE THREAD

**Issue by ddahan** [vitalik/django-ninja#248]
I just read the whole Ninja documentation and it seems amazing.

The only question I still have: does it support recursive schemas? I did not see any mention of it (maybe I missed it), and I know that in DRF, I need a [plugin](https://github.com/heywbj/django-rest-framework-recursive) for this purpose.

For example, will that work?
```
class Employee(Schema):
    first_name: str
    last_name: str
    manager: Employee
```

No matter if it's currently supported or not, I think the info could be added to [this page](https://django-ninja.rest-framework.com/tutorial/response-schema/#nested-objects).

Thanks a lot.

**Comment by stephenrauch** [comment]
Yes, recursive schemas are supported.  Some test cases showing some possibilities are here: https://github.com/vitalik/django-ninja/blob/master/tests/demo_project/multi_param/api.py

**Comment by ddahan** [comment]
Ohhh, amazing, I missed it, thanks a lot.
