### ISSUE TITLE
Using a source attribute in schemas?

### ISSUE THREAD

**Issue by ddahan** [vitalik/django-ninja#250]
I'm in the middle of migrating a Django Rest Framework API to Django ninja.

What is the workaround to the `source` keyword used in DRF, which does not seem to exist with Django ninja?

For example for this DRF code:
```python
class RecipeSerializer(serializers.ModelSerializer):
    name = serializers.CharField(source="item.name")
    cooking_tools = CookingToolSerializer(many=True)
```

```python
class RecipeSchema(ModelSchema):
    name: str # Obviously, it can NOT work as the `name` attribute belongs to `Item` model, not a `Recipe` model.
    cooking_tools: List[CookingToolSchema]
```

Any idea? Thanks.

**Comment by ddahan** [comment]
Thanks a lot, it makes sense to use properties as a clean workaround.

Side question (which does not require another issue IMO): do I have to use a property to access reverse related fields too?

For example, let's say I want to make this ninja code work:

```python
class ItemSchema(ModelSchema):
    recipe_id: int = None

    class Config:
        model = Item
        model_fields = (
            # ...
        )

class RecipeSchema(ModelSchema):
    item: ItemSchema

    class Config:
        model = Recipe
        model_fields = (
            "item",
        )

@api.get("/recipe/{recipe_id}", response=RecipeSchema)
def recipe(request, recipe_id: int):
    recipe = get_object_or_404(Recipe, id=recipe_id)
    return recipe
```

Do I have to create the `recipe_id` by myself like this??

```python
class Recipe(models.Model):
    item = models.OneToOneField("Item", on_delete=CASCADE)

class Item(models.Model):

    # ...

    @property
    def recipe_id(self) -> Optional[int]:
        if self.recipe:
            return self.recipe.id
```

This code works as expected, but I'm just wondering is there is a simpler way, without declaring a property manually.
Thanks a lot.

**Comment by stephenrauch** [comment]
If I understand correctly what you are asking (ie: needing to add a `recipe_id` property to `Item`), generally Django takes care of that for you.

https://docs.djangoproject.com/en/3.2/ref/models/fields/#database-representation

**Comment by stephenrauch** [comment]
Not sure what the difference in the setups are, but from a python shell I get:
```python
>>> from django.db import models
>>> class Recipe(models.Model):
...     class Meta:
...         app_label = "testy"
...     item = models.OneToOneField("Item", on_delete=models.CASCADE)
...
>>> class Item(models.Model):
...     class Meta:
...         app_label = "testy"
...
>>> recipe = Recipe()
>>> [x for x in dir(recipe) if x.endswith('id')]
['id', 'item_id']
>>> recipe.item_id is None
True
>>>
```
