### ISSUE TITLE
ModelSchema typing

### ISSUE THREAD

**Issue by asaff1** [vitalik/django-ninja#259]
Nice project. Good to see the ideas from FastAPI get integrated with Django.

The problem,
when using `ModelSchema`, an IDE like pycharm does not autocomplete the generated schema.

```python
class CustomerIn(ModelSchema):
    extra_field: str

    class Config:
        model = Customer
        model_fields = ['name', 'date']
```
Then
```python
customer: CustomerIn
customer.name  # unknown field for the IDE
customer.extra_field  # ok
```

Possible workarounds?

**Comment by paulzakin** [comment]
Just confirming that I'm also experiencing the issue with VSCode and mypy. I was gonna open an issue myself, but then I saw your issue!

**Comment by vitalik** [comment]
@asaff1 @paulzakin 
Well, I do not see solution here.. simply because actual schema is created at runtime from ModelSchema...

my general use case - if fields not that many - i tend to use just schema, but if model has like 10+ fields - I use ModelSchema (usually in that case you never access each individual field separately anyway)

**Comment by paulzakin** [comment]
Ok, I figured that would be the answer. Makes total sense to me, and that's the solution I was gonna to implement. Just wanted to make sure I wasn't missing anything. Awesome library by the way!

**Comment by sebastian-philipp** [comment]
For proper type checking, we're going to need a django-ninja mypy plugin, if I'm not mistaken.

**Comment by sebastian-philipp** [comment]
Possible workaround might be to at least define the fields for mypy:

```python
from typing import TYPE_CHECKING
if TYPE_CHECKING 
   class MySchema(Schema):
       my_field: str
else:
   class MySchema(ModelSchema):
       class Config
           model = MyDjangoModel
```
As `ModelSchema` is providing more than just the field definitions, I think it still makes sense to use `ModelSchema` regardless.

**Comment by asaff1** [comment]
@sebastian-philipp this is not fun to write when you have many models : (
mypy plugin does make sense, like pydantic have one

**Comment by hiaselhans** [comment]
Is this solved in master?

**Comment by sebastian-philipp** [comment]
@hiaselhans what do you by "solved"?

**Comment by hiaselhans** [comment]
i mean: do we have a mypy plugin ready?

**Comment by vitalik** [comment]
@hiaselhans well this is not solvable issue - if you use modelschema - mypy will not be happy
