### ISSUE TITLE
fk_id fields does not work with `ModelSchema`

### ISSUE THREAD

**Issue by asaff1** [vitalik/django-ninja#261]
Assuming `Customer` has a `ForeignKey` to User, this does not work:
```python
class CustomerSchema(ModelSchema):
    class Config:
        model = Customer
        model_fields = ['user_id', 'name']
```

I get 
```
ninja.errors.ConfigError: Field(s) {'user_id'} are not in model.
```
(But `user` instead of `user_id` does work, and gives a number)

I would expect the generated schema to be consistent with attribute lookups of django orm. So, `user_id` should return a the id as well.
Is there a reason this doesn't work?

**Comment by art3mHQ** [comment]
can someone explain please why here https://django-ninja.dev/guides/response/django-pydantic/
code looks like that 
```
class UserSchema(ModelSchema):
    class Meta:
        model = User
        fields = ['id', 'username', 'first_name', 'last_name']
```

but you use `Config` instead of `Meta` 
- my code is not working with `Meta` django-ninja  0.20.0

**Comment by art3mHQ** [comment]
> __ can someone explain please why 

because Doc for the version is here https://github.com/vitalik/django-ninja/blob/v0.20.0/docs/docs/guides/response/django-pydantic.md
