### ISSUE TITLE
Please make the response model optional!

### ISSUE THREAD

**Issue by aprilahijriyan** [vitalik/django-ninja#262]
I always get this on openapi.

```
ninja.errors.ConfigError: Schema for status 400 is not set in response dict_keys([200])
```

when I don't add a specific response model, it shouldn't be validated!

**Comment by aprilahijriyan** [comment]
Sorry for the slow response, this is my code:

```python
order_router.add_api_operation(
    "",
    ["GET"],
    views.read,
    response={
        400: ResponseSchema,
        404: ResponseSchema,
    },
)
```

When I return a response with a status code of 200 this error will occur as below:

```
ninja.errors.ConfigError: Schema for status 200 is not set in response dict_keys([400, 404])
```

**Comment by aprilahijriyan** [comment]
@vitalik This feature request is optional only, this error can be fixed by adding a schema 200 response with ``typing.Any``. Feel free if this issue wants to be closed :)

**Comment by vitalik** [comment]
@aprilahijriyan 

well it looks like what you need to do is just return the correct code based on your logic:

```Python
order_router.add_api_operation(
    "",
    ["GET"],
    views.read,
    response={
        400: ResponseSchema,
        404: ResponseSchema,
    },
)


# views.py:

def read(...):
     if foo:
          return 400, {some: data}
     else:
           return 404, {some: other_data}
```

**Comment by SmileyChris** [comment]
@vitalik I think the OP is just asking that no error is raised for response statuses that aren't in the response dict -- just assume `Any` for every missing status code.

The same thing tripped me up when I started too (but I'm indifferent as to whether it needs "fixing")

If that's not going to happen, let's just close this issue :)

**Comment by vitalik** [comment]
@SmileyChris @aprilahijriyan 

My general feeling is that letting return `http-code, data` tuples was a mistake

users want too much from it like returning headers, cookies, redirects...

---

The idea of verbose `response` is to document API with OpenAPI spec - so if it's NOT defined - it's not documented and API users might get unexpected codes/results


I think the general approach in cases when you defined one response code but want to throw some 4xx codes is to use exceptions:


```Python
from ninja.errors import HttpError

@api.get('/foo', response=SomeSchema)
def foo(request):
     if random.randint(1,5) == 3:
             raise HttpError(400, "Something bad happend")  # !!!
     return {...}
```

or use [custom exception handlers](https://django-ninja.rest-framework.com/tutorial/errors/#custom-exception-handlers)
