### ISSUE TITLE
is there a way to protect /docs? 

### ISSUE THREAD

**Issue by lgabs** [vitalik/django-ninja#267]
Is there a way to protect the `/docs` endpoint using authentication?

**Comment by Ophuscado** [comment]
Another alternative is to enable HTTP Basic Authentication from your web server.

**Comment by farialima** [comment]
I was asked to authenticate the docs, with the Django Admin authentication, I hacked it that ways:

```python
from functools import partial

from django.urls import path
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

import ninja
from ninja.openapi.views import openapi_json, swagger


admin_login = reverse_lazy('admin:login')

authenticated_openapi_json = login_required(login_url=admin_login)(openapi_json)

authenticated_swagger = login_required(login_url=admin_login)(swagger)


class NinjaAPI(ninja.NinjaAPI):
    def _get_urls(self):
	# adapted from  ninja.openapi.urls.get_openapi_urls                                                                                                                       
        # same code but replacing each view by its authenticated versions                                                                                                         

	openapi_url = self.openapi_url
	# avoid generating default openapi paths...                                                                                                                               
        try:
            self.openapi_url = None
            urls = super(NinjaAPI, self)._get_urls()
        finally:
            self.openapi_url = openapi_url

        return urls + [
            # ... but generate them with our authenticated views                                                                                                                  
            path(
                self.openapi_url.lstrip("/"),
                partial(authenticated_openapi_json, api=self),
                name="openapi-json",
            ),
            path(
                self.docs_url.lstrip("/"),
		partial(authenticated_swagger, api=self),
		name="openapi-swagger",
            )
        ]
```
i.e. basically copied the upstream code... 
... but indeed I should probably have used a middleware !!!

**Comment by vitalik** [comment]
Hi @farialima 

yeah.. middleware seems hard to read...


here is another way that to me looks more verbose and clear:

```Python
...
from ninja.openapi.views import openapi_json, swagger

# 1) Disable default open api urls:

api = NinjaAPI(openapi_url=None)

# 2) Make open api urls login_required:
@login_required
def authenticated_openapi_json(request):
    return openapi_json(request, api)


@login_required
def authenticated_swagger(request):
    return swagger(request, api)

# 3) Add these views to urlpatters:

urlpatterns = [
    path('api/', api.urls),
    path('api/docs', authenticated_openapi_json),          # + !!!!!
    path('api/openapi.json', authenticated_openapi_json),  # + !!!!!
    ...
]
```
so basically - disable default openapi views and then wrap views to login_required view and add them to urlpatterns

**Comment by radusuciu** [comment]
@vitalik 

That seems like a nice solution, but I'm getting this error when trying to access the docs (while logged in): `django.urls.exceptions.NoReverseMatch: Reverse for 'openapi-json' not found.`

The error persists even if I add a `name='openapi-json'` to the `api/docs` path. Any pointers? I've tried to explicitly set the namespace as well but that didn't seem to work either

**Comment by vitalik** [comment]
@radusuciu 

add a `name` to path:


```Python
   path('api/openapi.json', authenticated_openapi_json, name='openapi-json'),
```

**Comment by SmileyChris** [comment]
I wonder if adding a decorator function to `get_openapi_urls` would be a nice option...

Then you could just do 

api_urlpatterns = [
    path('', include(get_openapi_urls(api, decorator=login_required)),
    path('', api.urls),
]

urlpatterns = [
    path('api/', include(api_urlpatterns),
    ....
]

**Comment by vitalik** [comment]
@SmileyChris 

well in that case maybe the instance param would make sense

like:
```Python
api = NinjaAPI(docs_decorator=login_required)
```

**Comment by SmileyChris** [comment]
Totally! But wasn't sure if you want to keep overloading the main API with
more features for edge cases. Since maybe you'd want both docs_decorator
and openapi_decorator...

**Comment by radusuciu** [comment]
> @radusuciu
> 
> add a `name` to path:
> 
> ```python
>    path('api/openapi.json', authenticated_openapi_json, name='openapi-json'),
> ```

I did attempt that, but unless I've missed something obvious or my setup had some idiosyncrasy I've not realized, the error persists. The relevant bits of code:

```python
# views/api.py
from django.contrib.auth.decorators import login_required
from ninja.security import django_auth
from ninja.openapi.views import openapi_json, swagger


# disabling openapi_url since we want to replace it with
# authenticated versions. See authenticated_openapi_json
# and authenticated_swagger. For more details:
# https://github.com/vitalik/django-ninja/issues/267#issuecomment-1013140999
ninja = NinjaAPI(auth=django_auth, openapi_url=None, csrf=True)

# 2) Make open api urls login_required:
@login_required
def authenticated_openapi_json(request):
    return openapi_json(request, ninja)
```

```python
# urls.py
from django.urls import path

from .views import ninja, authenticated_swagger, authenticated_openapi_json

urlpatterns = [
    path('api/', ninja.urls),
    path('api/docs/', authenticated_swagger, name='openapi-swagger'),
    path('api/openapi.json', authenticated_openapi_json, name='openapi-json'),
]
```

and the error

```
NoReverseMatch at /api/docs/

Reverse for 'openapi-json' not found. 'openapi-json' is not a valid view function or pattern name.
```

Env details
- Python 3.9.9
- Django 3.2.11
- django-ninja: 0.17.0

Running in an official python docker image.

Thanks for the help!

**Comment by YoniSeedx** [comment]
@radusuciu - any luck with this?  I'm experiencing the same issue...

**Comment by SmileyChris** [comment]
Thinking about this some more, it'd be better if you could just pass the whole doc view to the api. Then you could just inherit the standard one and wrap it in a standard auth decorator or do whatever other magic you wanted.

**Comment by vitalik** [comment]
@SmileyChris 
yeah, I was thinking maybe something like let users override few methods on the NinjaAPI instance:

```Python
class AuthedDocsAPI(NinjaAPI):
    def view_docs(self, request):
             if not requst.user.is_staf:
                    return HttpFobidden()
             return super().view_docs(request)

   def view_openapi_json(self, request):
         ....

```

**Comment by YoniSeedx** [comment]
As an update to my question from a few days ago, I got it to work by adding the swagger/json endpoints directly to the Ninja API.  Hopefully this helps someone else who ran into the same problems.

Ie:
```
@router.get("/docs", auth=None)
def authenticated_swagger(request):
   if auth_logic:
       return swagger(request, api)
```

**Comment by iforvard** [comment]
> 

In version 0.18.0 authenticated_openapi_view replaced authenticated_swagger  
https://github.com/vitalik/django-ninja/pull/427

@staff_member_required
def authenticated_openapi_view(request):
    return openapi_view(request, api)

**Comment by quroom** [comment]
Full code

in your project ```urls.py```
Add
```
path('api/docs', authenticated_swagger, name='openapi-swagger'),
path('api/openapi.json', authenticated_openapi_json, name='openapi-json'),
path("api/", api.urls),
```

in your ```api.py``` which includes NinjaAPI
Add
```
from django.contrib.admin.views.decorators import staff_member_required
from ninja.openapi.views import openapi_json, openapi_view

@staff_member_required
def authenticated_openapi_json(request):
    return openapi_json(request, api)

@staff_member_required
def authenticated_swagger(request):
    return openapi_view(request, api)
```

Whatever you want , you can change decorate. like login_required.

**Comment by vitalik** [comment]
since version 0.19 you now can protect docs with decoroator:
https://django-ninja.rest-framework.com/tutorial/api-docs/#protecting-docs

```Python
from django.contrib.admin.views.decorators import staff_member_required

api = NinjaAPI(docs_decorator=staff_member_required)
```

**Comment by amoralesc** [comment]
The docs on how to protect API docs have moved here:
https://django-ninja.dev/guides/api-docs/#protecting-docs
