### ISSUE TITLE
Example multiple files and some meta 

### ISSUE THREAD

**Issue by vitalik** [vitalik/django-ninja#269]
Add docs example for the case when need to upload list of files along with some form data

**Comment by vladyslavushakov** [comment]
@vitalik 
I faced the same issue with multiple file uploads. Is there any documentation about this case?

**Comment by vitalik** [comment]
@vladyslavushakov seems that's already there https://django-ninja.rest-framework.com/guides/input/file-params/#uploading-array-of-files

list of files:

```Python
@api.post('/user')
def create_user(request, details: UserDetails = Form(...), files: list[UploadedFile] = File(...)):
    return [details.dict(), [f.name for f in files]]
```
