### ISSUE TITLE
how to generate opional values in api doc when using choice field

### ISSUE THREAD

**Issue by lihuacai168** [vitalik/django-ninja#270]
# Question
The env field is a choice field.
But there are not opional values in api doc.

# view
```python
@router.post('/datasource/create')
def create(request, datasource_config: Union[schemas.MySQL]):
    """创建一个数据源"""
    obj = models.MySQL.objects.create(**datasource_config.dict())
    return {'id': obj.id}
```
![image](https://user-images.githubusercontent.com/11568297/139674879-6b5f295f-db55-439d-b52a-02371050ddf8.png)

# ModelSchema
```python
# schemas.py
from ninja import ModelSchema

class DataSourceBaseModelSchema(Schema):
    @validator('type', check_fields=False)
    def type_must_in_range(cls, v):
        if v not in models.DataSourceCoreModel.TYPE:
            raise UnprocessableEntity(f'type must in {models.DataSourceCoreModel.TYPE}')
        return v

    @validator('name', always=True, check_fields=False)
    def name_must_be_unique(cls, name, values):
        obj = models.MySQL.objects.filter(name=name).first()
        if obj:
            raise UnprocessableEntity(f"Duplicate entry {name} for key 'name'")
        return name

    class Config:
        pass


class MySQL(ModelSchema, DataSourceBaseModelSchema):
    class Config:
        model = models.MySQL
        model_fields = ['name', 'env',]
```

```python
# models.py

from model_utils import Choices


class DataSourceCoreModel(models.Model):
    """
    """
    ENV = Choices(
        (0, 'TEST'),
        (1, 'STABLE'),
        (2, 'STAGING'),
        (3, 'UAT'),
        (4, 'LIVE'),
        (5, 'LIVEISH')
    )
    name = models.CharField(max_length=255, help_text="数据源名称", unique=True, db_index=True)
    env = models.IntegerField(help_text="数据源环境", choices=ENV, default=0, db_index=True)
```
![image](https://user-images.githubusercontent.com/11568297/139674543-ab24379a-1dbc-419d-98e3-f6ec90c2f7d0.png)
# API Doc
![image](https://user-images.githubusercontent.com/11568297/139674598-8dba6906-8c24-4c52-a2e7-8253a9ba2b59.png)

**Comment by vitalik** [comment]
@lihuacai168 

can you show what is  `model_utils.Choices` in your case ?
```Python
from model_utils import Choices
```

**Comment by vitalik** [comment]
@lihuacai168 

model-schema currently not creating choices automatically... I'm yet not sure how best appraoch it

but for your case you can for now do the following:

```Python
from enum import IntEnum

# create enum choice 
EnvEnum = IntEnum('EnvEnum', 'TEST STABLE STAGING UAT LIVE LIVEIS', start=0)


class MySQL(ModelSchema, DataSourceBaseModelSchema):
    env: EnvEnum # !!!!!!!!!!!!!!! <------
    class Config:
        model = models.MySQL
        model_fields = ['name', 'env',]

```

**Comment by lihuacai168** [comment]
> @lihuacai168
> 
> can you show what is `model_utils.Choices` in your case ?
> 
> ```python
> from model_utils import Choices
> ```

here is [model_utils.Choices](https://github.com/jazzband/django-model-utils)

**Comment by lihuacai168** [comment]
> @lihuacai168
> 
> model-schema currently not creating choices automatically... I'm yet not sure how best appraoch it
> 
> but for your case you can for now do the following:
> 
> ```python
> from enum import IntEnum
> 
> # create enum choice 
> EnvEnum = IntEnum('EnvEnum', 'TEST STABLE STAGING UAT LIVE LIVEIS', start=0)
> 
> 
> class MySQL(ModelSchema, DataSourceBaseModelSchema):
>     env: EnvEnum # !!!!!!!!!!!!!!! <------
>     class Config:
>         model = models.MySQL
>         model_fields = ['name', 'env',]
> ```

Using IntEnum, it work like that: 
![image](https://user-images.githubusercontent.com/11568297/139776842-9888cddd-57ef-453f-b0c9-ba575d4c6aa0.png)

But still not show the env value `TEST STABLE STAGING UAT LIVE LIVEISH`

**Comment by rexzhang** [comment]
```
class EventLevel(models.TextChoices):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"

class Event(models.Model):
    level = models.TextField(choices=EventLevel.choices)
    message = models.TextField()

class EventSchema(ModelSchema):
    level: EventLevel

    class Config:
        model = Event

```
<img width="405" alt="截屏2021-12-02 13 03 17" src="https://user-images.githubusercontent.com/238707/144361031-31fc8245-3bff-4fc2-a1e3-69fcb5efe9f1.png">

it's work on Django3.2.9, ninjia0.16.1

`django.db.models.TextChoices` is a subclass of `enum.Enum`

**Comment by rexzhang** [comment]
BTW, how use this in func `ninja.orm.create_schema`?
