### ISSUE TITLE
Not required fields in Response Schema

### ISSUE THREAD

**Issue by albertocerrone** [vitalik/django-ninja#279]
I'm trying to have responses that don't show not required fields.

At the moment, if I follow the docs I can reach something like that
![image](https://user-images.githubusercontent.com/72306953/140961862-9f37eb15-1de0-447d-87d1-f04b9a0caacb.png)
But this returns `test` as `null`
![image](https://user-images.githubusercontent.com/72306953/140961980-46a1a681-895f-421b-a455-62d23a7e76d4.png)

How can avoid returning `test` at all? 
Thank you so much 🙏🏼

**Comment by vitalik** [comment]
Hi @albertocerrone 

you can use `exclude_none` argument on your view:

```Python

@api.get('/foo', response=SSS, exclude_none=True)
def viwefunc(request,... ):
    ...

```

**Comment by albertocerrone** [comment]
@vitalik Thank you so much! 🙏🏼

**Comment by albertocerrone** [comment]
Pardon @vitalik but I have to ask more.

This method works fine if I want to exclude all the none value. but there are cases where I want to send some none field and some fields I don't want to show them.
How can I exclude a single attribute? In this case just `test`.

thank you again

**Comment by vitalik** [comment]
Hm.. that a rare one 

you can try other parameter `exclude_defaults` - which will exclude values that equal to default values

note: under the hood django-ninja uses pydantics [dict() method](https://pydantic-docs.helpmanual.io/usage/exporting_models/#modeldict)
