### ISSUE TITLE
Tutorial - how to do a simple CRUD

### ISSUE THREAD

**Issue by zafon18** [vitalik/django-ninja#28]
Hello,
I am a beginner in Django Ninja, I would like to know if there are tutorials on how to do a simple CRUD in Django Ninja?
greetings,

**Comment by vitalik** [comment]
Hi @zafon18 

there you go - https://django-ninja.rest-framework.com/tutorial/crud/

Please check/try - let me know what parts made you struggle

**Comment by zafon18** [comment]
Hey @vitalik,

Last time there was no this tutorial;) - You are fast (just like django-ninja).

Thanks again for your help and good health.

Greetings.
