### ISSUE TITLE
Async and tests

### ISSUE THREAD

**Issue by al-stefanitsky-mozdor** [vitalik/django-ninja#284]
Hi! Is there any async tests example?

I tried httx (what exectly i used to test FastAPI) and it didn't work.

Error says: `TypeError: 'NinjaAPI' object is not callable`

**Comment by vitalik** [comment]
Hi @al-stefanitsky-mozdor 

the error look like some sort of invalid import... can you show more source code ?

as for async tests - you can check it here (with pytest)

https://github.com/vitalik/django-ninja/blob/master/tests/test_async.py

**Comment by al-stefanitsky-mozdor** [comment]
Ahh, thanks!

**Comment by al-stefanitsky-mozdor** [comment]
I can't show, sorry, it's complicated and it's from my work...
