### ISSUE TITLE
Why flint instead of poetry? How to contribute?

### ISSUE THREAD

**Issue by al-stefanitsky-mozdor** [vitalik/django-ninja#287]
Hi! I want to contribute, but i found that project depends on flint and it seems very unfriendly to me.

It gave 2 questions to me:
- Could we add some docs for contributors?
- Could we move to poetry?

**Comment by vitalik** [comment]
> * Could we add some docs for contributors?

Already there https://github.com/vitalik/django-ninja/blob/master/CONTRIBUTING.md

> * Could we move to poetry?

Well the whole CI/CD process is already configured with flit (and tehnically we do not need full power from poetry - our case is just install deps and deploy to pypi)

but to start locally you just need to install dependencies from [pyproject.toml](https://github.com/vitalik/django-ninja/blob/master/pyproject.toml) with any tool you like

**Comment by al-stefanitsky-mozdor** [comment]
Hm, thanks, i tried, but when i run tests i get this:
`No module named 'tests.demo_project'`

**Comment by vitalik** [comment]
@al-stefanitsky-mozdor 
could you show full log and command that you executed ?

**Comment by al-stefanitsky-mozdor** [comment]
> @al-stefanitsky-mozdor could you show full log and command that you executed ?

Sure:
![image](https://user-images.githubusercontent.com/93194623/143213188-34007b63-abdb-495d-ac3d-a081d4af9489.png)

**Comment by al-stefanitsky-mozdor** [comment]
Is that can be a problem with python 3.9?

**Comment by vitalik** [comment]
Nope - I have by default 3.9 (and django ninja has [full matrix of 3.6 3.7 3.8 3.9 3.10 support](https://github.com/vitalik/django-ninja/blob/master/.github/workflows/test_full.yml#L13) )
```
platform darwin -- Python 3.9.4, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/vitaliy/projects/django-ninja
plugins: cov-2.12.1, asyncio-0.15.1, django-4.4.0
collected 379 items                                                                                                                                                                       

tests/test_django_models.py .   
...
```

did you installed all with flit ?

**Comment by al-stefanitsky-mozdor** [comment]
Yes, i did it with `flit install --deps develop --symlink`

**Comment by al-stefanitsky-mozdor** [comment]
I'll try to reinstall whole repo

**Comment by al-stefanitsky-mozdor** [comment]
On my personal laptop all works fine, something wrong with my envs, nevermind, thanks!
