### ISSUE TITLE
Response delayed

### ISSUE THREAD

**Issue by p-baum** [vitalik/django-ninja#289]
hello. i just started with django-ninja. I dont know what im doing wrong but when i send a json request which takes about 4 seconds to update the database,  the response is not sent until about another 4 seconds after my post function returns.  This doubles the time taken.  Where is this time spent? what is happenening?

**Comment by vitalik** [comment]
@p-baum 
well this is hard to tell - can be anything - you need at least give some code exaples or profiling report

**Comment by p-baum** [comment]
I just tried it with a plain old JsonResponse and the issue persists.  I guess the issue doesnt belong here.  I am however still stumped on this.  Django debug logs reveal nothing in the lost time window between view return and request response received.  Its a fairly hefty request updating or creating about 30 models hence the 4 second time.  How can I find out where this time is spent and what is happening?

**Comment by vitalik** [comment]
@p-baum 
try [django-debug-toolbar (+history plugin)](https://github.com/vitalik/django-ninja/discussions/268)

**Comment by p-baum** [comment]
Thankyou. Sorry for the disturbance.
