### ISSUE TITLE
RuntimeError: error checking inheritance of {200: <class 'user.schema.Token'>, 401: <class 'user.schema.Message'>} (type: dict)

### ISSUE THREAD

**Issue by begyy** [vitalik/django-ninja#29]
![image](https://user-images.githubusercontent.com/44405438/96619090-2c1dda80-131f-11eb-8adb-068212ba43d3.png)

![image](https://user-images.githubusercontent.com/44405438/96619126-37710600-131f-11eb-883d-6f50d3685e6b.png)

**Comment by begyy** [comment]
![image](https://user-images.githubusercontent.com/44405438/96619214-51aae400-131f-11eb-8956-e8eb9ffcea57.png)
но так работает))

**Comment by MaksimLion** [comment]
@begyy 
this is Enhancement Proposals
It will not work right now

**Comment by vitalik** [comment]
@begyy 
this approach is part of #16 proposal that is not yet implemented / designed
