### ISSUE TITLE
Path parameters outside decorator don't work

### ISSUE THREAD

**Issue by grucha** [vitalik/django-ninja#292]
Hello

I'm using `django-tenants` with tenant name in URL. It is being used by middleware.

- django==2.2
- django-ninja==0.16.1

urls.py:
```
from myapp.views import api

urlpatterns += [
    path("api/v1/<str:organization_name>/cases/", api.urls),
]
```

views.py:
```
from ninja import NinjaAPI

api = NinjaAPI(csrf=False)

@api.get("/{int:some_id}/hola")
def some_view(request, some_id: int, organization_name: str):
    return {"hola": some_id, "organization_name": organization_name}

    # Returns validation error: field required ("loc": ["query", "organization_name"])
```

With the above setup there are two issues:

1. Most importantly `django-ninja` is freaking out about `organization_name` param upon accessing the docs: `/api/v1/some-org/docs`. Results with ```swagger() got an unexpected keyword argument 'organization_name'```
2. I can't access this param in the view even if I declare it in function definition. I get a 400 response with validation error saying that this query param is missing (it interprets this param as query param).

Can you help?

**Comment by vitalik** [comment]
Hi @grucha 

it is not possible (at least ATM) to pass params outside django ninja instance...

what you can do is either add kwargs:

```Python
@api.get("/{int:some_id}/hola")
def some_view(request, some_id: int, **kwargs): #!!!
    return f'some_id: {some_id}, kwargs: {kwargs}'

```
that will only do silence for django ninja validation

but at the end you will loose alot of helpsers like swagger UI, and kwargs will not actually hold the organization_name

OR

you need to pass organization_name to views:

```Python
# urls.py
urlpatterns += [
    path("api/v1/", api.urls),
]

# views

@api.get("/{organization_name}/cases/{some_id}/hola")
def some_view(request, some_id: int, organization_name: str):
    return f'some_id: {some_id}, organization_name: {organization_name}'


```

**Comment by grucha** [comment]
Is there maybe a way to introduce some "external_kwargs" param while instantiating NinjaAPI? I mean would curernt architecture allow it? I could look into coding it and push some PR but can you please let me know if it's  even worth looking into?

**Comment by vitalik** [comment]
@grucha 

well generally I do not like the idea when some variable is "magically" apearing breacking the commong logic (if argument not market it expected to come from query params)

```Python
@api.get("{some_id}/hola")
def some_view(request, some_id: int, organization_name: str):
```

BUT there is another way - use Path market to specifiy that this variable will come from path params:


```Python
```
