### ISSUE TITLE
ModelSchema to include all model fields

### ISSUE THREAD

**Issue by rngallen** [vitalik/django-ninja#293]
What if my model have many fields and I want to include all fields on my model schema?
I have tried to put empty list on `model_exclude` but I got ```ninja.errors.ConfigError: Creating a ModelSchema without either the 'model_fields' attribute or the 'model_exclude' attribute is prohibited```
My model

```
class TitleOutSchema(ModelSchema):
    class Config:
        model = Title
        model_exclude = []
```

**Comment by vitalik** [comment]
@rngallen 

why would you need ModelSchema then ?
just use regular Schema

**Comment by ddahan** [comment]
@vitalik I'm not sure to understand your answer about this. How using a regular Schema would be better than a ModelSchema if you need to include all fields in the payload, no matter these fields?

The author and I are looking for the Ninja equivalent to this in Django Rest Framework:
```
class AccountSerializer(serializers.ModelSerializer):
    class Meta:
        model = Account
        fields = '__all__'
```

**Comment by rngallen** [comment]
I was looking for something like that but as per his answer he mean we can use this

`from ninja.orms import create_schema`

And to use it as

`AccountSchema = create_schema(Account, name='AccountSchema)`

All fields will be included

**Comment by vitalik** [comment]
@rngallen @ddahan 
Ok, I got what you mean
so next release will have the `__all__` option:
```Python
class TitleOutSchema(ModelSchema):
    class Config:
        model = Title
        model_fields = "__all__"   # <--- !
```
