### ISSUE TITLE
Is this project production ready ?

### ISSUE THREAD

**Issue by StitiFatah** [vitalik/django-ninja#294]
Sorry if the question has already been asked but it's been a year since I've last checked this project and I'm still hesitating between django ninja and DRF for a work project since I already have experience whith the later. Any area where it's lacking comparing to DRF that I should be aware of ? 

Thanks in advance

**Comment by vitalik** [comment]
Yes, this project production ready
In fact it's already used by 10+ companies I know of
and according to stats 1000+ developers are trying it every month

as for DRF copmarasent - I guess at this moment it just lacks few batteries that would be nice to have built-in (like caching, better pagination, throttling)

**Comment by StitiFatah** [comment]
Thanks for your reply., I'm going to read the docs and and give it a try.
