### ISSUE TITLE
Dynamic response schema depending on user data

### ISSUE THREAD

**Issue by hazaard** [vitalik/django-ninja#295]
Hi.
I'm currently trying out django ninja and find it really amazing. One thing I'm not able to do is to limit fields list depending on user data.
Example:
As normal user I'd like to access my user data via api where I can see my email, first_name, last_name.
As admin user I'd like to access my user data via api where I can see my email, first_name, last_name and list of my permissions.
both requests are going to the same api endpoint. 

Currently I'm able to do it by checking request.user in view and return different JsonResponse objects depending of user.is_staff status. Is there a way to use two Schemas on same endpoint and switch them depending on request data?

**Comment by vitalik** [comment]
Hi @hazaard 

maybe something like this - use schemas to serialize objects based on is_staff:

```Python

class UserSchema(Schema):
     first_name: str
     last_name: str

class UserPermsSchema(Schema):
    permissions: list[str] = []

...

@api.get('/me', response=UserPermsSchema)
def get_me(request):
    user = request.user
    if request.user.is_staff:
        serializer = UserPermsSchema
    else:
        serializer = UserSchema
     return serializer.from_orm(user).dict()

```

**Comment by mom1** [comment]
will it work?
```python
@api.get('/me', response={200: UserPermsSchema, 202: UserSchema})
def get_me(request):
    return (200 if request.user.is_staff else 202) , request.user
```

**Comment by hazaard** [comment]
@vitalik 
I can use your solution if i don't provide response paramater in router:
`
@api.get('/me')
def get_me(request):
    user = request.user
    if request.user.is_staff:
        serializer = UserPermsSchema
    else:
        serializer = UserSchema
     return serializer.from_orm(user).dict()
`
The only drawback is that schemas are not displayed in swagger. If you have something like SecretAdminSchema, it's not even a drawback to not having it displayed.

Using Union however i've got strange behaviour when there are two fields in both serializers (first_name for example) it will switch to the first serializer. The only exception here is id field. You can safely have it in both serializers and switch them.

@mom1 your option works. However it feels incorrect.

I'm totally okay with having router without "response" parameter in it.
