### ISSUE TITLE
Browser and NinjaAPI receive only null values

### ISSUE THREAD

**Issue by till-fechteler** [vitalik/django-ninja#297]
Hi,

first of all, thank you for developing such a great library. 

During the use of NinjaAPI the following problem came up.  I use _create_schema()_ to create a schema of the following model:

```
class SimulationScenarios(models.Model):
    scenario_id = models.AutoField(primary_key=True, blank=True, null=False)
    description = models.TextField(blank=True, null=True)
    creation_date = models.TextField(blank=True, null=True)
    creation_user = models.TextField(blank=True, null=True)
    scenario = models.TextField(blank=True, null=True)
    sim_mode = models.TextField(blank=True, null=True)
    weeks = models.IntegerField(blank=True, null=True)
    startdate = models.TextField(blank=True, null=True)
    vls_sorting_time = models.IntegerField(blank=True, null=True)
    ws_mot = models.ForeignKey(MeansOfTransport, models.DO_NOTHING, db_column='ws_mot', blank=True, null=True, related_name='mot1')
    ws_shipping_strategy = models.TextField(blank=True, null=True)
    ws_box_waiting_time = models.IntegerField(blank=True, null=True)
    vls_mot = models.ForeignKey(MeansOfTransport, models.DO_NOTHING, db_column='vls_mot', blank=True, null=True, related_name='mot2')
    vls_shipping_strategy = models.TextField(blank=True, null=True)
    rate_ftl = models.FloatField(blank=True, null=True)
    energy_consumption = models.FloatField(blank=True, null=True)
    ttw_energy_consumption = models.FloatField(blank=True, null=True)
    ttw_thg_emission = models.FloatField(blank=True, null=True)
```
The API retrieves the data objects correctly as the following print statement shows:

`{'_state': <django.db.models.base.ModelState object at 0x00000160ED1DBA30>, 'scenario_id': 1, 'description': 'Simulation Scenario 2', 'creation_date': '20211126', 'creation_user': 'tfe', 'scenario': '2', 'sim_mode': 'CORES', 'weeks': 52, 'startdate': '20210101', 'vls_sorting_time': 14, 'ws_mot_id': '7,5 t', 'ws_shipping_strategy': 'LTL', 'ws_box_waiting_time': 14, 'vls_mot_id': '18 t', 'vls_shipping_strategy': 'LTL', 'rate_ftl': 500.0, 'energy_consumption': 1.41, 'ttw_energy_consumption': 43.1, 'ttw_thg_emission': 3.21}`

but the calling browser or the NinjaAPI is receiving only null values in the response body:

![image](https://user-images.githubusercontent.com/82208100/145464919-c82e474f-1d64-46be-ba20-7ac631983c8f.png)

There is a second table in my database (sqlite) that produces the same problem. Other tables are working without any problems.

Your help is appreciated. Many thanks in advance,
Till

**Comment by vitalik** [comment]
@till-fechteler 

could you show some code (the schema creation and view function) ?

**Comment by till-fechteler** [comment]
Hi,

here is the view function:

```
@api.get("/scenarios", response=SimulationScenariosSchema, auth=api_key)
def get_scenarios(request):
    sc_lst = get_list_or_404(SimulationScenarios)
    print(sc_lst[0].__dict__)
    return sc_lst
```
And here is the schema creation:

```
from ninja import ModelSchema

from .models import Workshops
from .models import Cores
from .models import BoxesPerDay
from .models import CoresPerDay
from .models import SimulationScenarios
from .models import SimulationRuns
from ninja.orm import create_schema

# class WorkshopsSchema(Schema):
#     class Config:
#         model = Workshops
#         model_fields = ['id_workshop', 'country', 'latitude', 'longitude', 'id_nuts']
        
# class CoresSchema(Schema):
#     class Config:
#         model = Cores

WorkshopsSchema = create_schema(Workshops)        
CoresSchema = create_schema(Cores)
BoxesPerDaySchema = create_schema(BoxesPerDay)
CoresPerDaySchema = create_schema(CoresPerDay)
SimulationScenariosSchema = create_schema(SimulationScenarios)
SimulationRunsSchema = create_schema(SimulationRuns)

```
The last schemas produce the above mentioned problem. The uncommented way of creating schemas does not work at all. The response body is always empty in that case.

Best regards,
Till

**Comment by vitalik** [comment]
@till-fechteler do you wan to return list of 1st object ?

if you want to return list do this `List[Schema]`:
```Python
@api.get("/scenarios", response=list[SimulationScenariosSchema], auth=api_key):
def get_scenarios(request):
     return get_list_or_404(SimulationScenarios)
```

if you want a single object (first item from the list):
```Python
@api.get("/scenarios", response=SimulationScenariosSchema, auth=api_key):
def get_scenarios(request):
     items = get_list_or_404(SimulationScenarios)
     return items[0]
```

**Comment by till-fechteler** [comment]
What a stupid error of me! I actually missed the List[] statement in the annotation. Was propably too late yesterday evening ;-). Many thanks for your help.
