### ISSUE TITLE
[Question] Display documentation of limited endpoints

### ISSUE THREAD

**Issue by abxsantos** [vitalik/django-ninja#299]
Is there any way in which I can display limited endpoints documentations based on a given parameter?

For example, I have two routes, `/order` and `/users`.

The endpoints at the `/order` route  should be seen by everyone that has access to the ninja `/docs`.
The endpoints at the `/users` route  should be enabled to be seen only by specific people in the ninja `/docs`, thus hiding its presence to the public.

Is this possible?

**Comment by vitalik** [comment]
@abxsantos 

you can try the following:

1) disable default opepnapi docs and json
```Python
api = NinjaAPI(openapi_url=None)
```

2) add you custom json view
```python
# urs.py
...
def your_swagger_json(request):
    schema = api.get_openapi_schema()
    if not request.is_superuser:
        # patch here schema object by removing path's that are not allowed ! <<<<
    return Response(schema)

def your_swagger_json(request):
    ...
...
path('api/docs', your_docs_view),
path('api/swagger.json', your_swagger_json),
path('api/', include(api.urls)),
...

```

**Comment by abxsantos** [comment]
Nice, thanks a lot!
