### ISSUE TITLE
Class based views

### ISSUE THREAD

**Issue by simplynail** [vitalik/django-ninja#3]
Hi,
Great work, Pydantic with its standard lib type annotations is surely way forward for APIs!

Do you think class based views would be something easily implemented to Ninja?
I've seen couple of gh issues on this for Fastapi, however it hasn't arrived to the package yet.
But there's fastapi-utils extension that does the job:
https://fastapi-utils.davidmontague.xyz/user-guide/class-based-views/
Do you think something similar could be done here?

**Comment by vitalik** [comment]
@simplynail I have some thoughts, still collecting requirements to produce some nice looking api 
(indeed fastapi-utils approach looks easy doable)

if you have any suggestion to how the code api for the user should look like - please share your thoughts

**Comment by simplynail** [comment]
Actually I really like the implementation from fastapi-utils CBV from link above, it's quite clean.

It's quite different from what DRF is doing (so you decorate each method directly in fastapi-utils instead of providing class methods named same as http methods).
I think fastapi-utils way is better, as it gives you more flexibility on how you would like to use CBV (ie for simple methods grouping instead of strict "individual class for resource" approach.
Also other interesting arguments on decorating and possible implementations is here
https://github.com/tiangolo/fastapi/issues/270#issuecomment-511218890

**Comment by vitalik** [comment]
moved to proposals section
