### ISSUE TITLE
how to change the default response when parameter is missing while calling the API?

### ISSUE THREAD

**Issue by ali-farhad** [vitalik/django-ninja#30]
first off, thanks for this great tool. I'm new into creating APis so please bear with me. 

I'm building an **API A** from off another **API B**.    I have to clone this **API A** for an academic activity. 

so when API A is called : 

```python
/api/v1/login?email={email}&password={password}
``` 
it results in proper JSON but when you call it with something like:
```python
/api/v1/login?email={email}
```
 it results in specific JSON response that reads:
```JSON
 {"response":{"status":202,"message":"Invalid email & credentials"}}
```

so far, I have setup API calls, and it is working fine for when I make correct call. However, when I make call with missing parameter like this:
```python
http://127.0.0.1:8000/api/v1/login?email`
```
it always returns the default JSON response :
```JSON
 {"detail": [{"loc": ["query", "email"], "msg": "field required", "type": "value_error.missing"}]}
```

so how do I change the above response to match with the error response of  **API A** whenever it is called with a parameter missing?

thank you so much for your time. 

BTW here is my code so far:

```python

from django.contrib import admin
from django.urls import path
from ninja import NinjaAPI
from ninja import Schema
import requests

api = NinjaAPI()
version = "v1"


@api.get("/login") 
def login(request, email:str, password:str):
    response = requests.get(f'some_host_address/api/v1/login?email={email}&password={password}')
    mydata = response.json()
    
    return {"result": mydata}


urlpatterns = [
    path('admin/', admin.site.urls),
     path(f"api/{version}/", api.urls),
]
```

**Comment by vitalik** [comment]
Hi @ali-farhad 

Thank you for trying this project

well my guess is that you have email and password non-required inputs - in that case you can just mark email and password as non required fields (by providing `default value = ""`):

```Python
@api.get("/login") 
def login(request, email:str = "", password:str = ""):
...

```

**Comment by ali-farhad** [comment]
that worked flawlessly. Thank you for your support! ❤️
