### ISSUE TITLE
question: Can integrate requests in Ninja?

### ISSUE THREAD

**Issue by wjhgg** [vitalik/django-ninja#306]
it is useful:
`from ninja import requests(or request or Request)`

**Comment by vitalik** [comment]
@wjhgg 
what are you trying to do ?

**Comment by wjhgg** [comment]
> @wjhgg what are you trying to do ?

I want to automatically add the returned result status code to the unified return content
cooperate with your integrated response: codes_1xx......

for example:
```python
class Base(Schema):
    code: int = xxx  #Automatic interface request status
    data: Any = None

class Message(Base):
    msg: str = None
```

**Comment by vitalik** [comment]
Well I still do not understand your goal...
try some more pseudocode...


maybe this ?
```Python

@api.get('/foo', response=Message)
def foo(request):
    if True:
          return 200, dict(code=200, data={}, msg='hi')
    else:
          return 403, dict(code=200, data={}, msg='fail')

```

**Comment by wjhgg** [comment]
> Well I still do not understand your goal... try some more pseudocode...
> 
> maybe this ?
> 
> ```python
> @api.get('/foo', response=Message)
> def foo(request):
>     if True:
>           return 200, dict(code=200, data={}, msg='hi')
>     else:
>           return 403, dict(code=200, data={}, msg='fail')
> ```

right, but it's should be this
```python
@api.get('/foo', response=Message)
def foo(request):
    if True:
          return 200, dict(code=200, data={}, msg='hi')
    else:
          return 403, dict(code=403, data={}, msg='fail')
```
I hope dict(code=xxx) is can auto, of course, it's OK to write every time

**Comment by wjhgg** [comment]
> Well I still do not understand your goal... try some more pseudocode...
> 
> maybe this ?
> 
> ```python
> @api.get('/foo', response=Message)
> def foo(request):
>     if True:
>           return 200, dict(code=200, data={}, msg='hi')
>     else:
>           return 403, dict(code=200, data={}, msg='fail')
> ```

I made a mistake when I used it like this
```shell
ninja.errors.ConfigError: Schema for status 403 is not set in response dict_keys([200])
```

**Comment by wjhgg** [comment]
> Well I still do not understand your goal... try some more pseudocode...
> 
> maybe this ?
> 
> ```python
> @api.get('/foo', response=Message)
> def foo(request):
>     if True:
>           return 200, dict(code=200, data={}, msg='hi')
>     else:
>           return 403, dict(code=200, data={}, msg='fail')
> ```
It should be this
```python
@api.get('/foo', response=Message)
def foo(request):
    if True:
          return dict(code=200, data={}, msg='hi')
    else:
          return dict(code=200, data={}, msg='fail')
```
