### ISSUE TITLE
Limiting ModelSchema / Field queryset

### ISSUE THREAD

**Issue by Uninen** [vitalik/django-ninja#307]
First of all, Kudos for this project, it seems very nice! I was able to convert a small DRF readonly API to Ninja in an evening 👍 

I know I can do this manually by composing the whole result dict by hand (ie. not using ModelSchemas) but I was wondering if there is currently any way to limit aliased ModelSchema fields queryset. I'd like to add a foreignkey list to the schema but instead of `.all()` to have `.limit(10)`:

in `models.py`
```py
...
    channel = models.ForeignKey(
        Channel, related_name="messages", on_delete=models.CASCADE
    )
...
```

in `api.py`
```py
class ChannelSchema(ModelSchema):
    latest_messages: List[MessageSchema] = Field(alias="messages", default=None)

    class Config:
        model = Channel
```

One workaround would of course be to add a property to the model itself and alias that instead but that feels a bit dirty as well.

PS. As a newcomer to the project (but with years of Django/Python experience), having more philosophical / deeper explanations for for example the Schemas and the way the serializing process works would definitely help a lot! There's pretty much magic going on and you need to read the source in order to figure things out. Also, some useful things like `Field` and `from_orm(instance).dict()`-method on Schema seem to be undocumented. (I found latter from some issue comment and used it to serialize things outside of the api but using the same code.)

**Comment by vitalik** [comment]
Hi @Uninen 
Yeah, at this moment the only way to achieve this by adding property to the model (`last_10_messages` or something)

But I'm currently working on smarter aliases (at least to reuse django template resolver for nested objects) - will see maybe this case will be covered as well

**Comment by Uninen** [comment]
Thanks for the swift reply! 👍
