### ISSUE TITLE
Http404 exception 

### ISSUE THREAD

**Issue by FJLendinez** [vitalik/django-ninja#31]
Shortcuts are useful to follow the DRY philosophy. For that, I think we must create a shortcuts file to overwrite the commonly-used functions in Django as get_object_or_404.
Here I let my contribution :)

```
from django.http import Http404
from django.shortcuts import get_object_or_404 as dj_get_object_or_404

def get_object_or_404(klass, *args, **kwargs):
    try:
        return dj_get_object_or_404(klass, *args, **kwargs)
    except Http404:
        return Response({}, status=404)
```

**Comment by vitalik** [comment]
hi @FJLendinez 

since django-ninja is built on top of django you can just use shortcuts from django as well:

```Python
@api.get("/foo/{foo_id}")
def foo(request, foo_id: int):
    foo = get_object_or_404(Foo, id=foo_id)
    ...
 ```

**Comment by FJLendinez** [comment]
Yes but this throws a Django's Http404 Exception and is not being handled by Django-ninja in order to provide the needed 404 response.

**Comment by FJLendinez** [comment]
Oh ok, sorry, I see that this exception has status 404 so in production environments, this is not shown. I check how DRF makes it and it launches Http404 exception anyway. 

https://github.com/encode/django-rest-framework/blob/master/rest_framework/generics.py#L13

**Comment by vitalik** [comment]
@FJLendinez 

you now should be abled customize output for http404 errors
https://django-ninja.rest-framework.com/tutorial/errors/
