### ISSUE TITLE
strange presentation of validation error when using `pydantic.error_wrappers.display_errors`

### ISSUE THREAD

**Issue by farialima** [vitalik/django-ninja#323]
hi - I want to return the validation errors in a semi-readable format to the caller of my apis, at least a format that makes it debuggable. A good candidate for formatting the `ValidationError` seems to be the Pydantic function `pydantic.error_wrappers.display_errors`. However, something in Ninja is modifying the error. Here's a very simplified version of my code:

```python
from ninja import NinjaAPI, Schema
from ninja.errors import ValidationError
from pydantic.error_wrappers import display_errors

api = NinjaAPI()

@api.exception_handler(ValidationError)
def validation_errors(request, exception):
    message = display_errors(exception.errors)
    print(message)
    return api.create_response(
        request,
        {"message": message}, status=422)

class ObjectIn(Schema):
    name: str

@api.post("/objects")
def add_object(request, body: ObjectIn):
    return 200, {
        'message': 'Object successfully added',
    }
```

and I send a POST without a name, the message displayed (and sent back, here) is:

```
body -> body -> name
  field required (type=value_error.missing)
```

The `body -> body -> name` is a little strange, I would expect simply `body -> name`. In fact, it's not coming from Pydantic, it's added in Ninja in https://github.com/vitalik/django-ninja/blob/a324ca75559989d5dd0378c0696169758a403e31/ninja/operation.py#L206 . But nowhere is documented what is this for. What would it be ? How can it be used ? Could we add some documentation/explanation ?

For now I'm simply removing the extraneous information, namely I'm adding:
```python
    for i in exception.errors:
        i['loc'] = (i['loc'][0], *i['loc'][2:])
```
at the beginning of my `validation_errors(request, exception)` function, but that seems like a big hack... 

I looked in the code history, still couldn't understand why it was added (at least not for non- model-based schemas)...

**Comment by mom1** [comment]
@farialima Hi. I think second `body` is parameter name.
if you do something like this:
`def add_object(request, obj: ObjectIn):`
then get this `body -> obj -> name`

**Comment by vitalik** [comment]
@farialima 

this is somehow always mixed but ninja.ValidationError is not the same as pydantic.ValidationError


ValidationError on top of pydantic validation also adds information where it happens (query/headers/body)

you see `body -> body -> name` because your argument called `body`

I think common workaround here is to name it like "payload" or object name

```Python
@api.post("/objects")
def add_object(request, payload: ObjectIn):
```

should get you error path like `body -> payload -> name`
