### ISSUE TITLE
Foreignkey assigning is searching for instance 

### ISSUE THREAD

**Issue by Kimmyungetouh** [vitalik/django-ninja#325]
Hello ! I create my schemas with create_schema(). When i try to perform a post request to create an object that has many foreignkeys in his model, i get an error like "UserIndividuel.id_document_type must be a TypePiece instance" for the field id_document_type that is renamed id_document_type_id in the generated schema. And when i remove the "id" string of foreignkeys in the schema in openAPI, it's work fine.

**Comment by vitalik** [comment]
Hi @Kimmyungetouh 

Yeah, this is a design question...

I did not came up with a solution, I see for now few:

1) create_schema should generage for FK fields with column names like (`document_id` instead of `document`)

2) add some adapter function that will resolve foreignkeys

```Python

@api.get('/foo')
def foo(request, payload: SomeSchema):
      data = resolve_objects(payload) # will replace IDs with database instances and return dict
      SomeModel.objects.create(**data)

```

**Comment by Kimmyungetouh** [comment]
Thank you for your answer.
