### ISSUE TITLE
Get operation Id for any given request.

### ISSUE THREAD

**Issue by mishbahr** [vitalik/django-ninja#327]
Is there an easy way to get `operation_id` for a given API request?

This is what I have so far:

```python
from django.urls import resolve

def get_operation_id(request: HttpRequest):
    view_func, _, _ = resolve(request.path)
    klass = view_func.__self__
    operation, _ = klass._find_operation(request)
    return operation.operation_id or klass.api.get_openapi_operation_id(operation)
```

I would like to use the `operation_id` for permissions checks.

```python
class NinjaAuth(SessionAuth):
    """
    Reusing Django session authentication
    """

    def authenticate(self, request: HttpRequest, key: Optional[str]) -> Optional[Any]:
        user = super().authenticate(request=request, key=key)
        if user is not None:
            operation_id = get_operation_id(request=request)
            perms = (operation_id,)
            if user.has_perms(perms):
                raise PermissionDenied("You do not have permission to perform this action.")
        return user
```

**Comment by vitalik** [comment]
Hi @mishbahr 

by default ninja uses this function to create operation id for each function: [ninja/main.py#L351-L354](https://github.com/vitalik/django-ninja/blob/master/ninja/main.py#L351-L354)

So you can either override this function to have your own logic

or just reuse this:

```Python
def get_operation_id(request: HttpRequest):
    view_func, _, _ = resolve(request.path)
    name = view_func.__name__
    module = view_func.__module__
    return (module + "_" + name).replace(".", "_")
```

just keep in mind - if you rename your viewfunc or move it to other module - your operation id can change

so I would suggest assignig each operation id manually if you rely permissions on it:


```Python
@api.get('/foo', operation_id='foo')
def my_view(request):
    ...
```

**Comment by mishbahr** [comment]
Thanks for your prompt response.

I'm aware how the operation id created. I just wanted to know if there was a simpler way to get the "operation id" for a given request.

**Comment by mishbahr** [comment]
The sample code you provided i.e 

```
def get_operation_id(request: HttpRequest):
    view_func, _, _ = resolve(request.path)
    name = view_func.__name__
    module = view_func.__module__
    return (module + "_" + name).replace(".", "_")
```

returns `ninja_operation__sync_view` i.e not `api_my_view`

**Comment by vitalik** [comment]
@mishbahr 
yeah, you right - `operation, _ = klass._find_operation(request)` seems the most optimal way to find callable
