### ISSUE TITLE
Camel case serialization/deserialization for Schema

### ISSUE THREAD

**Issue by fletcheaston** [vitalik/django-ninja#33]
I'm currently using DRF and a third-party package called [djangorestframework-camel-case](https://pypi.org/project/djangorestframework-camel-case/) (DRFCC). DRFCC provides "Camel case JSON support for Django REST framework", which simply outputs snake case to camel case, and vice versa for input. This is really helpful for my counterpart on the front-end/React side of our application, so he doesn't need to camel case fields himself. DRFCC has 348 stars at this point, so I believe this is a fairly popular use case.

An implementation of this seems fairly straightforward using [Pydantic's alias generators](https://pydantic-docs.helpmanual.io/usage/model_config/#alias-generator), and I see that you've already configured some specific Pydantic Config options for your Schema class.

Is this something you'd be interested in having included as an option to your Schema class? I'll be implementing this myself regardless, but I'm happy to discuss this in greater detail and submit a PR, I can also document this addition to the PR.

**Comment by fletcheaston** [comment]
I've basically solved this myself without library additions, the solution isn't perfect but I'm pretty happy with it.

I'm using the `pyhumps` package for camel-casing my strings.

```
from ninja import Schema
from humps import camelize


def to_camel(string: str) -> str:
    return camelize(string)


class CamelCaseSchema(Schema):

    class Config:
        alias_generator = to_camel
        allow_population_by_field_name = True

    def dict(self, ignore_alias: bool = False, by_alias: bool = True, **kwargs) -> 'DictStrAny':
        if ignore_alias:
            return super().dict(by_alias=False, **kwargs)

        return super().dict(by_alias=True, **kwargs)
```

And then I just use `CamelCaseSchema` as a drop-in for Schema everywhere.

It's a little funky, and I'm ignoring the `by_alias` entirely (because Ninja seems to have its own mind about using aliases). The only time I don't want to use `by_alias` is when I'm directly serializing the object to a Django Model, then I have to use...

`MyModel.objects.create(**myschema.dict(ignore_alias=True))`

This method allows me to serialize directly to a Django Model and the schema shows up in the Swagger documentation correctly. I personally think adding this to the library would be beneficial. I'm happy to submit a PR and update the Ninja docs to highlight this use case @vitalik. If you reopen the issue, I can throw this and the docs together and submit a PR in the next day or so.

**Comment by bolinocroustibat** [comment]
Thanks @fletcheaston , very useful!
