### ISSUE TITLE
Composable query parameters

### ISSUE THREAD

**Issue by fletcheaston** [vitalik/django-ninja#34]
I really enjoy using Schemas as you've defined and configured them for this project. However, I'm running into some issues when using a Schema with a list of strings in my query parameters. I've documented an example below of this issue.

I've got my filters as such...
```
class Filters(Schema):
    tags: List[str] = []

    def __init__(self, **data):
        print(data)
        super().__init__(**data)
```
I've used the init method for debugging, which I'll address in a bit.

My view function as...
```
@api.get("")
def search_tagged_objects(request, filters: Filters = Query(...)):
    pass
```

The Swagger documentation is generated correctly, yay! But unfortunately, when I actually pass in a tag (or multiple tags) to the filter (either through the Swagger documentation or a request URL), I'm met with the error displayed below.
 
![Screen Shot 2020-11-08 at 5 49 53 PM](https://user-images.githubusercontent.com/26908185/98492062-983b8200-21eb-11eb-9f89-561b33cfa05e.png)

When I print out the data passed to the Filters object, I'm met with the output...
```
{'tags': 'Tag A'}
```
... which is not the list of strings that I wanted to pass in.

The temporary fix that I've gotten working thus far is to NOT use a Schema model, and instead write the function definition as such...
```
def search_tagged_objects(request, tags: List[str] = Query(...)):
```

And while this totally works, it seems a bit messy. I've got 7 filters that I'd like to incorporate into a single function, and I've got pagination parameters (basically limit and offset) that I'd like to use for this function, as well as other functions. The issue seems to be solely with using a list inside an object in the query parameters.

I checked the tests and it doesn't look like this use case is covered (but correct me if I'm wrong). Let me know if this is something you'd like me to look at more, I'm happy to write some tests and submit a PR. I really do like how the documentation generated is correct (for both using the Filters and function-inline specifications), I'd like to add some small quality of life changes to this though.

**Comment by fletcheaston** [comment]
I'm trying to debug this using the source code, and I've run into some strange behavior. To be fair, this is likely an edge case.

From the demo project, I've got...
```
class EventSchema(BaseModel):
    title: str
    start_date: date
    end_date: date

    class Config:
        orm_mode = True


class Filters(BaseModel):
    titles: List[str] = Query(default=[])
    start_date: Optional[date]


@router.get("/search", response=List[EventSchema])
def search_events(request, filters: Filters = Query(...), xtitles: List[str] = Query(...)):
    print("filters", filters)
    return list(Event.objects.all().filter(title__in=filters.titles))
```

In my mind, the expected behavior is to have `titles` as an array of strings, `start_date` as a date, and `xtitles` as an array of strings (in the generated documentation). It appears that `xtitles` gets rendered correctly in the docs, but `titles` and `start_date` do not.

![Screen Shot 2020-11-09 at 3 28 57 PM](https://user-images.githubusercontent.com/26908185/98608595-66382780-22a0-11eb-9fcf-043a787a156a.png)

I believe this can be addressed by recursively iterating through Query attributes in the ViewSignature initializer. It looks fairly straightforward from there, so I'll submit a PR soon (hopefully!).

**Comment by fletcheaston** [comment]
I've narrowed the issue down to using the correct `_collection_fields` in the `_querydict_to_dict` function (in params_models.py), which involves detecting the available collection fields (somewhere in details.py, I believe). Unfortunately, I'm having a bit of trouble working my way through the code that far in, I haven't been able to find a clean, simple way of fixing this issue :/

**Comment by vitalik** [comment]
Hi @fletcheaston 
Please try latest `pip install django-ninja==0.8.3`

**Comment by fletcheaston** [comment]
That works great, thank you!
