### ISSUE TITLE
OPTIONS/HEAD HTTP Method doesn't work

### ISSUE THREAD

**Issue by facundopadilla** [vitalik/django-ninja#348]
Hello everyone, I created a router to be able to perform all CRUD operations but when assigning an OPTIONS or HEAD method, it does not work, it throws error 405.

```
@router.api_operation(["HEAD", "OPTIONS"], "/test")
def mixed(request):
    ...
```

![image](https://user-images.githubusercontent.com/64610246/152656632-09b7d617-a6ad-4583-9d14-6542761607d4.png)

 - Python version: 3.8.10
 - Django version: 3.2.9
 - Django-Ninja version: 0.16.2

**Comment by facundopadilla** [comment]
I solved it, the problem was in the endpoint, I just had to add a slash at the end and it worked.

```
@router.api_operation(["HEAD", "OPTIONS"], "/test/")
def mixed(request):
    ...

```

**Comment by eliassjogreen** [comment]
Hello @vitalik (don't know who I should ping about this but I am guessing you?). What is the reasoning behind not implementing the `HEAD` and `OPTIONS` (and for that matter `TRACE`, and perhaps even `CONNECT`) http methods as decorators. In the documentation it is mentioned once:
~~~md
This feature can also be used to implement other HTTP methods that don't have
corresponding **Django Ninja** methods, such as `HEAD` or `OPTIONS`.

```python hl_lines="1"
@api.api_operation(["HEAD", "OPTIONS"], "/path")
def mixed_operation(request):
    ...
```
~~~
But without any justification? Perhaps it's just an oversight/not been prioritized. In that case I would be willing to contribute the missing decorators if that would be appreciated.
