### ISSUE TITLE
Allow `max_length` for `JSONField`

### ISSUE THREAD

**Issue by c4ffein** [vitalik/django-ninja#349]
In my DRF project that I am finishing to migrate to Ninja, I used a `models.JSONField(default=list, max_length=10000)` as a model field. When migrating that model's view to Ninja, using either a `ModelSchema` or `create_schema`, I got a `ValueError: On field "content" the following field constraints are set but not enforced: max_length.`
I realized `max_length` is not documented for `JSONField` ( https://docs.djangoproject.com/en/4.0/ref/models/fields/#jsonfield ) contrarily to ( https://docs.djangoproject.com/en/4.0/ref/models/fields/#charfield ) for example. But still, it is accepted in `kwargs`, while adding random named argument raise errors, it just seems to be supposed to do nothing.

Could Ninja accept the `max_length` argument for `JSONField` and add a length check through pydantic? This would make enforcing size limitation for JSON easier, but on the other hand, as this argument is not documented, I don't think it would be the best solution to rely on it.

**Comment by vitalik** [comment]
@c4ffein 
yes, I think this can be fixed... but you will have a chance that your json payload encoded as string will overcome the max_length - so you should then double validate it before saving to database...

**Comment by c4ffein** [comment]
@vitalik

As I use Postgres, I checked to be sure, but `JSONField` always uses the `jsonb` Postgres data type. Contrarily to the other Postgres `json` field, `jsonb` stores data as a binary structure (which makes it indexable for example). So I don't know if it is safe/efficient to put limits based on that size, maybe that's why Django didn't seem to have it implemented. I don't know about other databases though.

In my use case I just want to be able to have a simple check to be sure users can't send huge jsons in fields that are supposed to contain little data just to fill the db : limiting the size just before deserialization should do that, unless I misunderstood your comment.

Anyway, thanks for considering my issue

**Comment by c4ffein** [comment]
Closing this issue as:
- The `max_length` of a `JSONField` isn't documented in Django
- The usage of a `max_length` that represents the global length of the JSON as a binary string and not specific parts of it might be confusing for the user
- Re-serializing this data just to check its size is not an elegant solution
- The end-user would be better-off just using a custom validator

I started implementing this feature and realized halfway through that this may not be a good idea after all, reopen this issue if you actually want me to release it
