### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by fletcheaston** [vitalik/django-ninja#35]
Is there a preferred workflow of writing endpoint tests with this library?

**Comment by vitalik** [comment]
@fletcheaston 

that's a good question...
Basically there are 2 ways:

1) once ninja api included to urls - you can use standard django TestClient against it

2) internally (to speedup tests) I also use custom test client that operates NinjaAPI instance directly (without django layer of middlewares and url resolvers) see - https://github.com/vitalik/django-ninja/blob/master/tests/client.py

I will think about it - maybe it makes sense also to add test client to main package...

**Comment by fletcheaston** [comment]
I'm more inclined towards using the internal client, so I can avoid dealing with middle layers like you mentioned. I'll just copy that for my own local use for now, maybe it's worth including in the main package? But unless this is something others would want, I think it's fine to leave it out for now.

Thanks!
