### ISSUE TITLE
Changing imports style to Python's best practice

### ISSUE THREAD

**Issue by nenkoru** [vitalik/django-ninja#352]
## Code style matters. Imports matter.

I am always looking towards code quality and readability, and so I propose to use importing module & package instead of the object itself. It gives so much readability and understanding in which module object exists without jumping to the top of the module!
Here is a more in-depth description from Google - [click](https://google.github.io/styleguide/pyguide.html#22-imports)

Basically, not too much to change but smth like this
```diff
- from ninja.operation import Operation
- from ninja.signature.details import is_collection_type
- from ninja.types import DictStrAny
+ from ninja import operation
+ from ninja.signature import details
+ from ninja import types
```
Indeed, this is a huge change in terms of the current codebase, I could be assigned to complete this issue. However, I need an acceptance from current maintainers to do this, so that PR would be accepted.
So having that said, here is a todo list:

- [ ] Acceptance from main maintainers of the project
- [ ] Imports changing
- [ ] Checking and fixing collisions that may occur in names within functions
- [ ] Testing & Merging changes

**Comment by vitalik** [comment]
Hi @nenkoru 

Thank you for participating

well... I have doubts this can be merged... because stuff like this:
```Python
schema: schemas.Schema = schemas.Schema(attrs...)
# instead of
schema: Schema = Schema(attrs...)
```
it will simply explode code width dramatically
and will make it not possible to merge with current awaiting PRs due to conflicts

**Comment by nenkoru** [comment]
> Hi @nenkoru 
> 
> Thank you for participating
> 
> well... I have doubts this can be merged... because stuff like this:
> ```Python
> schema: schemas.Schema = schemas.Schema(attrs...)
> # instead of
> schema: Schema = Schema(attrs...)
> ```
> it will simply explode code width dramatically
> and will make it not possible to merge with current awaiting PRs due to conflicts 

Hey there!
Alright, but what about adding an entry into the .flake8 with the plugin which would force using imports by modules and then once all the PRs are merged make this import style across all the codebase?
