### ISSUE TITLE
[BUG] Reverse url names are not auto generated

### ISSUE THREAD

**Issue by stinovlas** [vitalik/django-ninja#355]
**Describe the bug**
Reverse resolution of urls described on https://django-ninja.rest-framework.com/tutorial/urls/ does not work for me. By inspecting the generated resolver, I discovered, that views that do not explicitly specify `url_name` do not have a name generated at all. View function name is not used.

**Versions (please complete the following information):**
 - Python version: 3.8
 - Django version: 3.2
 - Django-Ninja version: 0.17.0

**Comment by vitalik** [comment]
Hi @stinovlas 

Could you provide some code examples ?

**Comment by stinovlas** [comment]
Sure:
1. Create new project with `django-admin startproject ninjaexample` and enter the created directory.
2. Put following content to `ninjaexample/urls.py`:
```python
from django.urls import path
from ninja import NinjaAPI
from django.urls import reverse

api = NinjaAPI()

@api.get('/index')
def index(request):
    return reverse('api-1.0.0:index')

urlpatterns = [
    path('api/', api.urls),
]
```
Run `./manage.py runserver` and access url `http://localhost:8000/api/index`. It throws following exception:
`django.urls.exceptions.NoReverseMatch: Reverse for 'index' not found. 'index' is not a valid view function or pattern name.`

When I specify url name explicitely (with `@api.get('/index', url_name='index')`, the view correctly returns `"/api/index"`.
