### ISSUE TITLE
DIFFERENT SCHEMA BASED ON API VERSION ON SWAGGER UI

### ISSUE THREAD

**Issue by rngallen** [vitalik/django-ninja#356]
I have two API versions but each with  it's own schemas
![image](https://user-images.githubusercontent.com/47332486/153483331-47b9687e-0f33-46af-87e0-461b45174a93.png)
The problem all schemas are displayed on both ends
How can I separate each schema to be displayed on the correct version 
![image](https://user-images.githubusercontent.com/47332486/153483522-c410af87-5db6-4bf9-99c8-1b04e571f119.png)

![image](https://user-images.githubusercontent.com/47332486/153483075-805558b4-31bb-4edd-a022-5a6daf806b30.png)
image above shows duplicate schema with Prefix (Paged)

**Comment by vitalik** [comment]
@rngallen 

do not understand... so the problem is with `Paged` schemas ? 
These are automatically created schemas for views that uses pagination
