### ISSUE TITLE
list value in form data is not parsed properly (it always returns list with length 1)[BUG] 

### ISSUE THREAD

**Issue by triumph1** [vitalik/django-ninja#377]
Hi! Thanks for the amazing framework!
I think I found a possible bug and the fix please have a look :)

## Context

From the tutorial... I added a simple form data

```py
from django.http import HttpRequest
from ninja import NinjaAPI, Schema, Form


class MyModel(Schema):
    my_list: list[str]


api = NinjaAPI()


@api.post("/hello")
async def hello(request: HttpRequest, my_model: MyModel = Form(...)):
    return 200, f"{my_model.my_list}"

```

swagger UI renders like below

![image](https://user-images.githubusercontent.com/77367491/155995032-63c847f4-d0af-407c-9485-49550097aaf9.png)

I added 'a' and 'b' to the list and sent a request.

## What I expected

in the `hello` view, `my_model.my_list` should be `['a', 'b']`

## What actually happened

But `my_model.my_list` is `['a,b']`, I think list is not parsed properly.

## Possible Fix
how about changing `ninja.parser.Parser.parse_querydict` line 24 to...
`result[key] = data.getlist(key)` -> `result[key] = data[key].split(',')`
like this? this fixes the issue.

```py
class Parser:
    "Default json parser"

    def parse_body(self, request: HttpRequest) -> DictStrAny:
        return cast(DictStrAny, json.loads(request.body))

    def parse_querydict(
        self, data: MultiValueDict, list_fields: List[str], request: HttpRequest
    ) -> DictStrAny:
        result: DictStrAny = {}
        for key in data.keys():
            if key in list_fields:
                result[key] = data.getlist(key)
            else:
                result[key] = data[key]
        return result
```

**Versions (please complete the following information):**
 - Python version: 3.9
 - Django version: 4.0.2
 - Django-Ninja version: 0.17.0

**Comment by SmileyChris** [comment]
It looks like Swagger UI just isn't building the request correctly.

According to https://swagger.io/docs/specification/describing-request-body/:
> Form fields can contain primitives values, arrays and objects. By default, arrays are serialized as array_name=value1&array_name=value2

We're describing it successfully, but the UI is concatenating to a single comma separated string rather than multiple params like it should.

**Comment by triumph1** [comment]
Hmm... seems like Swagger UI is using `explode:false` by default.

https://swagger.io/docs/specification/describing-request-body/
> but you can use other serialization strategies as defined by the OpenAPI 3.0 Specification. The serialization strategy is specified in the encoding section like so:

```
requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                color:
                  type: array
                  items:
                    type: string
            encoding:
              color:            # color=red,green,blue
                style: form
                explode: false
```

![image](https://user-images.githubusercontent.com/22769112/156122297-1f18e73b-91bc-4b23-8298-13bf7e2336d7.png)

https://swagger.io/docs/specification/serialization/

How about supporting both comma seperate and multi values? :)

**Comment by SmileyChris** [comment]
What if you want to post a single string that contains a comma though ...

**Comment by triumph1** [comment]
You are right... it might be better to just let it be as-is

**Comment by KonstantinosPetrakis** [comment]
You might wanna check my workaround at [this issue](https://github.com/vitalik/django-ninja/issues/1289).
