### ISSUE TITLE
Authentication Support

### ISSUE THREAD

**Issue by farzinh** [vitalik/django-ninja#38]
This project is amazing work that you did, but do you have any plan for an Athentication system for generating tokens and resetting the user's password and etc?, I mean for now should I do all of it manually right?

**Comment by vitalik** [comment]
Hi @farzinh 
Thank you for a feedback

indeed, auth level is pretty abstract, and the idea is that you either implement it yourself or use a plugin (which not available at this stage) 

but there is a plan to adopt some DRF plugins to ninja to simplify some common tasks like auth, caching, throttling, etc.

**Comment by farzinh** [comment]
Hi @vitalik

Thank you
