### ISSUE TITLE
AttributeError when running export_openapi_schema

### ISSUE THREAD

**Issue by lausek** [vitalik/django-ninja#381]
Running

```
./manage.py export_openapi_schema
```

Results in the following error:

```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File ".../venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File ".../venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".../venv/lib/python3.7/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".../venv/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File ".../venv/lib/python3.7/site-packages/ninja/management/commands/export_openapi_schema.py", line 45, in handle
    api = self._get_api_instance(options["api"])
  File ".../venv/lib/python3.7/site-packages/ninja/management/commands/export_openapi_schema.py", line 17, in _get_api_instance
    return resolve("/api/").func.keywords["api"]  # type: ignore
AttributeError: 'function' object has no attribute 'keywords'
```

Debugging with pdb on the corresponding line:

```
-> return resolve("/api/").func.keywords["api"]  # type: ignore
(Pdb) m = resolve("/api/").func
(Pdb) m
<bound method PathView._sync_view of <ninja.operation.PathView object at 0x7f6b81f7a5c0>>
(Pdb) dir(m)
['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__func__', '__ge__', '__get__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__self__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'csrf_exempt']
```

So it seems the original intention of this line was to determine the NinjaAPI instance. Yet, I fail to understand how a `keywords` attribute could be present on a bound method object. Wouldn't it be better to get the API instance like this?

```
return resolve("/api/").func.__self__.api 
```

**Versions:**
 - Python version: 3.7.3
 - Django version: 3.2.12
 - Django-Ninja version: 0.17.0
- Related work: https://github.com/vitalik/django-ninja/pull/288

<details>
    <summary>requirements.txt</summary>
<pre>
asgiref==3.5.0
async-generator==1.10
attrs==21.4.0
beautifulsoup4==4.10.0
bleach==4.1.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
colorama==0.4.4
configparser==5.2.0
crayons==0.4.0
cryptography==36.0.1
da-vinci==0.3.0
Django==3.2.12
django-appconf==1.0.5
django-compressor==3.1
django-cors-headers==3.11.0
django-libsass==0.9
django-markdownify==0.9.0
django-ninja==0.17.0
django-thumbnails==0.7.0
ecdsa==0.17.0
h11==0.13.0
idna==3.3
importlib-metadata==4.11.0
libsass==0.21.0
lxml==4.8.0
Markdown==3.3.6
outcome==1.1.0
packaging==21.3
Pillow==9.0.1
pycparser==2.21
pydantic==1.9.0
pymarkdown-video==1.0.0
pyOpenSSL==22.0.0
pyparsing==3.0.7
pytz==2021.3
rcssmin==1.1.0
requests==2.27.1
rjsmin==1.2.0
selenium==4.1.0
shortuuid==1.0.8
six==1.16.0
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.3.1
sqlparse==0.4.2
trio==0.19.0
trio-websocket==0.9.2
typing_extensions==4.1.0
urllib3==1.26.8
webdriver-manager==3.5.3
webencodings==0.5.1
wsproto==1.0.0
zipp==3.7.0
</pre>
</details>

**Comment by taobojlen** [comment]
I ran into this same thing. It occurred because my API is not defined at `/api/`, but at `/api/v1/`! I opened a PR to improve the error message; hopefully that will help someone else.
