### ISSUE TITLE
Generate response schema from pydantic model

### ISSUE THREAD

**Issue by stinovlas** [vitalik/django-ninja#388]
I have a library with some functions that return pydantic models. I'd like to have some simple way to convert those models to ninja response schema without copying all their attributes. I tried creating the schema by inheriting both the pydantic model and `ninja.Schema`, but that doesn't work at all. Is there an easy way to do this?

Alternatively, I'd also be kind of OK with not validating response schema at all. However, it seems that this is not possible if I want to return more than one status code from the view (e.g. 200 and 404). When I do want to output different status codes, I have to provide a response Schema, which is unfortunate.

**Comment by vitalik** [comment]
@stinovlas 

could you share some examles of usage - generally pydntic model should work fine as `response`

as for multiple codes - you can pass any number of codes

https://django-ninja.rest-framework.com/tutorial/response-schema/#multiple-response-codes

```Python

my_codes = frozenset({404, 403, 400, 300})
...
@api.post('/login', response={200: Token, my_codes: Message}):
def some_view(request):
      if foo:
             return 200, xxxxx
      elif bar:
             return 300, yyyy
      else:
             return 404, zzzz

```

**Comment by stinovlas** [comment]
@vitalik: As for multiple response codes, this is not what I meant. I would like to specify multiple response codes without specifiing response schema.

```python
@api.post('/login', response={200, 404})
def some_view(request):
    if foo:
        return 200, xxx
    else:
        return 404, yyy
```
If I don't specify `response` at all, the I am not allowed to return `404` response. Maybe I could achieve this by throwing some kind of exception?

As for the pydantic models, I'll prepare a minimal example.

**Comment by vitalik** [comment]
@stinovlas 

Use `Any`:

```Python
from typing import Any

Any200_404 = {frozenset([200, 404]): Any}


@api.get("/test", response=Any200_404)
def test(request):
    if True:
        return 200, [1, 2, 3]
    return 404, {"foo": "bar"}
```

Also keep in mind if your use case is mostly return 404 with custom structure - you better use custom exception handlers:

https://django-ninja.rest-framework.com/tutorial/errors/#djangohttphttp404


```Python
from django.http import Http404
...

@api.exception_handler(Http404)
def validation_errors(request, exc):
    return HttpResponse("four o four", status_code=404)

...

@api.get("/test")
def test(request):
    if some:
        raise Http404('stuff not found') # <-----
    return {'any': 'object'}


```

**Comment by stinovlas** [comment]
Huh, that's weird. I was not able to reproduce my previous problem with pydantic models. They seem to work now (even `pydantic.generics.GenericModel`).

**Comment by stinovlas** [comment]
@vitalik Well of course, `Any`! I somehow assumed that you have to specify `Schema` instance. That's settled then. Thank you for your help :slightly_smiling_face:.
