### ISSUE TITLE
Throwing a HttpError with `data`

### ISSUE THREAD

**Issue by ach0o** [vitalik/django-ninja#389]
I enjoy using `HttpError` as it is the simplest way to return an error response with a message anywhere in the project.
Yet, I've encountered some cases where I wish to return an error response with additional data (e.g. an error code or a dict of error fields and failed reasons).

Since a dict (`{ "detail": "{message}" }`) is returned by default, so I thought it would be better to make use of it.

Here is my suggestion and I would like to make PR if you agree with this feature. :)

```python3
# ninja/errors.py
class HttpError(Exception):
    # Add a new argument: data
    def __init__(self, status_code: int, message: str, data: dict = None) -> None:
        self.status_code = status_code
        self.data = data  # <<<
        super().__init__(message)

def _default_http_error(
    request: HttpRequest, exc: HttpError, api: "NinjaAPI"
) -> HttpResponse:
    if exc.data is None:
        return api.create_response(request, {"detail": str(exc)}, status=exc.status_code)
    return api.create_response(request, data, status=exc.status_code)   # <<<
    

# my_api.py
@api.get("/foo")
def some_operation(request):
    raise HttpError(400, "some error message", {"bar": ... })  # <<< Usage
```

**Comment by vitalik** [comment]
@ach0o 

I guess you can simply use your own exception handler


```Python
from ninja.errors import HttpError
...

@api.exception_handler(HttpError)
def validation_errors(request, exc):
    return HttpResponse("xxx", status_code=yyy)
```

or you can create your own exception and use it in your code and create a handler for it

**Comment by ach0o** [comment]
@vitalik

Oh I can't use the exception handler to solve my problem as `HttpError` does not accept arguments other than the status code and the message. Or, I'll have to do something like this to use the exception handler.
```python3
from ninja.errors import HttpError
from ninja.responses import Response
...

@api.exception_handler(HttpError)
def validation_errors(request, exc):
    data = getattr(exc, "data") or {}
    return Response(data=data, status_code=yyy)

@api.get("/foo")
def some_operation(request):
    _error = HttpError(400, "some error message")
    _error.data = {"bar": ... }
    raise _error
```
..which doesn't look so clean.

The other way of using a new exception + exception handler would work, but I find both solutions somewhat excessive because the change I wish to make is just slightly different from the built-in `HttpError` 😅.  As data(dict) is generally used for the response, I thought allowing the data argument would provide more convenient and more expressive way to build error responses. I would like to hear your opinion on this :).

**Comment by vitalik** [comment]
@ach0o 

just create a new custom exception and handler for it:

```Python
class MyHttpError(Exception):
    def __init__(self, status_code: int, message: str, data: dict = None) -> None:
        self.status_code = status_code
        self.data = data or {"message": message}
        super().__init__(message)

...

@api.exception_handler(MyHttpError)
def my_handler(request, exc, api):
    return api.create_response(request, exc.data, status=exc.status_code)

...

@api.get("/foo")
def some_operation(request):
    raise MyHttpError(400, "some error message", {"bar": "xxx"})


```

**Comment by ach0o** [comment]
I see. Thanks for the advice!
