### ISSUE TITLE
Django template syntax variables access using aliases

### ISSUE THREAD

**Issue by armarik** [vitalik/django-ninja#390]
Hello!

According to the [documentation](https://django-ninja.rest-framework.com/tutorial/response-schema/#aliases) I must be able to have access to [Model.get_FOO_display()](https://docs.djangoproject.com/en/4.0/ref/models/instances/#django.db.models.Model.get_FOO_display) when defining a schema, but for some reason I'm not able to.

**Model:**
```
class Plan(models.Model):
    FREE = 'FREE'
    PREMIUM = 'PREMIUM'

    PLANS = [
        (FREE, 'Free'),
        (PREMIUM, 'Premium')
    ]

    name = models.CharField(max_length=20, choices=PLANS, default=FREE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)`
```

**Schema:**
```
class PlanSchema(ModelSchema):
    display_name: str = Field(alias='get_name_display')

    class Config:
        model = Plan
        model_fields = ['name', 'price']
```

**Error:**
```
  File "pydantic/main.py", line 564, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 1 validation error for NinjaResponseSchema
response -> get_name_display
  str type expected (type=type_error.str)
```

**Version:**
django-ninja = "^0.17.0"
Django = "3.2.12"

The field `display_name` is required. It seems the callable `get_name_display` is not executed? Am I doing something wrong? I did some debugging and it seems the partial is not JSON serializable?

I did manage to "circumvent" this issue temporarily by creating a property named `display_name` that returns the result of the `get_display_name` method but it is by no means a tidy solution.

Thank you in advance! (I'm currently migrating a project from DRF to Ninja and I'm enjoying it a lot!)
Stay safe everyone.

**Comment by hiaselhans** [comment]
I think you the easiest is to make a function resolve_display_name on the schema

https://django-ninja.rest-framework.com/tutorial/response-schema/#resolvers

I guess get_display_name isnt evaluated and thus function != str …

**Comment by armarik** [comment]
> I think you the easiest is to make a function resolve_display_name on the schema

Yep, I actually ended up doing this as well. Thanks for the suggestion!

**Comment by vitalik** [comment]
@armarik 

this case :
```
class PlanSchema(ModelSchema):
    display_name: str = Field(alias='get_name_display')
``` 

in v 0.18 this should work even without resolvers
