### ISSUE TITLE
Django models as parameter type hints

### ISSUE THREAD

**Issue by OtherBarry** [vitalik/django-ninja#394]
## Problem

Often parameters to API views are used as references to a model. This results in a lot of similar boilerplate code at the start of each view function. e.g:

```python
class ExampleSchema(Schema):
    other_model: int
    foo: int
    bar: float

@router.post("/{model_id}", response=ModelOut)
def add_other_model_to_model(request, model_id: int, data: ExampleSchema):
    model = get_object_or_404(Model, model_id)
    try:
        other_model = OtherModel.objects.get(pk=data.other_model)
    except OtherModel.DoesNotExist:
        raise HttpError(422, "other_model is not a valid OtherModel id")
    model.do_something(other_model, data.foo, data.bar)
    return model
```

A possible workaround would be to retrieve the model using a validator in the schema, but this removes the typing benefits of having the schema, and involves a similar amount of boilerplate if you have several schemas.

## Proposed Solution

My proposed solution is to allow using the model class as a type hint in Schemas. This would parse input as the primary key of the model, and retrieve the actual model instance during validation.

This would allow the above example to be much simpler

```python
class ExampleSchema(Schema):
    other_model: OtherModel
    foo: int
    bar: float

@router.post("/{model_id}", response=ModelOut)
def add_other_model_to_model(request, model_id: int, data: ExampleSchema):
    model = get_object_or_404(Model, model_id)
    model.do_something(**data.dict())
    return model
```

Ideally, this system could be extended to path and query paramters as well. If  a model type hint is used in a path parameter, then a 404 error could be raised instead of a 422. This could knock the example method down to:

```python
@router.post("/{model}", response=ModelOut)
def add_other_model_to_model(request, model: Model, data: ExampleSchema):
    model.do_something(**data.dict())
    return model
```

This would also work for the CRUD example in the documentation

```python
@api.get("/employees/{employee_id}", response=EmployeeOut)
def get_employee(request, employee_id: int):
    employee = get_object_or_404(Employee, id=employee_id)
    return employee
```

becomes

```python
@api.get("/employees/{employee}", response=EmployeeOut)
def get_employee(request, employee: Employee):
    return employee
```

Additionally, custom settings could be defined using the field settings, to handle things such as alternate model managers, or non-pk lookup fields.

**Comment by vitalik** [comment]
Hi @OtherBarry 

Well this is a hard problem...

 - basically the idea of pydantic is only about validating input data (and not going to call databases or network)
 - even when you start implementing this - there will be lot of issues about async/not-async calls (basically you do not control on pydantic level if serialization was executed in sync or async context) 

btw, but you can simplify your code with get_object_or_404 shortcut (or make your own with 422 code):

```Python
@router.post("/{model_id}", response=ModelOut)
def add_other_model_to_model(request, model_id: int, data: ExampleSchema):
    model = get_object_or_404(Model, model_id)
    other_model = get_object_or_404(OtherModel,  pk=data.other_model) # <<<<<<<<<<<<<-----
    model.do_something(other_model, data.foo, data.bar)
    return model
```

Maybe you can also override `.dict` method on schema that will resolve ids to objects

**Comment by vitalik** [comment]
```Python
class SomeSchema(Schema):
    user_id: int

    def dict(self):
        data = super().dict()
        data['user'] = get_object_or_404(User, id=self.user_id)
        return data
```

**Comment by OtherBarry** [comment]
I hadn't considered the async aspect. That certainly makes it more difficult.

Thanks for the suggestions, I'll give them a shot.
