### ISSUE TITLE
ATOMIC_REQUESTS and async views

### ISSUE THREAD

**Issue by Tobi-De** [vitalik/django-ninja#395]
First of all, thank you very much for your work on this project. I sincerely hope that you and your family are doing well and I sincerely pray for the resolution of the conflict in Ukraine.

**Describe the bug**
I'm getting a RuntimeError on my django ninja async views when ATOMIC_REQUESTS is true 

**Versions**
 - Python version: 3.10
 - Django version: 4.0.3
 - Django-Ninja version: 0.17.0

```python3
# settings.py
DATABASES["default"]["ATOMIC_REQUESTS"] = True

# api.py


@transaction.non_atomic_requests
@router.post("/flight-hotel-search", response=FlightHotelSearchResult)
async def flight_hotel_search(request:HttpRequest, criteria: FlightHotelSearchCriteria):
  # there is zero database call done by me in this view
  ...



# Error
# RuntimeError: You cannot use ATOMIC_REQUESTS with async views.
```

**Comment by vitalik** [comment]
Hi @Tobi-De 

Thank you

try to put decorator AFTER `.post`

```Python

@router.post("/flight-hotel-search", response=FlightHotelSearchResult)
@transaction.non_atomic_requests  # <------- !!!!!!
async def flight_hotel_search(request:HttpRequest, criteria: FlightHotelSearchCriteria):
  # there is zero database call done by me in this view
```

**Comment by Tobi-De** [comment]
> Hi @Tobi-De
> 
> Thank you
> 
> try to put decorator AFTER `.post`
> 
> ```python
> @router.post("/flight-hotel-search", response=FlightHotelSearchResult)
> @transaction.non_atomic_requests  # <------- !!!!!!
> async def flight_hotel_search(request:HttpRequest, criteria: FlightHotelSearchCriteria):
>   # there is zero database call done by me in this view
> ```

I tried that, same issue

**Comment by bencleary** [comment]
I suspect that this is more related to Django than Django Ninja. The db package is in the process of becoming more async but right now its very hit and miss on the async support.

**Comment by Tobi-De** [comment]
> I suspect that this is more related to Django than Django Ninja. The db package is in the process of becoming more async but right now its very hit and miss on the async support.

I also think it has more to do with django than django-ninja, I'm screwed, I need to make several slow requests in this view, I'll have to write it in good old sync fashion and hope the performance isn't too bad.

**Comment by bencleary** [comment]
In terms of performance what is it you want to achieve? There might be other things to speed it up background tasks, celery, or dipping into async for database access?

**Comment by Tobi-De** [comment]
> In terms of performance what is it you want to achieve? There might be other things to speed it up background tasks, celery, or dipping into async for database access?

basically this:

```python

async def search():
        # run async call to api 1
        # run async call to api 2

```

**Comment by bencleary** [comment]
Ah that makes sense, yeah its one of the big gotchas of async and Django, until the ORM is finished its rough to get it all playing together.
