### ISSUE TITLE
schema_extra in Config class from schema

### ISSUE THREAD

**Issue by facundopadilla** [vitalik/django-ninja#398]
Greetings, I am loading an example inside the schema configuration class and it does not appear in the autodocumentation (OpenAPI).

```python
class Config:
    schema_extra = {
        "examples": [
            {
                "type": "Car"
            }
        ]
    }
```
but in the documentation it appears as follows

![image](https://user-images.githubusercontent.com/64610246/159097220-99a5e71d-241c-493d-a5e9-8f24a16f9977.png)

**Comment by vitalik** [comment]
Hi @facundopadilla 

try single ("example") instead of plurals ("exampleS"):
```
    schema_extra = {
       "example": {
           "type": "Car"
       }
```

**Comment by facundopadilla** [comment]
> Hi @facundopadilla
> 
> try single ("example") instead of plurals ("exampleS"):
> 
> ```
>     schema_extra = {
>        "example": {
>            "type": "Car"
>        }
> ```

Works!, thanks! :)
