### ISSUE TITLE
Casting response body onto schema

### ISSUE THREAD

**Issue by simplynail** [vitalik/django-ninja#4]
I can see Ninja does quite good job in casting requests into Schemas together with type casting.
Can I also return some object that will then be casted onto some other defined Schema ie to filter off some sensitive attributes? 
Something like response_model functionality from Fastapi:
https://fastapi.tiangolo.com/tutorial/response-model/

**Comment by vitalik** [comment]
Hi @simplynail 
That's a good question - yes you can , but there is a catch..


at this moment the way it is implemented is via python return annotation

```py
class MyResult(Schema):
       id: int
       foo: str


@api.get('/some/path'):
def someoperation(request) -> MyResult:
        obj = SomeModel.objects.get(...)
        return obj #   obj have id, foo, and way more other attributes

```

BUT 

based on my test,  usage and  extra things I need to define - I'm thinking about changing this to a api method parameter:

```py

@api.get('/some/path', response=Foo):
...

@api.get('/some/path', response={201: Foo, 202: Bar}):
...

this should land somewhere in v.0.3

**Comment by simplynail** [comment]
Sounds good, return annotation look clean, great it's there!

As for the proposed next steps, I'm not sure one method should be able to return different schemas - I guess there should be just one output that is expected by the client.
Having said that, to add to the subject, idea of reusing Schemas in different endpoints would be convenient. Different attributes to decorator could be however added to modify the schema a little, ie include/exclude fields sent.

Also, out of the curiosity, why would you want to return different "successful" 200/201/202 status codes from one endpoint?

**Comment by vitalik** [comment]
I would say 99% of the users/cases does not need multiple response types or different codes

BUT - the openapi schema it self lets you define multiple status codes with different response objects

https://swagger.io/docs/specification/describing-responses/ (section **HTTP Status Codes**)


and even one response code may return multiple object types - see section about  **anyOf, oneOf**

but yeah 99.9% of cases it's enough to just return one object with one status code 

> Also, out of the curiosity, why would you want to return different "successful" 200/201/202 status codes from one endpoint?

well just recently had a case:

`POST /api/work` - it may return **201 - Created** - it the work is small

but it may return **202 - Accepted** - if work is complex - and background job is started

**Comment by vitalik** [comment]
v0.3.0 - now have response method parameter instead of annotation

https://django-ninja.rest-framework.com/tutorial/response-schema/

**Comment by simplynail** [comment]
Hi Vitalik,
Great it got added!
One detail, perhaps it would be a good idea to name the argument more explicitly like "response_schema" or "response_body" instead of just "response" - as actually the schema is just a part of whole response object so being more descriptive here would be beneficial for clarity.
What do you think?

**Comment by vitalik** [comment]
@simplynail 

well as I already noted - the plan is to allow to pass not only single schema but multiple schemas with http codes into `response` parameters:

```python
@api.get('/some/path', response=Foo):
...
@api.get('/some/path', response={201: Foo, 202: Bar}):
```

as you can see this already raised an issue #10 :) 


so common word `response` seem to cover both cases for single schema and for multiple

**Comment by simplynail** [comment]
Hi, I raised this as the object (schema(s) class) passed to the decorator isn't a full "response" object in Django sense, it's only a part of it, hence the suggestion to name the attribute differently to avoid possible confusion in future.
Understood the aim is to have possibility to pass multiple classes, maybe it's just me but I feel like it would be a good approach if "request" /"response" is kept a "reserved keywords" in a way for web frameworks :)
No worries however, not imposing anything :)

**Comment by vitalik** [comment]
yeah, the naming is the most complex task in software development :) 

My current struggle - either give it a single name like "response" to handle both single schema and dict with multiple schemas

or use separate `response_schema` for single and `responses` for multiple - but there is a chance it will grow to a lot more arguments chaos later (like FastAPI currently have about 5 `response_*` arguments )

**Comment by simplynail** [comment]
Wouldn't "response_schemas" suit?
In normal, base case it would accept dict as described earlier {status_code: Schema_class} but it would also allow for shortcut definition when passing just Schema_class
