### ISSUE TITLE
Operations tags

### ISSUE THREAD

**Issue by HrachMD** [vitalik/django-ninja#40]
Hi, thank you for awesome framework. We really miss there tags=[] ability for operations. It will be fine having similar like in fastapi. Other-way all requests grouped under 'default' in /api/docs.
( https://swagger.io/docs/specification/grouping-operations-with-tags/ )
Thanks

**Comment by vitalik** [comment]
@HrachMD 

done in 0.9.2

https://django-ninja.rest-framework.com/tutorial/operation_params/
