### ISSUE TITLE
How to mock auth?

### ISSUE THREAD

**Issue by rsteenwyk** [vitalik/django-ninja#403]
First off, thanks for the project, it has been a pleasure to use.

I'm running into an issue trying to sort out how to mock successful authentication in my tests. 

Ninja is being instantiated like this:
```
api = NinjaAPI(
    title="Tasks API",
    urls_namespace="tasks",
    parser=ORJSONParser(),
    auth=MyHttpBearerAuth(),
)
```
The `MyHttpBearerAuth` class just overrides the `authenticate` method from `ninja.security.HttpBearer`

```
class MyHttpBearerAuth(HttpBearer):
    def authenticate(self, request, token):
        try:
            at = AccessToken(token)
            at.verify_token()
            if at.decoded_token:
                return at.token_has_role("AllowedAccess")
            return False
        except Exception as e:
            return False
```

I'm using pytest to start writing some tests and trying to figure out how to mock `MyHttpBearerAuth.authenticate` to always return True for some happy path tests.

I'm using the pytest mocker plugin, and I've tried patching like:
```
mocker.patch("tasks.api.MyHttpBearerAuth.authenticate", return_value=True)
```
Where `tasks.api` is the file where Ninja is instantiated and my functions are defined, but I'm still getting 401's.

I also tried a couple different ways of patching the `api` NinjaAPI object directly to just set `auth=None` but couldn't get that to work either.

Not sure where I'm going wrong here, but hoping someone can lend a hand :)

**Comment by vitalik** [comment]
Hi @rsteenwyk 

try overriding default test client... something like :

```Python
from ninja.testing import TestClient as BaseTestClient


class TestClient(BaseTestClient):

    def _build_request(self, method: str, path: str, data: dict, request_params: dict):
        token = <GENERATE YOUR TOKEN HERE> # <--------
        request_params['headers'] = {"Authorization": "Bearer " + token}
        return super()._build_request(method, path, data, request_params)

```

**Comment by rsteenwyk** [comment]
Thanks for the response @vitalik

I don't think that will really help me here because I'd then still need to hit the external auth service (Azure AD), and I'm trying to avoid external dependencies in these tests.

**Comment by vitalik** [comment]
maybe just add some settings switch

```Python
if settings.AUTH == 'test':
      auth = Dummy()
else:
    auth = Azure()

api = NinjaAPI(auth=auth)
```

**Comment by rsteenwyk** [comment]
Yeah I'd thought of that, but was hoping to avoid needing to make changes to the code under test.

I think I will just go that route, but if you don't mind I'll just keep this issue open in case anyone else has any better ideas.

Thanks again for your time!

**Comment by rsteenwyk** [comment]
Ended up sorting it out, I needed to override the TestClient and add a dummy token.

```
class TestClient(BaseTestClient):
    def _build_request(self, method: str, path: str, data: dict, request_params: dict):
        token = "fakeToken"
        request_params["headers"] = {"Authorization": "Bearer " + token}
        return super()._build_request(method, path, data, request_params)
```

Then my test:
```
def test_resp(mocker):
    import ipdb

    ipdb.set_trace()
    mocker.patch("tasks_api.api.MyHttpBearerAuth.authenticate", return_value=True)
    # apiNoAuth = mocker.patch.object(NinjaAPI, "auth", None)

    client = TestClient(api)
    resp = client.get("/tasks")
``` 

I didn't verify, but I assume that when I was sending in the `get` request previously my mocked `MyHttpBearerAuth` was never getting hit as Ninja was looking for a Authorization bearer header and returning a 401 since there wasn't one to pass along to the auth class.
