### ISSUE TITLE
ImportError: cannot import name 'ModelSchema' from 'ninja'

### ISSUE THREAD

**Issue by jontstaz** [vitalik/django-ninja#406]
I have a project  setup using django-ninja==0.13.2, Django 4.0 and django-ninja-auth

It used to work but I haven't worked on it for a few months and now I come back to run it in the same venv  and I'm getting this:

`ImportError: cannot import name 'ModelSchema' from 'ninja'`

Anyone know why this could be?

**Comment by jontstaz** [comment]
Ok I updated to latest django-ninja and now it works. I assume ModelSchema was removed from 0.13.2 for some reason?

**Comment by vitalik** [comment]
@jontstaz 

no - the ModelSchema was introduced inn 0.15
I guess your django-ninja-auth updated and started to use ModelSchema at some point
