### ISSUE TITLE
JSON:API

### ISSUE THREAD

**Issue by HrachMD** [vitalik/django-ninja#41]
This one also not issue, but a proposal. 
It will be very useful for response schema validation in jsonapi standards.

**Comment by vitalik** [comment]
hi @HrachMD 

Not sure I understand... do you have any references/links to this schema validation ?

**Comment by HrachMD** [comment]
Thank you for your response. I mean if we have such response schema:
> class SigninOutput(Schema):
>> email: EmailStr
>> name: str

Then do not return just {'email': '', 'name': ''}
But instead do this kind transformation:
{'data': {'type': 'sometype', attributes: {'email': '', 'name': ''}}}

**Comment by hbutau** [comment]
Maybe we need something like this :point_right:  https://github.com/django-json-api/django-rest-framework-json-api

**Comment by skorokithakis** [comment]
Ah, that makes sense, thank you.
