### ISSUE TITLE
How to make Django's internationalization and localization framework avaliable with ninja? Is there any plan in the future?

### ISSUE THREAD

**Issue by guancyxx** [vitalik/django-ninja#415]
Hi there, I recently have some trouble with ninja framework when I want to make some supports with Django's internationalization and localization framework, uasualy, I do this job coding like the following syle to declare some django orm model:
``` python
from django.utils.translation import gettext_lazy as _
from django.db import models
class User(models.Model):
    username = models.CharField(
        verbose_name=_("姓名"),
        ...
    )

from restframework import serializers

class UserSerializer(serializers.ModelSerializer):

    class Meta:
         model = User

```
when i use django restframwwork to descrbe an API,in the doc's page of swagger,i will get a title of username field replaced by Chinese languge ("姓名") or else，so I can support peoples from diffrent languge cultrue to use my services.

But when I changed the framework of my website from drf to ninja,I found it 's not work.there is what i coded like:
```python
from django.utils.translation import gettext_lazy as _

class UserListIn(Schema):
    
    username:str = Field(
        default=None,
        title=_("username")
    )

```
i expected when i request the openapi.json there will be a similiar result like i use drf,the username field will have a title or description replaced by local languge.I failed.

So, is there any way else to make ninja support  internationalization and localization work? or is there any plan with it?

Thanks a lot!

**Comment by vitalik** [comment]
Hi @guancyxx 

try using gettext instead of gettext_LAZY:
```Python
from django.utils.translation import gettext


class SomeSchema(Schema):
    user: int = Field(..., title=gettext('username'))


api = NinjaAPI()


@api.post("/test")
def get_user(request, data: SomeSchema):
 ...
```

<img width="542" alt="CleanShot 2022-04-07 at 12 56 35@2x" src="https://user-images.githubusercontent.com/95222/162173651-0788dcb8-89a3-4af5-869b-3682357481e2.png">

**Comment by guancyxx** [comment]
I tried with this case, but it's still not work.
actually, i think the gettext function returns a string object but not coming with request's header property like 'Accept Language' etc.

**Comment by vitalik** [comment]
@guancyxx 

the problem  you are getting with `Field` - is because pydanntic uses builtin validation - and does not like translation proxy objects

what you can do is suppress pydantc validation by creating your own Field class and use it your application:

```Python
from django.utils.translation import gettext_lazy as _
from pydantic.fields import FieldInfo

class Field(FieldInfo):
    def _validate(self): # ! <----- skip validation !!!!!!
        pass


class SomeSchema(Schema):
    user: int = Field(..., title=_("username"))
```
