### ISSUE TITLE
[BUG] Post and Put/Patch behaving differently for fileUpload + data combined requests

### ISSUE THREAD

**Issue by amritb** [vitalik/django-ninja#417]
_First of all, thanks for creating this amazing project!_

I would really like to contribute regarding #320 but a bit confused still. I am passing exact same parameters for post and patch - but they are behaving differently (patch requests are throwing validation errors).

```python
class BookSchema(ModelSchema):
    publisherInfo: TypedDictPubInfo

    class Config:
        model = models.Book
        model_exclude = ['created']

# works
@books_router.post("/{book_id}/")
def book_update_post(request, book_id: UUID, image: UploadedFile, payload: BookSchema):
    return {"success": True}

# throws validation errors
@books_router.patch("/{book_id}/")
def book_update_patch(request, book_id: UUID, image: UploadedFile, payload: BookSchema):
    return {"success": True}
```

Post works fine. But getting this on both Put & Patch
<img width="656" alt="Screenshot 2022-04-07 at 22 50 45" src="https://user-images.githubusercontent.com/3856322/162300040-5f75385b-b9bf-4ae8-96c0-3486e3b3cea1.png">

**Versions:**
 - Python version: 3.11
 - Django version: 4.0.3
 - Django-Ninja version: 0.17.0

**Comment by vitalik** [comment]
@amritb 

I'm not 100% sure - but I think PATCH method is a bit questionable when working with files (at least in Django) - you simply do not have any request.POST data when using PATCH (note when file is combined with JSON body - request body format is changed to multipart/forom-data)

what you can do is create middleware that will fix django.request in that case:
```Python
def process_request(self, request):
    if request.method in ("PUT", "PATCH") and request.content_type != "application/json":
        if hasattr(request, '_post'):
            del request._post
            del request._files
        try:
            initial_method = request.method
            request.method = "POST"
            request.META['REQUEST_METHOD'] = 'POST'
            request._load_post_and_files() # <----- this is the trick !!!!!!!!!!!!!!!!!
            request.META['REQUEST_METHOD'] = initial_method
            request.method = initial_method
        except Exception:
            pass
```

**Comment by amritb** [comment]
Thanks for the quick reply! I am migrating from DRF and it has nice partial updates and works perfectly with Put and Patch. Maybe they already have this magic internally.

I will then just stick with Post and not bother much about this :)

Appreciate your help!

**Comment by quroom** [comment]
I appreciate too. I faced same problems.

**Comment by FabianClemenz** [comment]
Thanks for this snippet!

whats to mention is, that it doesn't work (and i didn't get why) with using the django test client

**Comment by baseplate-admin** [comment]
> Thanks for this snippet!
> 
> whats to mention is, that it doesn't work (and i didn't get why) with using the django test client

This will probably work after #397
