### ISSUE TITLE
[BUG] Pydantic schema is using a higher version json schema than open api

### ISSUE THREAD

**Issue by shughes-uk** [vitalik/django-ninja#418]
**Describe the bug**
It seems pydantic is generating schema in line with the latest json schema draft, but openapi expects an older version. 
This issue has some info, and fastapi appears to have solved it but it might be worth solving this in ninja too.

https://github.com/samuelcolvin/pydantic/issues/1164 

The outcome of this at the moment is codegen tools for openapi do not work correctly with ninja produced openapi docs.

swagger codegen simply silently fails, https://github.com/openapi-generators/openapi-python-client explodes

The type causing the issue is used as part of the default pagination decorator so I imagine this applies to most ninja users.

**Comment by vitalik** [comment]
Hi @shughes-uk 

do you have some simple snippet that can be used to reproduce this bug ?

**Comment by shughes-uk** [comment]
Example api with paginate

```python
from django.contrib import admin
from django.urls import path
from ninja import NinjaAPI, Schema
from ninja.pagination import paginate

api = NinjaAPI()


@api.get("/add")
@paginate
def add(request, a: int, b: int, **kwargs):
    return [{"result": a + b}]


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", api.urls),
]
```
Running
```shell
python manage.py runserver &
pip openapi-python-client
openapi-python-client generate --url http://127.0.0.1:8000/api/openapi.json
```
Running this outputs
```
Error(s) encountered while generating, client was not created

Failed to parse OpenAPI document

3 validation errors for OpenAPI
paths -> /api/add -> get -> parameters -> 3 -> schema -> $ref
  field required (type=value_error.missing)
paths -> /api/add -> get -> parameters -> 3 -> schema -> exclusiveMinimum
  value could not be parsed to a boolean (type=type_error.bool)
paths -> /api/add -> get -> parameters -> 3 -> $ref
  field required (type=value_error.missing)
```

It's a little obtuse but those errors are from their pydantic representation of the openapi schema.
