### ISSUE TITLE
How can I not cause an error when the header is not set in HttpBeer authentication?

### ISSUE THREAD

**Issue by HoJin9622** [vitalik/django-ninja#421]
```py
class AuthBearer(HttpBearer):
    def authenticate(self, request: HttpRequest, token: str):
        token = jwt.decode(token, settings.JWT_SECRET, algorithms="HS256")
        user = User.objects.filter(id=token["id"]).get()
        return user
```

https://django-ninja.rest-framework.com/tutorial/authentication/#http-bearer

JWT certification is currently implemented.
I hope that people who have not set JWT token in Header can call API.
However, if the header is not set, 401, Unauthorized will occur.
How can it be implemented?

<img width="1360" alt="Screen Shot 2022-04-12 at 9 34 54 AM" src="https://user-images.githubusercontent.com/57439651/162855131-0d7aa9d8-3d2d-467c-91e4-6edd61e02ddf.png">

**Comment by vitalik** [comment]
hi @HoJin9622 
what's your expectation when authentication header is not set ?

**Comment by HoJin9622** [comment]
@vitalik 

```python
class AuthBearer(HttpBearer):
    def authenticate(self, request: HttpRequest, token: str):
        try:
            token = jwt.decode(token, settings.JWT_SECRET, algorithms="HS256")
            user = User.objects.filter(id=token["id"]).get()
            return user
        except User.DoesNotExist:
            return None


@api.get("/bearer", auth=AuthBearer())
def bearer(request):
    print(request.auth)     # None
```

If the header is not set and the user does not exist, request.auth will output None and no 401 error will occur.
If it's not implemented like this, could you tell me another way?
thanks!

**Comment by vitalik** [comment]
@HoJin9622 

No, the design is not like you think - if your authenticator returns None - that internally means that views will not be executed and user will get 401 response

As an alternative you can return some AnonymousUser if your auth failed:

```Python
from django.contrib.auth.models import AnonymousUser
class AuthBearer(HttpBearer):
    def authenticate(self, request: HttpRequest, token: str):
        try:
            ...
        except User.DoesNotExist:
            return AnonymousUser() # <-----


@api.get("/bearer", auth=AuthBearer())
def bearer(request):
    print(request.auth.is_authenticated)     # <-----
```

But I would not say this is recomended - django-ninja auth intended to to either block or unblock execution

if you need to check authentication in views - you better use standard django authentication framework (with Middlewares for example)

**Comment by HoJin9622** [comment]
@vitalik 
Thank you very much!
I will use standard django authenticationd.
I'll close the issue.
