### ISSUE TITLE
Trying to send file | no validator found for <class 'django.http.response.HttpResponse'>, see `arbitrary_types_allowed` in Config

### ISSUE THREAD

**Issue by maifeeulasad** [vitalik/django-ninja#424]
Hello, good people,

I'm trying to implement a file download functionality. And the code is pretty straightforward:
```
@api.get("/summary/", response=HttpResponse)
def report_summary(
    request: NinjaRequest, start_date: str, end_date: str
) -> HttpResponse:
    ...
    response = HttpResponse(
        output, # output is the file
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
    response["Content-Disposition"] = f"attachment; filename={fname}" # fname is the name of the file
    return response
```
But it gives me an error saying during bootup:
```
RuntimeError: no validator found for <class 'django.http.response.HttpResponse'>, see `arbitrary_types_allowed` in Config
```
_I don't want to set `arbitrary_types_allowed`._ 

Now how can I resolve this issue?

**Comment by vitalik** [comment]
@maifeeulasad 

remove this part 
```
, response=HttpResponse)
```

**Comment by maifeeulasad** [comment]
Thanks, @vitalik.

It resolved the issue, although I don't know how this works.

**Comment by elijahbenizzy** [comment]
Hey @vitalik -- thanks for your work on this library! Having the same issue -- I'd prefer not to remove `response=` as it helps generate openapi docs (which I use to generate a client later on...), but i'm not sure the right way to pass         `arbitrary_types_allowed = True` into my model (and don't think I even should...). 

Any otehr workaround for this?

**Comment by aou** [comment]
> (1) I was using `ModelSchema` to create my db models (2) I passed the django model, _not_ the schema model to my response function (3) It didn't work 😆

@elijahbenizzy This was helpful, I did the same thing. :)
