### ISSUE TITLE
Automatic docs custom title.

### ISSUE THREAD

**Issue by fabiocaccamo** [vitalik/django-ninja#425]
Hello, 
here I would like to see "MyProject API" instead of "NinjaAPI":

<img width="215" alt="Screenshot 2022-04-15 at 14 15 02" src="https://user-images.githubusercontent.com/1035294/163569696-4e6f1896-b017-409a-b594-6a293a1fe2d7.png">

Is it possible to change the automatic docs default title using a setting or an option?

**Comment by vitalik** [comment]
@fabiocaccamo 

Yes
```Python
api = NinjaAPI(title="MyProject API")
```
