### ISSUE TITLE
CORS, adding headers to response

### ISSUE THREAD

**Issue by HrachMD** [vitalik/django-ninja#43]
Dear @vitalik , this comment also not an issue, but more look like a question or proposal. But I really happy with using django-ninja, and faced to a problem, when it's required to add some key values to response header. Instead I've added middleware app to do that, but it breaks some logic for me.

**Comment by vitalik** [comment]
Hi

Well, I think django-ninja should not affect any cors headers, it handled by django layer
can you provide some details like settings file or something to be able to reproduce ?

**Comment by HrachMD** [comment]
Hi, I have figure out adding my custom header this way)
[![image](https://www.linkpicture.com/q/code_3.png)](https://www.linkpicture.com/view.php?img=LPic5fc4dde3ab1e81548982894)

**Comment by ddahan** [comment]
I confirm this is not related to Django Ninja.
Just use [Django corsheaders package](https://pypi.org/project/django-cors-headers/) like you would with another REST Framework, and configure it in the appropriate way.

For example, using Django ninja APIKey authentication, I had to add this in settings.py to avoid an error:
```python
from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = default_headers + ("x-api-key",)
```
