### ISSUE TITLE
SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by PatrickHXH** [vitalik/django-ninja#455]
![QQ截图20220526154742](https://user-images.githubusercontent.com/101628902/170443060-eb39a67d-0a21-4822-869b-9ea7b12bfd86.png)

**Comment by vitalik** [comment]
can it be that your internet provider blocks some CDNs ?

if so just put 'ninja' to INSTALLED_APPS (to get js bundle from distribution)
