### ISSUE TITLE
LimitOffsetPagination pagination does not work with statuses

### ISSUE THREAD

**Issue by MaksimLion** [vitalik/django-ninja#457]
Hello, I have strange issue
When I use @paginate(LimitOffsetPagination) I can't return status code because it breaks schemas
![image](https://user-images.githubusercontent.com/43618762/170862946-0bcc6ada-1466-4554-90a4-6a200c7a94d2.png)
![image](https://user-images.githubusercontent.com/43618762/170862963-74974a34-f065-40b8-b16f-cbe17852a704.png)
![image](https://user-images.githubusercontent.com/43618762/170862983-f1df391e-450c-491a-9796-d32ad814bf84.png)
![image](https://user-images.githubusercontent.com/43618762/170862995-a89ccda8-eae7-4b83-b721-fa8400609668.png)

As I understand, that instead of data, automatically passed status code to schema. I tried to define in router.get("/", response={200: RoleSchema}) 
But it does not help

Could you clarify, how I can do it?

**Comment by vitalik** [comment]
@MaksimLion 

you do not need return status code when using pagination

change this
```Python
return 200, Role.objects.all()
```

to this:
```Python
return Role.objects.all()
```

**Comment by MaksimLion** [comment]
@vitalik , Thank u so much
