### ISSUE TITLE
Response schema from annotation

### ISSUE THREAD

**Issue by fojetin** [vitalik/django-ninja#46]
In this moment ninja use decorator param to find response schema.

`@api.post('/login', response={200: Token, 401: Message, 402: Message})`
`@api.get("/tasks", response=List[TaskSchema])`
`@api.post("/users/", response=UserOut)`

I think we should use python annotation like as request schemas
`def login(request, payload: Auth) -> {200: Token, 401: Message, 402: Message}):`
`def tasks(request) -> List[TaskSchema]:`
`def create_user(request, data: UserIn) -> UserOut:`

We can take this schema `funcion.__annotations__.get('return')`

@vitalik what you think about this enhancement? I want take on this task!

**Comment by vitalik** [comment]
Hi @fojetin 
Initially django-ninja had responses done with return annotations...
But it was not covering all cases (like multiple response models and codes #16 ) and looked too long in practice

**Comment by fojetin** [comment]
multiple response models and codes works
``` py
>>> def login(request, payload: int) -> {200: str, 401: int, 402: str}:
...  pass
... 
>>> login.__annotations__
{'payload': <class 'int'>, 'return': {200: <class 'str'>, 401: <class 'int'>, 402: <class 'str'>}}
```

**Comment by fojetin** [comment]
I think it seems pretty

```py
def some_longlonglonglonglonglonglonglonglonglong_api_method_name(
    some_param: int,
    some_more: str,
    more: int,
    crazy_long_param_name: str,
    one_more_big_param_name_like_snake: int,
) -> {200: int, 400: dict}:
    pass
```

and of course we should save response in decorator

**Comment by fojetin** [comment]
Why i really wants to make it, because i want to defining endpoints and their schemas in many files and register them to API in one other file.

Now i should do this:
```py
def add(request, a: int, b: int):
    return {"result": a + b}
```
```py
import add

router = Router()

router.get("/add", response=t.Dict[str, int])(add)

```

This splits the request and response schema into different files.

**Comment by vitalik** [comment]
hm.. that's interesting approach 

ok, I think I will add both options - with `responnse` argument and return-type-annotation

but there is a big typing issue if you will use annnotations:

1) mypy will not validate this:

<img width="266" alt="CleanShot 2020-12-05 at 18 18 17@2x" src="https://user-images.githubusercontent.com/95222/101251628-98fe0000-3726-11eb-8a4c-837df08c52d4.png">


2) Even for one result mypy will not validate it 

```
def foo(request) -> Foo:
    return {'foo': 'bar'}
```

**Comment by fojetin** [comment]
Yeah, mypy not validate this, but flake8 returns no errors

**Comment by kristofgilicze** [comment]
Recent on-boarding experience with `django-ninja`:

Everything was clean and as expected ( _I did not even need the docs, everything was super intuitive._ ), up until the return schema handling. 

#### **The type hint approach what I was expecting.**

So this kind of breaks the 'flow'.

Despite this I really enjoy it so far!

I have checked the corresponding issues on FastAPI, so I sort of understand.

I like the idea of a `InferringRouter`, to keep backwards compatibility.
https://fastapi-utils.davidmontague.xyz/user-guide/inferring-router/

**Comment by vitalik** [comment]
hi @kristofgilicze 

Indeed overriding `Router.add_api_operation` is the recommended approach for making return annotations marked as response schemas

**Comment by kristofgilicze** [comment]
Ok!
Is an `InferringRouter`  something that will be eventually included in the module, or you prefer to keep the module API in sync with FastAPI?

**Comment by vitalik** [comment]
@kristofgilicze 

well this is a very controversial part..
lot of people would like to see this built in and lot of other people are strongly against it (because it just break type-checking ) 

I think for now I will just add some sort of best practices section to documentation where this example will be outlined and tests covered

**Comment by davidszotten** [comment]
what about supporting the type annotation in "simple" cases, e.g. when it's a single value, since that is also accepted by mypy?

**Comment by mom1** [comment]
for the case when the annotation is not set too
```python
if response is NOT_SET:
    response = get_type_hints(view_func).get("return") or NOT_SET
````
