### ISSUE TITLE
Ninja auths executed after django middlewares

### ISSUE THREAD

**Issue by M3te0r** [vitalik/django-ninja#463]
Hi, I noticed that Ninja auths are executed after django middlewares.

I have some custom and 3rd party middlewares that relies on the current user:
For instance a custom Locale and Timezone + Django-simple-history middlewares
But given that ninja auths (HttpBearer in my case) are separated from classic django auth and middelwares workflow I can't retrieve the current user

I managed to work aroud this by implementing a custom middleware that re use my own HttpBearer ninja auth

Is this behaviour correct ? What do you suggest ?

**Comment by vitalik** [comment]
Hi @M3te0r 

well django-ninja plugs into the urls layer (after middlewares)

so in your case I would authenticate users with some middleware (that goes first) and then use `request.user` inside django ninja
