### ISSUE TITLE
Update swagger UI version

### ISSUE THREAD

**Issue by kabell** [vitalik/django-ninja#465]
**Is your feature request related to a problem? Please describe.**
Hi, there is a security vulnerability in swagger UI <4.1.3 https://security.snyk.io/vuln/SNYK-JS-SWAGGERUI-2314885

**Describe the solution you'd like**
Could you please update swagger UI to a version which is not affected by this ? Thanks

**Comment by Atem18** [comment]
@kabell I
This could be closed: https://github.com/vitalik/django-ninja/commit/2e158a7039c01c44a2b688c2c9a2ad07f5d31af5
