### ISSUE TITLE
How to unify exception returns

### ISSUE THREAD

**Issue by zhiming429438709** [vitalik/django-ninja#468]
I want to unify the return value
like the following
{
  "code": 200,
  "data": [],
  "message": "xxxx"
}
Every time I need to use try except in the view function, it feels very annoying

**Comment by wu-clan** [comment]
Hi, for exception returns, I think you can use global exception capture, for `django-ninja`, it has a way: `exception_handler()`
Here are some examples:
```python
class ResponseBase(Schema):
    data: Optional[Any] = None

class Response500(ResponseBase):
    code: int = 500
    msg: Optional[Any] = Field(default='Internal Server Error')

def register_exception(app: NinjaAPI):
    @app.exception_handler(Exception)
    def all_exception_handler(request, exc: Exception):
        err_msg = "".join(exc.args)
        log.error(err_msg)
        return app.create_response(
            request,
            data=Response500(msg=err_msg),
            status=500,
        )
```
You just need to register `register_exception()`, It will automatically help you catch all exceptions and return.
