### ISSUE TITLE
[proposal] Suggestion for improvements response schema

### ISSUE THREAD

**Issue by fojetin** [vitalik/django-ninja#47]
Hi, i have some humble ideas.

## Function in multiple response dict
Now we have routes like `@router.get("/check_model", response={200: UserModel, 202: UserModel})` It's case from tests.

And i'm really frustrated that we must duplicate Schema (UserModel) for many cases.
I suggest allow functions as key to multiple response.

we can do it cause functions is immutable

Examples of enhancement usage:
```py
@router.get("/check_model", response={lambda x: x >= 200 and x < 300: UserModel})
```
or
```py
def response_200(n):
    return n >= 200 and n < 300
```
```py
from helpers import response_200


@router.get("/check_model", response={response_200: UserModel})

```

## Default response schema
Also i want to set default response schema, for example for errors

We can use functions for this:
```py
@router.get("/check_model", response={response_200: UserModel, lambda x: True: ErrorModel})
```
It will work because we check  status_codes sequentially from left to right.

or we can add special status like `0` or `'default'`

**Comment by vitalik** [comment]
Personally I'm not really fan of function here...

I think `set` sounds like a better candidate ( at least on syntetic speed tests it outperform function like 2x times )

then it can be constancts like

```
resp_2xx = set(range(200, 300)
resp_3xx = set(range(300, 400)
resp_4xx = set(range(400, 500)
...
```


```
@router.get("/check_model", response={resp_2xx: UserModel, None: ErrorModel})
```

`None` may tell to handle every other not defined code...

**Comment by fojetin** [comment]
Yep, set looks faster. By the way we should use frozenset, cause set can't be a dict key

**Comment by vitalik** [comment]
@fojetin 

multiple codes finally documented:


https://django-ninja.rest-framework.com/tutorial/response-schema/#multiple-response-codes
