### ISSUE TITLE
How to give Django model field an alias?

### ISSUE THREAD

**Issue by edugmes** [vitalik/django-ninja#475]
I have one question on how to use the API. Let's say I have a Django model like:
```
class User(models.Model):
    user_name = models.CharField(
        max_length=100, null=False, blank=False, unique=True
    )
    date_created = models.DateTimeField(auto_now_add=True)

    donating = models.ManyToManyField('self', blank=True, related_name='donators', symmetrical=False)

    def date_created_pretty(self):
        return self.date_created.strftime('%B-%Y')

    def real_donators(self):
        return self.donators.all().exclude(id=self.pk).count()
```
I've seem we can have `custom_fields` with `create_schema` like:
```
UserSchema = create_schema(
    User,
    fields=['id', 'user_name'],
    custom_fields=[
        ('date_created_pretty', str, None),
        ('real_donators', int, None),
    ]
)
```
How could I give `date_created_pretty` a specific alias, for example, `date_created` but using `date_created_pretty` callable as defined in `custom_fields`?

If that's not possible, may I set any field from `fields`to a callable (e.g. say I want to name the field `date_created` but call `date_created_pretty` to generate the result)?

Thanks in advance!

**Comment by vitalik** [comment]
@edugmes 

Use ModelSchema:


```Python
from ninja import ModelSchema, Field


class UserSchema(ModelSchema):
    date_created: str = Field("", alias="date_created_pretty") # <---- !!!!!
    class Meta:
          model = User
          fields = ['id', 'user_name']
 
```

**Comment by edugmes** [comment]
Thanks for your answer. It worked!

Just one last question on top of your answer:

How do I pass  a value to the callable? Let's say I add a parameter to `date_created_pretty` and want to assign it with some value taken from a URL query parameter?

**Comment by vitalik** [comment]
@edugmes 

Note: DjangoNinja's Schemas are based on pydantic

I guess you can make some root_validator that will check some values and set another one

https://pydantic-docs.helpmanual.io/usage/validators/#root-validators
