### ISSUE TITLE
Reuse existing Schema for validating standard requests data.

### ISSUE THREAD

**Issue by fabiocaccamo** [vitalik/django-ninja#478]
Is it possible to reuse an existing Schema for validating the POST data of a standard (not API) request?

If yes, could you provide an example please?

**Comment by vitalik** [comment]
@fabiocaccamo 

something like this:

```Python
from datetime import date
from ninja import Schema


class TestSchema(Schema):
    foo: int
    bar: date


POST = {'foo': '1', 'bar': '2022-01-01'}

data = TestSchema(**POST)
print(data.dict())

# >>> {'foo': 1, 'bar': datetime.date(2022, 1, 1)}
```

**Comment by fabiocaccamo** [comment]
@vitalik cool! And in case of non valid data?

Thank you for the very quick answer!

**Comment by vitalik** [comment]
@vitalik 
if data is not valid you will get an exception

note: django-ninja schemes are based on [pydantic data validation library](https://pydantic-docs.helpmanual.io/)
