### ISSUE TITLE
Hide validation errors in prodaction env

### ISSUE THREAD

**Issue by fojetin** [vitalik/django-ninja#48]
Hi! I need to hide {"detail": errors} on prod env. It's error after `_get_values(request, kw)`

I think, we should add some param to NinjaAPI, like hide_errors, to hide detail in error.
@vitalik do you approve this solution?

**Comment by vitalik** [comment]
this will be possible with custom response classes (along with #6)

**Comment by vitalik** [comment]
@fojetin 

This is now possible with [response renderers](https://django-ninja.rest-framework.com/tutorial/response-renderers/)

```Python
from ninja.renderers import JSONRenderer

class MyRenderer(JSONRenderer):

    def render(self, request, data, *, response_status):
        if not settings.DEBUG and response_status == 422:
                data = {"error": True}
        return super().render(request, data, response_status=response_status)


api = NinjaAPI(renderer=MyRenderer())

```
