### ISSUE TITLE
How to disable the interactive API documentation?

### ISSUE THREAD

**Issue by edugmes** [vitalik/django-ninja#480]
Since we import the urls such as this:
```
from . import api, views

urlpatterns = [
    path('', views.index, name='index'),
    path('api/', api.ninja_api.urls)
]
```
I'd like to try two things:
- disable the interactive input on the docs page (i.e. just read mode)
- disable the docs url at least for production

How do I get to do that?

**Comment by vitalik** [comment]
@edugmes 

to disable docs just use None as docs url  (on production)

```Python
api = NinjaAPI(..., docs_url=None)
```

and as for disable interactivity - I guess you can override default template and hide "Try out" button with css

 - add "ninja" to INSTALLED_APPS
 - copy and override [ninja/swagger.html](https://github.com/vitalik/django-ninja/blob/5dac89c59cf0371fa3ed51906072c4a9b7db2309/ninja/templates/ninja/swagger.html) file in your templates

**Comment by edugmes** [comment]
Thanks! I solved it by following what you said and will share it here for others:
1 -  disabling it all with
```
api = NinjaAPI(..., docs_url=None)
```
2 - disabling the "Try it out" button after adding "ninja" to INSTALLED_APPS and overriding `swagger.html` on the templates
```
const ui = SwaggerUIBundle({
            url: '{{ openapi_json_url }}',
            dom_id: '#swagger-ui',
        {% if not debug %}
            supportedSubmitMethods: [],  // <------ THIS LINE
        {% endif %}
            presets: [
            SwaggerUIBundle.presets.apis,
            SwaggerUIBundle.SwaggerUIStandalonePreset
            ],
    ...
```

**Comment by doctorixx** [comment]
> [@vitalik](https://github.com/vitalik) how to remove `/api/v1/openapi.json`?

Hi! 

```python
NinjaAPI(openapi_url=None)
```
