### ISSUE TITLE
How to use Foreign Key name instead of id during POST request.

### ISSUE THREAD

**Issue by recervictory** [vitalik/django-ninja#481]
### model.py
```{model.py}
class Department(models.Model):
   name = models.CharField(max_length=50)

class Employee(models.Model):
   name = model.CharField(max_length=50)
   dprt = models.ForeignKey(Department, on_delete=models.CASCADE)
```
### schema.py
```
class EmployeeIn(Schema):
   name : str
   dprt_id :  int = None
```

###  The above code takes name and id dprt_int as a foreign key. What I want instead of id I want to give name of the department int the POST request. So what will be the schema for that?

**Current  scenario  Post JSON structure is like this:**
`{ 
"name"  :  "Joe",
"dprt_id" :  1
}`

**What I want to give as JSON POST request:** 

`{ 
"name"  :  "Joe",
"dprt_name" :  "IT"
}`

**Comment by vitalik** [comment]
@recervictory 

like this ?

```Python

class EmployeeIn(Schema):
   name : str
   dprt_name :  str


@api.post('/employees')
def create_employee(request, payload: EmployeeIn):
      dprt = get_object_or_404(Department, name=payload.dprt_name)
      employee = Employee.objects.create(name=payload.name, dprt=dprt)

```

**Comment by recervictory** [comment]
Thanks, Solved.
