### ISSUE TITLE
How can we deliver '_user' to the Post of the Likes object?

### ISSUE THREAD

**Issue by HoJin9622** [vitalik/django-ninja#484]
### Please describe what you are trying to achieve
This is related #422 
I want to show user's like post list
`AttributeError: 'Post' objects has no attribute '_user'`
How can we deliver '_user' to the Post of the Likes object?

### Please include code examples (like models code, schemes code, view function) to help understand the issue
```py
class User(models.Model):
    ...


class Post(models.Model):
    ...


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(User, on_delete=models.CASCADE)


class PostSchema(Schema):
    ...
    is_like: bool

    @staticmethod
    def resolve_is_like(obj):
        return Like.objects.filter(user_id=obj._user.id, post_id=obj.id).exists()


class LikeSchema(Schema):
    ...
    posts: List[PostSchema]
    created: str


@api.get("/post/{post_id}", response=PostSchema)
def get_post(request, post_id: int):
    print("user: ", request.user) # user: username
    post = get_object_or_404(Post, id=post_id)
    post._user = request.user
    return post


@api.get("/users/{user_id}/likes", response=LikeSchema)
def get_user_likes(request, user_id: int):
    likes = Like.objects.filter(user_id=user_id)
    return likes
```

**Comment by vitalik** [comment]
@HoJin9622 

I'm concerned about your approach... basically if you querying likes - meaning you already know that user liked that stuff - so no reason  to go to resolve is_like in that case  (you will be just throwing a lot of unneeded  sql queries)

so maybe your solution would be to resolve is_like only if user is passed

```Python
    @staticmethod
    def resolve_is_like(obj):
        if hasattr(obj, '_user')
            return Like.objects.filter(user_id=obj._user.id, post_id=obj.id).exists()
        return True
```

**Comment by HoJin9622** [comment]
@vitalik 
This is to check the posts that other users like.
If you have users A and B, then user A wants to check user B's favorite posts and see if they are liked or not.
Is there a way to solve this problem?

**Comment by HoJin9622** [comment]
@vitalik 

Thank you.
I'll find another way and use it as a last resort.

**Comment by SmileyChris** [comment]
You probably want something like:
```Python
class PostQuerySet(models.QuerySet):
    def with_liked(self, user):
        return self.annotate(
            liked=models.Exists(
                Like.objects.filter(user=user, post=models.OuterRef("pk"))
            )
        )


class Post(models.Model):
    ...
    objects = PostQuerySet.as_manager()
```

**Comment by HoJin9622** [comment]
@SmileyChris 


```
TypeError: with_liked() missing 1 required positional argument: 'user': Did you fail to use functools.wraps() in a decorator?
```

Thank you for your answer.
But, it does not work.

**Comment by SmileyChris** [comment]
Because you didn't pass `request.user` to that method
