### ISSUE TITLE
Personalize and securize Redoc Page

### ISSUE THREAD

**Issue by JFeldaca** [vitalik/django-ninja#487]
Hello!
I'm trying to customize the Swagger/REDOC documenter a bit.

Is there a way to change the favicon displayed in the REDOC/Swagger documenter, without doing a complete override of templates/ninja/swagger.html|redoc.html ?

Swagger, in conjunction with the rest_famework package, can be configured to not allow unauthorized users to go to the documentation page, would it be possible to get that here too?

Old api in swagger, using rest_framework package, user not logged in:
![image](https://user-images.githubusercontent.com/102365010/176157053-e4106a87-3a33-486d-b520-3bfe35899a85.png)

New api in redoc, using django-ninja package, user not logged in: 
![image](https://user-images.githubusercontent.com/102365010/176157118-3a29a28f-83a1-46ef-82ba-fc1a81e1a177.png)

**Comment by vitalik** [comment]
@JFeldaca 

in 0.19 you can protect docs with decorators


https://django-ninja.rest-framework.com/tutorial/api-docs/#protecting-docs


```Python
from django.contrib.admin.views.decorators import staff_member_required

api = NinjaAPI(docs_decorator=staff_member_required)
```

**Comment by JFeldaca** [comment]
Hi @vitalik !

I've update to 0.19 and set up correctly, nice work!

For the other question, I understand that I have to do a complete override of the template for this, is that correct?

Regards,

**Comment by vitalik** [comment]
yes, put ninja to installed_apps and override template ( https://github.com/vitalik/django-ninja/tree/master/ninja/templates/ninja )
