### ISSUE TITLE
Two endpoints with the same url, but different method throws METHOD NOT ALLOWED

### ISSUE THREAD

**Issue by JFeldaca** [vitalik/django-ninja#497]
Hi!

I was implementing two endpoints that have the same url, but it changes in the query parameters, and they have different access methods, and in the second one it is responding with a status 405 and METHOD NOT ALLOWED.

Although it is true that typing the variables in the url solves the problem, the following question arises, can't there really be two endpoints with the same url but with different methods?

For example:
@api.get('/user/{userid}', tags=['users'])
def get_user_userid(request, userid: int):
  return "OK GET"

@api.put('/user/{userid}', tags=['users'])
def put_user_userid(request, userid: int)
  return "OK PUT"

The result of querying PUT /user/1 is a 405 METHOD NOT ALLOWED.

Changing the url of the PUT method to /user/{str:userid} does get the response I expect.

**Comment by JFeldaca** [comment]
Hi!

I have started a clean project from 0 to rule out that it was an issue with the module, and the CRUD operation works without problems, so I understand that the issue only occurs in the project that has already been started.

I'm going to move the code to the clean install, and check that it works as it should.

I close the issue.

**Comment by vitalik** [comment]
@JFeldaca 

check maybe you have conflicting urls

like `/user/{userid}` and then `/user/someaction`

in that case mark param as integer in url

```
/user/{int:userid}
```

**Comment by JFeldaca** [comment]
@vitalik 

Indeed, the problem came with a conflict with the url, as you indicate.

In the end we have rethought the urls of the module that was in conflict, so that it was not necessary to type the variables in url.

Thanks for your time, and sorry for the inconvenience.

**Comment by nythrox** [comment]
Hi. We're having the same problem, with one GET `user/{user_id}` route and a POST `user/refresh-token`. Our user_id is a uuid, so we cannot type it as an `int`. Since these are two different methods, I expect there would be no conflicts. Is there fix for this, other than changing our urls?

**Comment by OtherBarry** [comment]
@nythrox placeing the `user/refresh-token` endpoint before the `user/{user_id}` should fix it. Using a [path converter](https://docs.djangoproject.com/en/5.0/topics/http/urls/#path-converters) may also help.

**Comment by nythrox** [comment]
Yes, it usually would fix it, the problem is that there are other routes (with different methods) that become `NOT ALLOWED`. I assume this is a bug, since there is no actual namespace conflict.
