### ISSUE TITLE
Setting the OpenAPI component description

### ISSUE THREAD

**Issue by paulzakin** [vitalik/django-ninja#500]
Reading through [this file](https://github.com/vitalik/django-ninja/blob/master/ninja/openapi/schema.py) and the documentation [here](https://django-ninja.rest-framework.com/tutorial/operation_params/#operation-description), there doesn’t seem to be a way to pass in the description [for an OpenAPI component/parameter/response body](https://swagger.io/specification/). In contrast, for the path, it is inherited from the doc-string. 

Am I missing something? Happy to possibly submit a pull request if this feature does not exist. It would improve the quality of our documentation, I think, bringing it closer to a gold standard, like Stripe: https://stripe.com/docs/api/customers

—-

For the implementation, it gets a little tricky. I have a couple of thoughts on how to do this, but open to suggestions:

Option 1: The schema would have to take a double underscored property. For example, if you have a schema named Person and it has the key:value pair of first_name: str, the schema would have to take another key:value pair, like __first_name: “The first name of the person”.

Option 2:  The schema could take a hidden metadata property, called __metadata, which contains an identical schema to the schema it is inside of, only instead of the value being a type, the value is a string description of the key.

The second option seems better to me TBH, but let me know!

**Comment by vitalik** [comment]
Hi @paulzakin 

Django Ninja's schemes are powered with [pydantic](https://pydantic-docs.helpmanual.io/usage/schema/) 

there is a way to add description for schema and each attribute in schema:


```Python
from ninja import NinjaAPI, Schema, Field

class TestSchema(Schema):
    """
    This is a test schema description
    """
    name: str = Field(..., description="Description for name attribute")
    state: int

```
![CleanShot 2022-07-07 at 10 58 40@2x](https://user-images.githubusercontent.com/95222/177722518-c7527c78-9823-41be-a0b1-20d733e1b080.png)

**Comment by paulzakin** [comment]
Oh, lol, I missed that - and boy, that's a much better way to do it. Thanks for the heads up!
