### ISSUE TITLE
[BUG] Pagination, all responses are null

### ISSUE THREAD

**Issue by luizfelipevbll** [vitalik/django-ninja#502]
**@paginate** doest work with different responses/status codes
The [docs](url) says  whe must use the following:

```python
from ninja.pagination import paginate

@api.get('/users', response=List[UserSchema])
@paginate
def list_users(request):
    return User.objects.all()
```

This code doesnt work, it always return status code 200, even when it should return 400/404

```python
@router.get("/",response={200: List[UserSchemaOut], 400: MessageSchemaOut})
@paginate
def list_users(request):
    try:
        raise # this should return400 although it returns 200
        users = User.objects.all()
        if not users:
            raise Exception("users not found")
        return users
    except Exception as err:
        logger.error(f"ERRO list users: {err}")
        return 400, {"detail": "Could not list users"}
```

The error:
![image](https://user-images.githubusercontent.com/40257388/178081793-933ad198-8b2f-49af-b42b-973f711020dd.png)

 - Python version:3.10.5
 - Django version: 4.0.4
 - Django-Ninja version: 0.19.0

**Comment by Droxt1** [comment]
I'm having the same problem

**Comment by dizzydes** [comment]
How are people working around this right now in cases where pagination and response codes are needed?
Is there a fix in the works?

**Comment by OtherBarry** [comment]
@dizzydes you can raise an error (either an httperror, or an error you have a custom handler for) instead of returning 400. The error will bubble past the pagination logic, so you shouldn't get this issue.

I'll take a look at an actual fix shortly.

**Comment by vitalik** [comment]
@dizzydes 
> How are people working around this right now in cases where pagination and response codes are needed?

generally paginage expects always to get a queryset or a list as result

for now you can just throw a http error to achieve needed result:

```Python
from ninja.errors import HttpError

@router.get("/",response={200: List[UserSchemaOut], 400: MessageSchemaOut})
@paginate
def list_users(request):
        users = User.objects.all()
        if not users:
            raise HttpError(400, "users not found")

**Comment by vitalik** [comment]
@dizzydes 

also to write less code on each view that has pagination and should return 400 if it's empty - you can write your custom paginator that will detect that and will output needed http respnose 

https://django-ninja.rest-framework.com/guides/response/pagination/#creating-custom-pagination-class

**Comment by dizzydes** [comment]
Thanks a mil for your assistance @vitalik - just wondering with the paginated response eg List[JobOut] where JobOut is a valid Pydantic schema, is there any way to still have it appear in docs:
<img width="192" alt="Screenshot 2023-02-10 at 18 17 54" src="https://user-images.githubusercontent.com/10514807/218167141-6fe2de7c-5914-40e4-bfed-9e047f998fcf.png">

The fields in data have disappeared since turning on custom pagination:

```
class CustomPagination(PaginationBase):
    class Input(Schema):
        limit: int = Field(settings.PAGINATION_PER_PAGE, ge=1)
        offset: int = Field(0, ge=0)

    class Output(Schema):
        data: List[Any] # `items` is a default attribute
        detail: str = ''
        total: int

    items_attribute: str = "data"

    def paginate_queryset(self, queryset, pagination: Input, **params):
        offset = pagination.offset
        limit: int = pagination.limit
        return {
            "data": queryset[offset: offset + limit],
            "detail": "",
            "total": self._items_count(queryset)
        }
```

I have my Pydantic schemas drawn out and want to reuse this in multiple places... Perhaps I can make Output dynamic somehow? I know adding it in the endpoint's response param won't work as it requires a List[] input only.

**Comment by vitalik** [comment]
Hi @dizzydes 

the docs are there (look under "schema")  - here is example from your class:

```Python

class JobOut(Schema):
    id: int
    title: str

@api.get("/jobs", response=List[JobOut])
@paginate(CustomPagination)
def jobs(request):
    return Job.objects.all()
```

<img width="585" alt="SCR-20230210-u4a" src="https://user-images.githubusercontent.com/95222/218183196-c0a48bce-8dba-4d27-98e8-146007653605.png">

**Comment by jkeyes** [comment]
Hi @vitalik, I was experimenting this evening and came across an issue that looks like what @dizzydes is referring to above.

In this case it is not the schema docs being incorrect, but the docs for the sample response. For example if my function view uses the paginate decorator the response in redoc looks like this:

![with_paginate_decorator](https://user-images.githubusercontent.com/64932/229378401-c3e38809-4fa4-420f-bf47-c13d6a79fdab.png)

But, when I remove the paginate decorator the response then looks like this:

![no_paginate_decorator](https://user-images.githubusercontent.com/64932/229378428-810251b3-9139-403b-84d0-82ea242e4125.png)

It would be better if the response kept the example data present:

![expected_output](https://user-images.githubusercontent.com/64932/229378844-0209710b-bae4-45a1-8789-84f9f31e04ef.png)

**Comment by jkeyes** [comment]
See #728 where I removed the line passing an empty list to the type function. With this in place the API docs render with the fields of the object in the `response=List[]` present in the response example.

I've also tested this in Swagger doc. Before change:

![swagger_doc_before_change](https://user-images.githubusercontent.com/64932/229577002-ae96acc0-4333-4dd3-84e4-0f78130cd4e2.png)

After change:

![swagger_doc_after_change](https://user-images.githubusercontent.com/64932/229577020-5a19e677-2eec-485b-bac8-5d4308c72d69.png)

I couldn't think of an easy way to add a test for this change, but the existing tests all pass. Hope this helps, and if I've missed anything re how to contribute please let me know.
