### ISSUE TITLE
does django-ninja intentionally not allow api routes like `/users/me` but require `/users/{user_id}`

### ISSUE THREAD

**Issue by mandarup** [vitalik/django-ninja#507]
Trying to do something like:

```
@router.get("/users/test", response=str)
def user_test(request):
    return "hello" 
```

Throws error:

```
{
  "detail": [
    {
      "loc": [
        "path",
        "user_id"
      ],
      "msg": "value is not a valid uuid",
      "type": "type_error.uuid"
    }
  ]
}

```

how to get around this?

**Comment by mandarup** [comment]
Seems like the issue is 

`/users/test` works as long as there is no  `/users/{user_id}`. if you have both, then it you get above error.


There are two workarounds.

1)  add an ending `/`  like  `/users/test/` 

2)  define the  route `/users/test/`  before defining `/users/{user_id}`

**Comment by mandarup** [comment]
2nd approach, following the order seems like a more reliable approach.  Is there a better solution?

**Comment by RiccardoCherchi** [comment]
Hi this issue is very similar to Fastapi behaviour, so my approach usually is avoid to use this duplicated routes, for example i would do something like this:

- /users/me
- /users/public/{user_id}

but if you really need the above route, i think the first approach (adding '/') is better then an approach based on ordering.

**Comment by vitalik** [comment]
@RiccardoCherchi is is the way django urls work, if you have know for sure that your user_id is uuid - you can help django url resolver to pin to correct path - just add `uuid:user_id` - it will passed to urlresolver:

```Python



@router.get("/users/{uuid:user_id}", response=str) # <------------
def user_test(request, user_id):
    return "hello" 

@router.get("/users/me", response=str)
def user_test(request):
    return "hello" 

```

but in case your user ids are strings - the only thing that will help is placing /user/me **BEFORE** /user/user_id in codebase

**Comment by RiccardoCherchi** [comment]
Actually didn't know this, Django surprise me every time, thanks for the clarification!!
