### ISSUE TITLE
Type hint for the request.auth variable

### ISSUE THREAD

**Issue by RiccardoCherchi** [vitalik/django-ninja#508]
Hi there, i'm have trouble to get some typing hints from the `request.auth` variable issued by `AuthBearer`, is there any way to do this?

This is the only way I came out:
```py
def view(request: HttpRequest):
    user: UserInDBSchema = request.auth
    ...
```

**Comment by RiccardoCherchi** [comment]
For now, I created a custom class based on the official 'HttpRequest':

```
from django.http.request import HttpRequest
from users.schemas import UserInDBSchema

class Request(HttpRequest):
    auth: UserInDBSchema
 ```

<img width="594" alt="image" src="https://user-images.githubusercontent.com/51675691/179850085-9a0b13b0-2d32-4068-9743-fdc32ab9dd76.png">

**Comment by vitalik** [comment]
```Python
class Request(HttpRequest):
    auth: UserInDBSchema
```

yes, that's the way I would do it to satisfy type hints

**Comment by jleclanche** [comment]
@vitalik Is there a cleaner way to do this?

I would suggest reopening this in favour of a better solution...

1. A type hint for a django-ninja wrapped request, which expects an `auth: Unknown`. eg NinjaHttpRequest
2. Use a generic type for it, allowing eg. NinjaHttpRequest[MyAuthentication]
3. When wrapping the view with @request.get(auth=SomeAuth(...)), we *should* be able to get python's typing system to understand that something is wrong if the result of auth.authenticate() mismatches request.auth
4. It may even be possible to do this a cleaner way in reverse, with just `request: NinjaHttpRequest` if we can get the decorator to do this work for us (after all, the decorator returns a modified version of the function)

for 4, what I'm thinking is something along the lines of f(auth: T)(request: X[T]) but I dunno if it works in python.
