### ISSUE TITLE
Paginination with request information

### ISSUE THREAD

**Issue by Kristinus** [vitalik/django-ninja#512]
I want to have create a custom Pagination Schema with next and previous urls.

```python
class PaginationNextPrevSchema(PaginationBase):
...
    class Output(Schema):
        results: List[Any]
        count: int
        next: str
        prev: str

    def paginate_queryset(self, queryset, pagination: Input, request: HttpRequest, **params):
        ...
        return {
            ...
            "next": ... # builds absolute uri from request.build_absolute_uri() and update offset
            "prev": ...
        }
```

**Describe the solution you'd like**
Either by default of parameter in paginate decorator to inject request to paginate_queryset as kwargs
```python
if is_isntance(args[0], WSGIRequest):
    request = args[0]
result = paginator.paginate_queryset(items, pagination=pagination_params, request=request, **kwargs)
```

**Comment by vitalik** [comment]
@scott-8 this will be in next release

**Comment by zachmullen** [comment]
@vitalik this is fantastic and just what I needed! Is there a planned timeline for a release or pre-release of this? Wondering if I should wait or instead install from GitHub. Thanks!

**Comment by vitalik** [comment]
@zachmullen you can already test it out with `pip install django-ninja==1.0a1`

**Comment by zachmullen** [comment]
@vitalik I checked that out, and it looks like this change didn't make it into the `1.0a1` release. (That version was published to pypi on July 12, the fix was committed on July 22.)

**Comment by vitalik** [comment]
@zachmullen right :) 

Please try `pip install django-ninja==1.0a2`
