### ISSUE TITLE
AttributeError: 'NinjaExtraAPI' object has no attribute 'create_temporal_response'

### ISSUE THREAD

**Issue by vishalpatil2342** [vitalik/django-ninja#513]
from django.http import HttpRequest
from ninja_extra import NinjaExtraAPI

api = NinjaExtraAPI()

@api.get('/')
def index(request:HttpRequest):
  return "Hello World"

**Comment by vitalik** [comment]
@vishalpatil2342 this is a question for django-ninja-extra package (not managed here)

but my guess is that you need to upgrade django ninja to a newer version (`pip install -U django-ninja`)
