### ISSUE TITLE
How to handle custom headers with the interactive openAPI doc

### ISSUE THREAD

**Issue by bjerzyna** [vitalik/django-ninja#514]
For authentication I need to pass a header `x-team` together with a Bearer token to API endpoints.
This all works fine, however, I haven't been able to figure out how to successfully integrate this with the OpenAPI docs endpoint.
To make it appear in the (Swagger) UI, I need to specify it as a parameter in the endpoint handler, e.g.
```
@router.get('/', response={
    200: ResourceInfoCollectionSchemaOut,
    response_codes_4xx: FailureSchema,
    500: InternalServerErrorSchema})
def list_resources(
        request,
        team_uuid: Optional[UUID] = None,
        is_active: Optional[bool] = None,
        x_team: str | None = Header(default=None),
        authorization: str | None = Header(default=None)
        ):
```
Obviously, I can't call the parameter `x-team`.
Doing this makes the header appear in the OpenAPI doc.
Wen making a request the UI sends the header as `x_team`, however that is stripped out by many (most) HTTP servers/proxies, including the Django development server.

How can I make this work?

Many thanks in advance.

**Comment by selcukzd** [comment]
I have been able to resolve it using the `alias` keyword:

```
...
x_team: str | None = Header(alias="X-Team", default=None),
...
```
This causes the generated OpenAPI documentation to use the alias (`X-Team`) instead of the Python argument name (`x_team`).

**Comment by selcuk** [comment]
I have been able to resolve it using the `alias` keyword:

```
...
x_team: str | None = Header(alias="X-Team", default=None),
...
```
This causes the generated OpenAPI documentation to use the alias (`X-Team`) instead of the Python argument name (`x_team`).

**Comment by bjerzyna** [comment]
Thanks.

**Comment by amzar96** [comment]
hi, I have issue with the custom header. I follow the above code.

```python
@router.post("/invite_code", response=StdResponse)
def get_invitation_code(
    request,
    payload: InvitationCodeSchemaIn,
    user: str | None = Header(alias="user", default="None"),
):
   print(user) # None
```

My request body:
```
curl -X 'POST' \
  'http://127.0.0.1:8000/api/v1/invite_code' \
  -H 'accept: application/json' \
  -H 'user: 222' \
  -H 'Authorization: Bearer testapi123' \
  -H 'Content-Type: application/json' \
  -d '{
  "code": "string"
}'
```

Why it return as `None`?

**Comment by skynette** [comment]
I am using django how can i replicate this in my views? please help
