### ISSUE TITLE
Update the ninja docs

### ISSUE THREAD

**Issue by SmileyChris** [vitalik/django-ninja#523]
We've got a new release (0.19.1), but the docs haven't been updated yet.

I don't quite understand how you're building / uploading the docs -- it's not part of an github action that I can see.

**Comment by vitalik** [comment]
@SmileyChris thank you for the hint - fixed

basically the site is hosted with netlify.com (which basically executes the scripts/build-docs.sh file every time codes is pushed to the `docs` branch)
