### ISSUE TITLE
If response=List[ASchema or BSchema], the result is just returned according to ASchema, ignoring BChema ?

### ISSUE THREAD

**Issue by sunmouren** [vitalik/django-ninja#524]
``` python

class AModel(models.Model):
    a = models.CharField(max_length=32)
    
    
class BModel(models.Model):
    b = models.CharField(max_length=32)

ASchema = create_schema(AModel)
BSchema = create_schema(BModel)

@router.get('/list/{m}', response=List[AScheme or BSchema])
def get_list(request, m: str):
    if m == 'a':
        qs = AModel.objects.all()
    if m == 'b':
        qs = BModel.objects.all()
    return qs 
```
If m = 'b', the result is always returned according to ASchema, not BSchema

**Comment by vitalik** [comment]
@sunmouren 

I do not think `or` operator for this way for types - what you want is Union:


```Python
from typing import Union

class A(Schema):
    a: str

class B(Schema):
    b: int

@api.get("/test", response=list[Union[A, B]])
def test(request):
    return [{"b": "1"}, {"a": "2"}]

```

and in python 3.10 it's simplified to "`|`" operator - https://peps.python.org/pep-0604/

```Python
list[A | B]
```

`or` is a boolean operation - so 1st item from your comparasent (AScheme) always true

**Comment by sunmouren** [comment]
> @sunmouren 
> 
> I do not think `or` operator works for this way for types - what you want is Union:
> 
> 
> ```Python
> from typing import Union
> 
> class A(Schema):
>     a: str
> 
> class B(Schema):
>     b: int
> 
> @api.get("/test", response=list[Union[A, B]])
> def test(request):
>     return [{"b": "1"}, {"a": "2"}]
> 
> ```
> 
> and in python 3.10 it's simplified to "`|`" operator - https://peps.python.org/pep-0604/
> 
> ```Python
> list[A | B]
> ```
> 
> `or` is a boolean operation - so 1st item from your comparasent (AScheme) always true

My mistake, do as you said, it returns the result correctly。

**Comment by sunmouren** [comment]
> @vitalik 
> 
> I do not think `or` operator works for this way for types - what you want is Union:
> 
> ```python
> from typing import Union
> 
> class A(Schema):
>     a: str
> 
> class B(Schema):
>     b: int
> 
> @api.get("/test", response=list[Union[A, B]])
> def test(request):
>     return [{"b": "1"}, {"a": "2"}]
> ```
> 
> and in python 3.10 it's simplified to "`|`" operator - https://peps.python.org/pep-0604/
> 
> ```python
> list[A | B]
> ```
> 
> `or` is a boolean operation - so 1st item from your comparasent (AScheme) always true

My mistake, do as you said, it returns the result correctly.
