### ISSUE TITLE
Access request user in schema resolve function

### ISSUE THREAD

**Issue by ssandr1kka** [vitalik/django-ninja#526]
I have likes model between users, meaning that I can like other's profile.
I am looking forward to include likes count in schema, when accessing others profile, so that I can pass data to frontend.
```
class DetailedProfileSchema(Schema):
    id: uuid.UUID
    .....
    likes_count: int


    def resolve_likes_count(self, obj) -> int:
        print("1")
        request_profile: Profile = Profile.objects.get(id=self.request.user.id) <<<<< I need to access request user profile, how can I do it?
        print("2")
        return request_profile.likes.filter(target_profile__id=obj.id).count()
``` 

resolve function does not raise any errors, it reaches `print(1)` but not `print(2)`, the only log I get is:
```
pydantic.error_wrappers.ValidationError: 1 validation errors for NinjaResponseSchema
E   response -> likes_count
E     field required (type=value_error.missing)
```

**Comment by vitalik** [comment]
@ssandr1kka 

you can do something like this:


```Python
@api.get('/profile', response= DetailedProfileSchema)
def profile_details(request):
     profile = Profile.objects.get(...
     profile.request = request # <-------
     return profile
```

and then in schema access request:

```Python
class DetailedProfileSchema(Schema):
    ...
    def resolve_likes_count(self, obj) -> int:
         request_profile = Profile.objects.get(id=obj.request.user.id)  # note `obj.request` !!!!
          ....

```

**Comment by M3te0r** [comment]
Hi @vitalik I'm using this method of transferring out the user to the schema quite a lot in my company project. 
It works well but it feels a bit hacky sometimes when I have a list of objects and nested objects/schemas (essentially for my use of django-guardian for objects permissions).

Accessing the user (or request) seems to be something needed given the previous issues on this subject : #495 #484 #422 

It would be great to have a nicer way of dealing with this

**Comment by vitalik** [comment]
@M3te0r 

Well I'm open to solve this -  I do not see a nice solution yet..

Problem that schema can be used not only to OUTPUT responses but also validate data without any request/response context

**Comment by ssandr1kka** [comment]
Thank you it works well!
