### ISSUE TITLE
Can't input Enum of integers

### ISSUE THREAD

**Issue by Maksim-Burtsev** [vitalik/django-ninja#528]
We have simple view:

```python
class Numbers(int, Enum):
    ONE = 1
    TWO = 2
    THREE = 3


@api.get("/create")
def create(request, a: Numbers, b: Numbers):
    return {"res": a.value + b.value}
```

When we try to send request where for example **?a=1&b=3** we have validation error 422 with this decription:

```json
{
  "detail": [
    {
      "loc": [
        "query",
        "a"
      ],
      "msg": "value is not a valid enumeration member; permitted: 1, 2, 3",
      "type": "type_error.enum",
      "ctx": {
        "enum_values": [
          1,
          2,
          3
        ]
      }
    },
    {...same for b...}
  ]
}
```

*I would like to point: with **str enum** everything work correct.

The error above - EnumMemberError which raise **pydantic**. (this error raises in pydantic/validators/enum_member_validator)

 How we can get around this error and can we even do this?

*P.S. To fix this in my project i just use **:int** and write custom validator for variable.*

**Comment by vitalik** [comment]
Hi @Maksim-Burtsev 

Yeah I had the same weird behaviour.. basically you need to use builtin `IntEnum`:

```Python
from enum import IntEnum

class Numbers(IntEnum):
    ONE = 1
    TWO = 2
    THREE = 3


@api.get("/test")
def test(request, a: Numbers, b: Numbers):
    return {"res": a.value + b.value}

```

I'm not yet 100% sure if  it's a part of pydantic feature or a bug, if some one can time maybe can do investigation

**Comment by Maksim-Burtsev** [comment]
Very simple and elegant solution of problem, thanks!)
