### ISSUE TITLE
Not sure how to type some Django model fields (eg, ImageField)

### ISSUE THREAD

**Issue by johnthedebs** [vitalik/django-ninja#53]
Hey, I just found this project and wanted to say that it's exciting to have such a fast way to create an API in Django!

I'm trying it out on a small side project and ran into an issue with the types/casting for a Django ImageFieldFile. Calling `str` on the field gives the correct result (ie, it implements `__str__`), but setting the type for the field to `str` produces a `ValidationError` (`response -> 0 -> photo
  str type expected (type=type_error.str)`).

I'm not sure if this is something which hasn't been implemented or is a shortcoming in my understanding of pydantic or python type hinting (which are new to me), but I wasn't able to find anything relevant in the docs and my other attempts to understand the issue.

**Comment by vitalik** [comment]
Hi @johnthedebs 

Thank you for trying django-ninja

File/Image handling should be released somewhere soon 

for now you can do the following:

on your model add property like `image_url`:

```Python
class Picture(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images')

    @property
    def image_url(self):     # !!! <--------------------------
        return self.image.url
```

and then use this property in your schema:


```Python
from typing import List
from ninja import NinjaAPI, Schema
from images.models import Picture


api = NinjaAPI()


class PictureSchema(Schema):
    title: str
    image_url: str  # !!! <-------------------------
    

@api.get("/pictures", response=List[PictureSchema])
def pictures_list(request):
    return Picture.objects.all()

```

**Comment by johnthedebs** [comment]
Makes sense, thanks! Appreciate the quick response.

**Comment by vitalik** [comment]
Hey, @johnthedebs 

try latest version

`pip install -U django-ninja==0.9.6`

it should handle file and image fields automatically:


```Python
class Picture(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images')

...

class PictureSchema(Schema):
    title: str
    image: str   # <-------------

```
