### ISSUE TITLE
Pass request user to List[ObjectSchema]

### ISSUE THREAD

**Issue by ssandr1kka** [vitalik/django-ninja#532]
Good day, 

I am looking for a way to pass request user to List[ObjectSchema]
I tried such things
views.py
```
queryset.request_user = request.user
return 200, queryset

for obj in queryset:
    obj.request_user = request.user
return 200, queryset
```

schema.py
```
ObjectSchema(Schema):
    ....
    
    def resolve_field(obj):
         print(obj.request_user)
         ...
```
It throws an error
`AttributeError: 'Object' object has no attribute 'request_user`

Any help will be appreciated, thank you.

**Comment by ssandr1kka** [comment]
When I tried
```
 query_list = list(queryset)
 for room_object in query_list:
     print(room_object)
     room_object.request_user = request.user
 return 200, query_list 
 ```
 If I do this under resolve function:
 ```
 print(obj)
 200
 print(obj.request_user)
 AttributeError: 'int' object has no attribute 'id'
 ```

**Comment by vitalik** [comment]
@ssandr1kka 

maybe your `__str__` method for the User model referencing to some id ?

**Comment by ssandr1kka** [comment]
I have found that issue comes from @paginate decorator.
Is there no way to paginate queryset and also return status code?
`return 200, query_list``

**Comment by robinsandstrom** [comment]
What we have done is to use the project django scopes, and then make a middleware which sets the user. You can then import the method get_user, which lets you access the user at runtime if you need it in schemas.

**Comment by vitalik** [comment]
@robinsandstrom
currenntly no - the assumption that pagination always has a 200 code - so you can just return only queryset

**Comment by ssandr1kka** [comment]
Meaning that error handling should happen through `raise NinjaExceptions` 
Since I cannot return 400, messageSchema as statuscodes + schemas are no longer defined
