### ISSUE TITLE
ImageField missing complete URL?

### ISSUE THREAD

**Issue by TobiasEdqvist** [vitalik/django-ninja#534]
Hello, I'm currently migrating my app from Django Rest Framework and have some issues with ImageField. The resulting string is missing the https://domain.com/media part of the URL. Is there a way to include this information in the response from the API?

**Comment by vitalik** [comment]
@TobiasEdqvist 

you need to set your [settings.MEDIA_URL](https://docs.djangoproject.com/en/4.0/ref/settings/#media-url) to `"https://domain.com/media/"`

**Comment by TobiasEdqvist** [comment]
> @TobiasEdqvist
> 
> you need to set your [settings.MEDIA_URL](https://docs.djangoproject.com/en/4.0/ref/settings/#media-url) to `"https://domain.com/media/"`

Thanks! Interesting that DRF did its own URL prepend without the MEDIA_URL containing the correct information...
