### ISSUE TITLE
[BUG]  Getting started tutorial access api docs raises an error

### ISSUE THREAD

**Issue by mangelozzi** [vitalik/django-ninja#555]
**Describe the bug**
Following the tutorial at: https://django-ninja.rest-framework.com/tutorial/step2/
When I get to the part: `Self-documenting API`, if I navigate to `http://localhost:8000/api/docs`, it raises an error:

I dont know where `api-1.0.0` comes from, the tutorial has not mentioned setting an api version anywhere.

```
NoReverseMatch at /api/docs
'api-1.0.0' is not a registered namespace
Request Method:	GET
Request URL:	http://127.0.0.1:8000/api/docs
Django Version:	4.0.1
Exception Type:	NoReverseMatch
Exception Value:	
'api-1.0.0' is not a registered namespace
Exception Location:	/home/michael/.venv/project/lib/python3.9/site-packages/django/urls/base.py, line 82, in reverse
Python Executable:	/home/michael/.venv/project/bin/python3
Python Version:	3.9.13
Python Path:	
['/home/michael/project/src',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '/home/michael/.venv/project/lib/python3.9/site-packages',
 '/home/michael/.local/lib/python3.9/site-packages',
 '/usr/local/lib/python3.9/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/home/michael/project/src/apps_web',
 '/home/michael/project/src/pack']
Server time:	Wed, 07 Sep 2022 13:51:52 +0200
```

Traceback:
```
Traceback (most recent call last):
  File "/home/michael/.venv/project/lib/python3.9/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'api-1.0.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/.venv/project/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/michael/.venv/project/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michael/.venv/project/lib/python3.9/site-packages/ninja/openapi/views.py", line 47, in openapi_view
    "openapi_json_url": reverse(f"{api.urls_namespace}:openapi-json"),
  File "/home/michael/.venv/project/lib/python3.9/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'api-1.0.0' is not a registered namespace
[07/Sep/2022 13:51:52] "GET /api/docs HTTP/1.1" 500 88910
```

**Versions (please complete the following information):**
 - Python version: 3.9
 - Django version: 4.1
 - Django-Ninja version: django-ninja-0.19.1 pydantic-1.10.2

**Comment by vitalik** [comment]
@mangelozzi 

unfortunately there is too little information to debug

maybe you can attach zip file with your code ?

**Comment by ionelmc** [comment]
Most likely your `urls.py` has an `app_name` which is messing with the namespace thing that ninja has.  I think the tutorial needs to give some pointers about this namespacing thing.

**Comment by mangelozzi** [comment]
> Most likely your `urls.py` has an `app_name` which is messing with the namespace thing that ninja has. I think the tutorial needs to give some pointers about this namespacing thing.

I do have a few other apps installed, and do set the `app_name` in each `urls.py` so its quite likely. Unfortunately I have now formatted my computer and use Django-Rest-Framework so I don't have the old file to refer to. So I will close this issue, as it seems to be just me with the error.
