### ISSUE TITLE
Automatically convert JSON keys from Django to camelCase, and received data to snake_case

### ISSUE THREAD

**Issue by mangelozzi** [vitalik/django-ninja#556]
**Is your feature request related to a problem? Please describe.**

In Python we use `snake_case`, and in JavaScript we use `camelCase`. This always causing an issue in API's, because one side of the codebase ends up not using the correct naming standards.

**Describe the solution you'd like**

[djangorestframework-camel-case](https://github.com/vbabiy/djangorestframework-camel-case) solves this problem by automatically converting the JSON keys with some middleware.  If it is POST'ed data, the middleware converts the JSON keys to snake_case for python consumption.
If it is data is a response, the middleware changes it from snake_case to camelCase for JavaScript consumption.

 Would be great if there was something like this for Django Ninja.

**Comment by hiaselhans** [comment]
you can use a pydantic [alias_generator](https://pydantic-docs.helpmanual.io/usage/model_config/#alias-generator)

I guess you have three options here:

- write your schema-attributes in camelCase and let them be converted to snake_case db-equivalents
- use db-names as attributes and let them be converted to snake_case (as in the db-model)
  - in this case you would need a "by_alias" argument in the view decorator.
  - I think this will break the option to include an alias for a nested field in your schema
- let the client-generator convert snake_case attributes to camelCase (modelPropertyNaming in [OpenApi generators](https://openapi-generator.tech/docs/generator))
