### ISSUE TITLE
How to use django-ninja with class-based view of Django

### ISSUE THREAD

**Issue by davidchern** [vitalik/django-ninja#56]
I have found all the examples in the document are function-based view. As long as I am more accustomed to write code with class-based view rather than function-based view, how can I use class-based view with Django-Ninja?

Thank you!

**Comment by vitalik** [comment]
Hi @davidchern 

Thank you for trying this project

Unfortunately class based operation are yet not implemented and there still discussion going on on how to design it

please see details here https://django-ninja.rest-framework.com/proposals/cbv/

and give your thoughts in discussion - https://github.com/vitalik/django-ninja/issues/15

**Comment by MaxZzyo** [comment]
it's a good feature and i prefer to use django's type.
in your thought, authentication/queryset/filter may located in cbv's  `__init__` method
but change to class attribute as django did is better

like:
    `class DjangoView(viewsets.ModelViewSet):
         **queryset = Django.objects.all()**

         def  details():
               pass
         def  list():
               pass
`

**Comment by MajidHeydari** [comment]
use of class is good

**Comment by TaylorYY** [comment]
Hi @vitalik 
I think the Class Based Operations function is very good , When can it be achieved?

**Comment by omidraha** [comment]
See https://github.com/vitalik/django-ninja/issues/15
