### ISSUE TITLE
De-nesting json in serilization

### ISSUE THREAD

**Issue by larseen** [vitalik/django-ninja#561]
I keep encountering problems where I have schemas that require some massaging (moving a field if i have a through table) or de nesting fields in the example below, but i cant figure out a good way off doing it.
I have tried to do it manually in the api, and returning  serialised data from the route, however this breaks some stuff, like virtual getters etc.. 

Have anyone an elegant solution where its possible to rewrite the schema/model below to reach the desired output?

models.py
```python
class Product(BasisModel):
    name = models.CharField(max_length=255)
    description = models.TextField()
    currency = models.CharField(max_length=3, default="USD")
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="products"
    )


class ProductPrice(TimescaleModel):
    product = models.OneToOneField(
        Product, on_delete=models.CASCADE, related_name="price", primary_key=True
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
```

schemas.py
```python
class ProductModelSchema(ModelSchema):
    class Config(BaseSchema.Config):
        model = Product
        model_fields = "__all__"


class ProductPriceSchema(ModelSchema):
    class Config(BaseSchema.Config):
        model = ProductPrice
        model_fields = "__all__"


class ProductSchema(ProductModelSchema):
    price: ProductPriceSchema
```

api.py
```python
@router.get(
    "/{product_id}",
    response={**GetResponse, 200: ProductSchema},
    by_alias=True,
)
def get_product(request: OrganizationHttpRequest, product_id: str) -> ProductSchema:
    product = get_object_or_404(
        Product.objects.select_related("price"),
        id=product_id,
        organization=request.organization,
    )
    return product
```

Current output:
```json
{
    "id": "ff39264f-03d0-4134-b2de-44a75db86d4c",
    "createdAt": "2022-09-08T13:21:46.751Z",
    "updatedAt": "2022-09-08T13:21:46.751Z",
    "name": "test",
    "description": "test",
    "currency": "USD",
    "organization_id": "891e7917-bb6f-4885-9b77-6cba75486045",
    "price": {
        "time": "2022-09-08T13:21:46.753Z",
        "product_id": "ff39264f-03d0-4134-b2de-44a75db86d4c",
        "price": 123.14
    }
}
```

Wanted output:
```json
{
    "id": "ff39264f-03d0-4134-b2de-44a75db86d4c",
    "createdAt": "2022-09-08T13:21:46.751Z",
    "updatedAt": "2022-09-08T13:21:46.751Z",
    "name": "test",
    "description": "test",
    "currency": "USD",
    "organization_id": "891e7917-bb6f-4885-9b77-6cba75486045",
    "price": 123.14
}
```

**Comment by larseen** [comment]
One possible solution is to add the fields as `@property` is this the "best" way of doing this, or are there other solutions I just dont have figured out yet? 

**Example:**
```python
class Product(BasisModel):
    name = models.CharField(max_length=255)
    description = models.TextField()
    currency = models.CharField(max_length=3, default="USD")
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="products"
    )

    def get_current_price(self):
        return self.prices.filter().last()

    @property
    def price(self):
        return self.get_current_price().price


class ProductPrice(TimescaleModel):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="prices")
    
class ProductSchema(ModelSchema):
    price: float

    class Config(BaseSchema.Config):
        model = Product
        model_fields = "__all__"

```

**Comment by hiaselhans** [comment]
You can use [resolver functions](https://django-ninja.rest-framework.com/guides/response/#resolvers):

``` python
class ProductSchema(ninja.ModelSchema):
    class Config(BaseSchema.Config):
        model = Product
        model_fields = "__all__"

    price: float

    @staticmethod
    def resolve_price(product: Product):
        return product.prices.filter().last()
```

**Comment by larseen** [comment]
> You can use [resolver functions](https://django-ninja.rest-framework.com/guides/response/#resolvers):
> 
> ```python
> class ProductSchema(ninja.ModelSchema):
>     class Config(BaseSchema.Config):
>         model = Product
>         model_fields = "__all__"
> 
>     price: float
> 
>     @staticmethod
>     def resolve_price(product: Product):
>         return product.prices.filter().last()
> ```

Ah, thats pretty neat, thanks @hiaselhans guess I must have overlooked that!
Resolver functions seems like a decent way of serialising internal values to representation values, are there any good ways of encapsulating logic in the serialisation from representation value to  internal value, like using a custom steriliser with DRF as seen here? 
https://github.com/webkom/lego/blob/master/lego/apps/files/fields.py#L58

**Comment by hiaselhans** [comment]
hi @larseen,

great!

I don't know if such a thing exists. What i did was mostly to add a save() function to my schemas and do it manually or from the schema.dict() in that function.
especially with nested values i think it would be some (too much) work to find a generic solution.
