### ISSUE TITLE
[BUG] Incorrect storing url_name to URLconf 

### ISSUE THREAD

**Issue by denis-manakov-cndt** [vitalik/django-ninja#569]
In case that you have two endpoints with same url, but different `url_name` param, django will store only last name in URLconf for reverse matching.

Example:
We have companies_list endpoint and company_create endpoint with the same url '/' but different methods (GET and POST).
![image](https://user-images.githubusercontent.com/110812323/190637775-33eab48f-a849-4efb-9666-bf15e666ac38.png)
And only second name appears in URLconf list.
![image](https://user-images.githubusercontent.com/110812323/190638037-df2c4d50-c621-4e26-b15e-1057744dd04a.png)
So if we try make reverse match `reverse('api:companies_list ')` - NoReverseMatch exception will be raised.

**Versions (please complete the following information):**
 - Python version: 3.9
 - Django version: 3.2.15
 - Django-Ninja version: 0.18.0

**Comment by vitalik** [comment]
duplicate #451 - basically django does not allow to give more than one name to a path
