### ISSUE TITLE
[BUG] Django `reverse()` not working

### ISSUE THREAD

**Issue by chrismaille** [vitalik/django-ninja#575]
**Describe the bug**
Django `reverse` return only the last declared view with the same endpoint (ie.: `/domains/{domain_id}` but different method (ie. PUT, DELETE).

I'm using Router and mixed sync/aync views: 

```python
# api.py

router = Router(tags=["Domain"])

@router.get("/", response=list[DomainSchemaOut], url_name="list_domains")
def list_domains(_) -> list[Domain]:
    return service.list_instances()


@router.post("/", response=DomainSchemaOut, url_name="create_domain")  # <-- Show on reverse()
async def create_domain(request: HttpRequest, payload: DomainSchemaIn) -> Domain:
    return await service.create_instance(request.user, **payload.dict())


@router.get("/{domain_id}", response=DomainSchemaOut, url_name="retrieve_domain")
async def retrieve_domain(request: HttpRequest, domain_id: UUID) -> Domain:
    return await service.retrieve_instance(domain_id, request.user)


@router.put("/{domain_id}", response=DomainSchemaOut, url_name="update_domain")
async def update_domain(request: HttpRequest, domain_id: UUID, payload: DomainSchemaIn) -> Domain:
    return await service.update_instance(domain_id, request.user, **payload.dict())


@router.delete("/{domain_id}", response=DomainSchemaOut, url_name="delete_domain")  # <-- Show on reverse()
async def delete_domain(request: HttpRequest, domain_id: UUID) -> Domain:
    return await service.delete_instance(domain_id, request.user)

```

```python
# urls.py

api = NinjaAPI()

api.add_router("/domains/", router)

# API Patterns
urlpatterns = [
    path("api/v3/", api.urls),
]

```

```python
# tests.py

from django.urls import reverse

def test_list_domains(client):
   # Arrange 
   test_url = reverse("api-1.0.0:list_domains")

   # Act
   response =  client.get(test_url)

   # Assert
   assert response.status_code == 200

```

```text
# Test Output

>       raise NoReverseMatch(msg)
E       django.urls.exceptions.NoReverseMatch: Reverse for 'list_domains' not found. 'list_domains' is not a valid view function or pattern name.

```

```text
# Django Extensions `show_urls` command output:

/api/v3/                        ninja.openapi.views.default_home        api-1.0.0:api-root      functools.partial
/api/v3/docs                    functools._wrapped_view                 api-1.0.0:openapi-view
/api/v3/domains/                ninja.operation._async_view             api-1.0.0:create_domain
/api/v3/domains/<domain_id>     ninja.operation._async_view             api-1.0.0:delete_domain
/api/v3/openapi.json            functools._wrapped_view                 api-1.0.0:openapi-json
```

API works as expected:

![image](https://user-images.githubusercontent.com/11915032/192399478-64e77eea-4ffb-459f-b44e-eebd2a5db7e4.png)

**Versions (please complete the following information):**
 - Python version: 3.10
 - Django version: 4.1.1
 - Django-Ninja version: 0.19.1

**Comment by pguichon** [comment]
I had the same bug, only the first view for a url patern could be used.

**Comment by strange** [comment]
Came here for this. Was pulling my hair for hours last night.

**Comment by wilsoniya** [comment]
I just had to use @pguichon's workaround (thank you!). It would be nice to get a proper fix to this bug, as it affects what seems like a common use case.

**Comment by strange** [comment]
I created a PR some time ago. No comments still.

https://github.com/vitalik/django-ninja/pull/638

**Comment by vitalik** [comment]
Hi Everyone 
(@strange @wilsoniya @pguichon @chrismaille )

My general thinking is that letting reverse to work was a mistake :) it kinda block some reuse of api instance and give some configuration errors that users usually struggle with when they try to have more than 1 api instance

Django's approach is basically pretty firm - one url corresponds to one view function, while ninja-operation can be a function per url+method 

so by Django's naming convention the initial example should have naming like this:

```Python
@router.get("/",  url_name="domains")
...

@router.post("/", url_name="domains")
...

@router.get("/{domain_id}", url_name="domain_by_id")
...

@router.put("/{domain_id}", url_name="domain_by_id")
```
PR #638 by @strange makes a workaround here, but it introduces just a duplication or views inside a resolver for each method for the same url (which for ones that are not named it just sits in memory and does nothing)

Maybe the best approach would be actually to have custom url resolver like:

```Python
api_reverese('retrieve_domain', [1])
api_reverese('list_domains')
```

**Comment by chrismaille** [comment]
Hi @vitalik,

Thanks for the answer and for the amazing project.

Thinking about you answer, I believe the issue is the fact we have one object (url name) with two responsabilities: one for ninja and other for django.

Can I suggest split this?

```python
router = Router(resource="domains")  # <-- Used by Ninja to group operations

@router.get("/",  url_name="list_domain")  # <-- Used by Django on reverse method
...

@router.post("/", url_name="create_domain")
...

@router.get("/{domain_id}", url_name="retrieve_domain")
...

@router.put("/{domain_id}", url_name="update_domain")
```

Obviously, for `reverse` method to work, `router` is required. 

Again, thank you very much.

**Comment by strange** [comment]
Using Django's built-in resolver is a very elegant solution, but if it is wasting more memory than you're comfortable with, a custom resolver would work just fine!

**Comment by strange** [comment]
Ran some quick tests. With 1000 API endpoints the difference is `138500K` (without patch) vs `138908K` (with patch).

**Comment by vitalik** [comment]
ok, so far I think #638 should work fine - merged
