### ISSUE TITLE
[Question] Multiple Schema Response for same status code

### ISSUE THREAD

**Issue by AliGx97** [vitalik/django-ninja#579]
Hi everyone.
I was wondering how to implement an endpoint that could return different responses for same status code. Here is an example: 
```python
something_controller = Router()

@something_controller.get('/', responses={200: SCHEMA_1 OR SCHEMA_2}
def do_something(request):
    if some_condition:
        return 200, SCHEMA_1
    else:
        return 200, SCHEMA_2
```

**Comment by vitalik** [comment]
@AliGx97 

Yes - use `Union`

```Python
from typing import Union 

@something_controller.get('/', responses={200: Union[SCHEMA_1, SCHEMA_2]} )
def do_something(request):
   ...
```

**Comment by Sampleeeees** [comment]
@AliGx97 
Hi, you can try using my package. Error support with the same status_code works and is displayed correctly in swagger

https://github.com/Sampleeeees/django_ninja_errors
