### ISSUE TITLE
How to upload images?

### ISSUE THREAD

**Issue by moshthepitt** [vitalik/django-ninja#58]
Thanks for this amazing tool.  Quick question:  how do you set up an API route that allows users to upload images?

**Comment by rjLelis** [comment]
I think you just do like you would in normal Django:

```
from django.contrib import admin
from django.urls import path
from ninja import NinjaAPI

api = NinjaAPI()

@api.post('/image')
def post_image(request):
    image = request.FILES['image']
    return {'message': image.name}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', api.urls)
]
```
![2020-12-28_19-20](https://user-images.githubusercontent.com/28015016/103246286-b5feab00-4941-11eb-9a49-7da72121be0d.png)

**Comment by moshthepitt** [comment]
Thanks @rjLelis - but how do you provide a type hint such that OpenAPI renders a file upload button?

Additionally in your example you've just typed a string to represent the image.  Does that mean that you will ask the user to somehow convert the image to a string (maybe base64) first?

It would be nice to have an official example in the docs - and I'd be happy to send In a PR once it's clear to me how to handle this.

**Comment by vitalik** [comment]
Hi @moshthepitt 

the files/images schema will come in 10.x.x version (should be released somehwere soon)

in meanwhile you can use @rjLelis suggestion :

`image = request.FILES['image']` 

(where image is actually DjangoFile that your can read/save-to-model

after release image will be basically same Django File object... the parameters will be something like this:
```Python
@api.post('/images')
def upload_image(request, image: File):
      ...
```

**Comment by rjLelis** [comment]
@moshthepitt
> Additionally in your example you've just typed a string to represent the image. Does that mean that you will ask the user to somehow convert the image to a string (maybe base64) first?

I actually sent the file with **Content-Type** header set to **multipart/form-data**. With that, I can manipulate the file attributes.

```python
@api.post('/image')
def post_image(request):
    image = request.FILES['image']
    return {
        'name': image.name,
        'size': image.size,
    }
```

**Comment by moshthepitt** [comment]
Thank you @rjLelis  @vitalik - I am going to close this.
