### ISSUE TITLE
I need to comment the parameters in the URL address

### ISSUE THREAD

**Issue by hanbinloop** [vitalik/django-ninja#585]
Here's my view definition:
![image](https://user-images.githubusercontent.com/16644654/194811618-482f73f6-f03e-427f-950b-5a05c9278177.png)
This is openapi. Json:
![image](https://user-images.githubusercontent.com/16644654/194811885-69d3aa1d-72ab-4a95-9a18-51d7bcf3d712.png)

I need to change the title in the schema to Chinese

**Comment by hanbinloop** [comment]
@vitalik

**Comment by vitalik** [comment]
@hanbinloop 

Try:
```Python
from ninja import Path

@api.get('/tenant/{tenant_id}')
def get_foo(request, tenant_id: str = Path(..., title="TenantID", description="My description..."):
     return
```
