### ISSUE TITLE
openapi custom response header, content type

### ISSUE THREAD

**Issue by sookyomkim** [vitalik/django-ninja#587]
I want to add response custom header openapi document.
but response parameter of router's method function accept ninja schema only.

I want to do something like below [just like fastapi](https://fastapi.tiangolo.com/advanced/additional-responses/#combining-information).

```python
@router.get(
...
response={
    200: {
        "content": {"text/csv; charset=utf-8": {}},
        "headers": {"Content-Disposition": "attachment; filename=aaa.csv"},
    }
...
```

Is there any way to add swagger doc for response custom header or custom content type?

**Comment by pawelngei** [comment]
:+1: to this, I was wondering how we could easily return files from Django Ninja

**Comment by vitalik** [comment]
@sookyomkim 

you can define extra open api headers on response schema:

```Python

api = NinjaAPI()


class SomeData(Schema):
    title: str

    class Config:
        schema_extra = { # <------
            "example": {
                "title": "test",
            }
        }


@api.get('/test', response={200: SomeData})
def test_extra(request):
    return {"ok": True}

```

or per operation:


```Python

@api.get('/test', openapi_extra={"x-tag": "test"})
def test_extra(request):
    return {"ok": True}

```

**Comment by sookyomkim** [comment]
"requestBody" works.

``` python
```
But I got this error when I add responses.

**Comment by sookyomkim** [comment]
Thank you, vitalik.
It looks like the [documentation](https://django-ninja.rest-framework.com/reference/operations-parameters/#openapi_extra) was added at some point.

"requestBody" works.

```python
@api.get('/test', response={200: SomeData},
    openapi_extra={
        "requestBody": {"content": {"text/csv; charset=utf-8": {}}}
    }
)
def test_extra(request):
    return {"ok": True}    
```

But I got an error when I added "responses".

```python
@api.get('/test', response={200: SomeData},
    openapi_extra={
        "responses": {
            "200": {
                "headers": {
                    "Content-Disposition": {
                        "schema": {"type": "string", "example": "attachment; filename=aaa.csv"},
                        "description": "attachment",
                    }
                },
            }
        },
    }
)
def test_extra(request):
    return {"ok": True}    
```

<img width="1431" alt="image" src="https://github.com/vitalik/django-ninja/assets/103493250/3b92cf21-a970-4c2e-9e03-bd2aaec76b0e">

**Comment by vitalik** [comment]
@sookyomkim 

yeah, change the code to `int`(200) that should work - as internally it gets turned into string to support openapi:

```Python
@api.get(
    '/test',
    openapi_extra={
        "responses": {
            200: { # <------- 200 instead of "200"
                "headers": {
                    "Content-Disposition": {
                        "schema": {"type": "string", "example": "attachment; filename=aaa.csv"}, "description": "attachment"
                    }
                },
            }
        },
    },
)
def test_extra(request):
    return {"ok": True}
```

**Comment by sookyomkim** [comment]
👍 Thank you. I'd appreciate it if you could change the description [here](https://django-ninja.rest-framework.com/reference/operations-parameters/#openapi_extra) to int as well.
 I'll close this.
