### ISSUE TITLE
A call of Django Model functions in ModelSchema 

### ISSUE THREAD

**Issue by atlonxp** [vitalik/django-ninja#589]
**Is your feature request related to a problem? Please describe.**
Sometimes, I want to call a preprocessing function and calculate/transform something into another form before the output. For example

```
# in ModelSchema
class UserSchema(ModelSchema):
    role: str     # to process this, it should call a `role` function below
    class Config:
        model = get_user_model()
        include = ['uuid', 'email']

        def role(self):
             return "Admin" if self.is_superuser else "User"
```

This feature should also be applied in `create_schema` as well. 

I am not sure if this feature is already existed or not. I've tried to find the solution online, even in the documentation but no found.

**Comment by paolodina** [comment]
@atlonxp mind to share the answer/advice if you found one? Thanks.

**Comment by atlonxp** [comment]
> @atlonxp mind to share the answer/advice if you found one? Thanks.

https://django-ninja.rest-framework.com/guides/response/?h=reso#resolvers
We can use Resolver to solve this matter. it was my stupidness that I don't understand in the first place.
