### ISSUE TITLE
File Upload?

### ISSUE THREAD

**Issue by pj-simpson** [vitalik/django-ninja#59]
Hello @vitalik, I'm having lots of fun playing around with Django Ninja, congratulations it's great! 
One thing I was wondering: is it currently impossible to accommodate file uploads within the framework?

There seems to me, to be no obvious way to define a file object in a request body's schema. 
Apologies in advance, if I'm missing something obvious, and if anyone has a way of doing so, please let me know! 👍

**Comment by nirajdpandey** [comment]
Hello @vitalik any update on this would be very helpful. Thanks a lot for nice work.

**Comment by amiroff** [comment]
@pj-simpson  see https://github.com/vitalik/django-ninja/issues/58

**Comment by vitalik** [comment]
Hi @pj-simpson 
Thank you for trying django-ninja

so the schema for files are coming to 0.10.0 version (should be all ready any day now)

meanwhile you can use `request.FILES['xxx']` (see  #58 ) - later resulting parameter should be same time

**Comment by pj-simpson** [comment]
@vitalik & @amiroff ... thank you so much for your help, (and sorry to raise something which had already been answered)!
Looking forward to the new version :+1:
