### ISSUE TITLE
Cannot send more than one http request to the same endpoint

### ISSUE THREAD

**Issue by charissalaw** [vitalik/django-ninja#590]
I see that this issue was raised here [/issues/203](https://github.com/vitalik/django-ninja/issues/203) but I'm not sure why it was closed. I am having the issue still and I have tried the hacks suggested and nothing is working. I suspect it may be because the endpoint is SSL enforced but I'm not sure. I need both a POST and a GET to go to the same url address in order to integrate a third-party webhook.

My endpoints are as follows:
webhooks/api.py
```
router = Router()

@router.post("/webhook", response={400: str, 200: str})
def messenger_webhook(request, body: MessengerBody):
    if body.object == "page":
        return 200, 'Event Received'
    return 400, 'Invalid page body'
```
And in main api.py I have:
```
from webhooks.api import router as webhook_router

api = NinjaAPI()
api.add_router("/", webhook_router)

@api.get("/webhook", response={400: str, 200: str})
def validate_messenger(request):
    verify_token = request.GET.get('<token>')
    if verify_token == VERIFY_TOKEN:
            return 200, 'Success'
    return 400, ""
```
I have tried the suggested hacks of adding a variable and assigning different types
```
@router.post("/webhook/{str:value}", response={400: str, 200: str})\
def messenger_webhook(request, val: int, body: MessengerBody):
    ...
```
```
@api.get("/webhook/{str:value}", response={400: str, 200: str})
def validate_messenger(request, val: str):
    ...
```
Still only one endpoint will work. 

I have tried switching the hierarchy so that the GET request is in the router and the POST is in the main api.py. That did not work.

I also tried defining two separate NinjaAPI() modules and tricking them to the same namespace:
```
alt_api = NinjaAPI(urls_namespace='api')
@alt_api.get("/webhooks/webhook")
def validate_messenger(request):
    ...
```
```
api = NinjaAPI()
@api.post("/webhook")
def messenger_webhook(request, body: MessengerBody):
    ...
```
then in urls.py:
```
from main.api import alt_api
from webhooks.api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', alt_api.urls),
    path('api/webhooks/', api.urls),
]
```
In this last scenario, the `alt_api.urls` works fine but
I get `405 Method Not Allowed` when I try `api.urls` request

If i comment out `alt_api.urls` line then `api.urls` works fine.

I know this is a lot of information but I'm hoping it might help for a fix because I appreciate other aspects of the framework.

django-ninja==0.19.1
Django==4.1.2
Python==3.9.6

**Comment by OtherBarry** [comment]
I think the issue is that you have the same path in multiple routers. The incoming URL will be matched to a router, either the base API router, or the one you are adding, and then it'll look for appropriate methods within that.

### Solution 1
Put them in the same router, e.g:

```python
api = NinjaAPI()
@api.get("/webhook", response={400: str, 200: str})
def validate_messenger(request):
    ...
@api.post("/webhook", response={400: str, 200: str})
def messenger_webhook(request, body: MessengerBody):
    ...
```

### Solution 2
Give them different urls, e.g.

`webhooks/api.py`
```python
router = Router()

@router.post("/", response={400: str, 200: str})
def messenger_webhook(request, body: MessengerBody):
    ...
```

`main.py`
```python
from webhooks.api import router as webhook_router

api = NinjaAPI()
api.add_router("/different-webook", webhook_router)

@api.get("/webhook", response={400: str, 200: str})
def validate_messenger(request):
    ...
```

Solution one seems like what you're after though.
