### ISSUE TITLE
How to define responses for the swagger

### ISSUE THREAD

**Issue by JFeldaca** [vitalik/django-ninja#593]
Hello!

I'm passing my API responses to schemas so that the corresponding responses and status appear in the swagger documentation.

In those that return a list with keys I have no problem, but in those that return a plain text, or a list without keys, how could I define it?

For example, an endpoint returning the services available at a location, the current response is:

`['Internet', 'Aplicaciones', 'Wifi' .... ]`

Or an endpoint that returns the status of the API, it is currently returning "OK"

Regards!

**Comment by vitalik** [comment]
@JFeldaca 

not sure I understand..

maybe like this:
```Python

@api.get('/some', response=list[str])  # <--!
def list_view(request):
    return ['Internet', 'Aplicaciones', 'Wifi']
```
