### ISSUE TITLE
UploadedFile.__modify_schema__ raise TypeError[BUG] 

### ISSUE THREAD

**Issue by YuanmingLuo** [vitalik/django-ninja#594]
**Describe the bug**
when i request http://localhost:8000/api/docs, following exception is raising.
and i found that there is a method named get_field_schema_validations in pydantic.schema will call UploadedFile.\_\_modify_schema__ , the method named  get_field_schema_validations only pass the f_schema variable. but UploadedFile.\_\_modify_schema__ receives two params: ‘field_schema’ and 'field' . so it raise TypeError.

and i add the default value 'None' to the params 'field'. and it fixed. 
I don't know whether it's appropriate. so i add a issue to tell you

![image](https://user-images.githubusercontent.com/54884535/196590298-f85ab1e7-4140-424d-9c11-d7986c976bff.png)
![image](https://user-images.githubusercontent.com/54884535/196588190-93e55004-3eb9-41af-9188-ae23272ce6bf.png)

**Versions (please complete the following information):**
 - Python version: 3.9.12 64-bit 
 - Django version: 3.2.15
 - Django-Ninja version: 0.19.1

**Comment by vitalik** [comment]
@YuanmingLuo 

Whats your pydantic version ? try upgrade to latest ?

**Comment by YuanmingLuo** [comment]
> @YuanmingLuo
> 
> Whats your pydantic version ? try upgrade to latest ?

oh, i see. my pydantic version is 1.7.3
maybe other pkgs limit the pydantic version.
and thanks for your reply. :D
