### ISSUE TITLE
Can I add a default json renderer class?

### ISSUE THREAD

**Issue by begyy** [vitalik/django-ninja#6]
![image](https://user-images.githubusercontent.com/44405438/88390986-ba42fd00-cdd2-11ea-9b79-998f00d92f30.png)
and django also supports ujson and orsjon?  
![image](https://user-images.githubusercontent.com/44405438/88391194-21f94800-cdd3-11ea-8f4d-db9ebcb7aa4f.png)

**Comment by vitalik** [comment]
@begyy 

Yes, it's a good option, it's in my backlog

**Comment by vitalik** [comment]
Hey @begyy 

what are you thoughts...

Do you need to set response class for each individual operation?  `@api.get("", response_class=ORJsonResponse)`

or is it enough to set one global like `api = NinjaAPI(..., json_renderer=UJSON)` - that will handle both deserialising input and serialising output ?

I do not see any case for myself where I would want one  operation to have ujson or other one stdlib json lib

**Comment by begyy** [comment]
Hi @vitalik  better it api = NinjaAPI(..., json_renderer=UJSON)

**Comment by vitalik** [comment]
Hi @begyy 

Please try latest version with support for response renderers

https://django-ninja.rest-framework.com/tutorial/response-renderers/

**Comment by begyy** [comment]
ok

**Comment by begyy** [comment]
@vitalik good
