### ISSUE TITLE
[BUG] Poetry install fails

### ISSUE THREAD

**Issue by Roccoriu** [vitalik/django-ninja#605]
I cannot install django-ninja with poetry.
![image](https://user-images.githubusercontent.com/25778176/201069737-6afcc52e-4baf-4306-ac0c-18c09b56835b.png)

I don not know why this happens.

I am using the following versions of each library:
 - Python version: [3.10.6]
 - Django version: [4.1]
 - Django-Ninja version: [0.19.1]
 - Pydantic version: [1.10.2]

**Comment by alirezapla** [comment]
check your dependencies

**Comment by Roccoriu** [comment]
This was installed into a fresh project, so it would just install the standard dependencies.

**Comment by vitalik** [comment]
@Roccoriu 

I'm closing this for now - you still can reproduce - just list here a steps you do and reopen ticket
