### ISSUE TITLE
[BUG] Django `@transaction.atomic` does not work with router decorator

### ISSUE THREAD

**Issue by asaff1** [vitalik/django-ninja#607]
**Describe the bug**

Try the following, with a Django ORM model:
```
@transaction.atomic
@router.put("/comment/{obj_id}")
def update_comment(request, obj_id: int):
    obj = Comment.objects.select_for_update().filter(pk=obj_id)
    # ... code
    return "OK"

```
You will get an error that `select_for_update()` wasn't call inside a transaction.
However, if you swap the order of the decorators (i.e, that `@transaction.atomic` will be lower, hence the first) - it will work.

This is very unexpected, as the user who use the transaction decorator will expect it to work seamlessly. Some ORM operation will not even throw an error, hence risking the integrity of the user data.

**Versions (please complete the following information):**
 - Python version: 3.9
 - Django version: 3.2.12
 - Django-Ninja version: 0.16.1

```

**Comment by JFeldaca** [comment]
Hi @asaff1 

I've encounter with a similar problem and I solve it using the sentence with transaction.atomic()

example:

```python

@api.post("/purchase-process/", tags=["common"])
def post_purchase_process(request, payload: PurchaseProcessSchemaIN):
    if "," in payload.action:
        actions_to_make = payload.action.split(",")
    else:
        actions_to_make = ((payload.action),)
    response = {}
    with transaction.atomic():
        for action in actions_to_make:
            # .... code ....
        return response
```

In this endpoint all not 200 response is an automatic rollback.

**Comment by vitalik** [comment]
@asaff1 

decorators shoul be placed AFTER .get/post/put/etc:

try:
```Python

@router.put("/comment/{obj_id}")
@transaction.atomic    # <-------------------- 
def update_comment(request, obj_id: int):
```

**Comment by asaff1** [comment]
@vitalik I know, your code does work as I said. 
The problem is that the beginner developer might not notice it, and the "error" here will be silently ignored.
Best way if the library could check that in some way. 
Also this should be explained in the docs, that router decorators should be the topmost.

**Comment by vitalik** [comment]
@asaff1 

well that's an interesting problem - but I do not actually see any solution - after django-ninja executes .put decorator it is no longer in control of which functions decorates it next (higher)
