### ISSUE TITLE
[proposal] router parameters

### ISSUE THREAD

**Issue by laith43d** [vitalik/django-ninja#61]
Hi vitalik,

This project is magical, I cannot imagine myself developing APIs using anything else from now on, I'm actually in the process of migrating two projects to Ninja already! 🙂

I have an enhancement proposal for the router, I repetitively configure each route for auth, tags, response, etc. if it is possible to configure these generally in the router.

Examples:
instead of
```python
staff_router = Router()


@staff.get('/orders',
           tags=['staff'],
           auth=IsAuthorized(staff_auth),
           response={200: List[InventoryOrderSchemaOut]}
           )

@staff.get ...
```

we do
```python
staff = Router(
           tags=['staff'],
           auth=IsAuthorized('STAFF'),
)


@staff.get('/orders',
           response={200: List[InventoryOrderSchemaOut]}
           )
```

**Comment by vitalik** [comment]
Hi @aith43d 

Thank you! glad to hear this


Indeed, I have also experience some issues with with routers tagging

but the approach of dealing with this I think a bit different - the api.add_router should have these options...

for you case it can be something like this:

```Python
from some_module import staff # router

api = NinjaAPI()

api.add_router("/staff", staff, auth=IsAuthorized('STAFF'), tags=["staff"])

```
