### ISSUE TITLE
resolve_ methods are not called when returning a dict

### ISSUE THREAD

**Issue by tykling** [vitalik/django-ninja#610]
Hello,

`resolve_` methods do not work when returning a dict (as opposed to a queryset or model instance) from the view. It doesn't matter if a `Schema` or `ModelSchema` is used. The example in the docs https://django-ninja.rest-framework.com/guides/response/#resolvers only works if used in a view which returns a model instance, not when returning a dict.

I spent some time trying to cook this down to a manageable size. I created this `api.py` file in a fresh django project:

```python
from ninja import NinjaAPI, Schema, ModelSchema
from django.contrib.auth.models import User

class ModelUserOut(ModelSchema):
    foo: str

    class Config:
        model = User
        model_fields = ["username"]

    def resolve_foo(self, obj):
        return "resolved foo"

class UserOut(Schema):
    username: str
    foo: str

    def resolve_foo(self, obj):
        return "resolved foo"

api = NinjaAPI()

@api.get("/modelschema/returnmodel-modelschema", response=ModelUserOut)
@api.get("/schema/returnmodel-schema", response=UserOut)
def returnmodel(request):
    return User.objects.get_or_create(username="test")[0]


@api.get("/modelschema/returndict-modelschema", response=ModelUserOut)
@api.get("/schema/returndict-schema", response=UserOut)
def returndict(request):
    return {"username": "some user"}
```

In the two endpoints where a model instance is returned the `resolve_foo` method is called, in the two endpoints where a dict is returned I get the following traceback, exactly like I am seeing in my big project:

```
Traceback (most recent call last):
  File "/home/user/devel/ninjatest/venv/lib/python3.9/site-packages/ninja/operation.py", line 100, in run
    return self._result_to_response(request, result, temporal_response)
  File "/home/user/devel/ninjatest/venv/lib/python3.9/site-packages/ninja/operation.py", line 196, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
  File "/home/user/devel/ninjatest/venv/lib/python3.9/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
  File "pydantic/main.py", line 579, in pydantic.main.BaseModel.from_orm
pydantic.error_wrappers.ValidationError: 1 validation error for NinjaResponseSchema
response -> foo
  field required (type=value_error.missing)
```

The same Schema works in the shell:

```python
(venv) user@bornhack-dev:~/devel/ninjatest$ python manage.py shell
Python 3.9.10 (main, Jan 26 2022, 13:40:28) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from ninjatest.api import UserOut

In [2]: UserOut.from_orm({"username": "hejsa"})
Out[2]: UserOut(username='hejsa', foo='resolved foo')

In [3]: 
```

Any idea if this is a bug or I am doing something wrong? Thanks! :)

**Comment by tykling** [comment]
Hm, ok, resolve_* fields appear to work in ModelSchema, but not in regular Schema. https://django-ninja.rest-framework.com/guides/response/#resolvers shows using it in a regular schema though.

**Comment by vitalik** [comment]
Hi @tykling 

what I notice is double decorator usage:
```Python
@api.get("/modelschema/returnmodel-modelschema", response=ModelUserOut)
@api.get("/schema/returnmodel-schema", response=UserOut)
def returnmodel(request):
    ...
```
I think this it's contributing to the problem

try to split:

```Python
@api.get("/modelschema/returnmodel-modelschema", response=ModelUserOut)
def retrunmodel(request):
   ...

@api.get("/schema/returnmodel-schema", response=UserOut)
def returnschema(request):
    ...
```

**Comment by tykling** [comment]
Hello :)

Thank you for the quick reply. The double decorator is not to blame, I see the same behaviour with this code:

```
from ninja import NinjaAPI, Schema, ModelSchema
from ninja.operation import ResponseObject
from django.contrib.auth.models import User

class ModelUserOut(ModelSchema):
    foo: str

    class Config:
        model = User
        model_fields = ["username"]

    def resolve_foo(self, obj):
        return "resolved foo"

class UserOut(Schema):
    username: str
    foo: str

    def resolve_foo(self, obj):
        return "resolved foo"

api = NinjaAPI()

@api.get("/modelschema/returnmodel-modelschema", response=ModelUserOut)
def returnmodel(request):
    return User.objects.get_or_create(username="test")[0]

@api.get("/schema/returnmodel-schema", response=UserOut)
def returnmodel2(request):
    return User.objects.get_or_create(username="test")[0]


@api.get("/modelschema/returndict-modelschema", response=ModelUserOut)
def returndict(request):
    return ResponseObject({"username": "some user"})

@api.get("/schema/returndict-schema", response=UserOut)
def returndict2(request):
    return ResponseObject({"username": "some user"})
user@bornhack-dev:~/devel/ninjatest$ 
```

Thanks

**Comment by tykling** [comment]
For now I am working around this by manually calling `from_orm()` on the Schema and returning it directly as a HttpResponse, circumventing the bug:

```
@api.get("/test/", response=UserOut)
def returndict3(request):
    schema = UserOut.from_orm({"username": "some user", "user": User.objects.first()})
    return HttpResponse(schema.json(), content_type="application/json")
```

**Comment by kristian-lindin** [comment]
+1. I have the same issue. 

Defining a Schema like:

```
class Doggy(Schema):
        dog_name: str | None = None
        naming: str | None

        def resolve_naming(self, obj: Any) -> str | None:
            return f"name_{self.dog_name}"

```
and then when trying to serialize an instance of Doggy as the schema Doggy. I cannot trigger the "resolve_naming". Actually it doesn't even trigger when manually calling first ".from_orm" then ".dict".
When looking at the breakpoint inside from_orm it looks like like some class lookup is failing (see screenshot). My gut feeling here is that this error prevents further lookups on other attributes/nested objects. Thus, not triggering my desired resolve_naming function

<img width="1228" alt="Skärmavbild 2022-11-29 kl  08 53 58" src="https://user-images.githubusercontent.com/47393915/204470981-721c7cbe-03d3-4799-af1e-b35339417afa.png">

**Comment by SmileyChris** [comment]
PS: I had a look at this (the resolve methods is my code) and there's definitely something not right here.

I started a local branch that fixes it when looking at this the other day, but it's breaking a bunch of schema tests :-/

The discussions in #738 might have some hints at a better way to fix this, and will pave the way for Pydantic 2 support anyway...
