### ISSUE TITLE
Using form parameters in generated API documentation

### ISSUE THREAD

**Issue by ognjenk** [vitalik/django-ninja#62]
Hi, 
I'm pretty new to API programming so please bear with me.

I am trying to define login endpoint which will take username and password as form parameters, like this:

```python
@router.post("/token")
def get_token(request, username: str = Form(...), password: str = Form(...)):
    return {username: password}
```

Generated API docs will display endpoint and form parameters correctly, however when I try using the endpoint through the docs it will generate curl like this:

```
curl -X POST "http://localhost:8000/api/token" -H  "accept: */*" -d ""
```

and the error I get is code 422 Undocumented | Error: Unprocessable Entity
with response:
```
{
  "detail": [
    {
      "loc": [
        "form",
        "username"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    },
    {
      "loc": [
        "form",
        "password"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
```

Looks like the parameters and their values are not passed to the generated API call.

If I do a manual curl call like this:
```
curl -X POST -F 'username=myusername' -F 'password=mypassword' http://localhost:8000/api/token
```
everything works as expected.
Thanks in advance!

**Comment by vitalik** [comment]
Hi @ognjenk

Indeed, seems there is a bug in schema for forms - will check it out

Thanks

**Comment by ognjenk** [comment]
Thanks a lot for the quick response.

Also thanks for creating this project, I haven't spent too much time on it yet, but so far I am loving it!

**Comment by ognjenk** [comment]
Hi, just to let you know I have tried this in 0.10.0 release and it works great.
Thanks for the support!

**Comment by vitalik** [comment]
great!

**Comment by mohannadirshedat** [comment]
HI , @vitalik  
I got this issue on version 0.20.0 too 

```
def update_avatar(request, file: UploadedFile = File(...)):
    pass
```

could you help plz

**Comment by vitalik** [comment]
@mohannadirshedat which method do you use ? 

My guess is that you use PATCH - in this case you need to patch django with this middlewre - https://github.com/vitalik/django-ninja/issues/417#issuecomment-1092545699

**Comment by baseplate-admin** [comment]
Hey @vitalik 

Can we put this middleware in the documentation?
