### ISSUE TITLE
[BUG] Content Security Policy error at the API `/docs` url.

### ISSUE THREAD

**Issue by fabiocaccamo** [vitalik/django-ninja#621]
**Describe the bug**
Visiting the `/docs` url, there is a CSP error:

<img width="950" alt="Screenshot 2022-12-06 at 14 56 13" src="https://user-images.githubusercontent.com/1035294/205931186-65e2a3fa-551a-4432-ac86-7ff12c94207e.png">

Probably the image is loaded using an absolute url and not as static asset.

**Versions:**
 - Python version: `3.8`
 - Django version: `3.2`
 - Django-Ninja version: `0.19.1`
 - Pydantic version: `1.9.1`

**Comment by OtherBarry** [comment]
This is most likely solved by adding `ninja` to your `INSTALLED_APPS`. See [the docs here](https://django-ninja.rest-framework.com/guides/api-docs/)

**Comment by fabiocaccamo** [comment]
@OtherBarry totally missed it, sorry. Thank you very much!
