### ISSUE TITLE
Please add regex matching for paths in routers

### ISSUE THREAD

**Issue by hugo-onespace** [vitalik/django-ninja#629]
In django it is possible to define a url path for a view with a regex. This allows both weird urls, or as in my case, to be able to match everything after a base url. I have not found this capability in ninja.

For example, I would want the following urls to hit the same view:

/BASE/x/y
/BASE/a/b/c/d

I find that I can match the urls if I guess the number of path elements, like such:

router.get("/BASE/{path1}/{path2}/{path3}/{path4}")

But this is hackish, ugly and requires multiple entries to match different numbers of path elements.

Many thanks.

**Comment by vitalik** [comment]
@hugo-onespace 

well, regex approach seems not OpenAPI compatible...
but on the other hand you have standard django `path` modifier that you can use for described case:


```Python

@api.get('/BASE/{path:path_str}')  # <-- note the path marker
def someview(request, path_str: str):
       return path_str  # <-- will have a path including slashes
```

**Comment by hugo-onespace** [comment]
That solves my use case. Thank you for the quick response and I see you already added a note to the docs. Well done.
