### ISSUE TITLE
Sync style code with non-blocking I/O?

### ISSUE THREAD

**Issue by Adamantish** [vitalik/django-ninja#63]
I can't tell for sure from the docs whether this is as I think it is but here goes:

I love this project for the pydantic integration and not forcing me to choose between that and django.

For our new project at my company I'd prefer me and my team to write our new service with sync style code. gunicorn with gevent workers seems ideal for this. It monkey patches the most commonly used libraries for I/O such that even though we're not writing explicit async code, we have non-blocking I/O in the most important places. Sure, this is not the style to get every last drop of performance. It doesn't lend itself to sending a bunch of requests in parallel for instance. But for this project that's not a concern so I'd prefer not to add the overhead of forcing people think async and not risk a PR with a missing `await` that causes our event loop to block.

Have I described the above correctly? If so, is there a neat monkey patching solution for such that I can call a database in a sync method without worrying?

I'm new to python so I might be skipping over something that's obvious to anyone who knows its newer async abilities.

**Comment by vitalik** [comment]
Hi @Adamantish 

I'm not really expert on gunicorn and do not know how it patches django, but in general if you use regular sync operations from django-ninja nothing is really different from regular django views, so I guess my answer is yes - nothing to worry about.


My usual approach is to write all in sync mode, and once some operation is getting high concurrency and does some IO - then   it a good candidate to switch it to async mode.

**Comment by Adamantish** [comment]
Thanks @vitalik, I had I look around to try to understand why this is the case and I think [this question ](https://github.com/tiangolo/fastapi/issues/33) on FastApi was essentially the same as mine but more clearly formed.

When you don't define a view as async in FastAPI it will be sent to run in a pool of OS threads, much like gunicorn in threaded mode. I took a little look and once I got to [here in ninja](https://github.com/vitalik/django-ninja/blob/ce521059d0f4697231f8c16757458fb95a3413ff/ninja/operation.py#L60) it seems like confirmation that this doesn't do something similar. i.e. is it true that views not declared with `async` will block the event loop while waiting on I/O? Because that would be very different to normal django use.

**Comment by vitalik** [comment]
> is it true that views not declared with `async` will block the process while waiting on I/O?

Not really

if you define our ninja "view" as async - the [AsyncOperation](https://github.com/vitalik/django-ninja/blob/ce521059d0f4697231f8c16757458fb95a3413ff/ninja/operation.py#L143) will be used.


Both are just wrappers for regular django views which internally follow this logic

 - in async mode all async views are using event loop 
 - sync views will be executed in threads

Generally django-ninja is just a wrapper around django views, it does not bring any threading/event-loop features on top

read more about django async support here:

https://docs.djangoproject.com/en/3.1/topics/async/#async-views

**Comment by Adamantish** [comment]
Ah so sync views will be done in threads? The reason I ask is that with standard Django the app is single threaded and it's the web server such as gunicorn that's responsible for multithreading / gevent loop. Uvicorn, on the other hand, I couldn't find a threaded feature with which is why FastAPI uses asyncio's `ThreadPoolExecutor` via `run_in_executor`.

Is there somewhere in ninja that does similar?

**Comment by vitalik** [comment]
I kind of repeat my self - but django-ninja is not involved in any sync/async/thread behaviour - it just a validation/openapi wrapper

All the execution logic is described here:

https://docs.djangoproject.com/en/3.1/topics/async/#async-views

I cannot guaranty this 100%  - but my guess is that if you run django 3.1+ project under asgi (uvicorn or dafne) - sync views are executed under `asgiref.sync_to_async` (see https://github.com/django/asgiref/blob/master/asgiref/sync.py )

and it look like the execution is actually happening in threadpool executor

**Comment by Adamantish** [comment]
Ah thank you very much. This makes a lot more sense and seems a sensible separation. Forgive my ignorance, I had the weird assumption that Django didn't have anything built-in to use an ASGI server.

**Comment by nythrox** [comment]
Hey @Adamantish , how did this work out for you?

**Comment by luckyabsoluter** [comment]
@nythrox Are you looking for this kind of experiment result? https://github.com/luckyabsoluter/uvicorn-sleep-issue-example
