### ISSUE TITLE
Bump Django to 4.1+ and add async ORM queries

### ISSUE THREAD

**Issue by kigawas** [vitalik/django-ninja#630]
**Is your feature request related to a problem? Please describe.**

As of Django 4.1 async queries can be made. It's time to bump Django to 4.1+ and enjoy them!
This might be a huge change for code and documentation, but I think it's worth doing it.

**Describe the solution you'd like**

See the official documentation:

https://docs.djangoproject.com/en/dev/topics/db/queries/#async-queries

**Comment by OtherBarry** [comment]
All tests pass running on Django 4.1.4 - I don't think there's any tests that explicitly test the async ORM, but there's plenty that test async views generally.

Is there some particular aspect that isn't working for you on Django 4.1?

**Comment by kigawas** [comment]
Just a feature request to support async ORM queries. For example, we may write like this from Django 4.1:

```py
@api.get("/employees", response=list[EmployeeOut])
async def list_employees(request):
    return [q async for q in Employee.objects.all()]
```

This can make the Django-ninja project more ninja

**Comment by OtherBarry** [comment]
Does that not work currently?

**Comment by OtherBarry** [comment]
I updated the demo project's someapp.api to use async methods:

```python
@router.post("/create", url_name="event-create-url-name")
async def create_event(request, event: EventSchema):
    await Event.objects.acreate(**event.dict())
    return event


@router.get("", response=List[EventSchema])
async def list_events(request):
    return [a async for a in Event.objects.all()]


@router.delete("")
async def delete_events(request):
    await Event.objects.all().adelete()


@router.get("/{id}", response=EventSchema)
async def get_event(request, id: int):
    result = await Event.objects.aget(id=id)
    return result
```

And all tests passed, so it seems like everything works to me.

**Comment by vitalik** [comment]
Hi @kigawas 

4.1 async queries working out of the box
