### ISSUE TITLE
Get response schema from type hints instead of decorator parameter

### ISSUE THREAD

**Issue by adam-olema** [vitalik/django-ninja#633]
**Is your feature request related to a problem? Please describe.**

Would be a little cleaner to be able to derive the response schema from the function's type hints instead of requiring an additional parameter to the decorator.  When using type hints (and mypy) pervasively, it would help to eliminate the possibility of a mismatch between the return type of the request handler and the value of the `response` parameter.

**Describe the solution you'd like**

Instead of:

```python
@api.post("/somewhere", response=ResponseSchema)
def somewhere(request, data: RequestBodySchema):
``` 

Cleaner:

```python
@api.post("/somewhere")
def somewhere(request: HttpRequest, data: RequestBodySchema) -> ResponseSchema:
    ...
    return ResponseSchema(...)
```

The same process of inspecting the function parameter types can also be used to determine the response annotation type.

**Comment by vitalik** [comment]
Hi @adam-olema 

there was already discussion about this here #46

main problem is that responses can be complex with multiple status codes and different response schemas...

but for simple cases you can just override your NinjaAPI methods to support result annotations:


```Python
import inspect

class TypeRespRouter(Router):
    def add_api_operation(self, path, methods, view_func, *args, **kwargs):
          kwargs['response'] = inspect.signature(view_func).return_annotation
          return super().add_api_operation(path, methods, view_func, 
```

and then this should work:
```Python
api = TypeRespRouter()

@api.post("/somewhere")
def somewhere(request: HttpRequest, data: RequestBodySchema) -> ResponseSchema:
    ...
    return ResponseSchema(...)
