### ISSUE TITLE
Is it possible to combine both DRF and Django Ninja API?

### ISSUE THREAD

**Issue by gschurck** [vitalik/django-ninja#642]
I have currently a Django API project built with DRF. I would like to use async for some endpoints to optimize long API calls.
Would it be possible and interesting to migrate some endpoints to Django Ninja async ?
While keeping the rest with DRF.
So I would change my server from WSGI to ASGI.
Maybe my understanding of async is not right and the combination of both is bad, I don't know.

**Comment by gschurck** [comment]
Okay, so I need to use uvicorn with async views.
But how will Django + DRF work for all the rest that is still sync, on an asgi/uvicorn server ? There are no issues with this kind of setup ?

**Comment by vitalik** [comment]
@gschurck 

well this is not the best place to ask this, as it generally a core django  topic

but according to docs - once you start asgi process - all non sync views will be handled inside sync_to_async wrapper

you can follow details here - https://docs.djangoproject.com/en/4.1/topics/async/

**Comment by gschurck** [comment]
Okay so it should be doable, thanks.
