### ISSUE TITLE
Can't get the data, when the request  header is application/json

### ISSUE THREAD

**Issue by jykcc** [vitalik/django-ninja#643]
**The main function is**
```python
from ninja import Schema

class BaseItem(Schema):
    engine: str = "default"

    def __str__(self):
        return self.engine

class DemoItem(BaseItem):
    keys: Any
    text: Any

@api.post("/demo")
def demo(request: HttpRequest, item: DemoItem):
    # item is Null
```
**request code**
```python
data = {'keys': ['sex','age'], 'text': text}
h = {"content-type": "application/json"}
response = requests.post(url + api, headers=h, json=data)
return response.json()
```
How to make the item data  not use ```requests.post(url + api, headers=h, data=data)```

**Comment by vitalik** [comment]
@jykcc works for me...

maybe you forgot to return the item ? 

```Python
api = NinjaAPI()

class BaseItem(Schema):
    engine: str = "default"

    def __str__(self):
        return self.engine

class DemoItem(BaseItem):
    keys: Any
    text: Any


@api.post("/demo")
def demo(request: HttpRequest, item: DemoItem):
    return item  # <<<--- maybe you forgot to return the item ? 

```

```Python
import requests

data = {'keys': ['sex', 'age'], 'text': 'some text'}
h = {"content-type": "application/json"}

resposne = requests.post('http://localhost:8000/api/demo', headers=h, json=data)
print(resposne.status_code)
print(resposne.json())
```

```
python test.py
200
{'engine': 'default', 'keys': ['sex', 'age'], 'text': 'some text'}
```

**Comment by jykcc** [comment]
> @jykcc works for me...
> 
> maybe you forgot to return the item ?
> 
> ```python
> api = NinjaAPI()
> 
> class BaseItem(Schema):
>     engine: str = "default"
> 
>     def __str__(self):
>         return self.engine
> 
> class DemoItem(BaseItem):
>     keys: Any
>     text: Any
> 
> 
> @api.post("/demo")
> def demo(request: HttpRequest, item: DemoItem):
>     return item  # <<<--- maybe you forgot to return the item ? 
> ```
> 
> ```python
> import requests
> 
> data = {'keys': ['sex', 'age'], 'text': 'some text'}
> h = {"content-type": "application/json"}
> 
> resposne = requests.post('http://localhost:8000/api/demo', headers=h, json=data)
> print(resposne.status_code)
> print(resposne.json())
> ```
> 
> ```
> python test.py
> 200
> {'engine': 'default', 'keys': ['sex', 'age'], 'text': 'some text'}
> ```

Tanks,Seems to be the problem of middleware,  When I commented out the code, The code run Succes
