### ISSUE TITLE
Add Form() for Http Method PUT and PATCH

### ISSUE THREAD

**Issue by hazamashoken** [vitalik/django-ninja#645]
I am working on a Django ninja API project and I got a problem with Ninja Form() body it works perfectly fine for POST requests but it doesn't seem to work with PUT or PATCH. I thought it was a bug so I went through the issue forms and forums for answers but found non then I look at the documentation again and it seem that it only explicitly mention this

[Django Ninja also allows you to parse and validate requests.POST data (aka application x-www-form-urlencoded or multipart/form-data).](https://django-ninja.rest-framework.com/guides/input/form-params/?h=form)

I would like to request, if it's possible, to make Form() compatible with PUT and PATCH methods.

**Comment by vitalik** [comment]
@hazamashoken 

this is basically a part of django default behavioural

you can patch it with this middleware: https://github.com/vitalik/django-ninja/issues/417#issuecomment-1092545699

**Comment by hazamashoken** [comment]
Thank you, I won't have solved this issue by myself.
