### ISSUE TITLE
why use field.verbose_name.title() instead of field.verbose_name in orm/fields.py

### ISSUE THREAD

**Issue by adi1** [vitalik/django-ninja#646]
As the title says.... When we have lazy texts as verbose_names for django model fields, the schema generation will not use these in the correct language. Calling `field.verbose_name.title()` will evaluate it when the model is loaded and not when openapi.json is generated.

Changing `field.verbose_name.title()` to `field.verbose_name` resolves this issue, but I would like to know if this can cause other unexpected issues.

**Comment by vitalik** [comment]
@adi1 

how do you generate openapi.json ? (or should I ask differently - how do I reproduce the issue ? )

**Comment by adi1** [comment]
Sorry I'm not at the pc anymore so i will try my best to describe it on my phone. To reproduce, you need to import ugettext_lazy as _, then set your field verbose_name=_('some string'). I don't think i can describe the entire django i18n workflow.

This will use a proxy for the string, rather than the string itself. This proxy uses some funny thread local stuff (I think) which checks the current language, set at the beginning of every request.

To generate openapi.json, i simply go to /api/openapi.json . If my session (or if i have the right language cookie) is in German, the texts will be in German.

Currently, help_text is translated to german, verbose_name is english.

When you can .title() on that proxy, you're converting it to a string, without why language context, so it uses the original language of the text.

Let me know if you need more information, i can try to help better when I'm actually at the computer.

**Comment by adi1** [comment]
I had some time to look at the code and tests, and the simplest solution would be something like this:

```diff
--- a/ninja/orm/fields.py
+++ b/ninja/orm/fields.py
@@ -15,6 +15,7 @@ from uuid import UUID
 
 from django.db.models import ManyToManyField
 from django.db.models.fields import Field
+from django.utils.functional import Promise
 from pydantic import IPvAnyAddress
 from pydantic.fields import FieldInfo, Undefined
 
@@ -141,7 +142,7 @@ def get_schema_field(field: Field, *, depth: int = 0) -> Tuple:
         default = Undefined
 
     description = field.help_text
-    title = field.verbose_name.title()
+    title = field.verbose_name if isinstance(field.verbose_name, Promise) else field.verbose_name.title()
 
     return (
         python_type,
@@ -173,6 +174,6 @@ def get_related_field_schema(field: Field, *, depth: int) -> Tuple[OpenAPISchema
         FieldInfo(
             default=default,
             description=field.help_text,
-            title=field.verbose_name.title(),
+            title=field.verbose_name if isinstance(field.verbose_name, Promise) else field.verbose_name.title()
         ),
     )
```

This doesn't break any existing tests. Properly testing with translated strings would actually be more complicated, as it would require translating strings, creating .po files, etc.. To test, we would need models which use lazy strings for `verbose_name`, like so:
```python
from django.utils.translation import gettext_lazy as _

class Task(models.Model):
    title = models.CharField(_("Task title"), max_length=200)
    is_completed = models.BooleanField(_("Task completed"), default=False)

```

Another possibility would be to check if there was a verbose_name set when creating the field, or if it's automatically set by Django. It would make sense that if there was an explicit verbose_name, then that's how the user wants that field to be displayed, including capitalization. This could be done by [deconstructing](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.Field.deconstruct) the field, which would keep the original verbose_name.

```python
class M(models.Model):
   field1 = models.BooleanField()
   field2 = models.BooleanField("my field")
   class Meta:
      app_label = "test"



[field.deconstruct() for field in M._meta.fields]
[('id',
  'django.db.models.AutoField',
  [],
  {'verbose_name': 'ID',
   'primary_key': True,
   'serialize': False,
   'auto_created': True}),
 ('field1', 'django.db.models.BooleanField', [], {}),
 ('field2', 'django.db.models.BooleanField', [], {'verbose_name': 'my field'})]


[field.verbose_name for field in M._meta.fields]
['ID', 'field1', 'my field']


[field.deconstruct()[3].get('verbose_name', field.verbose_name.title()) for field in M._meta.fields]
['ID', 'Field1', 'my field']

```

The problem with this approach is that it breaks all the tests which expect camel case for everything. The main one is `Id`, since django explicitly sets a verbose_name of `ID`.

I don't really know the implications of this field title, or if it's required to be camel case. I also don't know if this applies to non-django models, so it's hard to say if any of these ideas actually work.

**Comment by adi1** [comment]
hi @vitalik , do you have any feedback on this issue?
