### ISSUE TITLE
Empty body and Schema with all optional attributes

### ISSUE THREAD

**Issue by fojetin** [vitalik/django-ninja#65]
Hi, @vitalik. Is it a bug?

When i send request with empty body, i getting this error
```{
    "detail": [
        {
            "loc": [
                "body",
                "data"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
```

It happens because when we get None from cls.get_request_data(request, path_params)
this code always crash
```
        if data is None:
            return cls()
```

![image](https://user-images.githubusercontent.com/24472835/104303339-085fd000-54db-11eb-8f5f-0ed541ff52b6.png)

**Comment by vitalik** [comment]
Hi

can you give example of your operation ?

```
@api.post(...
def foo(...
```

**Comment by fojetin** [comment]
Yep
```
import typing as t
from ninja import Schema


class Item(Schema):
    name: t.Optional[str]
    description: str = None
    price: t.Optional[float]
    quantity: t.Optional[int]


@router.post("/items")
def create(request, item: Item):
    return item
```

**Comment by fojetin** [comment]
so i just send request to this endpoint and get
```
{
    "detail": [
        {
            "loc": [
                "body",
                "item"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
```

**Comment by vitalik** [comment]
yeah, well it kind of expects at least an empty dictionary... "`{}`"


meanwhile you can handle empty body with `item: Item = None` (defaults to none if empty = None):

```Python
@ router.post("/items")
def create(request, item: Item = None):
    return item
```


I will keep this ticket open, will research how OpenAPI spec actually treats this case...

**Comment by fojetin** [comment]
Thanks you very much for this hint, it solved my problem.

Also i tried set t.Optional[Item], but it's also didn't works

**Comment by rkulinski** [comment]
@vitalik what was the solution to this problem?
