### ISSUE TITLE
API key not populated for Django test client

### ISSUE THREAD

**Issue by cornel-masson** [vitalik/django-ninja#652]
**Describe the bug**

I have implemented authentication by extending `APIKeyHeader`. It works fine when running the Django server and passing the API key as a header, but not when I try to unit-test my API with a Django test client.

My auth class (it uses the supplied API key to lookup a "Client" object in the database):

```
class ApiKeyAuth(APIKeyHeader):
    param_name = "X-API-Key"

    def authenticate(self, request, key):
        """Authenticate API access based on API key."""
        hashed_key = hash_api_key(key)
        client = Client.objects.filter(api_key__exact=hashed_key).get()
        if not client:
            user_agent = request.headers.get("User-Agent")
            get_logger(request).warning(
                f"Rejecting attempt to access API with unknown key '{key}'; User-Agent: '{user_agent}'"
            )
        return client
```

Unit test extract:

```
headers = {"X-API-Key": "abc123"}
r = Client().get("/api/status/", **headers)
```

When I debug, I can see that the `key` parameter of the call to `authenticate(self, request, key)` is _not_ populated (i.e. None).

**Versions (please complete the following information):**
 - Python version: 3.10
 - Django version: 4.1
 - Django-Ninja version: 0.19.1
 - Pydantic version: 1.10.2

**Comment by OtherBarry** [comment]
This is a Django issue, not a Ninja issue. The header argument to the test client needs to be `HTTP_X_API_KEY` to work. [See django docs here.](https://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpRequest.META)

**Comment by cornel-masson** [comment]
Thanks, got it. Will close.

**Comment by cornel-masson** [comment]
Thanks, got it. Closing.
