### ISSUE TITLE
Why do the docs say cookies not secure for API auth?

### ISSUE THREAD

**Issue by dmwyatt** [vitalik/django-ninja#656]
The [CSRF docs say](https://django-ninja.rest-framework.com/reference/csrf/): 

> Warning: It is not secure to use API's with cookie-based authentication! (like CookieKey, or django_auth)

Security professionals often *recommend* using cookie based auth for APIs.

AFAICT, there are pros and cons to any of the ways of doing auth and cookies are not obviously worse than (say) JWTs in `localStorage`.

**Comment by vitalik** [comment]
@dmwyatt 

well the sentence seems not finished in the docs... 
It is not secure ... **when csrf is turned OFF**

I'll add it 

Thank you
