### ISSUE TITLE
Async Auth is broken

### ISSUE THREAD

**Issue by shirecoding** [vitalik/django-ninja#658]
I've tried `django_auth` and it does not work with async endpoints because it reads `request.user.is_authenticated` which access the database, ok so i followed the "custom" authentication method as described in the documentation

```python
async def django_auth_async(request: HttpRequest):
    """
    Default django cookie based authentication
    """
    
    is_authenticated = await sync_to_async(lambda: request.user.is_authenticated)()

    return is_authenticated

...

api = NinjaAPI(urls_namespace="fireside", auth=django_auth_async, csrf=True)

...

@router.get("/cron_pretty", url_name="cron_pretty")
async def cron_pretty(request, cron: str) -> str:
    auth = await request.auth
    return _cron_pretty(cron)
```

I tried accessing the API `cron_pretty` without passing in any cookies, and it still manages to allow it to pass through! pretty dangerous. the only way is to throw an exception inside the auth function, but the documentation makes it sounds like django ninja handles this which is misleading

```python

async def django_auth_async(request: HttpRequest):
    """
    Default django cookie based authentication
    """
    
    is_authenticated = await sync_to_async(lambda: request.user.is_authenticated)()
    if not is_authenticated:
        raise Exception("PERMISSION DENIED")  # <------------- this is required
    return is_authenticated
```

**Comment by skokado** [comment]
same issue

version:
Python 3.11
Django 4.2
django-ninja 0.21.0

I checked by following code

```python
from ninja import NinjaAPI
from ninja.security import HttpBearer, APIKeyHeader

app = NinjaAPI()


class BearerAuth(HttpBearer):
    async def authenticate(self, request, token):
        # Just example authentication logic
        if token == "super-secret":
            return token


@app.get("/secret", auth=BearerAuth())
async def secret_view(request):
    return {"msg": "ok"}
```

results:

```shell
$ # Good (no send Bearer token)
$ curl -X 'GET' \
  'http://localhost:8000/api/secret' \
  -H 'accept: */*'
{"detail": "Unauthorized"}

$ # Good (send correct token)
$ curl -X 'GET' \
  'http://localhost:8000/api/secret' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer super-secret'
{"msg": "ok"}

$ # Bad! (will be authenticated with incorrect token)
$ curl -X 'GET' \
  'http://localhost:8000/api/secret' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer dummy!!'
{"msg": "ok"}
```

I found the fix of above issue.
Let me create PR about this :)

**Comment by skokado** [comment]
@shirecoding described behavior is related to Django's standard WSGIRequest/ASGIRequest will set AnonymousUser to `request.user` default.

I think the root cause of this problem is that the Auth handler does not expect async operations.
The following simple code confirms this.

```python
async def my_auth(request):
    request.called = True
    return "ok"


@app.get("/my_view", auth=my_auth)
def my_view(request):
    auth_called = hasattr(request, "called") and request.called
    return {"auth_called": auth_called}
```

```shell
$ curl localhost:8000/api/my_view
{"auth_called": false}
```

And you can also see that by making `my_view` to async mode then get `{"auth_called": true}` as response
This is because it does not expect async function/method as callback here.
https://github.com/vitalik/django-ninja/blob/3e46804bce183b022c5116220de232ccafbd8dff/ninja/operation.py#L150

I will re-open the PR about this.

**Comment by vitalik** [comment]
@shirecoding this should work in 0.22
