### ISSUE TITLE
Reverse-able url names.

### ISSUE THREAD

**Issue by jlward** [vitalik/django-ninja#66]
I'd like to be able to do something like:

`@router.post('/foo/', name='bar')`

Which would allow me to do `reverse('api-1.0.0:bar')` in order to dynamically get the URL without needing to hard code it. It looks like if [this line](https://github.com/vitalik/django-ninja/blob/master/ninja/router.py#L216) is updated to pass in an optional name, then I think it could work.

If I'm reading the code correctly, all the `METHOD`s (`get`/`post`/etc) would need to be updated to take an optional `name` (or `url_name` or something) argument. Additionally, `api_operation` and `add_api_operation` would need to be updated to take the same optional argument. Lastly, I think something like how `self.operations` is being updated in `add_api_operation` would need to be added to tell `urls_paths` what the names are. 

I don't know how off base I am here. Let me know what you think.

Super slick library by the way. Big fan.

Edit:

Alternatively, some kind of auto-generated name based on the app the end point is in + the path would also work.

If we have `@router.post('foo/bar/')` in an app called `baz`, an auto-name of something like `baz_foo_bar` so we could `reverse('api-1.0.0:baz_foo_bar')` could be pretty slick. This solution has the by product of not needing to update nearly as much code.

**Comment by vitalik** [comment]
Hi @jlward 

Yes, makes sense

**Comment by vitalik** [comment]
[url_name](https://django-ninja.rest-framework.com/tutorial/operation_params/#url_name) argument added to v0.12

**Comment by aprilahijriyan** [comment]
Hi @vitalik, I highly recommend giving the endpoint name based on the view function name. If we declare a name based on the 'url_name' parameter this is very difficult, when we have a lot of endpoints.

**Comment by fretchen** [comment]
I would like to reopen it. I did not find any documentation on how to use the `reverse` function. And in the example of the [CRUD](https://django-ninja.rest-framework.com/tutorial/crud/) I attempted something like:

```
url = reverse("get_employee", kwargs={"employee_id": 1})
```

However, I keep getting the error `Reverse for 'get_employee' not found. 'currencies' is not a valid view function or pattern name.`  Things like `api:get_employee` etc have similiar problems as namespaces seem to be unknown etc...

**Comment by fretchen** [comment]
I wanted to add another problem in adapting the *CRUD* example. Suppose that you implemented the two following views described, but now with an added `url_name`:
```
@api.post("/employees", url_name="create_employee")
def create_employee(request, payload: EmployeeIn):
    employee = Employee.objects.create(**payload.dict())
    return {"id": employee.id}


@api.get("/employees", response=List[EmployeeOut], url_name="list_employees")
def list_employees(request):
    qs = Employee.objects.all()
    return qs
```

The `reverse` function does not find the `create_employee` anymore as it is overwritten by `list_employees` most likely as they have the same URL.

**Comment by vitalik** [comment]
@fretchen 
well that's the way django works
basically each url path has only one name

**Comment by erwzqsdsdsf** [comment]
now,2024,this probelm ,contine not working!!!!!
