### ISSUE TITLE
How to add multiple examples in swagger?

### ISSUE THREAD

**Issue by AsheKR** [vitalik/django-ninja#668]
![image](https://user-images.githubusercontent.com/42999044/215274886-3f2af313-a2e0-48f1-a66b-17095b643200.png)

More specifically, there are several types of 400 responses. How should I provide it in this case?

**Comment by huangjiarong** [comment]
<img width="789" alt="image" src="https://github.com/vitalik/django-ninja/assets/16524518/03157927-3dff-4042-b899-d88116d9e328">
<img width="976" alt="image" src="https://github.com/vitalik/django-ninja/assets/16524518/7d76e98b-0edd-403c-bf58-79ed41f90112">
<img width="1359" alt="image" src="https://github.com/vitalik/django-ninja/assets/16524518/e4fd43ce-fb8a-4e79-bca6-3b5db89a3ee1">
