### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by tboulogne** [vitalik/django-ninja#670]
Hello,

I miss something and need your help to understand it :-).

I have a main application and sub applications. I instantiate Ninja Api, into the main app.

```
# apibase.api
api = NinjaAPI(description="hello", title="LOL")
```

And import api into the sub apps:

```
from apibase.api import api

@api.get("/hola")
def hello(request):
    return f"Hello world {request.user.username}"
```

Get the doc running, but 404 when i try endpoints of sub apps.

If i instantiate a new Ninja API in sub apps :

```
api = NinjaAPI(urls_namespace="background", version="2")

@api.get("/hola")
def hello(request):
    return f"Hello world {request.user.username}"

#urls.py
urlpatterns = [
    path("", api.urls),]
```

Get the endpoints running, but i'm enable to get docs running.
(try with router too...)

Could you explain what is the right way to do it and get all working please :-) ?

Thanks

**Comment by baseplate-admin** [comment]
Did you follow the [docs](https://django-ninja.rest-framework.com/guides/authentication/)? 

If you follow the authentication example the user variable becomes `request.auth`

**Comment by tboulogne** [comment]
@baseplate-admin you point on error i made :-). There is no authentification there... but does not work anyway after fix. Agree with you, errors need to be less generic :-).

**Comment by baseplate-admin** [comment]
Also you will run into another error here. What kind of Authentication Mechanism are you using?

**Comment by tboulogne** [comment]
I did not use auth and remote ```request.user.username```.  So the error did not come from auth for now :-)

**Comment by tboulogne** [comment]
Hello,
I get it works this way :

Into my main application api file, I parse all sub_apps api files to find router and and and them to ninja api.
 
```
import importlib
api = NinjaAPI(description="hello", title="LOL")

for item in settings.INSTALLED_APPS:
    try:
        app = apps.get_app_config(item)
        sub_api = f"{app.path}/dash_api.py"
        if not sub_api.startswith(".") and os.path.exists(sub_api):
            try:
                mod = importlib.import_module(f"{item}.dash_api")
                router = getattr(mod, "router")
                api.add_router("", router)
            except Exception as e:
                logger.error(e)    
    except Exception as e:
       pass
```

Thanks for all.
