### ISSUE TITLE
How to define custom response in the Ninja Pagination

### ISSUE THREAD

**Issue by mohannadirshedat** [vitalik/django-ninja#677]
Hi , 
I want to have a custom response like this : 
```
{
"status":200,
"data":"data",
"msg":"msg"
}

```
my code : 
```
@api.get("/transactions", tags=["Internal Transactions"],response={"data":List[TransactionSchema]})
@pagination
def get_all_transaction(request...):
```
and i cannot do that in django ninja as well as the schema response force to return the data directly 

anyone can help 

thank you

**Comment by vitalik** [comment]
@mohannadirshedat 

you can create [custom pagination class](https://django-ninja.rest-framework.com/guides/response/pagination/#creating-custom-pagination-class)
