### ISSUE TITLE
using graphql with Django-Ninja

### ISSUE THREAD

**Issue by laith43d** [vitalik/django-ninja#68]
Hello Vitalik,

I hope you are fine and doing well.

I have finished migrating two projects to Ninja, it was an awesome experience, performance-wise, the outcome is very noticeable.

I have a project that deals with a somewhat complicated data structure, thus we decided to give the capability to select the required data to the frontend, we used to utilize Django-restql in the past in such cases, but it is very DRF coupled we couldn't use it with Ninja.

Hence, we looked into Graphql and I believe it is the best choice as far as our project's requirements.

My question is, do you have a suggestion on using GraphQL with Ninja, or should we just opt for Graphene or similar projects?

Thanks

**Comment by laith43d** [comment]
BTW, the project is now listed in Django utils section of Awesome list for web tools for Python :) 

https://github.com/ml-tooling/best-of-web-python#django-utilities

**Comment by vitalik** [comment]
Hi @laith43d 

Thank you, I really  glad to to hear that 

as for graphql - well yeah, you should use basically a separate package (Me: +1 for graphene), the only thing you might want to have some common authentication mechanism for graphql and rest
