### ISSUE TITLE
Just a share, Developed a web-admin system with django-ninja

### ISSUE THREAD

**Issue by FuAdmin** [vitalik/django-ninja#689]
Hi @vitalik

This is Jerry, Before I used DRF to develop applications. When I find out about Django-ninja I loved it right away. So I used Django-ninja and Vue3 to develop a web-admin system, welcome you to visit my project and provide some suggestions. Thank you a lot.

_Project address_: [Fuadmin Code](https://github.com/FuAdmin/fu-admin)
_Preview address_: [Fuadmin Preview](http://175.24.184.165:9090/)

BTW, Because the server is in china I don't sure if you can access the website.
Below are some screenshots of the system
![image](https://user-images.githubusercontent.com/108501535/221345234-2bbead8c-888d-4497-bdf4-ebaefc848fc0.png)
![image](https://user-images.githubusercontent.com/108501535/221345268-79e3864e-098a-4645-87eb-9cf216ee3b20.png)
![image](https://user-images.githubusercontent.com/108501535/221345315-4a49631f-527d-4cda-8423-c8f2f8097bfe.png)

**Comment by baseplate-admin** [comment]
Hi Maybe you should post in https://github.com/vitalik/django-ninja/discussions/categories/show-and-tell

**Comment by vitalik** [comment]
@FuAdmin 
Great work!
