### ISSUE TITLE
Using raw SQL queries

### ISSUE THREAD

**Issue by aleksisg** [vitalik/django-ninja#690]
I've got a complex SQL query which I'm unable to convert to use the Django ORM.

Obviously in Django I can run the query with Model.objects.raw() which isn't very elegant, but works.

Is there a way of doing this in Django Ninja? I can call the raw query set but then the validation fails and Pydantic hates me.

Is there an acceptable 'ninja'way of doing this, or am I opening a whole can of worms that I'm better avoiding?

**Comment by vitalik** [comment]
model.raw should work just fine - you just need to convert result of the raw function to list:

```Python

class UserSchema(Schema):
    id: int
    email: str


@api.get('/raw-users', response=list[UserSchema])
def get_users(request):
    raw_qs = User.objects.raw('select id, email, username from auth_user where id > 1')
    return list(raw_qs)  # <------- !

```
