### ISSUE TITLE
ModelSchema with lower camel case results?

### ISSUE THREAD

**Issue by boxydog** [vitalik/django-ninja#697]
**Is your feature request related to a problem? Please describe.**

I have Django models that are snake case, as is traditional (e.g., full_name). The client already specified lower camel case (e.g., fullName). So, every API call I have, I want to use lower camel case.

**Describe the solution you'd like**

I'd like to be able to use alias_generator=to_lower_camel.

This sort of code does not currently work for me:

```
from pydantic.utils import to_lower_camel

from .models import MyObj
from ninja import ModelSchema

class MyObjSchema(ModelSchema):
    class Config:
        model = MyObj
        model_fields = ["id", "name", "full_name"]
        # make names lower camel case
        alias_generator = to_lower_camel
```

It results in `full_name: null` in all the results. If I comment out the alias_generator, it returns `full_name` populated, so I know this is the alias_generator.

**Comment by vitalik** [comment]
@boxydog 

you also need `allow_population_by_field_name`  see docs https://docs.pydantic.dev/usage/model_config/#options

and do not forget `by_alias=True` on the operation

here is an example:


```Python

class UserSchema(ModelSchema):
    class Config:
        model = User
        model_fields = ["id", "email"]
        alias_generator = to_camel
        allow_population_by_field_name = True  # !!!!!! <--------


@api.get("/users", response=list[UserSchema], by_alias=True) # !!!!!! <-------- by_alias
def get_users(request):
    return User.objects.all()

```

results:

```JSON
[
  {
    "Id": 1,
    "Email": "tim@apple.com"
  },
  {
    "Id": 2,
    "Email": "sarah@smith.com"
  },
  {
    "Id": 3,
    "Email": "bar@bar.com"
  }
]

```

**Comment by boxydog** [comment]
Thanks for your quick reply. And it works, so I'm going to close this.

However, a few thoughts. I don't fully understand the solution, and I don't know how I ever would have arrived at it. Some things that might help:

1. Error checking that tells me my config is wrong in the original example. Since "full_name" was always null, it seems pretty clear something is mis-wired, but I don't know enough about django-ninja to know what.

2. Documentation that shows this answer. I would write it myself as a pull request, but I don't know enough. I'm not sure how this situation differs from "Example Camel Case Mode" at https://django-ninja.rest-framework.com/guides/response/config-pydantic/. I feel like it should be next to that page.

I'm happy to open these two things as issues if you think that's a good idea, otherwise I'll leave this as-is.

Thanks again for your work on django-ninja.
