### ISSUE TITLE
Supports Enum Doc ?

### ISSUE THREAD

**Issue by begyy** [vitalik/django-ninja#7]
![image](https://user-images.githubusercontent.com/44405438/89026564-5f655480-d342-11ea-82ab-7954043880f4.png)
![image](https://user-images.githubusercontent.com/44405438/89026598-6c824380-d342-11ea-94ae-09738a11ac75.png)
![image](https://user-images.githubusercontent.com/44405438/89026627-7a37c900-d342-11ea-8f39-409cbd6c55e5.png)

**Comment by vitalik** [comment]
@begyy 
this is fixed - please use latest version ( `pip install django-ninja==0.3.2` )

**Comment by awalasz** [comment]
@vitalik 
Hi, I just found that closed issue. 
As you said the fix is present in the 0.3.2 version but unfortunately not in the latest one (`0.12.3`).
