### ISSUE TITLE
I want to use docs in an offline environment，What is the configuration process?

### ISSUE THREAD

**Issue by sanmaomashi** [vitalik/django-ninja#705]
Is there a mount function like FastAPI?

app = FastAPI(
    title=cfg.PROJECT_NAME,
    openapi_url="/api/v1/openapi.json",
    docs_url=None,
    redoc_url=None,
)

app.mount("/static", StaticFiles(directory="./static"), name="static")

**Comment by baseplate-admin** [comment]
You can use [whitenoise](https://github.com/evansd/whitenoise) to serve files.


But in my opinion use nginx and serve both the application and the static files.

**Comment by sanmaomashi** [comment]
How to use it specifically? Please advise.

**Comment by baseplate-admin** [comment]
Okay share your requirement.txt

**Comment by baseplate-admin** [comment]
https://medium.com/@naufal.ihsan21/how-to-serve-static-files-in-django-using-whitenoise-cda11f9bb643

**Comment by vitalik** [comment]
@sanmaomashi 

If [you add "ninja" to INSTALLED_APPS](https://django-ninja.rest-framework.com/guides/api-docs/?h=cdn#cdn-vs-staticfiles) - it will be hosted "offline" not from CDN
