### ISSUE TITLE
Allow to customize favicon and support redoc x-logo to add logo

### ISSUE THREAD

**Issue by chenatlas** [vitalik/django-ninja#710]
I find it hard to add the x-logo support for redoc/easily add a favicon url

Solution:
adding favicon_url and x_logo_url into `__init__` `main.py` 
```    def __init__(
        favicon_url: str = "",
        x_logo_url: str = "",
```

using `api.favicon_url` in the templates
```  <link rel="shortcut icon" href="{{ app.favicon_url }}">```

and allow more attributes in the schema info section:
```
        info_kwargs = {}
        if api.x_logo_url:
            info_kwargs["x-logo"] = {"url": api.x_logo_url}
        super().__init__(
            [
                ("openapi", "3.0.2"),
                (
                    "info",
                    {
                        "title": api.title,
                        "version": api.version,
                        "description": api.description,
                        **info_kwargs
                    },
                ),
```

testing it locally:
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/10290635/227245955-7436f341-0b20-4236-bbd3-5c33e6f419dc.png">

**Comment by ganong** [comment]
Hope this helps someone in the future. You can add `x-logo` to the `openapi_extra` option when creating the app (at least with current ninja version as of this writing):
```
api = NinjaAPI(
    docs=Redoc(),
    openapi_extra={
        "info": {
            "x-logo": {
                "url": "./path/to/logo.svg",
                "backgroundColor": "#FFFFFF",
                "altText": "App Logo",
            },
        },
    },
)
```

I'm still looking for how to customize the favicon though.
