### ISSUE TITLE
[Feature request] Template url resolve Swagger Docs

### ISSUE THREAD

**Issue by SunsetOrange** [vitalik/django-ninja#712]
I am trying to add a hyperlink on my site to the Swagger docs for the API. However I can't find any information on the web, or in the Ninja documentation on how or what the url resolve name would be for the Swagger docs.
e.g.
`<a href="{% url 'api-1.0.0:docs' %}">API Docs</a>`

I just getting NoReverseMatch errors no matter what I try.
> "Reverse for 'docs' not found. 'docs' is not a valid view function or pattern name."
> "Reverse for 'swagger' not found. 'swagger' is not a valid view function or pattern name."

I'm guessing a url name for the Swagger docs was just never included?
Therefore I'd like to request a way to url resolve the api/docs/ in a template.

**Comment by vitalik** [comment]
@SunsetOrange 

try `api-1.0.0:openapi-view`

**Comment by SunsetOrange** [comment]
Thank you, works great.
Though, I think it would be worth adding it to the [API reference page](https://django-ninja.rest-framework.com/guides/api-docs/), as there are no other referecnces to this trick on the internet.

**Comment by baseplate-admin** [comment]
@SunsetOrange Would you mind closing this issue ?
