### ISSUE TITLE
[`Enhancement`] : Add file upload middleware to docs

### ISSUE THREAD

**Issue by baseplate-admin** [vitalik/django-ninja#716]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when  i cant upload files in `PATCH` method

**Describe the solution you'd like**
I want to contribute this fully functional type hinted async and sync middleware to the docs

```python
from django.utils.decorators import sync_and_async_middleware
from collections.abc import Callable
from django.http import HttpRequest, HttpResponse
from asgiref.sync import sync_to_async

import asyncio


@sync_and_async_middleware
def process_put_patch(get_response: Callable) -> Callable:
    if asyncio.iscoroutinefunction(get_response):

        async def middleware(request: HttpRequest) -> HttpResponse:
            if (
                request.method in ("PUT", "PATCH")
                and request.content_type != "application/json"
            ):
                initial_method = request.method
                request.method = "POST"
                request.META["REQUEST_METHOD"] = "POST"
                await sync_to_async(request._load_post_and_files)()
                request.META["REQUEST_METHOD"] = initial_method
                request.method = initial_method

            return await get_response(request)

    else:

        def middleware(request: HttpRequest) -> HttpResponse:
            if (
                request.method in ("PUT", "PATCH")
                and request.content_type != "application/json"
            ):
                initial_method = request.method
                request.method = "POST"
                request.META["REQUEST_METHOD"] = "POST"
                request._load_post_and_files()
                request.META["REQUEST_METHOD"] = initial_method
                request.method = initial_method

            return get_response(request)

    return middleware
```

**Comment by vitalik** [comment]
@baseplate-admin 

maybe it's even better to add it to code base - so that in docs we can just reference as "include this middleware to be able to handle file uploads with with patch/put requests")

Somewhere under ninja/compatibility/middlewares.py

Could you make PR from this ?

**Comment by baseplate-admin** [comment]
Hey vitalik,

I think the top level ( eg: ninja/middlewares.py ) would be a better place for this no? 

Since some other projects also use top level for middleware. 
1. [`django-axes`](https://github.com/jazzband/django-axes/tree/55bf2956867f87dbed89a3cdbe83f3830fc8f9a4/axes)
2. [`django-defender`](https://github.com/jazzband/django-defender/tree/cc6145b84ec73eca5ed9aac521975cad46b23542/defender)
3. [`django`](https://github.com/django/django/tree/main/django/contrib/sessions)
---

> Could you make PR from this ?

Taking a look. Gimme a few hours

**Comment by baseplate-admin** [comment]
https://github.com/vitalik/django-ninja/pull/719#issuecomment-1493037385
