### ISSUE TITLE
Error 403 when sending POST using AJAX

### ISSUE THREAD

**Issue by Hazqeel09** [vitalik/django-ninja#722]
Previously I implemented it using DRF and it worked fine both in local environment and deploy environment. After I changed to django-ninja, it worked only in local and not deployment.

This is the ajax code inside a js function:
```javascript
$.ajax({
    url: "{% url 'api:check_validity' %}",
    data: {
        customDoasLists: JSON.stringify(allCustomDoas),
        csrfmiddlewaretoken: '{{ csrf_token }}',
    },
    method : "post",
    dataType : "json",
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin', // Do not send CSRF token to another domain.
    csrfmiddlewaretoken: '{% csrf_token %}',
```
This is from api.py that should process the data from the ajax:
```python
api = NinjaAPI(docs_url=None,csrf=True,urls_namespace="api")

    
@api.post("/check_validity",url_name="check_validity",auth=None)
def check_validity(request):
    start = time.process_time()
    model = DoaConfig.mlmodel
    tokenizer = DoaConfig.mltokenizer
    model.to("cpu")
    doa_sentences = json.loads(request.POST.get('customDoasLists'))
    ada_ke_tak = features.check('raqm')

    answer = True
    for text in doa_sentences:
        encoded_input = tokenizer(preprocess_text(text), return_tensors='pt')
        output = model(**encoded_input)
        if output.logits[0][0] > output.logits[0][1]:
            answer = False
    time_taken = time.process_time() - start
    data = {'return_answer':answer,
            'time_taken':str(time_taken),
            'ada_ke_tak':ada_ke_tak}
    return JsonResponse(data)
```
I suspected this is cause from csrf token because I tried it using GET instead of POST and it worked. It also worked previously when using DRF and it also work now when I run it on my laptop. But when I deploy it on AWS EC2, I got 403 error.

Does anyone know how to fix this? Or did I missed any steps?

**Comment by vitalik** [comment]
@Hazqeel09 
any message on 403 ? 403 can be something with permissions of the webserver..

**Comment by Hazqeel09** [comment]
I have changed settings to make debug=True
![image](https://user-images.githubusercontent.com/33782405/228881656-50560dc8-0136-4cb3-8547-ff4a78607f58.png)

**Comment by baseplate-admin** [comment]
Hey its a new settings in django 4.0 that is throwing this error.

Please check the [docs](https://docs.djangoproject.com/en/4.1/ref/settings/#csrf-trusted-origins)
