### ISSUE TITLE
Unprocessable Entity

### ISSUE THREAD

**Issue by w4ugit** [vitalik/django-ninja#727]
Я маю ось такий endpoint

```
@api.post("/save-token")
def saveToken(request, uuid, token):
    model = Number.objects.filter(uuid=uuid).first()
    model.fcmToken = token
    model.save()
    return True
```

При звернені я отримую помилку

```
Unprocessable Entity: /api/save-token
```

Якщо змінити на GET - працює. Щось потрібно додатково налаштувати?

**Comment by chrismaille** [comment]
Hi @w4ugit, sorry i dont speak ukrainian - but looking at the code and the 422 error, my guess you're attempt a GET request on a POST endpoint.

**Comment by w4ugit** [comment]
Yes, I already figured it out. It's all not my attention. I didn't read that POST necessarily needs to define a schema
