### ISSUE TITLE
[BUG] missing endpoints in openapi doc

### ISSUE THREAD

**Issue by rednaks** [vitalik/django-ninja#730]
**Describe the bug**

I noticed that some endpoints are missing in the generated openapi documentation but not sure why ... is it a bug ? if I change the path it works ...

```python

@router.post("/location", url_name="Create Location")
def create_location(request, data: LocationSchemaIn):
    ...


@router.get(
    "/location/{location_id}",
    url_name="Get a Location",
    response=LocationSchemaOut,
)
def get_location(request, location_id: int) -> LocationSchemaOut:
    ...


@router.get(
    "/location", url_name="List All Locations", response=List[LocationSchemaOut]
)
def list_locations(request) -> List[LocationSchemaOut]:
    ...


@router.delete(
    "location/{location_id}", url_name="Delete Location", response=LocationSchemaOut
)
def delete_location(request, location_id: int) -> LocationSchemaOut:
    ...
```

and here is the openapi doc:

![image](https://user-images.githubusercontent.com/1383161/229899605-c32ff7fd-08d1-4ffd-a2fe-e057ef5fddc3.png)

you can see `GET /location/{location_id}` is missing. it's worth mentioning that when I query the endpoint it works !

**Versions:**
 - Python version: 3.10.5
 - Django version: 4.2
 - Django-Ninja version: 0.21.0
 - Pydantic version: 1.10.7

**Comment by baseplate-admin** [comment]
Okay i can repro this.

Note i am also missing the get request Only

**Comment by rednaks** [comment]
is this a regression ? if yes maybe it's worth adding some unit tests ?

**Comment by baseplate-admin** [comment]
> is this a regression ?

I dont think this was ever addressed. ( i just discovered it yesterday )

> if yes maybe it's worth adding some unit tests ?

Due to the war issue the maintainer cant dedicate his time to this project. I am maintaining my own fork with features added upstream.

**Comment by rednaks** [comment]
I wrote a quick test to see if I can reproduce it with unittest, but it seems that it's working fine ...
```python
def test_all_paths_rendered():
    api = NinjaAPI(renderer=TestRenderer)

    @api.post("/1")
    def some_name(
        request,
    ):
        pass

    @api.get("/1")
    def some_name(
        request,
    ):
        pass

    @api.get("/1/{param}")
    def some_name(request, param: int):
        pass

    @api.delete("/1/{param}")
    def some_name(request, param: int):
        pass

    schema = api.get_openapi_schema()

    expected_result = {"/api/1": ["post", "get"], "/api/1/{param}": ["get", "delete"]}
    result = {p: list(schema["paths"][p].keys()) for p in schema["paths"].keys()}
    assert expected_result == result
```

any ideas ?

**Comment by baseplate-admin** [comment]
```python
def test_all_paths_rendered():
    api = NinjaAPI(renderer=TestRenderer)

    @api.post("/1")
    def some_name_create(
        request,
    ):
        pass

    @api.get("/1")
    def some_name_list(
        request,
    ):
        pass

    @api.get("/1/{int:param}")
    def some_name_get_one(request, param: int):
        pass

    @api.delete("/1/{str:param}")
    def some_name_delete(request, param: str):
        pass

    schema = api.get_openapi_schema()

    expected_result = {"/api/1": ["post", "get"], "/api/1/{param}": ["get", "delete"]}
    result = {p: list(schema["paths"][p].keys()) for p in schema["paths"].keys()}
    assert expected_result == result
```

**Comment by rednaks** [comment]
okay this one seems to fail

**Comment by rednaks** [comment]
alright, I made a fix and committed the two tests, hope it will be approved: https://github.com/vitalik/django-ninja/pull/731

**Comment by baseplate-admin** [comment]
> alright, I made a fix and committed the two tests, hope it will be approved: https://github.com/vitalik/django-ninja/pull/731

Thanks for the Pull Request.

<sub>( but i dont know if it will get approved )</sub>

**Comment by vitalik** [comment]
Hi @rednaks 

yeah, seems a bug

for you specific case it's because you did not include the slash:

```
@router.delete(
    "location/{location_id}", url_name="Delete Location", response=LocationSchemaOut
)
def delete_location(request, location_id: int) -> LocationSchemaOut:
    ...
```

For now you can fix it like this

Change: 
```@router.delete("location/{location_id}")```
to
```@router.delete("/location/{location_id}")``` - add a slash before location

@baseplate-admin 

for your case mixing django-path with open api path is not good, like no matter what this example will never work as expected:

```Python
@api.get("/foo/{str:bar}")
def foo1(request, bar: str):
    ...

@api.get("/foo/{int:bar}")
def foo2(request, bar: int):
    ...
```
since Openapi does not support typed params in urls (while Django does)

The PR should work, but I guess perfect solution should change if you try to create case like I showed it should give an error

**Comment by vitalik** [comment]
@rednaks 

one more note - `url_name="Delete Location"` the **url_name** is a django url name which does not recomend using spaces there, what you probably need is `summary="Delete Location"`
