### ISSUE TITLE
Prepare for Pydantic v2 release

### ISSUE THREAD

**Issue by Sesota** [vitalik/django-ninja#733]
Any plans to migrate to Pydantic v2? I know it's still a pre-release but the API changes and best-practices are already outlined [here](https://docs.pydantic.dev/blog/pydantic-v2-alpha/) and they are so many. So I believe to be able to catch up we would need to start from now.

Upgrading the pydantic to the alpha version for an existing django project would cause exceptions raised from the django-ninja code. Since there might be so many incompatibilities, I didn't include all of them here.
 
I would be happy to be able to contribute to this myself. Although currently I don't have a big picture of what should be changed and I fear that I might step in to a wrong way. I would appreciate if @vitalik could share some insight with me (like where in the code is the most-coupled to pydantic v1 and how he plans to change it overally).

**Comment by vitalik** [comment]
Hi @Sesota 

Yes, I already started touching this area. So far it looks like pydantic v2 will make  make a lot of breaking changes that will lead to breaking changes in django-ninja - so most likely djnago-ninja  will become v1.x.x withoout backward compatibility with pydantic1.x and django-ninja0.x

**Comment by vitalik** [comment]
Once I collect all the issues and problem will release some roadmap with issues and potential PRs

**Comment by vitalik** [comment]
as of now I did not find any good replacement for GetterDict in pydantic v2, so any help in that area is welcome

more detials: https://github.com/pydantic/pydantic/issues/5440

**Comment by baseplate-admin** [comment]
@vitalik ,

[Pydantic seems to have a codemod](https://github.com/pydantic/bump-pydantic) that will do the manual labors for you.

Check : https://github.com/pydantic/bump-pydantic/issues/1

For now lets wait and see how things roll out

**Comment by vitalik** [comment]
Unfortunately it's not that easy

**Comment by baseplate-admin** [comment]
> Unfortunately it's not that easy

Figured this would be the case. Lets handle it step by step :) ( you can make an issue with checkboxs  )

**Comment by ethicadev** [comment]
@baseplate-admin Does this bump-pydantic repo help finding the GetterDict alternative? Did you find a time to take a look at the issue?

**Comment by Sesota** [comment]
@baseplate-admin Does this bump-pydantic repo help finding the GetterDict alternative? Did you find a time to take a look at the issue?

**Comment by baseplate-admin** [comment]
> @baseplate-admin Does this bump-pydantic repo help finding the GetterDict alternative? Did you find a time to take a look at the issue?

Hi @Sesota, The repo is less than 1 day old. It doesn't do anything at this point. It promises to auto update  fastapi ( since the creator of the repo is a maintainer of fastapi )

So i was asking @vitalik to maybe look #733 after `bump-pydantic` gets more mature.

**Comment by brianbruggeman** [comment]
I think (?) it's possible to [import the v1 api from pydanticv2](https://github.com/pydantic/pydantic/blob/1cf7cef3dcc01c849d78fc89c5bbf81888f80c81/README.md?plain=1#L27).

**Comment by baseplate-admin** [comment]
> I think (?) it's possible to [import the v1 api from pydanticv2](https://github.com/pydantic/pydantic/blob/1cf7cef3dcc01c849d78fc89c5bbf81888f80c81/README.md?plain=1#L27).

I think vitalik will port everything to `pydantic` v2. So some form of shim is not needed.

**Comment by brianbruggeman** [comment]
I have no doubt that's true.  But I wonder about the timing.  Wouldn't it be easier to take an incremental approach?  That takes some pressure off building something quickly and still makes ninja compatible for those projects that could progress in the mean time.

I'm mostly asking because if anyone wants to use django-ninja in their stack, they're unable to do so and still use pydantic v2.  In a large dependency tree, this could be limiting, and it will only be exacerbated over time as we end up with a mix of different requirements from different libraries.

**Comment by vitalik** [comment]
@brianbruggeman 

since pydantic2 released we have some stability

so far I managed to update all the parts so at least tests are passing - branch: https://github.com/vitalik/django-ninja/tree/pydantic2

since this is somewhat breaking change it will lead to django-ninja to become 1.0 and I will include few more possible breaking changes

but overall my hope is for those who used django-ninja Schema's instead of pydantic models - the migration process should be smooth and might be without any code change

**Comment by landeholt** [comment]
Awesome work! Looking forward to test it out asap 🔥

**Comment by aaronsgithub** [comment]
Hey Vitalik, great work.

I plan on playing around with [1.0alpha1](https://github.com/vitalik/django-ninja/releases/tag/v1.0a1) over the next few days.

Have you identified anything you feel is missing which would be required to promote it from alpha?

If you were to set up some milestones for any gaps you are aware of - I would be happy to contribute 🙂

**Comment by vitalik** [comment]
@aaronsgithub 

I'm planning also adding `Annotated` support and might rework swagger docs engine to be more pluggable

**Comment by alexerhardt** [comment]
Would love to give Django Ninja a whirl, but unfortunately the lack of Pydantic 2 prevents me to adopt it in my current project. The project is new-ish, but it's fully committed to Pydantic v2... I don't even know if it's making use of any of Pydantic's new features, but at this point I'm too afraid to ask. Going with DRF for now but will be happy to try a port to Ninja once you guys support Pydantic v2. 

Just my two cents for @vitalik and the devs, I've been eyeing the project for a while and it looks dope. Thanks for sharing it.

**Comment by emersonfoni** [comment]
@alexerhardt judging by https://github.com/vitalik/django-ninja/releases/tag/v1.0b2, specifically "This is the last change before 1.x release", the 1.0 version that uses Pydantic 2 is about to be released.

**Comment by vitalik** [comment]
@alexerhardt Thank you for the interest in django ninja 

the v1.0 release (with pydantic2 support) is coming in few days, but you can already start adopting it by `pip install django-ninja==1.0b2` which is pretty stable and already used by 10+ projects that I know.

**Comment by wkoot** [comment]
@vitalik is there a tracking issue for the formal v1.0.0 release? 1.0b2 has been out there for nearly a month now :)

**Comment by vitalik** [comment]
v1 is in the wild !

**Comment by brianbruggeman** [comment]
Congratulaations @vitalik Thank you so much!
