### ISSUE TITLE
customizing field names in output

### ISSUE THREAD

**Issue by minusf** [vitalik/django-ninja#739]
I need to override the fields being output in the response to an entirely custom value, so i think the "Example Camel Case mode" is not applicable here. Actually the values I need are the verbose names of the django model's fields.

```python
class A(models.Model):
    a = models.CharField("field a", ...)


class AOut(Schema):
    a: str  # need `"field a": value` in output 
```

**Comment by baseplate-admin** [comment]
Does [resolve](https://django-ninja.rest-framework.com/guides/response/?h=resolve#resolvers) solve your needs?

**Comment by minusf** [comment]
resolvers seem to enable changing values, not field names

**Comment by minusf** [comment]
well the api consumers dont really care about OpenAPI i am afraid :}

i need to output descriptive field names including spaces, and these are valid both in yaml and json...  is it a good idea?  no.  but i am just the messenger...

**Comment by vitalik** [comment]
well... when pydantic v2 will be released - you will be able to set input and output aliases (I think spaces should work there)

for now what you can do is mark stuff where you want spaces to be with 2 underlines (`"__"`) and [then create custom renderer](https://django-ninja.rest-framework.com/guides/response/response-renderers/#create-a-renderer) that will replace those with spaces:

```Python
class AOut(Schema):
    field__a: str = Field(..., alias='a')
#--------^

...
from ninja.renderers import JSONRenderer

class WhitespaceRenderer(JSONRenderer):

    def render(self, *a, **kw):
        return super().render(*a, **kw).replace('_', ' ') # this is not perfect solution but might work

api = NinjaAPI(renderer=WhitespaceRenderer())
```

**Comment by minusf** [comment]
thanks for the creativity but this is a bit too many hoops to jump over :D  i mean with all these kludges using a library will sadly soon be similar to simply using handrolled functions... it is not ninja's job to bend over trying to accomodate non-sensible schema's. i think this can be closed. thanks
