### ISSUE TITLE
Implementing User Authentication

### ISSUE THREAD

**Issue by KrystianMaccs** [vitalik/django-ninja#741]
### Discussed in https://github.com/vitalik/django-ninja/discussions/740

<div type='discussions-op-text'>

<sup>Originally posted by **KrystianMaccs** April 14, 2023</sup>
Hi Vitaliy, I just got started with django-ninja this week and so far it's been good and I am getting a hang of it. However, I have a little trouble implementing User Authentication and Authorization. How does it work? I have a User model already and schema. What do I do from here? Meanwhile, this is my repo: https://github.com/KrystianMaccs/cinema.git</div>

**Comment by vitalik** [comment]
@KrystianMaccs 

well the easiest is just to use standard django auth

```Python
from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
from ninja import NinjaAPI, Schema
from ninja.errors import HttpError
from ninja.security import django_auth # !!


api = NinjaAPI(auth=django_auth)  # !!!


class AuthSchema(Schema):
    username: str
    password: str


@api.post('/login', auth=None)
@csrf_exempt
def login(request, payload: AuthSchema):
    user = auth.authenticate(request, username=payload.username, password=payload.password)
    if not user:
        return HttpError(400, 'invalid username or password')
    auth.login(request, user)
    return {'success': True)


```

**Comment by KrystianMaccs** [comment]
Okay. And the same applies to register, and logout endpoints?

**Comment by KrystianMaccs** [comment]
> ### Discussed in #740
> Originally posted by **KrystianMaccs** April 14, 2023 Hi Vitaliy, I just got started with django-ninja this week and so far it's been good and I am getting a hang of it. However, I have a little trouble implementing User Authentication and Authorization. How does it work? I have a User model already and schema. What do I do from here? Meanwhile, this is my repo: https://github.com/KrystianMaccs/cinema.git

And what if I want to implement authorisation on another app somewhere, the same logic goes?

**Comment by KrystianMaccs** [comment]
Alright. Thanks a lot.

**Comment by KrystianMaccs** [comment]
I added another router to my project api and got this error when I ran the
command: r"aise ConfigError(
ninja.errors.ConfigError: Router@'/movies/' has already been attached to
API NinjaAPI:1.0.0". I don't get this error when I comment out the
users_api router.

urls.py
from ninja import NinjaAPI
from apps.movies.api import router as movies_router
from apps.users.api import api as users_api

api = NinjaAPI()
api.add_router("/movies/", movies_router)
api.add_router("/users/", users_api)

users.api.py

from django.contrib import auth
from django.views.decorators.csrf import csrf_exempt
from ninja import NinjaAPI, Schema
from ninja.errors import HttpError
from ninja.security import django_auth
from .schema import UserSchema


api = NinjaAPI(auth=django_auth)


@api.post('/login', auth=None)
@csrf_exempt
def login(request, payload: UserSchema):
user = auth.authenticate(request, username=payload.username, password
=payload.password)
if not user:
raise HttpError(400, 'invalid username or password')
auth.login(request, user)
return {'success': True}


@api.post('/register', auth=None)
def register(request, payload: UserSchema):
user = auth.models.User.objects.create_user(
email=payload.email,
username=payload.username,
first_name=payload.first_name,
last_name=payload.last_name,
password=payload.password
)
auth.login(request, user)
return {'success': True}


@api.post('/logout')
def logout(request):
auth.logout(request)
return {'success': True}

**Comment by baseplate-admin** [comment]
@KrystianMaccs unfortunately it's impossible to tell what went wrong here. You have to comment out some lines to get the actual error. Please check #684 


---

> ninja.errors.ConfigError: Router@'/movies/' has already been attached to
> API NinjaAPI:1.0.0". I don't get this error when I comment out the
> users_api router.

@vitalik same error i got in https://github.com/vitalik/django-ninja/issues/684#issuecomment-1505509879

**Comment by KrystianMaccs** [comment]
Ok, I'll check it out.

**Comment by baseplate-admin** [comment]
@KrystianMaccs , The error is due to some mistake you made during configuration. To fix it you have to comment out https://github.com/vitalik/django-ninja/blob/6ed724e24323647200f63593864c6074fc0827d5/ninja/router.py#L362-L369

**Comment by baseplate-admin** [comment]
@vitalik , We should close this
