### ISSUE TITLE
Support for path params in routers

### ISSUE THREAD

**Issue by calderwoodra** [vitalik/django-ninja#742]
### Is your feature request related to a problem? Please describe.
Let's say our API looks like this:
```
/api/users/
/api/company/{id}/
/api/company/{id}/foo/...
/api/company/{id}/bar/...
/api/company/{id}/baz/...
```

Each of the `...` could expand to dozens of APIs, so each `@router.get(...)` must declare the same substring `company/{id}` which is pretty repetative.
 

### Describe the solution you'd like
It would be nice if we could declare the `company/{id}/` company id as a path param in the router: `api.add_router('company/{id}/', router)`

**Comment by vitalik** [comment]
@calderwoodra 

Well that depends if you actaully need id inside your view function... technically it works:

```Python
router = Router()

@router.get('/test')
def test(request):
    return {'company': 'hello'}

api = NinjaAPI()
api.add_router('/company/{id}/', router)

```
but you do not have access to id variable in that case

if you want that you can mark it as Path to correctly read it (and OpenAPI swagger docs will also pass it to you):

```Python
from ninja import Path

@router.get('/test')
def test(request, id: int = Path(...)):
    return {'company': id}
```

but you will have to type  even more words in this case... 

to me the starndard way looks more clean:

```Python
router = Router()

@router.get('/{id}/foo')
def foo(request, id: int):
    return {'company': id, 'action': 'foo'}

@router.get('/{id}/bar')
def bar(request, id: int):
    return {'company': id, 'action': 'bar'}

api.add_router('/company', router)
```

**Comment by baseplate-admin** [comment]
Assuming @calderwoodra, your issue is fixed. Would you mind closing this issue?
