### ISSUE TITLE
Support custom decorators either before or after django-ninja decorators.

### ISSUE THREAD

**Issue by calderwoodra** [vitalik/django-ninja#743]
### Is your feature request related to a problem? Please describe.
Prior to django-ninja, I scoped my requests like so:
```
@user_scoped
@company_scoped
def foo(request, user, company, **kwargs):
  # ....
```

With django-ninja, this isn't supported.

### Describe the solution you'd like
It would be nice if I could do the following:
```
@router.get('company/{company_id}/foo')
@user_scoped
@company_scoped
def foo_request_method(user, company, company_id: int):
  # ....
```

**Comment by baseplate-admin** [comment]
https://github.com/vitalik/django-ninja/issues/725#issuecomment-1505449961

> (I'm working on a special decorator that will expose actual view function decoration)

**Comment by calderwoodra** [comment]
Thanks - I'll check back in a few weeks (months?) and resume my migration to django-ninja!

**Comment by baseplate-admin** [comment]
> Thanks - I'll check back in a few weeks (months?) and resume my migration to django-ninja!

I will ping you then :) ( or maybe you can subscribe to the main issue ? )

**Comment by vitalik** [comment]
Hi @calderwoodra 

could you describe what do you do inside `@user_scoped` `@company_scoped` ?

**Comment by calderwoodra** [comment]
@vitalik 

In @user_scoped, I parse a jwt token in a custom header, validate it and pass a user kwarg to the next function.

In @company_scoped, it accepts the user object and a company ID path param and validates the user is a member of that company. If everything checks out, it passes the company as a kwarg to the next function.

**Comment by vitalik** [comment]
@calderwoodra 

what you do in user_scoped/company_scoped looks more like stuff you can actually do in [authentication/authorization mechanizm](https://django-ninja.rest-framework.com/guides/authentication/#custom-function)


```Python
def user_scoped(request):
    if request.META["x-user-token"] == "123":
        request.user = User.object.get(id=123)
        return True

def company_scoped(request):
    if not user_scoped(request):
         return None

    company_id = request.path.split('/')[3]
    company = Company.objects.get(id=company_id)
    if request.user.has_access_to(company):
           request.company = company
           return True


# then do:

@router.get('/company/{company_id}/foo', auth=company_scoped)
def foo_request_method(request, company_id: int):
    return {'company': str(request.company), 'user': str(request.user)}


@router.get('/user/bar', auth=user_scoped)
def some_user_method(request, company_id: int):
    return {'user': str(request.user)}


```

theniccally you can make that decorator that will replace some arguments that you will pass - but that seems too much black magic

**Comment by calderwoodra** [comment]
Smart - I'll give that a shot! Thanks

**Comment by dan83g** [comment]
Hi!
I also need to make a decorator (@remove_vary_header) for specific endpoints in order to remove the "Vary" HTTP header.
Thanks
