### ISSUE TITLE
Drop python 3.6 - 3.7 and django 2.

### ISSUE THREAD

**Issue by baseplate-admin** [vitalik/django-ninja#744]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i see EOL dependencies are in `pyproject.toml`

**Describe the solution you'd like**
1. Drop every EOL or soon to be EOL python version. ( `3.6` - `3.7` )
2. Bump django dependency to 3.2 as django 2 is unsupported at this point.
 

Reasoning : 
1. We can directly support modern django features ( eg : `sync_and_async_middlewares` )
2. We can get access to Async ORM ( which is unsupported in django 2.0 )
3. ...
I think its a good time to address this as `django-ninja` is moving to a v1 release

**Comment by baseplate-admin** [comment]
@vitalik ,

What's your take on this ?

**Comment by skokado** [comment]
+1

**Comment by vitalik** [comment]
personally I do not see reason to drop django 2 - there are just few compatibility wrappers  (the async views are already used heavily alot by the projects I'm keeping eye on)


python 3.6 will be dropped with pydantic2

python 3.7 most likely will stay (basically what pydatic supports will be supported by django ninja) - I see in statas some persentage is still using 3.7

**Comment by l1b3r** [comment]
JFYI Pydantic dropped support for Python 3.7 in their version [2.6.0](https://github.com/pydantic/pydantic/blob/main/HISTORY.md#v260-2024-01-23) (2024-01-23) and Python 3.8 in version [2.11.0](https://pydantic.dev/articles/pydantic-v2-11-release#python-38-support-dropped) (2025-03-27)
