### ISSUE TITLE
Reference a schema in itself

### ISSUE THREAD

**Issue by Ash-Crow** [vitalik/django-ninja#75]
Sometimes a model references itself as a foreign key.

For example, in my Django Models file, I define that an Organization can be part of another organization :

```
class Organization(Model):
[...]
    part_of = models.ForeignKey(
        "Organization", blank=True, on_delete=models.SET_NULL, null=True
    )
```
But if I try to replicate it in a Schema :
```
class OrganizationSchema(Schema):
[...]
    part_of: OrganizationSchema = None

```
I get a NameError:
```
NameError: name 'OrganizationSchema' is not defined
```

I checked the documentation but could not find how to do this.

**Comment by vitalik** [comment]
Hi @Ash-Crow 

you can reference to self using the [pydantic Self-referencing Models](https://pydantic-docs.helpmanual.io/usage/postponed_annotations/#self-referencing-models)

basically for your case it something like this:

```Python
class OrgSchema(Schema):
    title: str
    part_of: 'OrgSchema' = None     #!! note the type in quotes here !!


OrgSchema.update_forward_refs()  # !!! this is important as well 


@api.get('/organizations', response=List[OrgSchema])
def list_organizations(request):
    return Organization.objects.all()
```

important notes - type must be in quotes

and you need to call `YourSchema.update_forward_refs()`


I will keep this ticket open to add documentation

**Comment by vitalik** [comment]
[documented](https://django-ninja.rest-framework.com/tutorial/response-schema/#self-referencing-schemes)

**Comment by vitalik** [comment]
@FabianClemenz 

1) I think the `|` operator might not work with cirulcal typing - so you probably need to explicity tell that is's Union:
```Python
class SomeOther(Schema):
    uid: int

class TreeSchema(Schema):
    id: int
    name: str
    children: list[Union["TreeSchema", SomeOther]] = []
#                    ^------- !!!!!
```

as for schema - I think this is the way swagger UI renders it - otherwise it will be infinite loop in dom or something... not sure but if you look into generated schema - the reference to itself is present:

```Json
{
    "components": {
        "schemas": {
            "TreeSchema": {
                "properties": {
                    "children": {
                        "default": [],
                        "items": {
                            "$ref": "#/components/schemas/TreeSchema" <--------------
                        },
                        "title": "Children",
                        "type": "array"
                    },
                    "id": {
                        "title": "Id",
                        "type": "integer"
                    },
                    "name": {
                        "title": "Name",
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name"
                ],
                "title": "TreeSchema",
                "type": "object"
            }
        }
    },

```

**Comment by FabianClemenz** [comment]
@vitalik Thanks a lot that solved it for me :)

Ok sure - it would render infinitely - could have thought of that

**Comment by emamzadealireza** [comment]
> OrgSchema.update_forward_refs() 

Hi @vitalik 
sorry to add comment to closed issue

thanks a lot for your guide and attached doc

but i' ve defined a modelschema with self-reference without code that quote replied

i think maybe it is not necessary, also there is no sign of this code in attached doc too.

thanks guy
