### ISSUE TITLE
Typo "@paginage" should be "@paginate"

### ISSUE THREAD

**Issue by MrEcho92** [vitalik/django-ninja#750]
There is typo in paginate decorator doc. It should be _paginate_ as referenced in [django ninja doc](https://django-ninja.rest-framework.com/guides/response/pagination/). 

Error locations:
https://github.com/vitalik/django-ninja/blob/1866e275ede76f891684507e113e61bfdebe8f8f/ninja/pagination.py#L99 & https://github.com/vitalik/django-ninja/blob/1866e275ede76f891684507e113e61bfdebe8f8f/ninja/pagination.py#L105

**Comment by baseplate-admin** [comment]
Good find..

**Comment by baseplate-admin** [comment]
Would you like to do a PR ?

cc : @vitalik

**Comment by MrEcho92** [comment]
@baseplate-admin, I tried committing a fix but not allowed to (getting permission 403). Could you forward guideline to create a PR?

**Comment by baseplate-admin** [comment]
First [Fork this repo](https://github.com/vitalik/django-ninja/fork)

There should be a create fork button.
![image](https://user-images.githubusercontent.com/61817579/233847839-74516f27-465c-4d7b-9359-73b04b4bc1c8.png)


Click it.
Then go to your [repo ](https://github.com/MrEcho92/django-ninja). Commit the changes and click on [compare](https://github.com/vitalik/django-ninja/compare)

Click on compare across forks and find your repo.

![image](https://user-images.githubusercontent.com/61817579/233847900-e34011fd-a0aa-4cad-aaf5-e5f040ac242d.png)

**Comment by MrEcho92** [comment]
@baseplate-admin Thank you! PR raised [pr752](https://github.com/vitalik/django-ninja/pull/752)

**Comment by baseplate-admin** [comment]
Looks good to me :)
