### ISSUE TITLE
models question

### ISSUE THREAD

**Issue by sanmaomashi** [vitalik/django-ninja#751]
"I defined a 'data' field in my ModelSchema with the following definition: 
`
class SegModels(models.Model):
data: List[Dict[str, Any]] = Field(..., description="Text data to be tokenized", min_items=1, error_messages={"value_error.list.min_items": "Text data to be tokenized"})

    @validator("data", each_item=True)
    def validate_data_item(cls, item):
        if "text" not in item:
            raise ValidationError(message="data 中的每个项目都必须包含一个 'text' 键")
        return item
`
 I'm using this field in my FastAPI application's request URLs with the following code: 
`
@seg_router.post("/test")
async def upload(request, params: SegItem= Form(...), file: Optional[UploadedFile] = File(None)):
`
However, no matter how I pass the parameters, I get an error and the Swagger UI interface shows the parameters as '{}'. Can someone please help me with this issue?"

I hope this helps!

**Comment by baseplate-admin** [comment]
`django-ninja` doesn’t support `validator`. 

It will probably after https://github.com/vitalik/django-ninja/issues/733

**Comment by vitalik** [comment]
Hi @sanmaomashi 

basically when you use files - you enforced to used multipart formdata - wehre each item in a form is a string (that later need to be parsed)

you can use pydantic Json type to atomatically do that - but the container type you will have to validate - this should work for you case I think:

```Python
from ninja import Schema
from pydantic import validator, Json, Field


class SegItem(Schema):
    data: Json = Field( # <----- !!!!!!
        ...,
        description="Text data to be tokenized",
        error_messages={"value_error.list.min_items": "Text data to be tokenized"},
    )

    @validator("data")
    def validate_data_item(cls, items):
        if not isinstance(items, list):
            raise ValueError('data must be a list')
        for item in items:
            if "text" not in item:
                raise ValueError("data 中的每个项目都必须包含一个 'text' 键")
        return items

```

**Comment by vitalik** [comment]
also `Json[List[Dict]]` might work as well
