### ISSUE TITLE
How to use the PATCH method to update only some fields

### ISSUE THREAD

**Issue by john2022wick** [vitalik/django-ninja#753]
Hello everyone, I am a beginner and I am very grateful for this great project. I am trying to learn and use it.

Currently, I have encountered a problem:
I am trying to write an API for updating data, and of course the Schema is generated by the Model.
My expected working logic is to pass in partial fields through the HTTP PATCH method and then only update the incoming fields.

model
```python
class Person(models.Model):
    name = models.CharField(max_length=254)
    ages = models.IntegerField(default=0)
    desc = models.TextField(blank=True)
```
schema
```python
class PersonSchema(ModelSchema):
    class Config:
        model = Person
        model_fields = "__all__"
```
api
```python
@api.put("/person/{person_id}")
def update_person(request, person_id: int, payload: PersonSchema):
    ...
    return {"msg": 'success'}
```

When I submit the data `{'age':18}`, a validation failure exception occurs, indicating that `name` and `desc` are required:
```
      "msg": "field required",
      "type": "value_error.missing"
```

After some attempts, I think that ModelSchema sets the model's fields as required. 
If I manually set the fields in the Schema as `Optional`, it can successfully pass the validation.

But when a model has many fields, it will be a very tedious and difficult to maintain task to set them one by one as `Optional`.

Is there any way to configure a ModelSchema as globally Optional?

**Comment by vitalik** [comment]
Hi @john2022wick 

yeah, good catch - this is actually often needed functionality, I guess will add some option to Config for it

as of now you can add this utility function to make your schema all optional:

```Python

def make_optional(schema_cls):
    for field in schema_cls.__fields__.values():
        if field.required:
            field.required = False
            field.default = None


make_optional(PersonSchema) 

@api.patch("/path")
def patch_person(request, poayload: PersonSchema):
    return poayload.dict(exclude_unset=True) # !<---- do not forget exclude_unset
```

**Comment by john2022wick** [comment]
@vitalik 
Thank you first!
You are so active and enthusiastic that I received your help in just a few hours.

During this time, I was still constantly looking for solutions. I found a package called `ninja-schema`, which achieved setting the schema to globally optional fields by configuring `optional = "__all__"` for `Config`. Like this:
```python
class PersonSchema(ModelSchema):
    class Config:
        model = Person
        model_fields = "__all__"
        optional = "__all__"
```

This is very valuable for reference.

**Comment by skokado** [comment]
@john2022wick  Hi, I'm one of who impressed by this repository :)

Following is my idea of ModelSchema usage for partial-update.

```python
class PersonSchema(ModelSchema):
    class Config:
        model = Person
        model_fields = "__all__"
        optional_fields = ("name", "age", "desc") # <- here


# then all of the following will be valid.
PersonSchema(id=1, name="Bob")
PersonSchema(id=1, age=21)
PersonSchema(id=1, desc="exam passed")
```

However, allowing the value `"__all__"` for "optional_fields` will be not good
if set `model_fields = "__all__"` then ModelSchema handles `id` primary-key field implicitly.
It will be necessary the primary-key field when partial update.

**Comment by baseplate-admin** [comment]
Why don't we use `extra_kwargs` to modify the fields as needed like `django-rest-framework` ?

For example

```python
class PersonSchema(ModelSchema):
    class Config:
        model = Person
        model_fields = "__all__"
        extra_kwargs = {
                'username': {
                    'required':False
                    "alias": 'user.name'
                }
        }
 ```

**Comment by skokado** [comment]
@baseplate-admin Great idea.
In `extra_kwargs` of DRF, allowed kwargs are based on `Serializer` class of DRF.

In case of `ninja.ModelSchema`, is it better to be based on the kwargs of Django Model ? or `pydantic.Field` ?
`pydantic.Field` does not allow `required` or `null` for kwargs, so control for optional might be a bit complicated.
https://github.com/pydantic/pydantic/blob/ca8069811a30c271c9ee0b36d455c9c0adb458a0/pydantic/fields.py#L492-L525

**Comment by skokado** [comment]
@baseplate-admin Great idea.
In `extra_kwargs` of DRF, allowed kwargs are based on `Serializer` class of DRF.

In case of `ninja.ModelSchema`, is it better to be based on the kwargs of Django Model ? or `pydantic.Field` ?
`pydantic.Field` does not allow `required` or `null` for kwargs, so control for optional might be a bit complicated.
https://github.com/pydantic/pydantic/blob/ca8069811a30c271c9ee0b36d455c9c0adb458a0/pydantic/fields.py#L492-L525

**Comment by vitalik** [comment]
hi @john2022wick 

please check on version 0.22.1

now you should be able to do this:
```Python
class PersonSchema(ModelSchema):
    class Config:
        model = Person
        model_fields = "__all__"
        model_fields_optional = '__all__' # or model_fields_optional = ['only_some']
```

[docs](https://django-ninja.rest-framework.com/guides/response/django-pydantic/#making-fields-optional)

**Comment by ddahan** [comment]
Hi there!

To help others, I suggest adding a note in [the CRUD example update section](https://django-ninja.dev/tutorial/other/crud/#update) for partial updates, as the `exclude_unset=True` pattern is not easy to find out.
