### ISSUE TITLE
Update request.auth instead of request.user

### ISSUE THREAD

**Issue by ianrodrigues** [vitalik/django-ninja#76]
I was wondering why did you decide to set `request.auth` instead of `request.user` during the authentication step here:

https://github.com/vitalik/django-ninja/blob/master/ninja/operation.py#L100

When I **intuitively** try to access `request.user` I always get `AnonymousUser`. I mean, I always saw that other libraries set `request.user`, and when necessary they set some other `request` attributes besides `user`.

Is that really intended? What is the reason for that?

Thanks for your work on this library, by the way. Nice job!

**Comment by vitalik** [comment]
Hi @ianrodrigues 
> Is that really intended? What is the reason for that?
yes, at the moment it it intended

because for APIs your auth entity is now always a user, can be token, can be boolean, etc

if you use django-ninja  as a backend for javascript client on same domain - you can use [django_session](https://django-ninja.rest-framework.com/tutorial/authentication/#intro) auth , and then you will have `request.user` available as expected

but on the other hand, I will think maybe it makes sense to have  request auth attribute configurable somehow...

**Comment by ianrodrigues** [comment]
It makes sense. However, I do believe we should have that configurable somehow, too.

In my case, `django-ninja` is both a backend for a React SPA (authenticating using Bearer) and a CLI tool (authenticating using Personal Access Token).

**Comment by vitalik** [comment]
probably implementation will be the following

```Python
class MyAuth(HttpBearer):
    request_attribute = 'user'   # !!!

    def authenticate(self, ...):
            return some_object
```

**Comment by Fingel** [comment]
I solved this issue of request.user not being available by adding a call to django's `login` method to my Ninja auth class:

```python
from users.models import User
from ninja.security import APIKeyHeader, django_auth
from django.contrib.auth import login


class ApiKey(APIKeyHeader):
    param_name = 'X-API-Key'

    def authenticate(self, request, key):
        user = User.objects.filter(token__key=key).first()
        if user is not None:
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')

        return user
```

The token stuff is my own implementation, but basically on the user = User.objects line, you want to find the user in the database given the key that was supplied.

I hope this helps anyone else facing this situation.

**Comment by quroom** [comment]
> I solved this issue of request.user not being available by adding a call to django's `login` method to my Ninja auth class:
> 
> ```python
> from users.models import User
> from ninja.security import APIKeyHeader, django_auth
> from django.contrib.auth import login
> 
> 
> class ApiKey(APIKeyHeader):
>     param_name = 'X-API-Key'
> 
>     def authenticate(self, request, key):
>         user = User.objects.filter(token__key=key).first()
>         if user is not None:
>             login(request, user, backend='django.contrib.auth.backends.ModelBackend')
> 
>         return user
> ```
> 
> The token stuff is my own implementation, but basically on the user = User.objects line, you want to find the user in the database given the key that was supplied.
> 
> I hope this helps anyone else facing this situation.

I don't think you need to put `` login(request, user, backend='django.contrib.auth.backends.ModelBackend')```
Simply we can access request.user instead request.auth add this ``` request.user = user ```
If you put login function there, each api call login again and again
