### ISSUE TITLE
[BUG] 0.22.0 release breaks static docs UI, 0.21.0 still works properly.

### ISSUE THREAD

**Issue by bubthegreat** [vitalik/django-ninja#768]
**Describe the bug**
TypeError: Cannot read properties of undefined (reading 'replace') when submitting responses in 0.22.0 for OpenAPI docs UI - this only occurs when using the INSTALLED_APPS += ('ninja') to serve the files statically - when using the web based version there's no issue.  Reverting to 0.21.0 fixes this.

Expected behavior: 
<img width="1280" alt="image" src="https://github.com/vitalik/django-ninja/assets/12198817/8dfaaa04-5af0-43de-8085-9bfdb5544a7a">

Actual behavior:
<img width="1280" alt="image" src="https://github.com/vitalik/django-ninja/assets/12198817/933bcd09-f9c8-4f8e-a7bd-8048ae43ffec">

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.x
 - Django-Ninja version: 0.22.0

**Comment by baseplate-admin** [comment]
Probably related to https://github.com/vitalik/django-ninja/pull/695

**Comment by vitalik** [comment]
@bubthegreat 

fixed - please try on 0.22.1

**Comment by bubthegreat** [comment]
Verified, thanks! 
![image](https://github.com/vitalik/django-ninja/assets/12198817/07bc6a3a-592a-48c3-a4bc-663c655f0ffc)
