### ISSUE TITLE
[BUG] The latest Django-ninja (0.22.1) doesn't support the latest  Django-ninja (0.18.8)

### ISSUE THREAD

**Issue by jankrnavek** [vitalik/django-ninja#769]
The latest Django-ninja (0.22.1) doesn't support the latest  Django-ninja (0.18.8) in connection with Poetry.

 - Python version: 3.11.3
 - Django version: 4.2
 - Django-Ninja version: 0.22.1

--------------------------------------------------------------------------------------------------------------
Poetry output

(app1 backend-py3.11) PS C:\git\app1> poetry update
Updating dependencies
Resolving dependencies...

Because django-ninja-extra (0.18.8) depends on django-ninja (0.21.0)
 and no versions of django-ninja-extra match >0.18.8,<0.19.0, django-ninja-extra (>=0.18.8,<0.19.0) requires django-ninja (0.21.0).
So, because app1 backend depends on both django-ninja (^0.22) and django-ninja-extra (^0.18.8), version solving failed.

**Comment by baseplate-admin** [comment]
`django-ninja-extra` is the conflicting package. 


CC: @eadwinCode

**Comment by jankrnavek** [comment]
Solved with latest django-ninja-extra package.
