### ISSUE TITLE
Raise 403 via AuthBearer()

### ISSUE THREAD

**Issue by patagoniapy** [vitalik/django-ninja#771]
Whenever logic fails in the AuthBearer() flow, instead of returning None, which currently results in a 500 error, I want to return a 403 error.

Here is the AuthBearer() flow I'm using: 

```python
class AuthBearer(HttpBearer):
    async def authenticate(self, request, token):
        if request.headers["Organization-Uuid"] is None:
            return None
        else:
            try:
                key = await Token.objects.select_related('user').aget(pk=token)
                try:
                    org_uuid = uuid.UUID(request.headers["Organization-Uuid"])
                    await UserOrganization.objects.aget(user=key.user, organization__organization_uuid=org_uuid)
                    return key.user
                except UserOrganization.DoesNotExist:
                    return None
            except Token.DoesNotExist:
                return None


api = NinjaAPI(auth=AuthBearer())
```

**Comment by vitalik** [comment]
@patagoniapy could you please provide your ninja version and python version ?

**Comment by patagoniapy** [comment]
Hi @vitalik , I am running `0.22.1` of ninja and python `3.9.16`

**Comment by ankushagar99** [comment]
You can raise httperror with 403 as status code with your message. I have done it and it's working

**Comment by patagoniapy** [comment]
Thanks @ankushagar99 . Could you provide an example of how you've done it previously? I've tried httperror but no luck

**Comment by vitalik** [comment]
@patagoniapy you might need to remove async for now from AuthBearer as it now not fully supported yet

**Comment by ankushagar99** [comment]
@patagoniapy I did this and it's working fine for me 
```class JwtAuth(JWTBaseAuthentication, APIKeyCookie):
    def authenticate(self, request, key):
        token = request.COOKIES.get("access")
        if token is not None:
            try:
                AccessToken(token)
                user = self.jwt_authenticate(request, token=token)
                return user
            except TokenError:
                raise HttpError(401, "Something went wrong, please login again")
        raise HttpError(403, "No access cookie not found")```

**Comment by patagoniapy** [comment]
I just revisited the code after not being in it a while and using `HttpError` with `async` works just fine for me so not totally sure what I was doing wrong before. I'm going to close this out now, thanks everyone.
