### ISSUE TITLE
Conditonally adding/including an endpoint

### ISSUE THREAD

**Issue by Svenito** [vitalik/django-ninja#773]
Using the `@api.get` etc decorators, is it possible to put a specific endpoint behind a feature flag that can be turned off and on at run time?
Conditional decorators are only evaluated once, so they won't change behaviour at runtime.

Essentially something like

```
@api.get('/path/', include_if=Settings.IS_ENABLED)
def method():
```

**Comment by OtherBarry** [comment]
You could use the `deprecated `or `include_in_schema `flags if you just want to change how it appears in the documentation.

If you actually want the route to not exist, you could presumably just do:

```
if Settings.IS_ENABLED:
    @api.get('/path/')
    def method():
        ...
```

Given that's not very pretty, I assume you could do something similar with a custom decorator that either conditionally doesn't call the inner function (if wrapping the @api method) or conditionally returns 404 (if getting wrapped by the @api method)

**Comment by Svenito** [comment]
Thank you the reply. 
I am look to not just removing from docs, but basically omitting it entirely from the URLs in the router. As if it weren't decorated. 
The example provided will work once, but if the application is running, and the user changes the settings, it doesn't update the routes in the API instance as the endpoint is already added or not. the conditional doesn't get evaluated again.

I could raise a 404 but that returns an API 404 (JSON formatted), not a Django page 404 (html). 
IMO an API 404 says that "I cannot find the resource you wanted to get" whereas the Django 404 is akin to "This page/endpoint isn't known to me"

**Comment by vitalik** [comment]
@Svenito you can do it with some decorator that will raise 404 if feature is not ON:

```Python
from functools import wraps


FEATURE = True  # Global setting object

def enable_with_feature(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if FEATURE:
            return func(*args, **kwargs)
        else:
            raise Http404

    return wrapper


@api.post("/topggle-feature")
def toggle_feature(request):
    global FEATURE
    FEATURE = not FEATURE
    return {"feature": FEATURE}


@api.get("/special-operation")
@enable_with_feature  # <-------------- !!!
def special_operation(request):
    return {"hello": "world"}
```

if you also need to hide it from openapi documetaion schema - just override  `get_openapi_schema`

```Python

class ApiWithFeature(NinjaAPI):
    def get_openapi_schema(self):
        schema = super().get_openapi_schema()
        if not FEATURE:
            del schema['paths']['/api/special-operation']
        return schema


api = ApiWithFeature()

```

**Comment by Svenito** [comment]
Thank you. This seems to perform the same as if you have a conditional in the body of the function and raise Http404 which is what we are doing now. 

We did however miss the latter part of your reply out, namely removing the endpoint from the docs as well in case the feature is off.

Cheers
