### ISSUE TITLE
Failed to load API definition - /api/docs

### ISSUE THREAD

**Issue by jankrnavek** [vitalik/django-ninja#774]
On /api/docs endpoint i get this html error.

Python version: 3.11.3
Django version: 4.2.2
Django-Ninja version: 0.22.1
Django-Ninja-Extra 0.18.9

With previous version everthing works fine.
(previous setup: Django-Ninja version: 0.21.x, Django-Ninja-Extra 0.18.8)

```
Failed to load API definition.
Errors
Fetch error
Internal Server Error /api/openapi.json
```

**Comment by jankrnavek** [comment]
![image](https://github.com/vitalik/django-ninja/assets/13521021/dac1cf7a-bdb1-44c2-80c4-da8c5e7d5998)

**Comment by M3te0r** [comment]
Hi @vitalik I had the same error, that was caused by a 3rd party django lib having a model field with a verbose_name property as a gettext str.
I had a ModelSchema with such model, and managed to avoid this using a plain Schema, but this does not fix the issue here.

I think this is caused by the `ninja.orm.fields.title_if_lower` function being decorated by `@keep_lazy_text `

**Comment by vitalik** [comment]
Hi @SmileyChris 

do you remember why keep_lazy is used here ?
```py
@keep_lazy_text
def title_if_lower(s: str) -> str:
    if s == s.lower():
        return s.title()
    return s
```

**Comment by vitalik** [comment]
@M3te0r @jankrnavek Please try latest version (0.22.2)

**Comment by jankrnavek** [comment]
Updating django-ninja-extra is needed as well..

**Comment by jankrnavek** [comment]
Everything works alright.
Thank you.

**Comment by davidroberthoare** [comment]
I'm having this same error. I've tried upgrading the whole site to django 4.2.3, as well as the most recent django ninja and django-ninja-extras.... 
Can't get to the Docs because having an 'UploadedFile' in any of my endpoints breaks it

**Comment by vitalik** [comment]
@davidroberthoare some exception or definition of "endpoints breaks it" would be nice
