### ISSUE TITLE
Jwt authentication with oauth

### ISSUE THREAD

**Issue by Priyansh2001here** [vitalik/django-ninja#78]
Hey I want to build a django rest api and want to apply login with Google functionality, 
I have worked with django all auth package in past but don't know how to integrate JWT, django all auth to work with ninja rest framework, I searched on internet but found resources for django-rest-framework

**Comment by ianrodrigues** [comment]
I _think_ you have to write your own authentication backends.

**Comment by vic-developer** [comment]
have the same problem! it's big issue in the ninja ecosystem! There is no good solution around.
