### ISSUE TITLE
Request attributes  issue

### ISSUE THREAD

**Issue by Ismaili1995** [vitalik/django-ninja#79]
How can get thing like this: request.data['Body'].lower() in Django ninja request
because mine it fails with: AttributeError: 'WSGIRequest' object has no attribute 'data'

**Comment by vitalik** [comment]
ninja request is a [django request object ](https://docs.djangoproject.com/en/3.1/ref/request-response/#httprequest-objects)

so I guess what you need is :

```Python
import json

data = json.loads(request.body)
data['Body'].lower()

```

**Comment by Ismaili1995** [comment]
Thanks
