### ISSUE TITLE
[BUG] Delete has to be above post for same path

### ISSUE THREAD

**Issue by Andrioden** [vitalik/django-ninja#792]
**Describe the bug**

There is a bug in the `http method + path pattern matching` code that require a delete router to be above a post router with the same path.

This work
``` python
@router.delete("/{int:id_}/")
def delete(request: WSGIRequest, id_: int) -> None:
    # ...

@router.post("/{str:nick}/", response=PlayerResponse)
def create(request: WSGIRequest, nick: str) -> Player:
    # ...
```

This gives `Method Not Allowed: /api/contacts/1/`
``` python
@router.post("/{str:nick}/", response=PlayerResponse)
def create(request: WSGIRequest, nick: str) -> Player:
    # ...

# This function has to be above create due to pattern matching
@router.delete("/{int:id_}/")
def delete(request: WSGIRequest, id_: int) -> None:
    # ...

# Output when calling the delete router:
# Method Not Allowed: /api/contacts/1/
# [14/Jul/2023 12:06:28] "DELETE /api/contacts/1/ HTTP/1.1" 405 18
```

My expectations is that the order of the functions should not matter, as django-ninja should priority matching on the http post method anyway.

**Versions:**
 - Python version: 3.11
 - Django version: 4.2.3
 - Django-Ninja version: 0.22.2
 - Pydantic version: 1.10.11

**Related:**

These are related, but i decided to make a new issue to make it more clear what the problem is.
- https://github.com/vitalik/django-ninja/issues/590
- https://github.com/vitalik/django-ninja/issues/227

**Comment by vitalik** [comment]
well it's kinda hard to prioritize one method over another as django ninja fully relies on django url resolver

django url resolver treats this `/api/contacts/1/` as string  match - so post with string will match (so according to django these are not the same paths)

I think in your case the most logical would be to use string url modifier and let ninja parse it to int:

```
@router.delete("/{str:id_}/")
def delete(request: WSGIRequest, id_: int) -> None:
    # ...
```
that way both methods should match as you expect

**Comment by Andrioden** [comment]
Thanks for the quick reply.

Changing to str still gives 405
```
@router.post("/{str:nick}/", response=PlayerResponse)
def create(request: WSGIRequest, nick: str) -> Player:
   # ...

@router.delete("/{str:id_}/")
def delete(request: WSGIRequest, id_: int) -> None:
   # ...
```

But if this is due to django url resolver, then i guess the bug is with django and i guess you can close this.

I am considering changing the api anyway, accepting a contact nick instead of id as part of the url is slightly bad design.

**Comment by Andrioden** [comment]
this works btw, both as int patterns
```
@router.post("/{int:id_}/", response=PlayerResponse)
def create(request: WSGIRequest, id_: int) -> Player:
   # ...

@router.delete("/{int:id_}/")
def delete(request: WSGIRequest, id_: int) -> None:
   # ...
```

**Comment by vitalik** [comment]
@Andrioden - yes as long as you use exactly same path (with same url typings) it will work

but if typing is different django treats it as two different paths
