### ISSUE TITLE
Add a sponsor button to the project!

### ISSUE THREAD

**Issue by magedhelmy1** [vitalik/django-ninja#795]
**Is your feature request related to a problem? Please describe.**
Github sponsor project :) 

**Describe the solution you'd like**
A button where the user can sponsor the [project](https://github.com/sponsors)

**Comment by nickmccullum** [comment]
+1!

**Comment by vitalik** [comment]
the "official" sponsor page is on bymeacoffe -  https://www.buymeacoffee.com/djangoninja
