### ISSUE TITLE
[BUG] Nested routers will overwrite the response if they are on the same path.

### ISSUE THREAD

**Issue by ndjman7** [vitalik/django-ninja#797]
**Describe the bug**
If I define the response schema for the api path `/test` on router 1 as ATest, 
and the response schema for the same path `/test` with the prefix `/api` on router 2 as BTest, 
and then register to the router, 
I get ATest as BTest in API Swagger.

My guess is that if the path is the same, the response is overwritten, but I don't know how to fix that.

I'm reporting this as a possible Django Ninja issue.

```python
# ---> API Swagger Response BTest (Error!)
@test_router.get(
    "/test",
    response=ATest,
)
def test_api(request):
    ...

# ---> API Swagger Response BTest
@api_test_router.get(
    "/test",
    response=BTest,
)
def api_test_api(request):
    ...

api.add_router("", test_router, tags=["test"])
api.add_router("/api", api_test_router, tags=["api_test"])
```

**Versions (please complete the following information):**
 - Python version: 3.11.1
 - Django version: 4.2.1
 - Django-Ninja version: 0.22.2
 - Pydantic version: 1.10.2

**Comment by vitalik** [comment]
Hi @ndjman7 

cannot replicate this - the following example works for me:

```Python
test_router = Router()
api_test_router = Router()


class ATest(Schema):
    a: str
    b: str


class BTest(Schema):
    x: str
    y: str


@test_router.get("/test", response=ATest)
def test_api(request):
    return {"a": "a", "b": "b"}


@api_test_router.get("/test", response=BTest)
def api_test_api(request):
    return {"x": "x", "y": "y"}


api = NinjaAPI()

api.add_router("", test_router, tags=["test"])
api.add_router("/api", api_test_router, tags=["api_test"])
```
<img width="931" alt="SCR-20230719-jxxk" src="https://github.com/vitalik/django-ninja/assets/95222/5e69be2c-c57f-413f-a1e8-f81f8f7c9809">

**Comment by ndjman7** [comment]
@vitalik Sorry for the late response.
Let me try to reproduce it.

**Comment by ndjman7** [comment]
Hi @vitalik 

As it turns out, the problem was caused by using the same Schema name.
I thought that a Schema nested in a different file would have the same name.


```python
# test.py
class NestedSchema(Schema):
    object: Any


class ATest(Schema):  # <--- crash
    a: str
    b: str

class NestedTestSchema(NestedSchema):
    object: ATest
```

```python
# AS-IS api_test.py
class NestedSchema(Schema):
    object: Any

class ATest(Schema):  # <--- crash
    x: str
    y: str

class NestedAPITestSchema(NestedSchema):
    object: ATest
```

---

```python
# TO-BE api_test.py
class NestedSchema(Schema):
    object: Any

class APIATest(Schema): 
    x: str
    y: str

class NestedAPITestSchema(NestedSchema):
    object: APIATest
```

Thank you for your time and consideration.
Again, we apologize for the delay in responding.
I think we can close this issue.
