### ISSUE TITLE
How can we validate CSRF-Token with Every POST Request?

### ISSUE THREAD

**Issue by Ammadhashmi** [vitalik/django-ninja#8]
I am trying to Validate the CSRF-Token on every Request Please Guide me how to do that in this API framework

**Comment by vitalik** [comment]
Hi @Ammadhashmi 

I will keep this open...

The plan is to allow to pass csrf flag either on top `NinjaAPI(..., csrf=True)` or per operation

**Comment by JusticeN** [comment]
hi did you try the django way of [protecting agains csrf](https://docs.djangoproject.com/en/3.1/ref/csrf/#how-it-works).

since ninja use the same views function as django, does it didn't works when you add `django.middleware.csrf.CsrfViewMiddleware` in your middleware ?

**Comment by vitalik** [comment]
by default Django Ninja have CSRF off
but if you start using any cookie based authentication it will throw an error
you need to set `csrf` flag to `True`:

api = NinjaAPI(csrf=True)


added in v.0.7.0

https://django-ninja.rest-framework.com/tutorial/csrf/
