### ISSUE TITLE
Defining a schema with a Point property

### ISSUE THREAD

**Issue by leonvisscher** [vitalik/django-ninja#809]
I have a Django model that has a `models.PointField(null=True, blank=True)` field from `from django.contrib.gis.db import models`.

When fetching an instance of this model from the db, the field is of type `django.contrib.gis.geos.point.Point`.

How can I define this field in a django-ninja schema?

When using:
```
class MySchema(Schema):
    id: object
    location: object
```

I get the error: `TypeError: Object of type Point is not JSON serializable`

I think I need to create a custom pydantic type for this but I do not know how.

**Comment by leonvisscher** [comment]
When trying it using the ModelSchema:

```
class MySchema(ModelSchema):
    id: object

    class Config:
        model = MyModel
        model_fields = ["location",]
```

I get the following error: `KeyError: 'PointField'`.

**Comment by OtherBarry** [comment]
This will show you how to make the custom pydantic type: https://docs.pydantic.dev/1.10/usage/types/#custom-data-types

Note that this changes quite a bit in pydantic 2, which will be used by django ninja in the v1 release, so you might be better off just using something like tuple[int, int] for the type, and a resolver to handle the conversion.

**Comment by vitalik** [comment]
@leonvisscher 

if that works you can apply that global (to use with ModelSchema)

```Python

from ninja.orm.fiels improt TYPES

TYPES["PointField"] = PointSchema

```

**Comment by leonvisscher** [comment]
> @leonvisscher
> 
> try the following:
> 
> ```python
> class PointSchema(Schema):
>    x: str # or float ?
>    y: str # or float ?
> 
> 
> class MySchema(Schema):
>     id: object
>     location: PointSchema
> ```

This works, thanks!
