### ISSUE TITLE
How to create Generic Schema for openapi?

### ISSUE THREAD

**Issue by suuperhu** [vitalik/django-ninja#818]
### Discussed in https://github.com/vitalik/django-ninja/discussions/817

<div type='discussions-op-text'>

<sup>Originally posted by **suuperhu** August  8, 2023</sup>
**I have the following piece of code, but there is a problem with openapi page, how should I solve it?**

_Code environment :
ubuntu 20.04
python 3.10.11
django 3.2.15
django-ninja  0.22.2
pydantic 1.10.12_

```python
from typing import TypeVar, Generic, List

from django.http import HttpRequest
from ninja import Router, Query, Schema
from pydantic import Field

T1 = TypeVar('T1')
T2 = TypeVar('T2')
router = Router()


class Params(Schema):
    name: str
    age: int = Field(0, ge=0, le=120)


class Response(Schema, Generic[T1, T2]):
    code: int
    data: T1
    message: T2


class Data(Schema):
    a: int
    b: List[str]


@router.get('demo/', response=Response[Data, str])
def list_level(request: HttpRequest, params: Params = Query(...)):
    return {
        'code': 200,
        'data': {'a': 1, 'b': ['a', 'b', 'c']},
        'message': 'good'
    }
```
The openapi page:
![图片](https://github.com/vitalik/django-ninja/assets/34603874/661da3f9-9a01-474e-8cea-31b2e8e29b8a)

So,How should I make the openapi page's 200 response look like this:
```json
{
  "code": 0,
  "data": {
    "a": 0,
    "b": [
      "string",
      "string",
      "..."
    ]
  },
  "message": "string"
}
```

</div>

**Comment by vitalik** [comment]
details are in #817
