### ISSUE TITLE
Validating schema

### ISSUE THREAD

**Issue by Priyansh2001here** [vitalik/django-ninja#82]
```
class LoginSchema(Schema):
    username: str
    password: str
```
I used this snippet for validating username and password in request body, Is there a way to validate string length

**Comment by vitalik** [comment]
hi @Priyansh2001here 

django-ninja uses Pydantic for schema vlidation

see here how to create your validators:


https://pydantic-docs.helpmanual.io/usage/validators/


----

also there is a simpler way for just string length validation 

```Python
from ninja import Field


class LoginSchema(Schema):
    username: str = Field(..., min_length=2, max_length=100)
    password: str = Field(..., min_length=2, max_length=100)
```

**Comment by Priyansh2001here** [comment]
Oh thanks
