### ISSUE TITLE
[BUG] Async authentication doesn't play well with sync views

### ISSUE THREAD

**Issue by selcuk** [vitalik/django-ninja#827]
**Describe the bug**
Django Ninja supports both sync and async authentication classes, but even though sync authentication works well with both sync and async views; async authentication requires async views.

To reproduce:
```
class MyAsyncTokenAuth(HttpAuthBase):
    openapi_scheme: str = "bearer"
    header: str = "Authorization"

    async def __call__(self, request: HttpRequest) -> Optional[Any]:
        # ...
        return {"user": "foobar"}
```
then
```
api = NinjaAPI(title="MyAPI", auth=MyAsyncTokenAuth())
```
this works well here:
```
async def my_async_view(request):
    if request.auth["user"] == "foobar":
        # The user is authenticated
```
but it fails with a sync view:
```
def my_async_view(request):
    if request.auth["user"] == "foobar":
```
Exception:
```
builtins.TypeError: 'coroutine' object is not subscriptable
```
**Cause**
Although `AsyncOperation._run_authentication` checks if the `__call__` method of the authentication class is async, its sync counterpart (`Operation._run_authentication`) does not perform this check.

**Versions (please complete the following information):**
 - Python version: [e.g. 3.11]
 - Django version: [e.g. 4.2.4]
 - Django-Ninja version: [e.g. 0.22.2]
 - Pydantic version: [e.g. 1.10.7]

**Comment by selcuk** [comment]
Hmm, on a closer look, this looks like a Duplicate of #756 and seems to be fixed in the latest `master` branch. 🎉

**Comment by vitalik** [comment]
@selcuk you can try it with recent alpha release `pip install django-ninja==1.0a3`
