### ISSUE TITLE
foreign-key value failed to be valid integer in NinjaResponseSchema

### ISSUE THREAD

**Issue by Ismaili1995** [vitalik/django-ninja#83]
``` 
ValidationError at /api/order/orders
6 validation errors for NinjaResponseSchema
response -> 0 -> customer_id
  value is not a valid integer (type=type_error.integer)
response -> 0 -> vendor_id
  value is not a valid integer (type=type_error.integer)
response -> 0 -> vender_product_id
  value is not a valid integer (type=type_error.integer)
response -> 1 -> customer_id
  value is not a valid integer (type=type_error.integer)
response -> 1 -> vendor_id
  value is not a valid integer (type=type_error.integer)
response -> 1 -> vender_product_id
  value is not a valid integer (type=type_error.integer)
```
my schema is like this: 
```
class OrderSchema(Schema):
    customer_id: int
    vendor_id: int
    vender_product_id: int
    total_product: int
    total_price: int
    created_on: datetime
    updated_on: datetime
```

**Comment by vitalik** [comment]
@Ismaili1995 
You may need to give your view code as well to understand your issue

**Comment by Ismaili1995** [comment]
> @Ismaili1995
> You may need to give your view code as well to understand your issue

Okay hope now is readble

**Comment by Ismaili1995** [comment]
its view:
```
def get_orders(request):
    try:
        orders = Order.objects.all().order_by('-id')
        return orders
    except:
        return HTTPExceptions.INTERNAL_SERVER_ERROR
```

**Comment by vitalik** [comment]
well except with empty is pretty bad practice...

seems that you are getting an exception and just returning some number INTERNAL_SERVER_ERROR which is not a valid result schema


you simply need to do 

```Python
def get_orders(request):
    return Order.objects.all().order_by('-id')
```

and then see what exception you are getting

**Comment by Ismaili1995** [comment]
> well except with empty is pretty bad practice...
> 
> seems that you are getting an exception and just returning some number INTERNAL_SERVER_ERROR which is not a valid result schema
> 
> you simply need to do
> 
> ```python
> def get_orders(request):
>     return Order.objects.all().order_by('-id')
> ```
> 
> and then see what exception you are getting

It returns the same thing
and this is my endpoint:
```
@api.get("/orders", response=List[OrderSchema])
def get_order_list(request):
   return get_orders(request)
```
Note: get_orders is imported from my view

**Comment by vitalik** [comment]
can it be that yours product, customer and vender are `null=True` in your model ?

if so you need to mark these fields as nullable:


```Python
class OrderSchema(Schema):
    customer_id: int = None
    vendor_id: int= None
    vender_product_id: int= None
    total_product: int
    total_price: int
    created_on: datetime
    updated_on: datetime
```

**Comment by Ismaili1995** [comment]
@vitalik 
Are not null=True and there is values have been added by using django admin 
my model is as follows:
```
class Order(models.Model):
    customer_id = models.ForeignKey(
        "customers.Customer", on_delete=models.CASCADE
    )
    vender_product_id = models.ForeignKey(
        "vendors.VendorProduct", on_delete=models.CASCADE
    )
    vendor_id = models.ForeignKey("vendors.Vendor", on_delete=models.CASCADE)
    total_product = models.IntegerField()
    total_price = models.IntegerField()
    created_on = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_on = models.DateTimeField(
        auto_now=True, auto_now_add=False, null=True, blank=True
    )

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"
        db_table = "order"

    def __str__(self):
        return self.vender_product_id.product_name

    def get_absolute_url(self):
        return reverse("Order_detail", kwargs={"pk": self.pk})
```

**Comment by Ismaili1995** [comment]
@vitalik  any idea please

**Comment by vitalik** [comment]
@Ismaili1995 

you general mistake is in naming model fields

```Python
customer_id = models.ForeignKey
```

Note - this is not a good practice - this leads to the fact that your column name will be named `customer_id_id` <-- note id 2 times


You should use 
```Python
customer = models.ForeignKey
```

then your integer attribute will be named `customer_id` 

and your schema will start to work

**Comment by Ismaili1995** [comment]
> @Ismaili1995
> 
> you general mistake is in naming model fields
> 
> ```python
> customer_id = models.ForeignKey
> ```
> 
> Note - this is not a good practice - this leads to the fact that your column name will be named `customer_id_id` <-- note id 2 times
> 
> You should use
> 
> ```python
> customer = models.ForeignKey
> ```
> 
> then your integer attribute will be named `customer_id`
> 
> and your schema will start to work

Okay thanks for your help
