### ISSUE TITLE
[BUG] `servers` are null, but should be empty list/non-existent

### ISSUE THREAD

**Issue by pgronkievitz** [vitalik/django-ninja#834]
**Describe the bug**
When exporting OpenAPI Schema, some tools (e.g. [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli)) can't handle null value. Handling null is not documented, but empty list/lack of this property is ([OpenAPI specs](https://spec.openapis.org/oas/v3.1.0#oasServers)).

**Versions (please complete the following information):**
 - Python version: 3.11.4
 - Django version: 4.2.4
 - Django-Ninja version: 0.22.2
 - Pydantic version: 1.10.12

**Comment by OtherBarry** [comment]
I've experienced the same thing (with the same library versions).

**Comment by vitalik** [comment]
@pgronkievitz added fix for a next release, meanwhile you can fix this by overriding 

```Python

class MyAPI(NinjaAPI):
    def get_openapi_schema(self, *a, **kw):
        result = super().get_openapi_schema(*a, **kw)
        if result["servers"] is None:
             result["servers"]  = []
        return result

```
