### ISSUE TITLE
[BUG] Django Ninja does not respect Schema config extra options

### ISSUE THREAD

**Issue by nofalx** [vitalik/django-ninja#835]
**Describe the bug**

**Versions (please complete the following information):**
 - Python version: 3.10
 - Django version: 4.24
 - Django-Ninja version: v1.0a3
 - Pydantic version: 2.3.0

I have the below structure and when trying to use the option `extra` it doesnt work. This is unlike the pre v1 versions
```

class UserTokenType(Schema):
    linking_id: LinkingId
    queue_reference_id: UUID | None = None
    meta_data: MetaData
    cp_transaction_entry: UUID

    class Config:
        extra = "forbid"
        
---------------


@router.post(
    "token/",
    response={201: dict, 400: dict, 403: dict, 404: ErrorResponse},
)
def survey_user_token_add(request: HttpRequest, user_token: UserTokenType):
   ....
```

**Comment by vitalik** [comment]
@nofalx 

does it work if you pass it [like in v2 docs ](https://docs.pydantic.dev/latest/usage/model_config/#extra-attributes)?

```Python
class UserTokenType(Schema):
    ...
    model_config = ConfigDict(extra='allow')
```

**Comment by nofalx** [comment]
@vitalik  I tried that approach as well and it did *not* work as well

 if keep both like below I get an error that i cant use both at same time, so im guessing both approach are supported and they both dont work even when used alone

```
class UserTokenType(Schema):
    model_config = ConfigDict(extra='forbid')
    
    class Config:
        extra = "forbid"
```
