### ISSUE TITLE
How do I build absolute URIs in Schema?

### ISSUE THREAD

**Issue by vtbassmatt** [vitalik/django-ninja#837]
# Please describe what you are trying to achieve

Hello! I'm using `django-ninja` to add a small API to a personal project. I'd like for my `list` endpoints to offer the ability to navigate down to the `detail` endpoint for a given object. Something like:

```
-> GET /api/foo

<- [
<-   {
<-     "name": "First",
<-     "id": 1,
<-     "url": "https://example.com/api/foo/1"
<-   },
<-   {
<-     "name": "Second",
<-     "id": 2,
<-     "url": "https://example.com/api/foo/2"
<-   }
<- ]
```

## Current state

I've gotten as far as using a resolver on the `FooSchema` to generate the path using `django.urls.reverse`. In order to generate the fully-qualified URL, I typically reach for `request.build_absolute_uri`. But I can't figure out how to get `request` passed into the resolver.

```
-> GET /api/foo

<- [
<-   {
<-     "name": "First",
<-     "id": 1,
<-     "url": "/api/foo/1"  // <-- note, missing protocol & host
<-   },
<-   {
<-     "name": "Second",
<-     "id": 2,
<-     "url": "/api/foo/2"
<-   }
<- ]
```

# Please include code examples (like models code, schemes code, view function) to help understand the issue

```python
class Foo(models.Model):
    name: models.CharField(max_length=100)

class FooSchema(ModelSchema):
    url: str = None

    class Config:
        model = Foo
        model_fields = ['name', 'id']

    def resolve_url(self, obj):
        # !! this gets me "/api/foo/{id}" but I would like a fully-qualified URL here
        return reverse("api-1.0.0:foo_detail", kwargs={'id': obj.id})

@api.get('/foo', response=list[FooSchema])
def foo_list(request):
    return Foo.objects.all()

@api.get('/foo/{id}', response=FooSchema)
def foo_detail(request, id: int):
    return get_object_or_404(Foo, pk=id)
```

Any pointers you can provide would be awesome. Thanks!

**Comment by vitalik** [comment]
@vtbassmatt 

with pydantic v1 (django-ninja 0.x) this is not yet possible - the only solution for now is to put request into `threading.local` and use it with `request.build_absolute_url(reverse('xxxxx'))`

in django-ninja v1.x there will be extra context argument that will contain request (you can already try it out with `pip install django-ninja==1.0a3`

but for now either thread locals or just add some setting with domain 

```Python
# settings.py

SITE_URL = 'https://some.com'

...

    def resolve_url(self, obj):
        path =  reverse("api-1.0.0:foo_detail", kwargs={'id': obj.id})
        return SITE_URL + path
...

```

**Comment by vtbassmatt** [comment]
Thank you! I’ll use the constant workaround for now and await the context enhancement in 1.0.
