### ISSUE TITLE
Support exposing additional Pydantic models

### ISSUE THREAD

**Issue by aurbano** [vitalik/django-ninja#843]
**Is your feature request related to a problem? Please describe.**
We have some internal Pydantic models for responses that the frontend gets directly from a separate API that is not exposing any documentation.

A simple approach would be to be able to expose these in the docs, even if they aren't used by any endpoint. We're currently solving this by creating a dummy API endpoint (i.e. `/expose-models`)

**Describe the solution you'd like**
Perhaps something like this?
```py
api.add_model(PydanticModelA)
```

That being said, maybe there's a better way without modifying the library? I also realise this is a fairly niche use-case, so no worries if it doesn't make sense to add it to the library, the workaround we're using works fine.

**Comment by vitalik** [comment]
@aurbano 

you can do it by extending NinjaAPI class - adding some dummy fake method and then removing it from /openapi.json shchema:

```Python
class MyNinjaAPI(NinjaAPI):
    def __init__(self, *a, **kw):
        super().__init__(*a, **kw)
        self.secret_models = []

    def add_model(self, model):
        self.secret_models.append(model)

    def get_openapi_schema(self, *a, **kw):
        def _dummy(response):
            pass
        self.post('_dummy', response=Union[tuple(self.secret_models)])(_dummy)
        schema = super().get_openapi_schema(*a, **kw)
        del schema['paths']['/api/_dummy']
        return schema


api = MyNinjaAPI()


class Schema1(Schema):
    id: int


class Schema2(Schema):
    name: str


api.add_model(Schema1)
api.add_model(Schema2)
```

<img width="391" alt="SCR-20230906-mikn" src="https://github.com/vitalik/django-ninja/assets/95222/b22185ef-c13c-4508-a98b-6838ffe64369">

**Comment by aurbano** [comment]
Genius, thanks!
