### ISSUE TITLE
Add schema field at runtime

### ISSUE THREAD

**Issue by aegeavaz** [vitalik/django-ninja#851]
Hi...

Is there any way to add a ModelField to an existing schema class at runtime?

Thank you very much.

**Comment by vitalik** [comment]
@aegeavaz 

not sure about the goal - could you share the use case ? 

maybe you need something like this -> #843 ?

**Comment by aegeavaz** [comment]
Yeah. Imagine that I have already define a complex schema class.

class MySchema(Schema):
   id: int
   name: str
   description: str
   creation_date: datetime

I'm using that schema to serialize some model django ORM objects from a view. But under a specific condition I need to add an extra field to that schema.

Right now I'm defining another schema that inherits from that one.

class MySchemaExtended(MySchema):
   extra_field: str

And using one class or another depending of the condition.

I just was wondering if there is another way to add that extra_field to the original schema without creating a new one.
Something like MySchema.addField(...)

Thanks.

**Comment by OtherBarry** [comment]
Why not just include the extra field with `extra_field: str | None = None`

**Comment by aegeavaz** [comment]
Hi Charlie.

Because I want to avoid db hits in the case that I don't need the field.

I have something like this:
qs = Model.objects.all().only('id', 'name', 'description', 'creation_date') if condition else Model.objects.all().only('id', 'name', 'description', 'creation_date', 'extra_field)

So I don't retrieve from db always that extra_field, only under some condition. If I add the extra_field to the schema, when I use Schema.fromOrm(data)... the schema tries to access the extra_field that has not been loaded from db and make a select to the db to retrieve that field.

Thanks.

**Comment by vitalik** [comment]
@aegeavaz you can use pydantic's "exclude_unset" option:


```Python
api = NinjaAPI()


class MySchema(Schema):
    id: int
    username: str
    email: str = None # <--- make extra field nullable


@api.get("/test", response=list[MySchema], exclude_unset=True) # <---- exclude_unset !!!
def some_test(request, add_extra=False):
    qs = User.objects.all()
    if add_extra:
        qs = qs.values("id", "username", "email")
    else:
        qs = qs.values("id", "username")
    return qs

```

<img width="960" alt="SCR-20230913-klig" src="https://github.com/vitalik/django-ninja/assets/95222/a7dc0a37-0fb8-4e73-a0d2-ff5f5a936a3a">

**Comment by OtherBarry** [comment]
@aegeavaz for the specific example you've posted, could you not use `.values` instead of `.only`?

**Comment by vitalik** [comment]
@aegeavaz 

yeah, `only()` creates orm objects (With all fields that are fetched only if you trying to accessing it) - what you actually need is `values()` as it returns dicts

try changing this:

```
    if add_extra:
        qs = qs.only("id", "username", "email")
        return [schema.from_orm(item) for item in qs]
    else:
        qs = qs.only("id", "username")
        return [schema.from_orm(item) for item in qs
```

to this:
```Python
    if add_extra:
        return qs.values("id", "username", "email")
    else:
        return qs.values("id", "username")

```

**Comment by aegeavaz** [comment]
Hi...

The example is a very very simplified example of my real code. Thats why I named the function that retrieve the data "some_function_that_generate_complex_data". ;)

We make very complex queries... some of them using prefetch calls, and django says this:

ValueError: Prefetch querysets cannot use raw(), values(), and values_list().

**Comment by vitalik** [comment]
hm.. well try select_related instead prefetch_related - maybe that will have similar performance

(Prefetch works with orm objects and lazy loads them later - so - you cannot really control if pydantic will try access it or not)

if select_related is too slow - then yeah - you option is to use inheritance (`MySchemaExtended(MySchema)`)

---

**OR** you can as well try `django-ninja==1.0.b1` with resolve methods - it now takes context

so you shoujld be able do do stuff like this:


```Python
class MySchema(Schema):
    f1: str
    f2: str
    some_extra_field: str = None

   @staticmethod
   def resolve_some_extra_field(obj, context: dict):
       if context['fetch_extra']:
             return some value
       return None


#.... 

MySchema.model_validate(obj, context={"fetch_extra": True})
     
```

Read more about pydantic validation context here - https://docs.pydantic.dev/latest/usage/validators/#validation-context

**Comment by aegeavaz** [comment]
Yeah. I agree that the inheritance, in this particular complex case is the best option.

Soo, how long to have implemented in your next version an addField method to add a new schema field at runtime?  I'm joking!!! ;) ;)

Thank you so much to dedicate this effort to try to provide me with solutions. I really appreciate it. :)
