### ISSUE TITLE
Generate client with "long" datatype?

### ISSUE THREAD

**Issue by winrid** [vitalik/django-ninja#859]
Hello! Maybe this is a Pydantic specific question - but wanted to start here.

If I have a schema with `int` - like for `id` - how do I generate clients for a language like Java where I want to use `long` instead? Python's `int` is auto promoting but for Java clients I'd need to use `long`...

Thanks for any help!

**Comment by OtherBarry** [comment]
Json schema doesn't have any concept of integer size, so there's nothing you could do in python to fix this. Perhaps whatever you are using to generate the Java client will have settings for this.

**Comment by winrid** [comment]
@OtherBarry not true: https://swagger.io/docs/specification/data-models/data-types/#numbers

I guess I want to specify `int64`.

(we're discussing openapi spec, not json schema)

**Comment by OtherBarry** [comment]
Right sorry, pydantic generates a jsonschema which does not support integer size, but the openapi extensions to jsonschema do. Thanks for the correction.

From quickly looking through the pydantic docs (v1.10), I think you should be able to do this:

```python
class MyModel(Schema):
    my_property: int = Field(..., json_schema_extra={"format": "int64"}) 
```

**Comment by winrid** [comment]
@OtherBarry Thanks for your reply, it looks like this is actually the mots elegant way:

```
id: int = Field(format="int64")
```

```
pydantic==1.10.11
```
