### ISSUE TITLE
support for objects as query parameters.

### ISSUE THREAD

**Issue by RafalSkolasinski** [vitalik/django-ninja#86]
I am looking for possibility to use objects as query parameters, [introduced in OpenAPI 3](https://www.baeldung.com/openapi-json-query-parameters#OAP3). 

I tried the following

```python
class Filters(Schema):
    limit: int = 100
    offset: int = None
    query: dict = None


@router.get("/models", response={200: List[ModelSchema]})
def list_models(request, filters: Filters = Query(...)):
    print(filters)
    qs = MyModel.objects.all()
    output = [ModelSchema.from_model(model) for model in qs]
    return output
```

but this does not seem to work properly
![image](https://user-images.githubusercontent.com/10928117/109214726-19725100-77aa-11eb-9d74-e3cb39c2590e.png)

as it is being send as 
```
http://localhost:8000/api/metadata/models?limit=100&test=yes
```

instead of 
```
http://localhost:8000/api/metadata/models?limit=100&query={"test":"yes"}
```

is something like this actually supported?

**Comment by vitalik** [comment]
Hi @RafalSkolasinski 

Seems no - not supported at this moment

workaround for now would be to use `str` and converting it to `dict` in validator

```Python

class Filter(Schema):
    ...
    query: str = None  # use str

    @validator('query')
    def str_to_dict(cls, v):
             return json.loads(v)
```

**Comment by RafalSkolasinski** [comment]
Thanks for the reply @vitalik, I will check the workaround, should work for my use case.

I will leave it to you if you want to keep the issue open or close it.
