### ISSUE TITLE
[BUG] happens error with trailing slash only POST Method 

### ISSUE THREAD

**Issue by quroom** [vitalik/django-ninja#861]
**Describe the bug**

**Versions (please complete the following information):**
 - Python version: [e.g. 3.6]     3.9.13
 - Django version: [e.g. 4.0]     4.2.1
 - Django-Ninja version: [e.g. 0.16.2]   0.21
 - Pydantic version: [e.g. 1.9.0]   1.10.8

Note you can quickly get this by runninng in `./manage.py shell` this line:
```
import django; import pydantic; import ninja; django.__version__; ninja.__version__; pydantic.__version__
```

```
@daily_router.post("/bulk/")
def create_bulk_daily_bible(request, bulk: BulkDailyBibleInSchema):
```

This makes error.. I am not sure the reason.
```
Method Not Allowed: /api/daily/bulk/
[19/Sep/2023 15:40:25] "POST /api/daily/bulk/ HTTP/1.1" 405 18
```
I tested it with curl. But same response.
```
curl -X 'POST' \
  'http://127.0.0.1:8000/api/daily/bulk/' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "group_id": 4,
  "daily_bible_list": [
    {
      "month": 1,
      "day": 1,
      "book": 1,
      "from_chapter": 2,
      "from_verse": 2,
      "to_chapter": 2,
      "to_verse": 3
    },
    {
      "month": 1,
      "day": 1,
      "book": 1,
      "from_chapter": 2,
      "from_verse": 4,
      "to_chapter": 2,
      "to_verse": 5
    }
  ]
}'
```
But without trailing slash,
it works well.

```
@daily_router.post("/bulk")
def create_bulk_daily_bible(request, bulk: BulkDailyBibleInSchema):
```
```
[19/Sep/2023 15:41:56] "POST /api/daily/bulk HTTP/1.1" 200 17
[19/Sep/2023 15:42:00] "POST /api/daily/bulk HTTP/1.1" 200 17
```

Do you guys have any ideas?

**Comment by quroom** [comment]
Now I am debugging with that.
But it looks like when I change url. It's not applied.. 
I have no idea.
This moment, /bulk/ only works /bulk doesn't work.

**Comment by OtherBarry** [comment]
@quroom do you have any other endpoints in the same router?

**Comment by quroom** [comment]
> @quroom do you have any other endpoints in the same router?

Nope.
Do you have any ideas?
If you leave some your opinions, I will look more deeply.
I don't really have any idea.

**Comment by baseplate-admin** [comment]
I think this is due to how django registers url.


Check this [article](https://dev.to/learndjango/trailing-url-slashes-in-django-4bf) and see if the solution there works

**Comment by OtherBarry** [comment]
@quroom My guess with the other endpoints is that they might be taking that other url first. e.g. if you had a GET endpoint that was `/daily/{name:str}` then it might be matching that first. It could also be an endpoint like `/{name:str}/bulk` or even `/daily/bulk/{name:str}` and it's matching an empty string after the final `/`.

If you're sure this isn't the case, then i would guess it's something related to the trailing / setting from the article linked above.

**Comment by quroom** [comment]
> @quroom My guess with the other endpoints is that they might be taking that other url first. e.g. if you had a GET endpoint that was `/daily/{name:str}` then it might be matching that first. It could also be an endpoint like `/{name:str}/bulk` or even `/daily/bulk/{name:str}` and it's matching an empty string after the final `/`.
> 
> If you're sure this isn't the case, then i would guess it's something related to the trailing / setting from the article linked above.

@OtherBarry 
I found what the problem is.
As you said, I missed some mistakes.
I defined one more url before defined /daily/bulk

1. /daily/{name:str}
2. /daily/bulk
/daily/bluk/ would not match forever.

It's really basic , but somehow I couldn't recoginze it :( 
Thanks for guys helping me
