### ISSUE TITLE
[BUG] Inner class shadowing when generating `openapi.json`

### ISSUE THREAD

**Issue by ostatni5** [vitalik/django-ninja#862]
**Describe the bug**
When two inner classes with the same name are used in different classes to define the field type, only the last one is generated in  `openapi.json` and all refs are pointing to it. 

**Versions:**
 - Python version: 3.11.4
 - Django version: 4.2.5
 - Django-Ninja version: 0.22.2
 - Pydantic version: 1.10.12
 
**Context**
I was trying to achieve a result schema with a single value that represents a type of response to be able to parse it in a typescript client properly. I know that in open API spec is something like `Discriminator` but I don't know how to tell Ninja to generate it pointing to the chosen property name.

**Code**
Sample schema definition:
```py
class ExA(Schema):
    class ExC(str, enum.Enum):
        foo = "foo"

    type: ExC = ExC.foo


class ExB(Schema):
    class ExC(str, enum.Enum):
        bar = "bar"

    type: ExC = ExC.bar
```

Schemas in `openapi.json`
```yml
    ExC:
      title: ExC
      description: An enumeration.
      enum:
        - bar
      type: string
    ExA:
      title: ExA
      type: object
      properties:
        type:
          default: foo
          allOf:
            - $ref: '#/components/schemas/ExC'
    ExB:
      title: ExB
      type: object
      properties:
        type:
          default: bar
          allOf:
            - $ref: '#/components/schemas/ExC'
```      
Probably prefixes made from the outer classes could fix this issue.

**Comment by OtherBarry** [comment]
@ostatni5 there's some workarounds listed in #537 - basically your options are to monkeypatch the schema generation code, or rename your models.

**Comment by vitalik** [comment]
@ostatni5 just a side note - seems pydantic2 will not allow you making nested classes.. so basically this approach is not recommended if you intend to upgarde to future versions of django ninja

**Comment by ostatni5** [comment]
Thanks for information

**Comment by jmduke** [comment]
@vitalik You mentioned that this is no longer possible in pydantic2, and indeed after trying to migrate my setup to `django-ninja@1.0rc` I run into the issue as outlined in #537. Is there a recommended path forward? This is a blocker for me, and I imagine it's not a particularly uncommon use case.
