### ISSUE TITLE
ModelSchema does not support reverse relations

### ISSUE THREAD

**Issue by zbmott** [vitalik/django-ninja#864]
macOS Venture 13.6
Python 3.11.4
Django 4.2.2
django-ninja 0.22.2
pydantic 1.10.13

Consider the following object relations and their corresponding schemas. `PrimaryObject` has a one-to-many relationship with `RelatedObject`, but the relation is defined on `RelatedObject`. I want to serialize a `PrimaryObject` and include all of its `RelatedObject` children in the representation.

```python
import typing

from django.db import models

from ninja import ModelSchema


class PrimaryObject(models.Model):
    pass


class RelatedObject(models.Model):
    primary_object = models.ForeignKey(PrimaryObject, related_name='relatedobjects', on_delete=models.CASCADE)


class RelatedObjectSchema(ModelSchema):
    class Config:
        model = RelatedObject
        model_fields = ['id']


class PrimaryObjectSchema(ModelSchema):
    relatedobjects: typing.List[RelatedObjectSchema]

    class Config:
        model = PrimaryObject
        model_fields = ['id', 'relatedobjects']
```

Attempting `manage.py runserver` with the above configuration produces
```
ninja.errors.ConfigError: Field(s) {'relatedobjects'} are not in model <class 'myapp.models.PrimaryObject'>
```
This is because they are excluded from the list of available fields in `ninja.factory.SchemaFactory._model_fields`.
 
This is a relationship that is supported by the Django ORM, and it should "just work" with any libraries that claim to support the Django ORM. `djangorestframework` and `djantic`, for example, both support this use case without any fuss.

I can understand why it might be undesirable to exclude ORM-generated relationships by default, for example when specifying `fields = '__all__'`, as it could lead to an unintended explosion of database joins, but they should be treated as valid if a developer positively includes them in a schema.

Additionally, this relationship is supported by `ninja.Schema` just fine. Serializing a `PrimaryObject` with the following schema produces the expected output, which means that using `ninja.ModelSchema` results in a loss of important functionality.
```python
from ninja import Schema


class RelatedObjectSchema(Schema):
    id: int


class PrimaryObjectSchema(Schema):
    id: int
    relatedobjects: typing.List[RelatedObjectSchema]
```

**Comment by OtherBarry** [comment]
The intent of `ModelSchema` is to automatically generate a schema from the provided fields. This can't be done on relationships, as there's no way for django-ninja to know how to represent the related models.

Specifying the types directly as you have done is certainly a solution, but at that point why use the ModelSchema functionality at all? If you still want some auto-generated fields, then as far as I'm aware this will do exactly as you want:

```python
class PrimaryObjectSchema(ModelSchema):
    relatedobjects: typing.List[RelatedObjectSchema]

    class Config:
        model = PrimaryObject
        model_fields = ['id']
```

That being said, I think your point about how this should "just work" is pretty valid. Maybe this can be done with a seperate config property, e.g.:

```python
class PrimaryObjectSchema(ModelSchema):
    class Config:
        model = PrimaryObject
        model_fields = ['id']
        relations = {"relatedobjects": RelatedObjectSchema}
```

And then an error can be raised if a relation field is specified in the `model_fields` property. The existing system feels better to me tbh, but there's no reason we can't have both (other than that someone would have to. take the time to implement this).

**Comment by zbmott** [comment]
@OtherBarry Thanks for pointing me in the right direction.

This is the functionality I'm looking for.
```python
class PrimaryObjectSchema(ModelSchema):
    relatedobjects: typing.List[RelatedObjectSchema]

    class Config:
        model = PrimaryObject
        model_fields = ['id']
```

However, I will suggest that this be clarified in the [documentation](https://django-ninja.rest-framework.com/guides/response/django-pydantic/#overriding-fields). This pattern for handling reverse relationships could be called out specifically.

`django-ninja` could also provide a more helpful error message. `djangorestframework`, for example, provides this when there's a mismatch between the `fields` option and declared Serializer attributes:
```
AssertionError at /api/v1/primaryobject/
The field 'relatedobjects' was declared on serializer PrimaryObjectSerializer, but has not been included in the 'fields' option.
```
