### ISSUE TITLE
Dates in query parameters without leading zeroes lead to 422 error

### ISSUE THREAD

**Issue by ognjenk** [vitalik/django-ninja#866]
Query parameters defined as date now expect to be in the format YYYY-MM-DD with leading zeroes.
Before upgrade to beta v1 it was possible to send date parameters without leading zeroes, e.g. 2023-9-29.
After upgrade this will yield 422 Unprocessable Entity.
The request works with leading zeroes, e.g. 2023-09-29
I have not tried this with dates in request body, but I expect it to behave the same.

I understand this may be due to the way pydantic v2 is parsing strings, but I wonder is this the intended behaviour? I have a pretty large application with hundreds of endpoints where JS front end is sending date parameters without leading zeroes. Do we need to refactor everything?

Thanks in advance!

**Versions (please complete the following information):**
 - Python version: 3.10
 - Django version: 4.2.5
 - Django-Ninja version: 1.0b1
 - Pydantic version: 2.4.2

**Comment by ognjenk** [comment]
As far as I can see, the date/datetime validation logic has been changed in Pydantic v2 and is now raising date_from_datetime_parsing Validation Error in this case.
I kind of agree that the date 2023-9-29 does not fit the format YYYY-MM-DD, although I'm not sure if there is a real need for this strict correctness.
As a potential solution I thought about intercepting request parameters in Django middleware and changing the formats there before the validation, but we will probably go with the front end refactor.

**Comment by vitalik** [comment]
@ognjenk yeah, pydantic now is a bit more strict here (which I think is actually better)

but if you want to keep some old behaviour working when upgrading to django-ninja 1.x you can use custom request parser and override [parse_querydict](https://github.com/vitalik/django-ninja/blob/8263a13e4e6e1ddd549f60472f324521c677e678/ninja/parser.py#L18) method

docs https://django-ninja.rest-framework.com/guides/input/request-parsers/

**Comment by ognjenk** [comment]
Right, that's a good solution as well. Thanks for the feedback and keep up with the good work @vitalik !
