### ISSUE TITLE
Anyone have luck integrating django-phonenumber-field?

### ISSUE THREAD

**Issue by PhoenixStorm1015** [vitalik/django-ninja#868]
I've tried numerous different solutions, including using the beta and pydantic v2 with pydantic-extra-types. It always returns:
`Input should be a valid string [type=string_type, input_value=PhoneNumber(country_code=...estic_carrier_code=None), input_type=PhoneNumber]`

or

`Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]`

I attempted to use django-phonenumber-field's own serializer, but, ironically, it has DRF as a dependency, which seems to just defeat the purpose of using it. Has anyone gotten an implementation with django-phonenumber-field running?

**Comment by OtherBarry** [comment]
@PhoenixStorm1015 are you getting these errors when serialising/deserialising with django ninja, or when saving the validated data to the field?

Personally, I would set up a custom validator in pydantic using the phonenumbers library (which is what django-phonenumber-field uses internally). Something like this (assuming pydantic v2):

```python
def valid_phonenumber(number: str) -> str:
    parsed = phonenumbers.parse(number, None)  # put in a default region if relevant
    assert phonenumbers.is_possible_number(parsed)
    return phonenumbers.format_number(parsed, phonenumbers.PhoneNumberFormat.E164)

PhoneNumber = Annotated[str, AfterValidator(valid_phonenumber)]


class MySchema(Schema):
    number: PhoneNumber
```

**Comment by PhoenixStorm1015** [comment]
Sorry! I should've specified! This is during serialization. I haven't reached the point of building the POST endpoints yet. Just trying to make sure data is being pulled from the database correctly. Clearly there's a disconnect somewhere, though.

**Comment by OtherBarry** [comment]
Oh - looks like I didn't read your question properly. The error messages show the actual problem. django-phonenumber-field returns a phonenumber instance, and not a string, so pydantic is throwing an error because it is expecting a string.

There's two options - you can either use a [resolver](https://django-ninja.rest-framework.com/guides/response/#resolvers) to format the phonenumber instance as a string, or you could type hint it as `phonenumber.phonenumber` and handle the serialisation issues within pydantic for [custom data types.](https://docs.pydantic.dev/latest/concepts/types/#custom-types)

**Comment by PhoenixStorm1015** [comment]
I take it resolvers would be the more "batteries included" approach, yes? I try to abide by Django's rule of not reinventing the wheel.

**Comment by OtherBarry** [comment]
@PhoenixStorm1015 resolvers are generally the nicer way to do it, but if you have multiple schemas that need to serialise a phone number field, then it would be a lot of repetition, so the custom type might be the nicer way to go.

**Comment by PhoenixStorm1015** [comment]
The resolvers worked flawlessly. Thank you for the response as well, @vitalik. I will stick with Resolvers for now, but I will definitely loop back to this if I decide I need to make a custom type.

**Comment by WayneLambert** [comment]
This one took me a while to figure out, so I thought I would document a simplified example here for future devs looking for a solution.

```py
# models.py

from django.db import models

from phonenumber_field.modelfields import PhoneNumberField


class MyUserModel(models.Model):
    ...
    contact_tel = PhoneNumberField(null=False, blank=True)
    ...
```

```py
# schemas.py

from ninja import ModelSchema


from users.models import MyUserModel


class UserSchema(ModelSchema):
    class Config:
        model = MyUserModel
        model_fields = [
            ...
            "contact_tel",
        ]

    @staticmethod
    def resolve_contact_tel(obj):
        if not obj.contact_tel:
            return
        return str(obj.contact_tel)
```

```py
# api.py

from ninja import NinjaAPI

from users.schemas import UserSchema
from users.models import MyUserModel

api = NinjaAPI()


@api.get("/", response=list[UserSchema])
def users(request):
    return MyUserModel.objects.all()
```

This yields a response of:

```json
{
    ...
    "contact_tel": "+441234123456" 
    ...
}


or

{
    ...
    "contact_tel": null 
    ...
}

```
