### ISSUE TITLE
Docs: Some questions about best practices.

### ISSUE THREAD

**Issue by Adamantish** [vitalik/django-ninja#87]
I find the existing docs to be excellent as far as they go. If they fall short it's in providing an overall sense of how to make it play nicely with Django, the website builder, with all its defaults and built-ins.

If building a pure API the answer is fairly simple. Turn nearly all the django features off. However, for this project we're going to want to use admin panel soon. As someone experienced with ruby but new to python it isn't clear to me how, for instance, one would gracefully switch on the required django middleware for admin panel but only for that particular url namespace. Or whether even worrying about such pollution is a real concern in practice.

Or right now, the one troubling me is standardizing error responses. Ninja has a particular format for 422 errors it emits and that seems a fine format for all the other errors. So is there somewhere in ninja to implement standard json templates for 404 and 500?  It seems I'd be encouraged to go higher in the stack and use the django handlers. But that seems to be part of the part of django that assumes you're making webpages. In debug mode it outputs html. It feels awkward to implement identically formatted errors in totally different places and in different ways. And did I really have to make an `ErrorMessages` schema to match that 422 output or did I miss something?

The point is I can't tell for sure whether I'm pointing to a real niggle in NinjaAPI ergonomics or I'm just doing it wrong. The existing docs seem to be aimed at people who are experienced with django. That's great and should probably remain the entrypoint. However, I'll bet a lot of people are like me. They're choosing django for the first time *because* of ninja. Many on my team have years of python experience but none with Django. It's all flask or data science stuff.

How about an explainer section to outline how it's all meant to fit together, or maybe just some basic example projects?

Thanks for reading. Feel free to close if I'm really just distracting with unhelpful noob questions. If there were a gitter I probably would have taken this there.

**Comment by vitalik** [comment]
Hi @Adamantish 

thank you for investing time to write so many word :) I really appreciate it

indeed, I hear more and more suggestions about error handling approaches...
The plan is the following - I will create a draft document about error handling and then few users/companies will review it and if everyone satisfied - will be implemented and landed to a nearest release

**Comment by vitalik** [comment]
Hi @Adamantish 
Please check error handling functionality in 0.11.0
https://django-ninja.rest-framework.com/tutorial/errors/
