### ISSUE TITLE
How to be more specific about allowed fields in a payload?

### ISSUE THREAD

**Issue by ddahan** [vitalik/django-ninja#875]
Hi there! I have a  Django model named `Badge` with fields these fields: `name`, `expiration`, `is_active`

I want to let the user modify `expiration` and/or `is_active` fields. I wrote this schema:

```python
class BadgeSchemaInUpdate(ModelSchema):
    class Config:
        model = Badge
        model_fields = ("expiration", "is_active")
        model_fields_optional = ("expiration", "is_active")
```

And this endpoint:

```python
@router.put("{id}", response=BadgeSchemaOut)
def update_badge(request, id: str, payload: BadgeSchemaInUpdate):
    """This accept partial updates by excluding unset fields."""

    badge = get_object_or_404(Badge, id=id)
    for field, value in payload.dict(exclude_unset=True).items():
        setattr(badge, field, value)
    badge.save()
    return badge
```

At this points, what's bother me is that when using this endpoint, the user is able to pass any wrong data in the payload without any error returned. For example:
- If passing `{name: "foo"}`, it will return no error, even if the name is not updated. This is misleading.
- If passing `{isactive: False}` (note the typo here), it will return no error and will let the user believe everything's fine.

How can I be more restrictive about the payload content?
I found a [Pydantic option](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra) for this but it seems to have no effect when setting it in Django ninja.

Thanks for you help!

**Comment by vitalik** [comment]
@ddahan 

try extra=forbid ? (I'm not sure if it worked in older pydantic, but in django-ninja 1.0b2 this is working)


```Python
class BadgeSchemaInUpdate(ModelSchema):
    class Config:
        model = Badge
        model_fields = ("expiration", "is_active")
        model_fields_optional = ("expiration", "is_active")
        extra = "forbid" # <--- !!!
```

**Comment by ddahan** [comment]
Ohhh ok it was that simple! Thanks a lot pour the quick answer 🥇 
Should we add an example in the documentation (unless I missed it)?

**Comment by vitalik** [comment]
Sure, PR  would be nice :)

**Comment by ddahan** [comment]
Sure! https://github.com/vitalik/django-ninja/pull/877
