### ISSUE TITLE
[BUG] OpenAPI schema generator error with ManyToMany UUID 

### ISSUE THREAD

**Issue by jam13** [vitalik/django-ninja#881]
**Describe the bug**
I have a `Project` model with a many_to_many relationship to `User` called `user`. Both models use UUID as pk.

Created a schema like this:
```Python
class ProjectOut(ModelSchema):
    class Config:
        model = Project
        model_fields = "__all__"
```

and an endpoint like this:
```Python
@api.get("/projects", response=List[ProjectOut])
def list_projects(request):
    return get_list_or_404(Project, user=request.user)
```

This seems to work as expected, with a list of UUID strings returned for `user`. However when trying to load the OpenAPI docs I get an error in the brower and log output:

```
...
  File "/opt/venv/lib/python3.11/site-packages/ninja/orm/fields.py", line 88, in __get_pydantic_json_schema__
    json_type = {
                ^
KeyError: <class 'uuid.UUID'>
```

If I exclude the `user` field, then OpenAPI is fine, and I can return the list of UUIDs by using resolve:
```Python
user: List[UUID]
@staticmethod
def resolve_user(obj):
    return [str(u.id) for u in obj.user.all()]
```

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.2
 - Django-Ninja version: 1.0b2
 - Pydantic version: 2.4

**Comment by gokaykucuk** [comment]
A simple addition of UUID type to ninja/orm/fields.py seems like working for me atm. But I haven't tested anything properly.
```
    json_type = {
        int: "integer",
        str: "string",
        float: "number",
        UUID: "string",
    }[type_]
```
