### ISSUE TITLE
[Feature request] simple way to generate error schema from validation error for models

### ISSUE THREAD

**Issue by RileyMathews** [vitalik/django-ninja#884]
**Is your feature request related to a problem? Please describe.**
Generating schemas from model fields is super easy and a huge boon to productivity. However, on the other side of the happy path I have not had good luck finding a good pattern on how to map model errors into a schema. The best I've been able to do would be something like this...

```python
class Widget(Model):
    name = models.TextField()
    amount = models.IntegerField()

class WidgetErrorSchema(Schema):
    name = Optional[List[str]]
    amount = Optional[List[str]]

@api.post("/widgets", response={200: WidgetModelSchema, 400: WidgetErrorSchema})
def create_widget(request, payload: WidgetCreateSchema):
    widget = Widget(**payload.dict())
    try:
        widget.full_clean()
    except ValidationError as e:
        print(e.message_dict)
        return 400, e.messages_dict

    widget.save()
    return widget
```

But this approach has at least one gotcha to it that I have run into. If your validation puts an error on the '__all__' field of the model error dictionary that will not come across in this schema. My immediate reaction was to try...

```python
class WidgetErrorSchema(Schema):
    __all__: Optional[List[str]]
    name = Optional[List[str]]
    amount = Optional[List[str]]
```

But that did not appear to work either. What I actually had to do was...
```python
class WidgetErrorSchema(Schema):
    all: Optional[List[str]]
    name = Optional[List[str]]
    amount = Optional[List[str]]

# ... abbreviated code
def create_widget(request, payload: WidgetCreateSchema):
    widget = Widget(**payload.dict())
    try:
        widget.full_clean()
    except ValidationError as e:
        print(e.message_dict)
        return 400, {"all": e.message_dict.get("__all__", []), **e.message_dict}

    # ...
```
And that 'works' but feels very hacky and error-prone to duplicate that pattern across multiple model CRUD endpoints.

**Describe the solution you'd like**
It would be nice if Ninja had a built-in way to generate a schema for a model's validation errors similar to how you can generate a model fields schema.

**Comment by vitalik** [comment]
@RileyMathews I guess you can try the following

1) use [custom exception handlers](https://django-ninja.dev/guides/errors/) to catch django validation errors globally:


```Python
from django.core.exceptions import ValidationError as DjangoValidationError
api = NinjaAPI()

@api.exception_handler(DjangoValidationError)
def django_model_validatoin(request, exc):
    return api.create_response(
        request,
        {"all": exc.message_dict.get("__all__", []), **exc.message_dict},
        status=400,
    )

```

Then you can simplify your view function to just this:

```Python
def create_widget(request, payload: WidgetCreateSchema):
    widget = Widget(**payload.dict())
    widget.full_clean() # <-- this will throw error that will be handled by api.exception_handler
```

there is just one issue - your error does not get openapi documented


if you need to do that - you can override router to automatically add 401 code to all views 

something like this:

```Python
class MyRouter(Router)
    def api_operation(self, methods, path, **kwargs):
        response = kwargs.get('response')
        if isinstance(response, dict):
               response[400] = WidgetErrorSchema
        # you might need handle other cases response == NOT_SET or response == some-type
        return super().api_operation(methods, path, **kwargs)

```

**Comment by RileyMathews** [comment]
@vitalik That works for my use case! The schema is nice but I'm not too worried about automatic documentation for API errors yet. And actually doing it that way the '__all__' key does show up in response just fine so its really even simpler that way. Thanks for the tip!
