### ISSUE TITLE
Overriding the validate method for Django Ninja Schema and call the base model's validate method

### ISSUE THREAD

**Issue by anandshende** [vitalik/django-ninja#891]
Hi, 
I wanted to add some custom validations in my [API Input Schema](https://django-ninja.dev/guides/input/body/). I also want to use the default validations given by Django Ninja.

I tried the following code, but nothing seems to work:
```
from ninja import Schema

class SampleUser(Schema):
    user_id: str
    user_name: str
    
    def validate(cls, value):
        super(cls,value)
        custom_validations(cls.user_id, cls.user_name)
```
The above code is results in [ninja.errors.ValidationError](https://django-ninja.dev/guides/errors/#ninjaerrorsvalidationerror).

Thanks in advance.

**Comment by Vr3n** [comment]
Refer [This comment](https://github.com/vitalik/django-ninja/issues/631#issuecomment-1689701260) it uses the [Inbuilt Pydantic Validator to enable writing custom validators for fields.](https://docs.pydantic.dev/1.10/usage/validators/)

**Comment by anandshende** [comment]
Thank you @Vr3n .
This worked like a Charm :+1:
