### ISSUE TITLE
How to NOT return a field defined in schema if it is empty

### ISSUE THREAD

**Issue by JFeldaca** [vitalik/django-ninja#893]
Schema:
```python
class NoContentSchema(Schema):
    status: bool
    message: str = None
```

API:
```python
@api.get('/test-not-content')
def get_test(request):
    return 204, {'status': True}


@api.get('/test-not-content-message')
def get_test_message(request):
    return 204, {'status': True, 'message': 'No content'}
```

Setup project:
Django==4.1.0
django-cors-headers==3.13.0
django-environ==0.9.0
django-jazzmin==2.6.0
django-ninja==0.21.0
django-silk==5.0.1
mysqlclient==2.1.1
mysql-connector-python==8.0.30
uWSGI

Hi!

I'm trying to make a schema not return a field if it is marked as optional.

As you can see, I have a schema with a single field (message) that, in some situations can contain a message and in others not.

I would like that, when I make a return 204, {"status":True} would not be sent as a response
```
{
     "status": true,
     "message": null
}
```

but simply {"status": true}.

How could I do it?

All the best,

**Comment by vitalik** [comment]
@JFeldaca try `exclude_none` param:

```Python
@api.get('/', response={204: NoContentSchema}, exclude_none=True)
def get_test(request):
    return 204, {'status': True}
```

**Comment by JFeldaca** [comment]
Hi @vitalik !

Thanks! It works like a charm
