### ISSUE TITLE
Django-nijia orm occur MySQL server has gone away

### ISSUE THREAD

**Issue by chengdonglin** [vitalik/django-ninja#894]
connect some mysql database, Java has not this propblem, and the django-nijia has occur has occur, I think maybe seeting has cause , how can I fix these question?

**Comment by baseplate-admin** [comment]
Did you run migrations that may have deleted the rows ?

**Comment by chengdonglin** [comment]
> @chengdonglin are you using ORM in web application ? or in some script ? do you ave full traceback ?
not full traceback, I see only the message is :  MySQL server has gone away

**Comment by chengdonglin** [comment]
> Did you run migrations that may have deleted the rows ?

no, the error may occur after running one day or three day

**Comment by vitalik** [comment]
hard to tell at this point - need more details/code example etc
