### ISSUE TITLE
Expose OpenAPI `path_prefix` in NinjaAPI contstructor

### ISSUE THREAD

**Issue by scott-8** [vitalik/django-ninja#898]
**Is your feature request related to a problem? Please describe.**
`get_openapi_schema` takes the `path_prefix` parameter, but the only way I can see to change it is to subclass `NinjaAPI`. Our use case is that we want to set the prefix to an empty string, and customize the path in the docs with the `servers` parameter.

**Describe the solution you'd like**
Something like this would be nice:
```python
api = NinjaAPI(
    servers=[
        {"url": "/api", "description": "Test"},
    ],
    openapi_prefix="",
)
```

```python
    def get_openapi_schema(
        self,
        *,
        path_prefix: Optional[str] = None,
        path_params: Optional[DictStrAny] = None,
    ) -> OpenAPISchema:
        if path_prefix is not None:
            prefix = path_prefix
        elif self.openapi_prefix is not None:
            prefix = self.openapi_prefix
        else:
            prefix = self.get_root_path(path_params or {})
        return get_schema(api=self, path_prefix=prefix)
```

**Comment by vitalik** [comment]
@scott-8 

subsclassing NinjaAPI is actually a recomended way - there lot of features that users would like to put as argument - but in that case it will be a million init arguments ;)
