### ISSUE TITLE
auth token key issue

### ISSUE THREAD

**Issue by bugiebhavya** [vitalik/django-ninja#9]
isAuthenticated token generation is by done by user manually by creating tables? is there any predefined method to get auth token or it is to be done manually

Type a message

quoting from docs : 
from someapp.models import Client
"and find a Client in database that corresponds to this key. The Client instance will be set to request.auth attribu"

**Comment by vitalik** [comment]
hey @bugiebhavya 

I guess I would need more details about your case to answer correctly..


but in general you are free to pick any token storage or procdure


in this example https://django-ninja.rest-framework.com/tutorial/authentication/#in-query - indeed token is stored in table clients (field key) and just shared with user

you can use also jwt to avoid any storage:


```python
from ninja.security import APIKeyHeader

@api.post('/token')
def get_token(request):
      # ... authenticate somehow
      return jwt token



class TokenAuth(APIKeyHeader):
    param_name = "X-API-Token"

    def authenticate(self, request, key):
       try:
            data = jwt.decode(key, secret)
       except JWTErrror:
             return None
        return data

@api.post('/somemethod', auth=TokenAuth())
def somemethod(request):
       auth_data = request.auth

```

**Comment by bugiebhavya** [comment]
Thanks,
One more thing, i want to apply custom validation in schema, can i write a validate method just like we do in serializers for this purpose?
like i want to check if email and password exist in database! can i achieve this in schema?
class UserLogin(Schema):
    email: str
    password: str
    
    def validate(self, attrs):
    		# if mail exist
    	return attrs


@authapi.get("auth/login")
def login(request, user_login: UserLogin):

and how to get if our Schema is Invalid, just like in DRF if serializer is not valid

**Comment by vitalik** [comment]
@bugiebhavya 

yes it is possible...

Schema is using [pydantic models under the hood ](https://pydantic-docs.helpmanual.io/usage/validators/)

```python
from pydantic import validator


class UserLogin(Schema):
    email: str
    password: str

    @validator('password')
    def check_auth(cls, v, values, **kwargs):
        user = User.objects.get(email=values['email'])  # <-- try/except here
        
        if not user.check_password(values['password']):
            raise ValueError('User or password does not match')
        return v

**Comment by bugiebhavya** [comment]
thanks it helped

**Comment by asaff1** [comment]
how this is work in testing? I'm testing with pytest-django and it doesn't seem to work

**Comment by vitalik** [comment]
> how this works in testing? I'm testing with pytest-django and it doesn't seem to work

do you have example code ?
