### ISSUE TITLE
[BUG] Optional[List[str]] does not show up in SwaggerUI as a list

### ISSUE THREAD

**Issue by SonQBChau** [vitalik/django-ninja#902]
**Describe the bug**
I have a schema with an optional list of strings, but SwaggerUI only shows a single textfield as input. 
```
class CustomerFilterSchema(FilterSchema):
    alias: Optional[List[str]] = Field(None)
```
There is no option to add multiple inputs here (as it should):
<img width="756" alt="Screenshot 2023-11-02 at 12 05 28 PM" src="https://github.com/vitalik/django-ninja/assets/12553570/5f499b7e-36ed-4cc4-8596-5c9bbcb7ad30">

However, when using `List[str]`, the list displays correctly.
```
class CustomerFilterSchema(FilterSchema):
    alias: List[str] = Field(None)
```
The UI shows up:
<img width="756" alt="Screenshot 2023-11-02 at 12 06 01 PM" src="https://github.com/vitalik/django-ninja/assets/12553570/7e458e20-d1d4-485c-b20d-393c4c78a235">

Is this expected behaviour?

**Versions:**
 - Python version: 3.11.1
 - Django version: 4.2.3
 - Django-Ninja version: 1.0b2
 - Pydantic version: 2.4.2

**Comment by vitalik** [comment]
@SonQBChau 

I think this is how generally swagger behavess when you need to pass acutal "null" value

maybe in your case would make more sense to set default as empty list ?

```Python
class CustomerFilterSchema(FilterSchema):
    alias: List[str] = []
```

**Comment by SonQBChau** [comment]
Thank you, I will do that. It just tripped me since it didn't show up and I thought it was a bug.
