### ISSUE TITLE
403 Forbidden (CSRF token missing) when trying to use Django Auth

### ISSUE THREAD

**Issue by pzantoniak** [vitalik/django-ninja#908]
I'm trying to use Django Ninja with Django Authentication with a Vue frontend. I can log in, but I'm having issues with the CSRF token when I try to make a post request. I get a 403 Forbidden (CSRF token missing) error in the console.

I'm not a very experienced programmer, so it's possible I'm doing something completely wrong.

Here's the code in my users/api.py file with the router:

```
from ninja import NinjaAPI, Schema, Router
from ninja.security import django_auth, django_auth_superuser, HttpBearer

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt, csrf_protect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpRequest, HttpResponse

from users.models import User

userRouter = Router(auth=django_auth,)

@userRouter.post("/login", auth=None)
@csrf_exempt
def userlogin(request, username:str="admin", password:str="password"):
    if request.user.is_authenticated:
         return request.user.username + " is already logged in."
    else:
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return user.get_username() + " has logged in."
        else:
            return "incorrect credentials"

@userRouter.post("/howdy", auth=django_auth)
def howdy(request):
    return "Howdy from the api POST method!"
```

and here's the main api.py file where I connect the routers to the api:

```
from ninja import NinjaAPI
from ninja.security import django_auth, HttpBearer

from users.api import userRouter

api = NinjaAPI(csrf=True,auth=django_auth)

api.add_router("/users/",userRouter)
```

This is the response I get:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <title>403 Forbidden</title>
  <style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; color:#000; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    #info { background:#f6f6f6; }
    #info ul { margin: 0.5em 4em; }
    #info p, #summary p { padding-top:10px; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
  </style>
</head>
<body>
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>


</div>

<div id="info">
  <h2>Help</h2>
    
    <p>Reason given for failure:</p>
    <pre>
    CSRF token missing.
    </pre>
    

  <p>In general, this can occur when there is a genuine Cross Site Request Forgery, or when
  <a
  href="https://docs.djangoproject.com/en/4.2/ref/csrf/">Django’s
  CSRF mechanism</a> has not been used correctly.  For POST forms, you need to
  ensure:</p>

  <ul>
    <li>Your browser is accepting cookies.</li>

    <li>The view function passes a <code>request</code> to the template’s <a
    href="https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render"><code>render</code></a>
    method.</li>

    <li>In the template, there is a <code>{% csrf_token
    %}</code> template tag inside each POST form that
    targets an internal URL.</li>

    <li>If you are not using <code>CsrfViewMiddleware</code>, then you must use
    <code>csrf_protect</code> on any views that use the <code>csrf_token</code>
    template tag, as well as those that accept the POST data.</li>

    <li>The form has a valid CSRF token. After logging in in another browser
    tab or hitting the back button after a login, you may need to reload the
    page with the form, because the token is rotated after a login.</li>
  </ul>

  <p>You’re seeing the help section of this page because you have <code>DEBUG =
  True</code> in your Django settings file. Change that to <code>False</code>,
  and only the initial error message will be displayed.  </p>

  <p>You can customize this page using the CSRF_FAILURE_VIEW setting.</p>
</div>

</body>
</html>
```
Also, here's the POST request using axios from my Vue frontend:

```
axios.defaults.withCredentials = true
axios.defaults.xsrfCookieName = 'csrftoken'
axios.defaults.xsrfHeaderName = "X-CSRFToken"

async function postAxios() {
  const response = await axios.post("http://127.0.0.1:8000/api/users/howdy",
  )
}
```

I think this is an issue with getting, storing, and passing the CSRF token correctly. Sometimes when I log in, it will save the CSRF token in cookies and sometimes it won't (I get a 401 Unauthorized error when that happens, but it's not a consistent failure mode). Can someone point me in the right direction, maybe an example project with Django Auth working so I can see how it's done? I've been trying for hours to resolve this. Thank you.

**Comment by elnygren** [comment]
You are not sending the CSRF Token in your axios.post call.

https://docs.djangoproject.com/en/4.2/howto/csrf/#using-csrf-protection-with-ajax

**Comment by vitalik** [comment]
@pzantoniak 
 
for cookie based authentications you need to pass CSRF with you request 

I think with axios you can simply do it like this:
```
axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
axios.defaults.xsrfCookieName = "csrftoken";
```

Docs:

 - https://axios-http.com/docs/req_config
 - https://docs.djangoproject.com/en/4.2/ref/csrf/

**Comment by pzantoniak** [comment]
> @pzantoniak
> 
> for cookie based authentications you need to pass CSRF with you request
> 
> I think with axios you can simply do it like this:
> 
> ```
> axios.defaults.xsrfHeaderName = "X-CSRFTOKEN";
> axios.defaults.xsrfCookieName = "csrftoken";
> ```
> 
> Docs:
> 
> * https://axios-http.com/docs/req_config
> * https://docs.djangoproject.com/en/4.2/ref/csrf/

I should have included my axios options in the original post, my bad. I already have those headers included.
I have these defaults set:

```
axios.defaults.withCredentials = true
axios.defaults.xsrfCookieName = 'csrftoken'
axios.defaults.xsrfHeaderName = "X-CSRFToken"
```




> You are not sending the CSRF Token in your axios.post call.
> 
> https://docs.djangoproject.com/en/4.2/howto/csrf/#using-csrf-protection-with-ajax

I tried this and it did not work. getCookie('csrftoken') returns a null value, though I can see the csrftoken cookie in Chrome DevTools under application.

**Comment by vitalik** [comment]
@pzantoniak 
is `http://127.0.0.1:8000/api/users/howdy` is the same host (127.0.0.1) that you are running your frontend ? 

maybe you test from 127.0.0.1:3000? or localhost:8000 ?

**Comment by pzantoniak** [comment]
I just figured it out.

> @pzantoniak is `http://127.0.0.1:8000/api/users/howdy` is the same host (127.0.0.1) that you are running your frontend ?
> 
> maybe you test from 127.0.0.1:3000? or localhost:8000 ?

This was part of the issue. When running my Django server, I had to use `py manage.py runserver localhost:8000`

I needed these in my settings.py file:

```
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = ['http://localhost:5173']

CSRF_TRUSTED_ORIGINS = ['http://localhost:5173']

SESSION_COOKIE_DOMAIN='localhost'
```

I added an api call that returns an HttpResponse to extract the CSRF token:

```
@userRouter.get("/getcsrftoken",auth=None)
@ensure_csrf_cookie
def getcsrf(request):
    response = HttpResponse()
    return response
```

And here is the JavaScript from my Vue file:

```
const csrftoken = ref("")
const user = ref("")

const apicaller = axios.create({
  withCredentials: true,
  })

getcsrfToken()

async function getcsrfToken(){
  const response = await apicaller.get("http://localhost:8000/api/users/getcsrftoken")
  csrftoken.value = getCookie('csrftoken') ?? ""  
  apicaller.defaults.headers.common['X-CSRFTOKEN'] = csrftoken.value
  return 
}

async function postAxios() {
  const response = await apicaller.post("http://localhost:8000/api/users/howdy")
  console.log(response.data)
}

async function loginTestAxios() {
  const payload = {
    username: 'admin',
    password: 'password'
  }
  const response = await apicaller.post("http://localhost:8000/api/users/login",{
    data: payload
  })
  user.value = response.data
  console.log(user.value)
}
```

The `getCookie()` function is from typescript-cookie. Setting the Axios default xsrfCookieName and xsrfHeaderName didn't do anything, so I had to force the header with  `apicaller.defaults.headers.common['X-CSRFTOKEN'] = csrftoken.value`. 

I hope this can help anyone that runs into a similar issue.

Thank you for your help @vitalik.
