### ISSUE TITLE
decimal.Decimal is `number` in the OpenAPI schema but returned as a string

### ISSUE THREAD

**Issue by elnygren** [vitalik/django-ninja#909]
Which is awkward if trusting the generated TypeScript types.

Workarounds:
- flip the Schema type type to `float` instead of `decimal.Decimal`
- flip the Schema type to `str` and validate carefully

### Versions
- latest everything

**Comment by vitalik** [comment]
@elnygren 

as for decimal - this is a pydantic convention - https://docs.pydantic.dev/latest/api/standard_library_types/#decimaldecimal

(and in pydantic2 you can change that behaviour)

**Comment by elnygren** [comment]
@vitalik is there a way to make Django Ninja / Pydantic to generate the OpenAPI schema so that decimal.Decimal python type becomes string instead of number in the OpenAPI schema? 

Right now the current behavior is just broken, because OpenAPI schema says number but returns a string.

IMO this is a real bug, not just a "convention" 🤔

**Comment by akx** [comment]
@vitalik The document you linked says

> Serialization: Pydantic serializes Decimal types as strings.

but as reported by @elnygren, the OpenAPI schema generated by Ninja says `type: number`. 

Changing Pydantic's behavior to emit floats (or more generally JSON number literals) for `Decimal`s is generally not acceptable, since JSON parsers tend to interpret JSON number literals as floating-point numbers instead of arbitrary-precision values, and that'd be likely to cause precision loss at some end.

**Comment by vitalik** [comment]
@akx @elnygren 

Not exactly - not sure what version you are referencing to - but pydantic2 marks it as **both string and number:**

```Python
from decimal import Decimal
from pydantic import BaseModel


class Data(BaseModel):
    x: Decimal


print(Data.model_json_schema())
```

outputs:
```
{'properties': {'x': {'anyOf': [{'type': 'number'}, {'type': 'string'}], 'title': 'X'}}, 'required': ['x'], 'title': 'Data', 'type': 'object'}
```
see: `'anyOf': [{'type': 'number'}, {'type': 'string'}],`

while pydantic1 gives only number

```
{"x": {"title": "X", "type": "number"}}
```

also pydantic2 lets you change that behaviour globally

**Comment by akx** [comment]
@elnygren any chance you're using pydantic 1 then?

**Comment by elnygren** [comment]
@vitalik @akx 

Latest version of django-ninja from pypi uses pydantic1. Pydantic2 is in a 1.0rc from 2 days ago?

https://pypi.org/project/django-ninja/
https://github.com/vitalik/django-ninja/blob/v0.22.2/pyproject.toml

**Comment by vitalik** [comment]
> Pydantic2 is in a 1.0rc from 2 days ago?

beta version with pydantic2 is already few months in the wild, once all parties verify RC is good - it will be tagged

**Comment by elnygren** [comment]
@vitalik awesome! I updated to 1.0rc and can confirm that this issue is fixed.

```bash
npx openapi-typescript http://localhost:8000/api/openapi.json -o ./src/schema.d.ts
```

```typescript
// schema.d.ts

       /** Price Amount */
-      price_amount: number;
+      price_amount: number | string;
```
