### ISSUE TITLE
HTTP Status Code Support

### ISSUE THREAD

**Issue by SonQBChau** [vitalik/django-ninja#912]
**Is your feature request related to a problem? Please describe.**
It would be nice if django-ninja supported a convenience feature for HTTP status codes, such as `status.HTTP_201_CREATED`, which is available in both [DRF](https://github.com/encode/django-rest-framework/blob/master/rest_framework/status.py) and [FastAPI](https://github.com/encode/starlette/blob/master/starlette/status.py).

**Describe the solution you'd like**
Built-in support for using HTTP status codes to make the code more readable and convenient.

**Comment by vitalik** [comment]
@SonQBChau 

http statuses are already in stdlib (since python 3.5)

https://docs.python.org/3/library/http.html
