### ISSUE TITLE
neo4j database

### ISSUE THREAD

**Issue by MajidHeydari** [vitalik/django-ninja#92]
What database does Django ninja support and what do I intend to use neo4j database?

**Comment by vitalik** [comment]
django-ninja is a built on top of [Django](https://www.djangoproject.com/) framework

as for neo4j - this seems the candidate to try - https://github.com/neo4j-contrib/django-neomodel

**Comment by MajidHeydari** [comment]
Would it be much easier to learn if Django Ninja had a guide with an example?

**Comment by MajidHeydari** [comment]
Would it be much easier to learn if Django Ninja had a guide with an example?
