### ISSUE TITLE
[BUG] URL dispatch bug

### ISSUE THREAD

**Issue by huangjiarong** [vitalik/django-ninja#933]
```python
@api.get("/{item_id}/")
def read_item(request, item_id: int):
    return {"id": item_id}


@api.get("/all/")
def read_item_all(request):
    return {"data": 'all'}
``` 
It's just a demo.

When I access http://127.0.0.1:8000/api/1/, the URL correctly matches the first endpoint. However, when I visit http://127.0.0.1:8000/api/all/, it throws an error: 'message': 'item_id: value is not a valid integer.' It seems to be matching http://127.0.0.1:8000/api/all/ to the first URL. When I swap the positions of the two methods, they work as expected.
Is this a bug? Currently, my workaround is to place all URLs with path parameters at the end.

When I use native Django, the following URLs match correctly:
```python
def detail(request, id):
    return HttpResponse(id)

def all_list(request):
    return HttpResponse('ok')

path("account/<int:id>/", views.detail, name="detail"),
path("account/all_list/", views.all_list, name="all_list"),
``` 

version:
python==3.9
django==4.2.6
django-ninja==0.22.2

**Comment by vitalik** [comment]
hi @huangjiarong 

that's because there are not hints to urls resolver about `/{item_id}/` - because `"all"` also matches it...

so you have two options

1) put read_item_all BEFORE read_item
2) mark item id with int (like you did with urls example):

```Python
@api.get("/{int:item_id}/")
def read_item(request, item_id: int):
    return {"id": item_id}
```

**Comment by huangjiarong** [comment]
thanks vitalik.

**Comment by huangjiarong** [comment]
> thanks vitalik.

**Comment by blue212121** [comment]
also another solution which makes sense to me is if you would use 

```
@api.get("/id/{item_id}/")
def read_item(request, item_id: int):
    return {"id": item_id}


@api.get("/all/")
def read_item_all(request):
    return {"data": 'all'}
```

which would clearly distinguish getting by id and getting all items, since the paths differ at the same level

or maybe better yet if the get request for the all, would be the root, for example:

```
@api.get("/items/{item_id}/")
def read_item(request, item_id: int):
    return {"id": item_id}


@api.get("/items")
def read_item_all(request):
    return {"data": 'all'}
```
