### ISSUE TITLE
[BUG] Documentation has a Grammar Error

### ISSUE THREAD

**Issue by benjamin-lawson** [vitalik/django-ninja#935]
**Describe the bug**
The documentation has a grammatical error on [line 192 of whatsnew_v1.md](https://github.com/vitalik/django-ninja/blob/8ca977464ba9e3bb37770d372036d0f6e063f96e/docs/docs/whatsnew_v1.md?plain=1#L192C1-L192C26). The line reads "This example do not work." but should read "This example does not work." or "This example will not work." 
**This is a non-breaking change.**

**Versions (please complete the following information):**
 - Branch: Master

**Comment by vitalik** [comment]
fixed
