### ISSUE TITLE
[BUG] Memory leak in django-ninja v1 or pydantic v2.5

### ISSUE THREAD

**Issue by Andrioden** [vitalik/django-ninja#936]
**Describe the bug**
I experience memory problems after upgrading to django-ninja v1 on my Google App Engine F1/F2 linux instances. When reverting the upgrade, the memory problem disappeared. As i was not able to reproduce the problem on my windows machine, i gave up trying to find the root problem as I then dont got easy access to memory debuggers.

Sorry for the vauge report, but i figured i'd post it here incase someone else experience it. I have reverted back and will stay there for a while hoping maybe someone fixes something.

The problem is either related to:
- Django Ninja
  - ??
  - Changing from this `filters: PlayersFilters = Query(...)` pattern to this `filters: Query[PlayersFilters]` 
- Pydantic
  - Considering Pydantic is rewritten into Rust i suspect its that.
  - Changing from this `HeroCreate.parse_obj(payload)` pattern to this `HeroCreate(**payload.dict())`
  - Changing from this `CityZoneQ.parse_obj(q))` pattern to this `CityZoneQ(**q.model_dump())`
  - Or some of the other Pydantic migration steps
- Any other part of my tech stack, but it never occured before and was made worse after upgrading due to pydantic's increased memory usage (which i read while googling this)

The behavior i see on the memory usage is this:
- Using F2 instance on GoogleAppEngine. Max 768MB.
- Before upgrading:
  - Instance starts at 550MB memory usages, heavy page refreshing bumps it to 620MB and very slow increases while spamming page refreshes. Capping at 660MB.
  - I see autoscaling of amount of instances happen
- After upgrading:
  - Instance starts at 550MB memory usage, one page refresh bumps it ~60MB, waiting and doing one refresh bumps it another ~20MB. Keep doing this, until eventually it exceeds the memory limit and GoogleAppEngine kills my instance.
  - I **dont** see autoscaling of amount of instances happen

**Versions:**
 - Python version: 3.11.3
 - Django version: 4.2.7
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.5.?

**Comment by vitalik** [comment]
Hi @Andrioden 

there have been reported higher memory consumption on pydantic2... hard to tell yet - Would be nice if you could investigate or isolate some specific code ? or try to increase instance type to see if it will stop increasing at some point ?

**Comment by Andrioden** [comment]
Before upgrading it ran fine on 360mb instances (autoscaling thou).

I will look into this again next year i think. Its not top priority right now.

**Comment by baseplate-admin** [comment]
Hi, What is your `asgi`/`wsgi` server?

**Comment by Andrioden** [comment]
wsgi, [default app engine behavior](https://cloud.google.com/appengine/docs/standard/python3/runtime#application_startup), which seems to be [gunicorn](https://gunicorn.org/)

**Comment by Andrioden** [comment]
I tried again upgrading to newest django-ninja (1.1.0) and pydantic (2.7.1). I still se a slight memory leak, but i also had a slight memory leak before upgrading so I cant conclude its due to this upgrade. Memory usage is increased.

All inn all, i will close this Issue.
