### ISSUE TITLE
[BUG] field_validator("field", mode="before")

### ISSUE THREAD

**Issue by ssandr1kka** [vitalik/django-ninja#942]
**Describe the bug**
`@field_validator("custom_room_rule_id", mode='before')`
Field validation does not happen before the pydantic validators.
In this case I would like to handle the valid uuid and display the well read message. Beforehands with pre=True it used to work now it does not. Any work arounds?

**Versions (please complete the following information):**
 - Python version: 3.10
 - Django version: 4.0
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.5.0

**Comment by vitalik** [comment]
Could you provide more code and expected behavior?

**Comment by ssandr1kka** [comment]
For example I have BaseSchema 
```
class BaseSchema(Schema):

    id: uuid.UUID

    @field_validator("id", mode="before")
    @classmethod
    def convert_uuid_to_str(cls, field_value) -> str:
        if isinstance(field_value, uuid.UUID):
            return str(field_value)
        print("hello")
        raise CustomNinjaResponseDefinedElsewhere
```
I could not get this function to execute before actual uuid validator and instead of hello I see `Input should be a valid UUID`

**Comment by ssandr1kka** [comment]
Found the culprit I was overriding the default Schema config which I missed out to remove.
