### ISSUE TITLE
Management command to output schema json

### ISSUE THREAD

**Issue by shughes-uk** [vitalik/django-ninja#947]
We're starting to use the openapi client generators. It's not too hard to just `curl` the json file in local dev, but for CI it would be slightly annoying to have to do.

It would be nice if there was a clean `python manage.py ninja-schema` that would output the json schema without having to start up gunicorn or the django dev server. I believe DRF has a similar option.

**Comment by vitalik** [comment]
Hi @shughes-uk 

it's already there - put "ninja" to INSTALLED_APPS and then you should have command:

```
python manage.py export_openapi_schema
```

**Comment by SonQBChau** [comment]
If your project has multiple apps, you might need to tell ninja the location. Replace the path to where `api = NinjaAPI()`:
```
python manage.py export_openapi_schema --api path.to.your.api | python -m json.tool > schema.json
```

**Comment by shughes-uk** [comment]
Thanks @SonQBChau @vitalik 

I had to use the --api to specify it as we do have multiple apps, before that we just `django.urls.exceptions.Resolver404`.

Nice to know this exists, I was searching the docs for an export option but didin't find it directly. Perhaps it's worth adding the part about adding "ninja" to the installed apps to the quickstart, and documenting the management command?
