### ISSUE TITLE
api doc for models.BigAutoField primary_key

### ISSUE THREAD

**Issue by shimachao** [vitalik/django-ninja#955]
my model define:
```python
class Messages(models.Model):
    id = models.BigAutoField(primary_key=True)
```
ModelSchema define:
```python
class MessageOut(ModelSchema):

    class Meta:
        model = Messages
        fields = ["id"]
```
unexpectedly，on the API/doc page, the  SCHEMA for ID is `Id (integer) or Id (null) (Id)`， instead of  `Id (integer)`.
how to make the  SCHEMA tobe `Id (integer)`?

**Comment by vitalik** [comment]
well the thing is when atofields are using - means that you may not pass it when creating an object (and should not)

basically auto fields are handling both cases input and output

if you tend to use this schema only for output - then I guess it's better to mark it on schema as required:

```Python
class MessageOut(ModelSchema):
    id: int

    class Meta:
        model = Messages
        fields = [...]
```

**Comment by brendan-morin** [comment]
It may be worth documenting this workaround in https://django-ninja.dev/guides/response/django-pydantic/. Because Django `models.Model` populates the id field as an AutoField by default, anyone returning `id` fields really anywhere will run into this.
