### ISSUE TITLE
[BUG] filter() does not behavior like document described

### ISSUE THREAD

**Issue by samuelchen** [vitalik/django-ninja#968]
**Describe the bug**
FilterSchema.filter() method will use field filter ONLY if custome_filter() not implemented. But in document, it shows "The custom_expression method **takes precedence over** any other definitions described **earlier**, including filter_<fieldname> methods."

My understanding is "when there is `customer_expression`, we evaluate it first. Then we will append/combine others".

I am not native English speaker. I checked with GPT.
https://django-ninja.dev/guides/input/filtering/

point me out if I have misunderstanding.
Thank you guys.

![image](https://github.com/vitalik/django-ninja/assets/22304/604b94ac-c7ee-4278-bfdb-e90fb426ac40)
![image](https://github.com/vitalik/django-ninja/assets/22304/d12d5a77-572f-44c7-bd85-eb7a6e83253b)
![image](https://github.com/vitalik/django-ninja/assets/22304/e4b552fa-e358-490f-b275-9d959d191b1e)

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.2
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.1.1

**Comment by vitalik** [comment]
I am not native English speaker as well :)

but what is happening - if you override custom_expression - then only queryt returned by  this method will be used to filter out objects

**Comment by l1b3r** [comment]
I apologize for the incorrect wording in the documentation. You are correct, if  a subclass of `FilterSchema` defines a `custom_expression` method, all other filtering definitions are completely **ignored**.

**Comment by samuelchen** [comment]
thanks for you response. @l1b3r
