### ISSUE TITLE
Change root_url for serving openapi.json behind a reverse proxy

### ISSUE THREAD

**Issue by stvdrsch** [vitalik/django-ninja#969]
I'm encountering this exact problem: https://fastapi.tiangolo.com/advanced/behind-a-proxy/#proxy-with-a-stripped-path-prefix

Proxy is on: `/inspection/docs`
on server:` /api/docs`

So I need to configure it in such a way that openapi.json is served on /inspection and not /api . I tried doing it through urls_namespace but no succes. I get this 

<img width="635" alt="image" src="https://github.com/vitalik/django-ninja/assets/8971598/e470f11f-b391-4409-9929-7689044c2fc0">

Which is correct as I can see that the `openapi.json` definition is served on proxy `/inspection/openapi.json` and not `/api/openapi.json`. From the fastapi documentation it looks like I should change the root_url but that doesn't seem to work through NinjaApi.

**Code**
```
api = NinjaAPI(
    auth=authentications,
    title="Inspection API",
    description="This is an api that handles everything concerning the inspection of an asset on a trade-in",
    docs_decorator=docs_decorator,
    urls_namespace='inspection'
)
```

**Comment by vitalik** [comment]
@stvdrsch well the root path is determined by `urls.py`

so I guess wha you can do is in urls.py do it like this:

```Python

urlpatterns = [
    ...
    path("inspection/", api.urls),  # <---------- !
]
```

**Comment by stvdrsch** [comment]
There's no way to change the path root path where openapi.json is served without changing the root path for all my other endpoints?

**Comment by vitalik** [comment]
@stvdrsch 

You did not mention what version you use - but if you use ninja v1.x you can override Docs class : 

```Python
from ninja import Swagger

class MySwagger(Swagger):
     def get_openapi_url(self, *a, **kw):
          return '/inspection/openapi.json'

api = NinjaAPI(docs=MySwagger())
```

for v 0.x you need to put `ninja` to INSTALLED_APPS and override template `ninja/swagger.html`:

(see: `data-openapi-url`)

```HTML
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link type="text/css" rel="stylesheet" href="{% static 'ninja/swagger-ui.css' %}">
    <link rel="shortcut icon" href="{% static 'ninja/favicon.png' %}">
    <title>{{ api.title }}</title>
</head>
<body
    data-openapi-url="/inspection/openapi.json"
    data-csrf-token="{% if api.csrf %}{{ csrf_token }}{% endif %}"
    data-api-csrf="{{ api.csrf|default:"" }}">
    
    <div id="swagger-ui"></div>

    <script src="{% static 'ninja/swagger-ui-bundle.js' %}"></script>
    <script src="{% static 'ninja/swagger-ui-init.js' %}"></script>

</body>
</html>
```

**Comment by stvdrsch** [comment]
I'll upgrade to try this out. Thanks for the great responsiveness!
