### ISSUE TITLE
[BUG] pagination does not support async view

### ISSUE THREAD

**Issue by samuelchen** [vitalik/django-ninja#977]
**Describe the bug**
I created async APIs with ninja pagination. error occurs as below.
The qs passed into pagination class is coroutine. 

![image](https://github.com/vitalik/django-ninja/assets/22304/30f00926-5117-4da5-8d72-aa69b8fe0432)

**Versions (please complete the following information):**
 - Python version: 3.11
 - Django version: 4.2
 - Django-Ninja version: 1.0.1
 - Pydantic version: 2.1.1

**Comment by vitalik** [comment]
duplicate #547
