### ISSUE TITLE
[question] Throttling / Rate Limiting

### ISSUE THREAD

**Issue by ifxory-plugins** [vitalik/django-ninja#99]
I'm building API with django.

And I needed to make a restriction for calls to it. So that the user can make requests only once every 10 seconds, for example. Is it possible to do this and how?

**Comment by vitalik** [comment]
Hi @ifxory-plugins 

well there are no out of the box solution at the moment

but you can create some custom decorator function and do some rate limiting...

```Python
from functools import wraps

...
api = NinjaAPI()


def ratelimit(func):
    @wraps(func)
    def wrapper(request, *a, **kw):      
         # write here some rate limit logic    <---------------------------------
         # if get_redis_key is > some_value:
         #      return HttpResponse(420, "Too many requests")
        return func(request, *a, **kw)

    return wrapper


@api.get("/articles")
@ratelimit
def list_articles(request):
    return []
```

**Comment by Jihadik** [comment]
I think this issue worth renaming to Throttling / Rate Limiting for better discoverability.
