### ISSUE TITLE
how to set request.user like `django rest framework`?

### ISSUE THREAD

**Issue by kosuke-zhang** [vitalik/django-ninja#990]
I can get request.user from django rest framework, how to do in ninja?

```python
class GlobalAuth(HttpBearer):
    def authenticate(self, request: HttpRequest, token: str):
        user = xxx.authenticate(token)
        request.user = user
        if user.is_anonymous:
            return False
        return True
```

`api = NinjaAPI(auth=GlobalAuth())` does not suitable for my needs, it will return 401 when user is AnonymousUser, I don't want to set the return value of this function to true all the time, so the request.auth is invalid.

<img width="839" alt="截屏2023-12-09 15 27 17" src="https://github.com/vitalik/django-ninja/assets/30019034/b5dd8612-7c3b-4493-8258-29451e1c314d">

![whiteboard_exported_image](https://github.com/vitalik/django-ninja/assets/30019034/87de2002-af28-40ff-aeaa-532d111b3f26)

**Comment by kosuke-zhang** [comment]
I also don't want to set it in django middleware, which will affect our original rest framework api.

**Comment by OtherBarry** [comment]
In it's current form, GlobalAuth will set request.user to the authenticated user, and set request.auth to True if the user is not anonymous, or false (and also return 401) if the user is anonymous.

The way auth works is:
- The returned value is set as the request's `auth` property
- If the returned value is falsey, endpoints using the auth will return 401

You can also attach whatever other data you want to the request object, as the same instance will be passed to the api functions. It can get a bit messy with type hinting, but nothing a custom type class can't fix, as shown in the docs.

I'm not quite clear on what behaviour you are after that isn't being met by the existing GlobalAuth function.

**Comment by jellis18** [comment]
Are you asking about what logic you would need to do in `xxx.authenticate` to get the user. I've implemented something like this and I decode the token, extract certain claims (for me it was an email claim) that you can use to look up the user and set. Something like this
```python
class JwtAuth(HttpBearer): 
    def authenticate(self, request: HttpRequest, token: str) -> Dict[str, Any]:
        try:
            payload = jwt.decode(token, options={"verify_signature": False})
        except Exception as e:
            logger.exception("Error decoding token")
            raise HttpError(HTTPStatus.UNAUTHORIZED, "Error decoding token") from e

        try:
            user = self._get_user(request, payload)
        except Exception as e:
            logger.exception("Error getting user")
            raise HttpError(HTTPStatus.UNAUTHORIZED, "Error getting user") from e

        request.user = user 
        return payload
```
Where `_get_user` looks up the user by email from the token payload. I'm not verifying the token here because I use an API gateway but you could verify here as well

**Comment by vitalik** [comment]
@kosuke-zhang so what's your goal ?  do anonymous user have access to you API ?

**Comment by kosuke-zhang** [comment]
> @kosuke-zhang so what's your goal ? do anonymous user have access to you API ?

Yes, anyone can access my api, but I need to know the identity of these people, is anonymous or is authenticated

**Comment by kosuke-zhang** [comment]
@vitalik Thank you. I get it, the key to the problem is to return the user object, not the Boolean!

**Comment by benjaoming** [comment]
When trying to define endpoints with anonymous access, I also ran into this issue.

The solution is to create two authentication callables. One that uses the token, and then a second fallback that allows access as an anonymous user.

For instance:

```python
class AuthBearer(HttpBearer):
    def authenticate(self, request: HttpRequest, token: str=None):
        if not token:
            raise InvalidToken()
        try:
            user = User.objects.get(token=token)
        except User.DoesNotExist:
            raise InvalidToken()
        request.user = user
        return user

def anonymous_fallback(request):
    user = AnonymousUser()
    request.user = user
    return user

api = NinjaAPI(auth=[AuthBearer(), anonymous_fallback])
```

Please let me know if there's something I've misunderstood :+1: Otherwise, I can add it to the docs.
