### ISSUE TITLE
How to calculate the time spent by ninja on data validation？

### ISSUE THREAD

**Issue by shimachao** [vitalik/django-ninja#991]

**Comment by baseplate-admin** [comment]
[`django-cprofile-middleware`](https://pypi.org/project/django-cprofile-middleware/)

**Comment by shimachao** [comment]
> [`django-cprofile-middleware`](https://pypi.org/project/django-cprofile-middleware/)
It seems that it is not suitable for django 4
AttributeError: 'ProfilerMiddleware' object has no attribute 'profiler'

**Comment by baseplate-admin** [comment]
> > [`django-cprofile-middleware`](https://pypi.org/project/django-cprofile-middleware/)
> 
> It seems that it is not suitable for django 4

I been using it for django 5.. While the repository is not updated, it still works.

**Comment by shimachao** [comment]
> > > [`django-cprofile-middleware`](https://pypi.org/project/django-cprofile-middleware/)
> > 
> > 
> > It seems that it is not suitable for django 4
> 
> I been using it for django 5.. While the repository is not updated, it still works.

127.0.0.1:55712 - - [09/Dec/2023:21:13:29] "GET /api/messages/?prof" 200 254
Internal Server Error: /api/messages
Traceback (most recent call last):
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/django/core/handlers/base.py", line 337, in check_response
    raise ValueError(
ValueError: The view ninja.operation.method.__call__ didn't return an HttpResponse object. It returned an unawaited coroutine instead. You may need to add an 'await' into your view.
2023-12-09 21:13:34,349 ERROR    Internal Server Error: /api/messages
Traceback (most recent call last):
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/django/core/handlers/base.py", line 265, in _get_response_async
    self.check_response(response, callback)
  File "/home/chao/message_center_django/env311/lib/python3.11/site-packages/django/core/handlers/base.py", line 337, in check_response
    raise ValueError(
ValueError: The view ninja.operation.method.__call__ didn't return an HttpResponse object. It returned an unawaited coroutine instead. You may need to add an 'await' into your view.

**Comment by baseplate-admin** [comment]
Apologises, the project i work on uses wsgi. Since `django-cprofile-middleware` is not maintained, i see 3 options 
1. Use `timeit` to monitor the wait time between validation logic ( best bet, requires more effort ) 
2. Use `django-silk`, `django-debug-toolbar` ( medium bet, you cant get precise timing but you get a rough idea for each endpoint ) 
3. Port `django-cprofile-middleware` to asgi ( uh, it’s a bit of work to get things updated )

**Comment by vitalik** [comment]
@shimachao 

to calculate validation time - you need to get time of the start of request and substract the time when operation started (validated already)

here is an example decorator called `track_time` that will print total request time, and validation time:


```Python

def request_wrapper(func):
    # Logs and prints time by request
    @wraps(func)
    def wrapper(request, *args, **kwargs):
        request._req_start = time.monotonic()
        response = func(request, *args, **kwargs)
        total_time = time.monotonic() - request._req_start
        validation_time = request._operation_start - request._req_start
        print(f'Total time: {total_time:0.4}. Validation time: {validation_time:0.4}')
        return response

    return wrapper


def operation_wrapper(func):
    # Logs time when operation is called (after validation)
    @wraps(func)
    def wrapper(request, *args, **kwargs):
        request._operation_start = time.monotonic()
        return func(request, *args, **kwargs)

    return wrapper


def track_time(func):
    func = operation_wrapper(func)
    func = decorate_view(request_wrapper)(func)
    return func


api = NinjaAPI()


class SomeSchema(Schema):
    id: int
    name: str

    @staticmethod
    def resolve_name(obj):
        time.sleep(0.3)  # emulating hard work in validation
        return 'hello'


@api.post('/some')
@track_time  # <------------------------- !!!!!
def some(request, data: SomeSchema):
    time.sleep(0.3)  # emulating hard work in operation
    return data.dict()

```


```
```

**Comment by shimachao** [comment]
> @shimachao
> 
> to calculate validation time - you need to get time of the start of request and substract the time when operation started (validated already)
> 
> here is an example decorator called `track_time` that will print total request time, and validation time:
> 
> ```python
> def request_wrapper(func):
>     # Logs and prints time by request
>     @wraps(func)
>     def wrapper(request, *args, **kwargs):
>         request._req_start = time.monotonic()
>         response = func(request, *args, **kwargs)
>         total_time = time.monotonic() - request._req_start
>         validation_time = request._operation_start - request._req_start
>         print(f'Total time: {total_time:0.4}s. Validation time: {validation_time:0.4}s.')
>         return response
> 
>     return wrapper
> 
> 
> def operation_wrapper(func):
>     # Logs time when operation is called (after validation)
>     @wraps(func)
>     def wrapper(request, *args, **kwargs):
>         request._operation_start = time.monotonic()
>         return func(request, *args, **kwargs)
> 
>     return wrapper
> 
> 
> def track_time(func):
>     func = operation_wrapper(func)
>     func = decorate_view(request_wrapper)(func)
>     return func
> 
> 
> api = NinjaAPI()
> 
> 
> class SomeSchema(Schema):
>     id: int
>     name: str
> 
>     @staticmethod
>     def resolve_name(obj):
>         time.sleep(0.3)  # emulating hard work in validation
>         return 'hello'
> 
> 
> @api.post('/some')
> @track_time  # <------------------------- !!!!!
> def some(request, data: SomeSchema):
>     time.sleep(0.3)  # emulating hard work in operation
>     return data.dict()
> ```
> 
> will print logs like this
> 
> ```
> Total time: 0.6051s. Validation time: 0.3025s
> ```

Thank you so much for your reply! Your reply was very detailed and I was able to resolve the issue.
